"""Domain 1 — Network Fundamentals (Cisco CCNA 200-301).

20% of the exam. Scenario-based "best answer" questions covering objectives
1.1-1.13, including subnetting/address math. Every distractor targets a
specific real misconception.
"""

QUESTIONS = [
    # ------------------------------------------------------------- 1.1 components
    {
        "id": "cd1-001",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Network components",
        "stem": "A campus network uses lightweight access points. Client traffic and AP management must be coordinated centrally, including RF management and roaming. Which device performs this role?",
        "options": [
            {"id": "a", "text": "Wireless LAN controller (WLC)", "correct": True, "rationale": "Correct. Lightweight APs use the split-MAC model and rely on a WLC for centralized control: RF management, channel/power assignment, client roaming, and policy. The AP handles only real-time 802.11 functions."},
            {"id": "b", "text": "Layer 2 switch", "correct": False, "rationale": "Incorrect. An L2 switch forwards frames by MAC address and may provide PoE to APs, but it does not centrally manage RF, roaming, or lightweight AP control functions."},
            {"id": "c", "text": "Next-generation firewall", "correct": False, "rationale": "Incorrect. An NGFW enforces security policy and inspects traffic; it does not coordinate lightweight AP RF or client roaming."},
            {"id": "d", "text": "Router", "correct": False, "rationale": "Incorrect. A router forwards packets between networks using L3 information; it has no role in centralized wireless control."},
        ],
        "explanation": "In the split-MAC (lightweight) architecture, real-time 802.11 operations stay on the AP while management functions (RF, roaming, security policy) are centralized on the WLC. Autonomous APs, by contrast, operate independently without a controller.",
    },
    {
        "id": "cd1-002",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Network components",
        "stem": "Which statement BEST distinguishes a Layer 3 switch from a traditional router in a campus design?",
        "options": [
            {"id": "a", "text": "A Layer 3 switch performs high-speed inter-VLAN routing in hardware (ASICs) but typically lacks the broad WAN interface support of a router", "correct": True, "rationale": "Correct. L3 switches route between VLANs at wire speed using ASICs and are optimized for LAN/inter-VLAN routing, but they generally lack the diverse WAN interfaces (serial, DSL, etc.) and advanced WAN features routers provide."},
            {"id": "b", "text": "A Layer 3 switch cannot route between VLANs", "correct": False, "rationale": "Incorrect. Inter-VLAN routing is precisely what a Layer 3 switch is designed to do via switched virtual interfaces (SVIs)."},
            {"id": "c", "text": "A router forwards frames based on MAC addresses only", "correct": False, "rationale": "Incorrect. Routers forward packets based on Layer 3 (IP) information, not MAC addresses; MAC-based forwarding is a switch (Layer 2) behavior."},
            {"id": "d", "text": "Only routers can build a MAC address table", "correct": False, "rationale": "Incorrect. Switches build MAC address tables; this is a switch function, not a router-only capability."},
        ],
        "explanation": "Layer 3 switches combine switching and routing, doing fast inter-VLAN routing in hardware, but are LAN-focused. Routers excel at connecting disparate networks and WANs with broad interface and feature support, often in software/CPU-assisted paths.",
    },
    {
        "id": "cd1-003",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Network components",
        "stem": "An access switch must power a number of 802.3at devices (cameras and APs) over the data cabling. Which capability must the switch support, and what is the per-port power ceiling of that standard?",
        "options": [
            {"id": "a", "text": "PoE+ (802.3at), up to ~30 W per port", "correct": True, "rationale": "Correct. 802.3at is PoE+, delivering up to about 30 W at the port (roughly 25.5 W at the device), suitable for PTZ cameras and many APs."},
            {"id": "b", "text": "PoE (802.3af), up to ~30 W per port", "correct": False, "rationale": "Incorrect. 802.3af is the original PoE at up to ~15.4 W per port (~12.95 W to the device), not 30 W; the 30 W figure belongs to 802.3at."},
            {"id": "c", "text": "UPOE (802.3bt) Type 4, up to ~15 W per port", "correct": False, "rationale": "Incorrect. 802.3bt provides far more (up to ~60-90 W), not 15 W; the value is mismatched with the standard."},
            {"id": "d", "text": "EtherChannel, up to ~30 W per port", "correct": False, "rationale": "Incorrect. EtherChannel bundles links for bandwidth/redundancy; it has nothing to do with delivering power over Ethernet."},
        ],
        "explanation": "Power over Ethernet tiers: 802.3af (PoE) ~15.4 W, 802.3at (PoE+) ~30 W, 802.3bt (PoE++/UPOE/Type 3-4) up to ~60-90 W per port. Match the powered device's draw to the correct standard.",
    },
    # ------------------------------------------------------------- 1.2 topologies
    {
        "id": "cd1-004",
        "domain": 1,
        "objective": "1.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Network topologies",
        "stem": "A data center adopts a spine-leaf topology. What is the PRIMARY benefit compared with a traditional three-tier (access/distribution/core) design for east-west (server-to-server) traffic?",
        "options": [
            {"id": "a", "text": "Every leaf is exactly one hop from every other leaf via any spine, giving predictable, consistent latency", "correct": True, "rationale": "Correct. In spine-leaf, each leaf connects to every spine and never directly to another leaf, so any server-to-server path crosses exactly one spine — uniform, predictable latency that scales well for east-west traffic."},
            {"id": "b", "text": "It eliminates the need for any Layer 3 routing", "correct": False, "rationale": "Incorrect. Spine-leaf fabrics typically rely heavily on Layer 3 routing (often with ECMP) between leaves and spines; it does not remove routing."},
            {"id": "c", "text": "Leaf switches connect directly to each other for the shortest path", "correct": False, "rationale": "Incorrect. Leaves do NOT connect to each other in spine-leaf; they connect only to spines. Leaf-to-leaf links would violate the design."},
            {"id": "d", "text": "It requires Spanning Tree to block most links", "correct": False, "rationale": "Incorrect. A key advantage is using all links via L3 ECMP instead of STP blocking, increasing usable bandwidth — the opposite of relying on STP to block links."},
        ],
        "explanation": "Spine-leaf gives any-leaf-to-any-leaf paths of equal length (one spine hop), predictable latency, and full link utilization via ECMP rather than STP-blocked links — ideal for the heavy east-west traffic of modern data centers.",
    },
    {
        "id": "cd1-005",
        "domain": 1,
        "objective": "1.2",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Network topologies",
        "stem": "Which description BEST matches a SOHO network?",
        "options": [
            {"id": "a", "text": "A small office/home office served by a single integrated device combining router, switch, wireless AP, and firewall functions", "correct": True, "rationale": "Correct. SOHO networks are small and typically built around one multifunction device that integrates routing, switching, wireless, and basic firewall/NAT in a single box."},
            {"id": "b", "text": "A large enterprise campus with separate core, distribution, and access layers", "correct": False, "rationale": "Incorrect. That describes a three-tier enterprise campus, not a small office/home office."},
            {"id": "c", "text": "A global service-provider backbone", "correct": False, "rationale": "Incorrect. A provider backbone is a large-scale WAN, the opposite of a SOHO."},
            {"id": "d", "text": "A data center spine-leaf fabric", "correct": False, "rationale": "Incorrect. Spine-leaf is a data-center topology, not a small office/home office network."},
        ],
        "explanation": "SOHO networks serve a handful of users and usually consolidate router, switch, wireless AP, and firewall/NAT into one device. Enterprise campuses and data centers use multi-tier, multi-device designs.",
    },
    # ------------------------------------------------------------- 1.3 cabling
    {
        "id": "cd1-006",
        "domain": 1,
        "objective": "1.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cabling & interfaces",
        "stem": "A 10 Gbps link must span 20 km between two buildings. Which media is appropriate?",
        "options": [
            {"id": "a", "text": "Single-mode fiber", "correct": True, "rationale": "Correct. Single-mode fiber uses a narrow core and a laser source to carry light long distances (tens of kilometers) with minimal modal dispersion — appropriate for a 20 km run."},
            {"id": "b", "text": "Multimode fiber", "correct": False, "rationale": "Incorrect. Multimode's larger core suffers modal dispersion, limiting 10 Gbps reach to roughly a few hundred meters (e.g., ~400 m on OM4) — far short of 20 km."},
            {"id": "c", "text": "Cat 6a UTP copper", "correct": False, "rationale": "Incorrect. Twisted-pair copper is limited to ~100 m regardless of category; it cannot span 20 km."},
            {"id": "d", "text": "Coaxial cable", "correct": False, "rationale": "Incorrect. Coax is not used for 10 Gbps building-to-building Ethernet at this distance and cannot reach 20 km at that speed."},
        ],
        "explanation": "Single-mode fiber (laser, small core) is the long-haul choice, reaching tens of kilometers. Multimode (LED/VCSEL, larger core) is for short reaches. Copper twisted pair tops out near 100 m.",
    },
    {
        "id": "cd1-007",
        "domain": 1,
        "objective": "1.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Interface/cable troubleshooting",
        "stem": "A 'show interfaces' output for GigabitEthernet0/1 shows a rising 'late collisions' counter while the link is up. What is the MOST likely cause?",
        "options": [
            {"id": "a", "text": "A duplex mismatch (one side full-duplex, the other half-duplex)", "correct": True, "rationale": "Correct. Late collisions (collisions after the first 64 bytes) on an up link are the classic symptom of a duplex mismatch: the full-duplex side transmits whenever it wants while the half-duplex side expects CSMA/CD, producing late collisions on the half-duplex end."},
            {"id": "b", "text": "Both sides are correctly set to full-duplex", "correct": False, "rationale": "Incorrect. A correctly matched full-duplex link has no collision domain to share and should not record collisions at all, let alone late ones."},
            {"id": "c", "text": "The cable is a crossover instead of straight-through", "correct": False, "rationale": "Incorrect. A wrong cable type typically prevents link or is auto-corrected by Auto-MDIX; it does not specifically generate late collisions on an up link."},
            {"id": "d", "text": "The interface speed is set too high for the switch", "correct": False, "rationale": "Incorrect. A speed mismatch usually prevents the link from coming up at all, rather than producing late collisions on an established link."},
        ],
        "explanation": "Late collisions on an active link almost always indicate a duplex mismatch. The half-duplex side, running CSMA/CD, detects the full-duplex side transmitting mid-frame and records late collisions. Set both ends to the same duplex (or both to autonegotiate).",
    },
    {
        "id": "cd1-008",
        "domain": 1,
        "objective": "1.4",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Interface/cable troubleshooting",
        "stem": "An interface shows 'GigabitEthernet0/1 is up, line protocol is down'. Which cause is MOST consistent with this state?",
        "options": [
            {"id": "a", "text": "A Layer 2 issue such as a keepalive or encapsulation/protocol mismatch", "correct": True, "rationale": "Correct. 'Up/line protocol down' means the physical layer (Layer 1) is fine but Layer 2 is failing — e.g., keepalive failures or an encapsulation mismatch on the link."},
            {"id": "b", "text": "The cable is unplugged", "correct": False, "rationale": "Incorrect. An unplugged cable produces 'down/down' (Layer 1 failure), not 'up/line protocol down'."},
            {"id": "c", "text": "The interface was administratively shut down", "correct": False, "rationale": "Incorrect. A 'shutdown' interface shows 'administratively down/down', not 'up/line protocol down'."},
            {"id": "d", "text": "An incorrect default gateway on a PC", "correct": False, "rationale": "Incorrect. A PC's gateway setting is a host configuration issue and does not change a router/switch interface's physical/data-link state."},
        ],
        "explanation": "Interface status reads as (Layer1 status)/(Layer2 protocol). Up/down = physical good but data-link failing (keepalives, encapsulation). Down/down = Layer 1 problem. Administratively down = manually shut.",
    },
    # ------------------------------------------------------------- 1.5 TCP/UDP
    {
        "id": "cd1-009",
        "domain": 1,
        "objective": "1.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "TCP vs UDP",
        "stem": "An application streams live voice and prioritizes low latency over guaranteed delivery; occasional lost packets are acceptable. Which transport protocol behavior matches this need, and why?",
        "options": [
            {"id": "a", "text": "UDP, because it is connectionless with no retransmission or ordering overhead, minimizing latency", "correct": True, "rationale": "Correct. Real-time voice uses UDP: it has no handshake, acknowledgments, retransmission, or reordering, so it avoids the delay those introduce. A late retransmitted voice packet is useless, so dropping it is preferable."},
            {"id": "b", "text": "TCP, because its retransmission guarantees every voice packet arrives", "correct": False, "rationale": "Incorrect. TCP's retransmission and in-order delivery add latency and head-of-line blocking; a re-sent voice sample arrives too late to be useful, making TCP a poor fit for real-time voice."},
            {"id": "c", "text": "TCP, because the three-way handshake reduces jitter", "correct": False, "rationale": "Incorrect. The handshake establishes a reliable session but does nothing to reduce jitter; reliability mechanisms generally increase delay variation for real-time media."},
            {"id": "d", "text": "UDP, because it guarantees ordered delivery without acknowledgments", "correct": False, "rationale": "Incorrect. UDP does NOT guarantee ordering or delivery at all; the reasoning is wrong even though UDP is the right protocol."},
        ],
        "explanation": "UDP is connectionless and lightweight (no handshake/ACK/retransmission/reordering), ideal for real-time voice/video where timeliness beats reliability. TCP is connection-oriented and reliable but adds latency unsuitable for live media.",
    },
    {
        "id": "cd1-010",
        "domain": 1,
        "objective": "1.5",
        "type": "multiple_response",
        "difficulty": "hard",
        "study_topic": "TCP vs UDP",
        "stem": "Which TWO mechanisms are provided by TCP but NOT by UDP? (Choose TWO.)",
        "options": [
            {"id": "a", "text": "Flow control using a sliding window", "correct": True, "rationale": "Correct. TCP uses a windowing/sliding-window mechanism for flow control between sender and receiver; UDP has no flow control."},
            {"id": "b", "text": "Reliable delivery via acknowledgments and retransmission", "correct": True, "rationale": "Correct. TCP acknowledges segments and retransmits lost ones for guaranteed delivery; UDP does neither."},
            {"id": "c", "text": "Source and destination port numbers", "correct": False, "rationale": "Incorrect. BOTH TCP and UDP use 16-bit source and destination ports, so this is not unique to TCP."},
            {"id": "d", "text": "Encapsulation of application-layer data", "correct": False, "rationale": "Incorrect. Both protocols encapsulate application data into their segments/datagrams; this is not a TCP-only feature."},
            {"id": "e", "text": "A checksum field", "correct": False, "rationale": "Incorrect. Both TCP and UDP include a checksum for error detection (UDP's is optional in IPv4 but mandatory in IPv6), so it is not exclusive to TCP."},
        ],
        "explanation": "TCP adds reliability (ACK/retransmission), in-order delivery, flow control (windowing), and connection setup/teardown. UDP shares ports, checksums, and encapsulation but omits TCP's reliability and flow-control machinery.",
    },
    # ------------------------------------------------------------- 1.6 subnetting
    {
        "id": "cd1-011",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv4 subnetting",
        "stem": "A host is configured as 172.16.20.200/26. Which statement about its subnet is correct?",
        "options": [
            {"id": "a", "text": "The network address is 172.16.20.192 and the broadcast is 172.16.20.255", "correct": True, "rationale": "Correct. A /26 (255.255.255.192) has block size 64, so subnets are .0, .64, .128, .192. Address .200 falls in the .192 subnet: network .192, broadcast .255, usable .193-.254."},
            {"id": "b", "text": "The network address is 172.16.20.128 and the broadcast is 172.16.20.191", "correct": False, "rationale": "Incorrect. The .128 subnet (/26) covers .128-.191; .200 is beyond .191, so it is not in this subnet."},
            {"id": "c", "text": "The network address is 172.16.20.192 and the broadcast is 172.16.20.223", "correct": False, "rationale": "Incorrect. .223 is the broadcast for a /27 (block 32) at .192, not a /26. With a /26 the block is 64, so broadcast is .255."},
            {"id": "d", "text": "The address is invalid because .200 cannot be a host in any /26", "correct": False, "rationale": "Incorrect. .200 is a perfectly valid host within the .192/26 subnet (.193-.254 usable)."},
        ],
        "explanation": "For /26, block size = 256 - 192 = 64. Subnets increment by 64; .200 lands in .192-.255. Network .192, broadcast .255, 62 usable hosts (.193-.254).",
    },
    {
        "id": "cd1-012",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv4 subnetting",
        "stem": "You must create subnets that each support at least 50 usable hosts, using the fewest host bits possible. Which subnet mask should you use?",
        "options": [
            {"id": "a", "text": "/26 (255.255.255.192)", "correct": True, "rationale": "Correct. 6 host bits give 2^6 - 2 = 62 usable hosts, the smallest mask that still meets 'at least 50.' A /27 gives only 30 usable hosts (too few)."},
            {"id": "b", "text": "/27 (255.255.255.224)", "correct": False, "rationale": "Incorrect. 5 host bits give 2^5 - 2 = 30 usable hosts, which is fewer than the required 50."},
            {"id": "c", "text": "/25 (255.255.255.128)", "correct": False, "rationale": "Incorrect. A /25 provides 126 usable hosts — it meets the requirement but wastes addresses; the question asks for the fewest host bits that still satisfy 50, which is /26."},
            {"id": "d", "text": "/24 (255.255.255.0)", "correct": False, "rationale": "Incorrect. A /24 gives 254 usable hosts, far more than needed and using more host bits than necessary."},
        ],
        "explanation": "Usable hosts = 2^(host bits) - 2. Need >= 50: /26 (6 bits) = 62 works; /27 (5 bits) = 30 does not. Choose the smallest mask that meets the requirement to conserve address space.",
    },
    {
        "id": "cd1-013",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "IPv4 subnetting",
        "stem": "Using VLSM in the 192.168.1.0/24 space, a point-to-point WAN link needs exactly 2 usable host addresses with no waste. Which prefix should you assign?",
        "options": [
            {"id": "a", "text": "/30 (255.255.255.252)", "correct": True, "rationale": "Correct. A /30 has 2 host bits = 2^2 - 2 = 2 usable addresses, exactly right for a point-to-point link with one address per router interface and no waste."},
            {"id": "b", "text": "/29 (255.255.255.248)", "correct": False, "rationale": "Incorrect. A /29 yields 6 usable hosts — more than needed, wasting 4 addresses on a 2-host link."},
            {"id": "c", "text": "/31 (255.255.255.254)", "correct": False, "rationale": "Incorrect. A /31 (RFC 3021) provides 2 addresses with no network/broadcast, used for point-to-point, but standard CCNA host-count math treats /31 as 0 'usable' by the 2^n - 2 rule; the expected answer for '2 usable hosts' is /30."},
            {"id": "d", "text": "/28 (255.255.255.240)", "correct": False, "rationale": "Incorrect. A /28 gives 14 usable hosts, vastly more than the 2 needed for a point-to-point link."},
        ],
        "explanation": "Point-to-point links conventionally use /30 (2 usable hosts) under the 2^n - 2 rule. VLSM lets you assign different masks per segment so each gets just enough addresses, minimizing waste.",
    },
    {
        "id": "cd1-014",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "IPv4 subnetting",
        "stem": "Which summary route most efficiently aggregates exactly these four networks and no others: 10.1.0.0/24, 10.1.1.0/24, 10.1.2.0/24, and 10.1.3.0/24?",
        "options": [
            {"id": "a", "text": "10.1.0.0/22", "correct": True, "rationale": "Correct. /22 has block size 4 in the third octet, covering 10.1.0.0-10.1.3.255 — exactly the four /24s and nothing more."},
            {"id": "b", "text": "10.1.0.0/23", "correct": False, "rationale": "Incorrect. A /23 covers only 10.1.0.0-10.1.1.255 (two /24s), missing 10.1.2.0 and 10.1.3.0."},
            {"id": "c", "text": "10.1.0.0/21", "correct": False, "rationale": "Incorrect. A /21 covers 10.1.0.0-10.1.7.255 (eight /24s), so it includes networks beyond the four specified."},
            {"id": "d", "text": "10.1.0.0/24", "correct": False, "rationale": "Incorrect. A /24 is a single network and cannot summarize four separate /24s."},
        ],
        "explanation": "To summarize, find the prefix whose block size in the relevant octet exactly spans the range. Third-octet values 0-3 need block size 4 = /22 (256 - 252). /23 is too small; /21 is too large.",
    },
    {
        "id": "cd1-015",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv4 subnetting",
        "stem": "Given host 10.10.10.73/28, what are the network and first usable host addresses?",
        "options": [
            {"id": "a", "text": "Network 10.10.10.64, first usable 10.10.10.65", "correct": True, "rationale": "Correct. A /28 (255.255.255.240) has block size 16: subnets .64, .80, etc. Address .73 is in .64-.79: network .64, usable .65-.78, broadcast .79. First usable is .65."},
            {"id": "b", "text": "Network 10.10.10.72, first usable 10.10.10.73", "correct": False, "rationale": "Incorrect. .72 is not a subnet boundary for a /28 (boundaries are multiples of 16: .64, .80). .73 belongs to the .64 subnet."},
            {"id": "c", "text": "Network 10.10.10.64, first usable 10.10.10.64", "correct": False, "rationale": "Incorrect. .64 is the network address itself and is not usable as a host; the first usable host is .65."},
            {"id": "d", "text": "Network 10.10.10.80, first usable 10.10.10.81", "correct": False, "rationale": "Incorrect. .80 begins the NEXT /28 subnet; .73 falls in the .64 subnet, not .80."},
        ],
        "explanation": "For /28, block size = 256 - 240 = 16, so subnets are .0, .16, .32, .48, .64, .80... Address .73 lands in .64-.79: network .64, first usable .65, broadcast .79.",
    },
    # ------------------------------------------------------------- 1.7 private/NAT
    {
        "id": "cd1-016",
        "domain": 1,
        "objective": "1.7",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Private addressing & NAT",
        "stem": "Which TWO address ranges are private (RFC 1918) addresses? (Choose TWO.)",
        "options": [
            {"id": "a", "text": "10.0.0.0 - 10.255.255.255", "correct": True, "rationale": "Correct. 10.0.0.0/8 is the Class A private range defined by RFC 1918."},
            {"id": "b", "text": "172.16.0.0 - 172.31.255.255", "correct": True, "rationale": "Correct. 172.16.0.0/12 (172.16.0.0-172.31.255.255) is the Class B private range."},
            {"id": "c", "text": "192.0.2.0 - 192.0.2.255", "correct": False, "rationale": "Incorrect. 192.0.2.0/24 is TEST-NET-1, reserved for documentation, not an RFC 1918 private range."},
            {"id": "d", "text": "172.32.0.0 - 172.32.255.255", "correct": False, "rationale": "Incorrect. The private Class B range ends at 172.31.255.255; 172.32.x.x is public."},
            {"id": "e", "text": "169.254.0.0 - 169.254.255.255", "correct": False, "rationale": "Incorrect. 169.254.0.0/16 is APIPA/link-local, assigned automatically when DHCP fails — not an RFC 1918 private range."},
        ],
        "explanation": "RFC 1918 private ranges: 10.0.0.0/8, 172.16.0.0/12 (172.16-172.31), and 192.168.0.0/16. APIPA (169.254/16) and documentation ranges (192.0.2.0/24) are separate reserved blocks.",
    },
    {
        "id": "cd1-017",
        "domain": 1,
        "objective": "1.7",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Private addressing & NAT",
        "stem": "Why must a router perform NAT before forwarding traffic from a 192.168.1.0/24 LAN to the internet?",
        "options": [
            {"id": "a", "text": "Private RFC 1918 addresses are not routable on the public internet, so they must be translated to a public address", "correct": True, "rationale": "Correct. ISPs drop traffic sourced from private addresses; NAT translates the private source to a routable public address so return traffic can find its way back."},
            {"id": "b", "text": "NAT encrypts the LAN traffic for security", "correct": False, "rationale": "Incorrect. NAT translates addresses; it does not encrypt traffic. Encryption is provided by protocols like IPsec/TLS."},
            {"id": "c", "text": "NAT is required to assign IP addresses to LAN hosts", "correct": False, "rationale": "Incorrect. Address assignment is DHCP's job, not NAT's."},
            {"id": "d", "text": "NAT converts IPv4 to IPv6 automatically", "correct": False, "rationale": "Incorrect. Standard NAT translates between IPv4 addresses; IPv4-to-IPv6 translation is a separate mechanism (NAT64), not what RFC 1918 internet access requires."},
        ],
        "explanation": "Private addresses (RFC 1918) are non-routable on the internet. NAT/PAT maps inside private addresses to one or more public addresses so internal hosts can communicate externally and replies can return.",
    },
    # ------------------------------------------------------------- 1.8/1.9 IPv6
    {
        "id": "cd1-018",
        "domain": 1,
        "objective": "1.8",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv6 addressing",
        "stem": "Which is the correct, fully compressed form of 2001:0db8:0000:0000:0000:ff00:0042:8329?",
        "options": [
            {"id": "a", "text": "2001:db8::ff00:42:8329", "correct": True, "rationale": "Correct. Leading zeros in each hextet are dropped (0db8->db8, 0042->42), and the single run of all-zero hextets is replaced by '::' exactly once, yielding 2001:db8::ff00:42:8329."},
            {"id": "b", "text": "2001:db8:0:0:0:ff00:42:8329", "correct": False, "rationale": "Incorrect. This drops leading zeros but fails to compress the consecutive zero hextets with '::', so it is valid but not fully compressed."},
            {"id": "c", "text": "2001:db8::ff00::42:8329", "correct": False, "rationale": "Incorrect. '::' may appear only ONCE in an address; using it twice makes the address ambiguous and invalid."},
            {"id": "d", "text": "2001:0db8::ff00:0042:8329", "correct": False, "rationale": "Incorrect. Leading zeros (0db8, 0042) must also be removed for full compression; this form is not fully compressed."},
        ],
        "explanation": "IPv6 compression rules: remove leading zeros in each hextet, and replace one contiguous run of all-zero hextets with '::' (only once). Both rules together give 2001:db8::ff00:42:8329.",
    },
    {
        "id": "cd1-019",
        "domain": 1,
        "objective": "1.9",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv6 address types",
        "stem": "A router interface automatically generates an address beginning with fe80:: when IPv6 is enabled. What type of address is this and what is its scope?",
        "options": [
            {"id": "a", "text": "A link-local address, valid only on the local link and never routed", "correct": True, "rationale": "Correct. fe80::/10 is the link-local range, auto-generated per interface. It is used for on-link communication (neighbor discovery, next-hop, routing protocol peers) and is never forwarded by routers."},
            {"id": "b", "text": "A global unicast address routable on the internet", "correct": False, "rationale": "Incorrect. Global unicast addresses come from 2000::/3 (e.g., 2001:...); fe80:: is link-local, not globally routable."},
            {"id": "c", "text": "A unique local address equivalent to RFC 1918", "correct": False, "rationale": "Incorrect. Unique local addresses are fc00::/7 (fd00::); fe80:: is link-local, a different scope."},
            {"id": "d", "text": "A multicast address", "correct": False, "rationale": "Incorrect. IPv6 multicast is ff00::/8; fe80:: is unicast link-local."},
        ],
        "explanation": "IPv6 prefixes: 2000::/3 global unicast, fe80::/10 link-local (auto-configured, link-only, never routed), fc00::/7 unique local (private), ff00::/8 multicast. Link-local addresses are required on every IPv6 interface.",
    },
    {
        "id": "cd1-020",
        "domain": 1,
        "objective": "1.9",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "IPv6 address types",
        "stem": "An interface with MAC address 00:1A:2B:3C:4D:5E builds its interface ID using modified EUI-64. What is the resulting 64-bit interface ID?",
        "options": [
            {"id": "a", "text": "021A:2BFF:FE3C:4D5E", "correct": True, "rationale": "Correct. EUI-64 inserts FFFE in the middle of the MAC (001A:2B + FFFE + 3C:4D5E) and flips the 7th bit of the first byte: 00 (0000 0000) becomes 02 (0000 0010), giving 021A:2BFF:FE3C:4D5E."},
            {"id": "b", "text": "001A:2BFF:FE3C:4D5E", "correct": False, "rationale": "Incorrect. FFFE is inserted correctly, but the 7th bit (universal/local) of the first byte was not flipped; 00 should become 02."},
            {"id": "c", "text": "021A:2B3C:4DFF:FE5E", "correct": False, "rationale": "Incorrect. FFFE must be inserted in the exact middle of the 48-bit MAC (after the first 24 bits), not after 32 bits."},
            {"id": "d", "text": "FF1A:2BFE:FE3C:4D5E", "correct": False, "rationale": "Incorrect. EUI-64 inserts FFFE (not FF/FE split like this) and does not alter the OUI bytes except flipping the U/L bit of the first byte."},
        ],
        "explanation": "Modified EUI-64: split the 48-bit MAC, insert FFFE in the middle, and invert the 7th bit (U/L bit) of the first byte. 00 -> 02 here, producing 021A:2BFF:FE3C:4D5E.",
    },
    {
        "id": "cd1-021",
        "domain": 1,
        "objective": "1.9",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv6 address types",
        "stem": "Which IPv6 multicast address is used to reach ALL routers on the local link (e.g., for router solicitation responses)?",
        "options": [
            {"id": "a", "text": "ff02::2", "correct": True, "rationale": "Correct. ff02::2 is the all-routers link-local multicast group; ff02::1 is all-nodes. Hosts send router solicitations to ff02::2."},
            {"id": "b", "text": "ff02::1", "correct": False, "rationale": "Incorrect. ff02::1 is the all-NODES multicast group (every IPv6 host on the link), not all-routers."},
            {"id": "c", "text": "fe80::1", "correct": False, "rationale": "Incorrect. fe80::1 is a link-local UNICAST address, not a multicast group."},
            {"id": "d", "text": "ff02::5", "correct": False, "rationale": "Incorrect. ff02::5 is the OSPFv3 all-OSPF-routers group, not the general all-routers group used for router solicitation."},
        ],
        "explanation": "Well-known IPv6 link-local multicast: ff02::1 = all nodes, ff02::2 = all routers, ff02::5/6 = OSPFv3, ff02::9 = RIPng, ff02::a = EIGRP. Router solicitations target ff02::2.",
    },
    # ------------------------------------------------------------- 1.10 client verify
    {
        "id": "cd1-022",
        "domain": 1,
        "objective": "1.10",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Client IP verification",
        "stem": "A Windows user reports no internet access. 'ipconfig' shows an address of 169.254.45.12 and no default gateway. What does this indicate?",
        "options": [
            {"id": "a", "text": "The client failed to obtain a DHCP lease and self-assigned an APIPA address", "correct": True, "rationale": "Correct. 169.254.0.0/16 is the APIPA range Windows assigns when no DHCP server responds. The absence of a gateway confirms the host never received DHCP configuration."},
            {"id": "b", "text": "The client has a valid public IP and a routing problem", "correct": False, "rationale": "Incorrect. 169.254.x.x is a link-local APIPA address, not a public IP; the issue is failure to reach DHCP, not external routing."},
            {"id": "c", "text": "DNS is misconfigured but addressing is fine", "correct": False, "rationale": "Incorrect. An APIPA address with no gateway is an addressing/DHCP failure, not merely a DNS issue."},
            {"id": "d", "text": "The subnet mask is wrong but the gateway is correct", "correct": False, "rationale": "Incorrect. There is no gateway at all, and the address is APIPA — this is a DHCP failure, not a mask problem."},
        ],
        "explanation": "An APIPA address (169.254.x.x) with no default gateway means the DHCP client got no response. Investigate the path to the DHCP server: NIC, cable, switch port, VLAN, or DHCP relay/scope.",
    },
    {
        "id": "cd1-023",
        "domain": 1,
        "objective": "1.10",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Client IP verification",
        "stem": "Which command displays the full IP configuration, including DNS servers and MAC address, on a Linux host?",
        "options": [
            {"id": "a", "text": "ip address show (and cat /etc/resolv.conf for DNS)", "correct": True, "rationale": "Correct. On modern Linux, 'ip address show' (or 'ip addr') displays interface IP/MAC details; DNS resolver settings are typically in /etc/resolv.conf. The legacy 'ifconfig' is similar but deprecated."},
            {"id": "b", "text": "ipconfig /all", "correct": False, "rationale": "Incorrect. 'ipconfig /all' is a Windows command, not Linux."},
            {"id": "c", "text": "show ip interface brief", "correct": False, "rationale": "Incorrect. That is Cisco IOS syntax for routers/switches, not a Linux host command."},
            {"id": "d", "text": "netsh interface ip show config", "correct": False, "rationale": "Incorrect. 'netsh' is a Windows utility, not available on Linux."},
        ],
        "explanation": "Per-OS IP verification: Windows uses 'ipconfig /all'; Linux uses 'ip addr' / 'ip address show' (legacy 'ifconfig'); macOS uses 'ifconfig' or networksetup; Cisco IOS uses 'show ip interface brief'.",
    },
    # ------------------------------------------------------------- 1.11 wireless
    {
        "id": "cd1-024",
        "domain": 1,
        "objective": "1.11",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Wireless principles",
        "stem": "In a dense office, several 2.4 GHz APs are placed near each other. To avoid co-channel and adjacent-channel interference, which channel plan should be used in North America?",
        "options": [
            {"id": "a", "text": "Channels 1, 6, and 11 (the non-overlapping 2.4 GHz channels)", "correct": True, "rationale": "Correct. In the 2.4 GHz band, only channels 1, 6, and 11 are non-overlapping (20 MHz spacing). Reusing this set across nearby APs minimizes interference."},
            {"id": "b", "text": "Channels 1, 2, and 3", "correct": False, "rationale": "Incorrect. Channels 1, 2, 3 overlap heavily (channels are 5 MHz apart but ~20 MHz wide), causing adjacent-channel interference."},
            {"id": "c", "text": "All APs on channel 6", "correct": False, "rationale": "Incorrect. Putting every AP on one channel maximizes co-channel interference and contention."},
            {"id": "d", "text": "Channels 1, 5, 9, 13", "correct": False, "rationale": "Incorrect. This set overlaps and channel 13 is not usable in North America (FCC), so it is not the standard non-overlapping plan."},
        ],
        "explanation": "The 2.4 GHz band has only three non-overlapping 20 MHz channels in North America: 1, 6, 11. Adjacent channels overlap because each is wider than the 5 MHz channel spacing. The 5 GHz band offers many more non-overlapping channels.",
    },
    {
        "id": "cd1-025",
        "domain": 1,
        "objective": "1.11",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Wireless principles",
        "stem": "What is the function of the SSID in a wireless network?",
        "options": [
            {"id": "a", "text": "It is the network name that identifies a WLAN to clients", "correct": True, "rationale": "Correct. The Service Set Identifier is the human-readable WLAN name clients use to select and associate with a particular wireless network."},
            {"id": "b", "text": "It encrypts all wireless frames", "correct": False, "rationale": "Incorrect. Encryption is provided by WPA2/WPA3, not the SSID; the SSID itself offers no security and is often broadcast in the clear."},
            {"id": "c", "text": "It assigns IP addresses to wireless clients", "correct": False, "rationale": "Incorrect. IP assignment is DHCP's role; the SSID only identifies the network."},
            {"id": "d", "text": "It selects the radio frequency channel automatically", "correct": False, "rationale": "Incorrect. Channel selection is a radio/AP configuration (or RRM on a WLC), independent of the SSID name."},
        ],
        "explanation": "The SSID is simply the WLAN's name advertised to clients. Security (WPA2/WPA3), addressing (DHCP), and channel selection are separate functions; hiding an SSID is not a real security control.",
    },
    {
        "id": "cd1-026",
        "domain": 1,
        "objective": "1.11",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Wireless principles",
        "stem": "Which 2.4 GHz Wi-Fi behavior explains why a single client transmitting reduces throughput for all other clients on the same AP and channel?",
        "options": [
            {"id": "a", "text": "Wi-Fi uses a half-duplex, shared medium with CSMA/CA, so only one device transmits at a time per channel", "correct": True, "rationale": "Correct. Wireless is a half-duplex shared medium; stations use CSMA/CA to take turns. While one transmits, others must wait, so aggregate channel airtime is shared among all clients."},
            {"id": "b", "text": "Wi-Fi is full-duplex, so collisions never occur", "correct": False, "rationale": "Incorrect. Wi-Fi is half-duplex per channel; devices cannot transmit and receive simultaneously on the same channel, which is why CSMA/CA is needed."},
            {"id": "c", "text": "Each client gets a dedicated channel automatically", "correct": False, "rationale": "Incorrect. Clients associated to one AP share its channel; they do not each receive a dedicated channel."},
            {"id": "d", "text": "Throughput drops because of NAT overhead", "correct": False, "rationale": "Incorrect. NAT is a Layer 3 translation function unrelated to the shared-airtime behavior of the wireless medium."},
        ],
        "explanation": "Wi-Fi is a half-duplex, shared-medium technology using CSMA/CA: stations contend for airtime and transmit one at a time per channel. More active clients means each gets less airtime, so per-client throughput falls.",
    },
    # ------------------------------------------------------------- 1.12 virtualization
    {
        "id": "cd1-027",
        "domain": 1,
        "objective": "1.12",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Virtualization & containers",
        "stem": "How do containers PRIMARILY differ from traditional virtual machines?",
        "options": [
            {"id": "a", "text": "Containers share the host OS kernel and package only the app and its dependencies, while each VM runs a full guest OS on a hypervisor", "correct": True, "rationale": "Correct. Containers virtualize at the OS level, sharing the host kernel and bundling just the application plus dependencies — making them lighter and faster to start than VMs, which each include a complete guest OS atop a hypervisor."},
            {"id": "b", "text": "Containers each run their own independent kernel and hardware drivers", "correct": False, "rationale": "Incorrect. Containers share the host kernel; they do not run separate kernels. That is a property of full VMs."},
            {"id": "c", "text": "VMs are always smaller and faster to boot than containers", "correct": False, "rationale": "Incorrect. The reverse is generally true: containers are smaller and boot faster because they avoid a full guest OS."},
            {"id": "d", "text": "Containers require a Type 1 hypervisor to run", "correct": False, "rationale": "Incorrect. Containers run on a container engine over the host OS, not on a hypervisor; hypervisors are for VMs."},
        ],
        "explanation": "VMs virtualize hardware (full guest OS per VM on a hypervisor); containers virtualize the OS (share the host kernel, package app + dependencies). Containers are lighter and faster to deploy but offer less isolation than VMs.",
    },
    {
        "id": "cd1-028",
        "domain": 1,
        "objective": "1.12",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Virtualization & containers",
        "stem": "A router uses VRFs to keep two customers' routing information completely separate on the same physical device. Which statement BEST describes what a VRF provides?",
        "options": [
            {"id": "a", "text": "Multiple independent routing tables on one router, isolating each customer's routes even if they use overlapping address space", "correct": True, "rationale": "Correct. VRF (Virtual Routing and Forwarding) creates separate routing/forwarding instances on a single router, so overlapping or distinct customer prefixes stay isolated — effectively routing-table virtualization."},
            {"id": "b", "text": "A way to encrypt routing updates between routers", "correct": False, "rationale": "Incorrect. VRF segments routing tables; it does not encrypt routing protocol traffic."},
            {"id": "c", "text": "A single shared routing table optimized for speed", "correct": False, "rationale": "Incorrect. VRF is the opposite of a single shared table — it provides multiple separate tables."},
            {"id": "d", "text": "A Layer 2 VLAN trunking feature", "correct": False, "rationale": "Incorrect. VLANs/trunking are Layer 2 segmentation; VRF is Layer 3 routing-table segmentation."},
        ],
        "explanation": "VRF virtualizes the Layer 3 control/forwarding plane, giving a router multiple isolated routing tables. It is the routing analog of VLANs at Layer 2 and enables overlapping address space and per-tenant isolation.",
    },
    # ------------------------------------------------------------- 1.13 switching
    {
        "id": "cd1-029",
        "domain": 1,
        "objective": "1.13",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Switching concepts / MAC table",
        "stem": "A switch receives a frame whose destination MAC address is not in its MAC address table. What does the switch do?",
        "options": [
            {"id": "a", "text": "Floods the frame out all ports in the same VLAN except the port it arrived on", "correct": True, "rationale": "Correct. For an unknown unicast destination, a switch floods the frame out every port in that VLAN except the ingress port, so the destination (wherever it is) can receive it and reply, letting the switch learn its location."},
            {"id": "b", "text": "Drops the frame because the destination is unknown", "correct": False, "rationale": "Incorrect. Switches do not drop unknown unicast frames; they flood them within the VLAN."},
            {"id": "c", "text": "Sends the frame back out the port it came in on", "correct": False, "rationale": "Incorrect. A switch never floods a frame back out its ingress port."},
            {"id": "d", "text": "Forwards the frame to the default gateway", "correct": False, "rationale": "Incorrect. Layer 2 switching uses MAC addresses within a VLAN; it does not send unknown unicast to a gateway based on the destination MAC."},
        ],
        "explanation": "Switch logic: learn source MAC -> port mapping; for known unicast, forward to the mapped port; for unknown unicast, broadcast, or multicast (without snooping), flood within the VLAN except the ingress port.",
    },
    {
        "id": "cd1-030",
        "domain": 1,
        "objective": "1.13",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Switching concepts / MAC table",
        "stem": "How does a switch build its MAC address table?",
        "options": [
            {"id": "a", "text": "By examining the SOURCE MAC address of incoming frames and associating it with the ingress port", "correct": True, "rationale": "Correct. Switches learn by reading the source MAC of each received frame and recording which port it came in on, building the table dynamically with an aging timer to remove stale entries."},
            {"id": "b", "text": "By examining the DESTINATION MAC address of incoming frames", "correct": False, "rationale": "Incorrect. The destination MAC is used for the forwarding decision, not for learning; learning is based on the source MAC."},
            {"id": "c", "text": "By querying a DHCP server for MAC-to-port mappings", "correct": False, "rationale": "Incorrect. DHCP assigns IP addresses; it has no role in populating the switch MAC table."},
            {"id": "d", "text": "By reading the source IP address of frames", "correct": False, "rationale": "Incorrect. MAC learning operates at Layer 2 using MAC addresses, not Layer 3 IP addresses."},
        ],
        "explanation": "Switches learn from the SOURCE MAC of incoming frames, mapping it to the ingress port (refreshed by an aging timer, default ~300 s). They forward based on the DESTINATION MAC. Source = learn, destination = forward.",
    },
    {
        "id": "cd1-031",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Network components",
        "stem": "What is the primary role of Cisco DNA Center in an intent-based network?",
        "options": [
            {"id": "a", "text": "A centralized controller and management platform for designing, provisioning, applying policy, and assuring the network", "correct": True, "rationale": "Correct. Cisco DNA Center is the controller/management platform for intent-based networking, handling design, provisioning, policy, and assurance/analytics across the campus fabric."},
            {"id": "b", "text": "A replacement for all routing protocols", "correct": False, "rationale": "Incorrect. DNA Center orchestrates and assures the network but does not replace routing protocols, which still run on devices."},
            {"id": "c", "text": "A wireless access point", "correct": False, "rationale": "Incorrect. DNA Center is a management/controller platform, not an AP."},
            {"id": "d", "text": "A DHCP server appliance", "correct": False, "rationale": "Incorrect. While it can integrate with network services, DNA Center's role is centralized controller-based management, not serving DHCP."},
        ],
        "explanation": "Cisco DNA Center is the centralized controller for intent-based networking: design, policy, automated provisioning, and assurance. It abstracts device-by-device configuration into business intent.",
    },
    {
        "id": "cd1-032",
        "domain": 1,
        "objective": "1.5",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "TCP vs UDP",
        "stem": "Which sequence correctly lists the TCP three-way handshake?",
        "options": [
            {"id": "a", "text": "SYN -> SYN-ACK -> ACK", "correct": True, "rationale": "Correct. The initiator sends SYN, the responder replies SYN-ACK, and the initiator completes with ACK, establishing the connection before data transfer."},
            {"id": "b", "text": "ACK -> SYN -> SYN-ACK", "correct": False, "rationale": "Incorrect. The handshake begins with SYN, not ACK; this ordering is wrong."},
            {"id": "c", "text": "SYN -> ACK -> FIN", "correct": False, "rationale": "Incorrect. FIN is used to tear down a connection, not to establish it; the setup uses SYN, SYN-ACK, ACK."},
            {"id": "d", "text": "SYN-ACK -> SYN -> ACK", "correct": False, "rationale": "Incorrect. The first segment must be a SYN from the initiator; a SYN-ACK cannot come first."},
        ],
        "explanation": "TCP establishes a session with SYN, SYN-ACK, ACK before exchanging data, and tears it down with FIN/ACK exchanges. This connection setup is part of what makes TCP reliable and connection-oriented.",
    },
    {
        "id": "cd1-033",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv4 subnetting",
        "stem": "How many usable host addresses does a /23 subnet provide?",
        "options": [
            {"id": "a", "text": "510", "correct": True, "rationale": "Correct. A /23 has 9 host bits: 2^9 - 2 = 512 - 2 = 510 usable hosts. The /23 spans two /24 blocks."},
            {"id": "b", "text": "512", "correct": False, "rationale": "Incorrect. 512 is the total addresses (2^9); you must subtract the network and broadcast addresses, leaving 510 usable."},
            {"id": "c", "text": "254", "correct": False, "rationale": "Incorrect. 254 is the usable count for a /24 (8 host bits); a /23 doubles the host space."},
            {"id": "d", "text": "508", "correct": False, "rationale": "Incorrect. This wrongly subtracts 4; only the network and broadcast (2 addresses) are unusable, giving 510."},
        ],
        "explanation": "Usable hosts = 2^(32 - prefix) - 2. For /23: 2^9 - 2 = 510. Always subtract exactly two addresses (network and broadcast) per subnet.",
    },
    {
        "id": "cd1-034",
        "domain": 1,
        "objective": "1.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cabling & interfaces",
        "stem": "Two PCs are connected directly by their NICs without a switch, on devices that do NOT support Auto-MDIX. Which cable is required?",
        "options": [
            {"id": "a", "text": "A crossover cable (T568A on one end, T568B on the other)", "correct": True, "rationale": "Correct. Connecting two like devices (PC-to-PC) without Auto-MDIX requires a crossover cable so transmit pairs on one end map to receive pairs on the other."},
            {"id": "b", "text": "A straight-through cable", "correct": False, "rationale": "Incorrect. Straight-through cables connect unlike devices (PC-to-switch). Two PCs directly would have TX-to-TX and RX-to-RX, which fails without crossover or Auto-MDIX."},
            {"id": "c", "text": "A rollover (console) cable", "correct": False, "rationale": "Incorrect. Rollover cables connect a PC to a device's console port for management, not for Ethernet data between two NICs."},
            {"id": "d", "text": "A fiber patch cable", "correct": False, "rationale": "Incorrect. Standard PC NICs use copper RJ45, not fiber; a fiber patch cable is irrelevant here."},
        ],
        "explanation": "Without Auto-MDIX, like-to-like connections (PC-PC, switch-switch, router-router) need a crossover cable; unlike connections (PC-switch, switch-router) use straight-through. Auto-MDIX, when present, auto-detects and removes this requirement.",
    },
    {
        "id": "cd1-035",
        "domain": 1,
        "objective": "1.9",
        "type": "multiple_response",
        "difficulty": "hard",
        "study_topic": "IPv6 address types",
        "stem": "Which TWO statements about IPv6 are correct? (Choose TWO.)",
        "options": [
            {"id": "a", "text": "IPv6 has no broadcast addresses; that role is handled by multicast", "correct": True, "rationale": "Correct. IPv6 eliminates broadcasts entirely and relies on multicast (and anycast) for one-to-many delivery, reducing unnecessary all-host interruptions."},
            {"id": "b", "text": "Every IPv6-enabled interface must have a link-local address", "correct": True, "rationale": "Correct. A link-local address (fe80::/10) is automatically configured and required on every IPv6 interface for on-link operations like neighbor discovery."},
            {"id": "c", "text": "IPv6 addresses are 64 bits long", "correct": False, "rationale": "Incorrect. IPv6 addresses are 128 bits, not 64. (A /64 commonly denotes the interface-ID boundary, but the address itself is 128 bits.)"},
            {"id": "d", "text": "IPv6 requires NAT to reach the internet", "correct": False, "rationale": "Incorrect. IPv6's huge address space removes the need for NAT; global unicast addresses are routable directly."},
            {"id": "e", "text": "ARP is used in IPv6 to resolve addresses", "correct": False, "rationale": "Incorrect. IPv6 replaces ARP with Neighbor Discovery Protocol (NDP) using ICMPv6 messages."},
        ],
        "explanation": "Key IPv6 facts: 128-bit addresses, no broadcast (multicast/anycast instead), mandatory link-local on every interface, NDP (not ARP) for resolution, and no NAT requirement thanks to abundant global addresses.",
    },
    {
        "id": "cd1-036",
        "domain": 1,
        "objective": "1.6",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "IPv4 subnetting",
        "stem": "A subnet must accommodate 300 hosts. Which is the smallest standard prefix that works, and how many usable hosts does it provide?",
        "options": [
            {"id": "a", "text": "/23, providing 510 usable hosts", "correct": True, "rationale": "Correct. 300 hosts exceed a /24's 254, so you need 9 host bits: /23 gives 2^9 - 2 = 510 usable, the smallest mask that fits 300."},
            {"id": "b", "text": "/24, providing 254 usable hosts", "correct": False, "rationale": "Incorrect. 254 usable hosts cannot accommodate 300; a /24 is too small."},
            {"id": "c", "text": "/22, providing 1022 usable hosts", "correct": False, "rationale": "Incorrect. A /22 (1022 usable) fits 300 but wastes addresses; /23 is the smaller mask that still meets the requirement."},
            {"id": "d", "text": "/25, providing 126 usable hosts", "correct": False, "rationale": "Incorrect. A /25 provides only 126 usable hosts, far fewer than 300."},
        ],
        "explanation": "Find the smallest host-bit count where 2^n - 2 >= required hosts. For 300: /24 (254) is too small, /23 (510) works. Choosing the smallest sufficient mask conserves address space.",
    },
    {
        "id": "cd1-037",
        "domain": 1,
        "objective": "1.13",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Switching concepts / MAC table",
        "stem": "By default, how long does a Cisco switch keep a dynamically learned MAC address entry idle before aging it out?",
        "options": [
            {"id": "a", "text": "300 seconds (5 minutes)", "correct": True, "rationale": "Correct. The default MAC address aging time on Cisco switches is 300 seconds; if no frame is seen from that source within the interval, the entry is removed."},
            {"id": "b", "text": "30 seconds", "correct": False, "rationale": "Incorrect. 30 seconds is far shorter than the default; this would churn the table unnecessarily."},
            {"id": "c", "text": "3600 seconds (1 hour)", "correct": False, "rationale": "Incorrect. One hour is much longer than the 300-second default."},
            {"id": "d", "text": "Entries never age out by default", "correct": False, "rationale": "Incorrect. Dynamic entries do age out (default 300 s); only static/sticky entries persist. "},
        ],
        "explanation": "Dynamic MAC entries age out after a default 300 seconds of inactivity, keeping the table current as devices move. Static and port-security sticky entries are exceptions that persist.",
    },
    {
        "id": "cd1-038",
        "domain": 1,
        "objective": "1.2",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Network topologies",
        "stem": "In a three-tier campus architecture, which layer's PRIMARY role is to aggregate access-layer switches and implement policy (routing, filtering) between them?",
        "options": [
            {"id": "a", "text": "Distribution layer", "correct": True, "rationale": "Correct. The distribution layer aggregates access switches, provides inter-VLAN routing, and enforces policy (ACLs, route summarization) between the access and core layers."},
            {"id": "b", "text": "Access layer", "correct": False, "rationale": "Incorrect. The access layer connects end devices (PCs, phones, APs) and provides port-level features; it does not aggregate other switches or apply inter-block policy."},
            {"id": "c", "text": "Core layer", "correct": False, "rationale": "Incorrect. The core is the high-speed backbone that switches traffic between distribution blocks as fast as possible, deliberately avoiding policy/filtering overhead."},
            {"id": "d", "text": "Spine layer", "correct": False, "rationale": "Incorrect. 'Spine' belongs to spine-leaf (data center) topology, not the three-tier campus model's access/distribution/core."},
        ],
        "explanation": "Three-tier campus: access (connect endpoints), distribution (aggregate access, routing/policy/summarization), core (fast backbone between distribution blocks). Policy and aggregation live at the distribution layer.",
    },
    {
        "id": "cd1-039",
        "domain": 1,
        "objective": "1.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "TCP vs UDP",
        "stem": "A network engineer captures traffic and sees a flow on UDP port 69 transferring a configuration file with no connection setup. Which application is MOST likely in use?",
        "options": [
            {"id": "a", "text": "TFTP", "correct": True, "rationale": "Correct. TFTP uses UDP port 69 and is connectionless and lightweight, commonly used to transfer device configs/IOS images. The lack of a handshake fits UDP-based TFTP."},
            {"id": "b", "text": "FTP", "correct": False, "rationale": "Incorrect. FTP uses TCP (ports 20/21) with connection setup and authentication; it would not appear as connectionless UDP/69 traffic."},
            {"id": "c", "text": "SSH", "correct": False, "rationale": "Incorrect. SSH uses TCP port 22 and establishes an encrypted session; it is not UDP/69 file transfer."},
            {"id": "d", "text": "HTTP", "correct": False, "rationale": "Incorrect. HTTP uses TCP port 80, not UDP/69."},
        ],
        "explanation": "TFTP (UDP/69) is a minimal, connectionless file-transfer protocol often used for network-device configs and images. FTP (TCP/20-21), SSH (TCP/22), and HTTP (TCP/80) are all connection-oriented TCP services.",
    },
    {
        "id": "cd1-040",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Network components",
        "stem": "Which device operates primarily at Layer 1 and simply repeats incoming electrical signals out all other ports, creating a single collision domain?",
        "options": [
            {"id": "a", "text": "A hub", "correct": True, "rationale": "Correct. A hub is a Layer 1 repeater: it regenerates and floods signals out all other ports, so all attached devices share one collision domain and one bandwidth segment."},
            {"id": "b", "text": "A switch", "correct": False, "rationale": "Incorrect. A switch operates at Layer 2, forwards by MAC address, and places each port in its own collision domain — the opposite of a hub."},
            {"id": "c", "text": "A router", "correct": False, "rationale": "Incorrect. A router operates at Layer 3, forwarding packets between networks and separating broadcast domains; it is not a Layer 1 repeater."},
            {"id": "d", "text": "A firewall", "correct": False, "rationale": "Incorrect. A firewall enforces security policy (typically Layer 3-7); it is not a Layer 1 signal repeater."},
        ],
        "explanation": "Hubs (Layer 1) repeat signals to all ports, forming one collision domain — obsolete due to contention. Switches (Layer 2) give each port its own collision domain; routers (Layer 3) separate broadcast domains.",
    },
]
