"""Domain 3 — IP Connectivity (Cisco CCNA 200-301).

The largest exam domain (25%). Scenario-based "best answer" questions covering
objectives 3.1-3.5, with routing-table interpretation and longest-prefix-match
math. Every distractor targets a specific real misconception.
"""

QUESTIONS = [
    # ------------------------------------------------------ 3.1 routing table
    {
        "id": "cd3-001",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Routing table components",
        "stem": "In the routing table entry 'O 10.2.0.0/16 [110/65] via 192.168.1.2, GigabitEthernet0/0', what do the numbers in brackets [110/65] represent?",
        "options": [
            {"id": "a", "text": "Administrative distance (110) and metric (65)", "correct": True, "rationale": "Correct. The bracket format is [administrative distance/metric]. 110 is OSPF's default AD, and 65 is the OSPF cost (metric) to reach 10.2.0.0/16."},
            {"id": "b", "text": "Metric (110) and administrative distance (65)", "correct": False, "rationale": "Incorrect. The order is reversed: the FIRST number is administrative distance, the second is the metric."},
            {"id": "c", "text": "Hop count (110) and bandwidth (65)", "correct": False, "rationale": "Incorrect. The bracket values are AD and metric, not hop count and bandwidth; OSPF doesn't even use hop count."},
            {"id": "d", "text": "Process ID (110) and area (65)", "correct": False, "rationale": "Incorrect. Process ID and area are OSPF configuration parameters, not what appears in the route's bracket; the bracket is [AD/metric]."},
        ],
        "explanation": "Routing-table entries show [administrative distance/metric]. The 'O' code marks OSPF (default AD 110); 65 is the cumulative OSPF cost. AD chooses between protocols; metric chooses among routes within one protocol.",
    },
    {
        "id": "cd3-002",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Routing table components",
        "stem": "A router's table shows 'Gateway of last resort is 203.0.113.1 to network 0.0.0.0' and 'S* 0.0.0.0/0 [1/0] via 203.0.113.1'. What does this indicate?",
        "options": [
            {"id": "a", "text": "A static default route is installed; unmatched traffic is sent to 203.0.113.1", "correct": True, "rationale": "Correct. The 'S*' marks a static default route (0.0.0.0/0), and the gateway of last resort is set accordingly. Any packet not matching a more specific route is forwarded to 203.0.113.1."},
            {"id": "b", "text": "The router has no default route and will drop unmatched packets", "correct": False, "rationale": "Incorrect. The presence of 0.0.0.0/0 and a gateway of last resort means there IS a default route; unmatched packets are forwarded, not dropped."},
            {"id": "c", "text": "203.0.113.1 is a directly connected host route", "correct": False, "rationale": "Incorrect. 0.0.0.0/0 is the default route (everything), not a /32 host route; 203.0.113.1 is the next hop, not a connected host."},
            {"id": "d", "text": "The route was learned via OSPF", "correct": False, "rationale": "Incorrect. The 'S' code indicates a STATIC route; OSPF routes are marked 'O'."},
        ],
        "explanation": "0.0.0.0/0 is the default route ('quad-zero'). The asterisk in 'S*' and the gateway of last resort show it is the candidate default. Packets without a more specific (longer-prefix) match follow it.",
    },
    # ------------------------------------------------ 3.2 forwarding decision
    {
        "id": "cd3-003",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Forwarding decision & longest prefix match",
        "stem": "A router has all of these routes. Which is used to forward a packet destined for 10.1.1.130?\n  S    10.1.1.0/24   [1/0]   via 192.168.1.1\n  O    10.1.1.128/26 [110/2] via 192.168.2.1\n  D    10.1.1.0/25   [90/3] via 192.168.3.1",
        "options": [
            {"id": "a", "text": "10.1.1.128/26 via 192.168.2.1", "correct": True, "rationale": "Correct. 10.1.1.130 is in 10.1.1.128/26 (.128-.191) and also in /24 (.0-.255) but NOT in /25 (.0-.127). Among the routes that CONTAIN .130, the /26 is the longest prefix, so it wins regardless of AD/metric."},
            {"id": "b", "text": "10.1.1.0/24 via 192.168.1.1 (lowest AD of 1)", "correct": False, "rationale": "Incorrect. Lowest AD does not override longest prefix match. The /24 contains .130 but is less specific than the /26, so it loses despite its AD of 1."},
            {"id": "c", "text": "10.1.1.0/25 via 192.168.3.1", "correct": False, "rationale": "Incorrect. The /25 covers only .0-.127; .130 is NOT in this subnet, so this route doesn't even match the destination."},
            {"id": "d", "text": "The router load-balances across all three", "correct": False, "rationale": "Incorrect. Load balancing happens only among equal routes to the same prefix; these are different prefixes, so longest match selects exactly one."},
        ],
        "explanation": "Forwarding always uses the longest prefix match that CONTAINS the destination. .130 is in /24 and /26 (not /25). The /26 is longest, so it's chosen — AD and metric only break ties between routes of the SAME prefix length.",
    },
    {
        "id": "cd3-004",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Administrative distance",
        "stem": "The same prefix 172.16.0.0/16 is learned via OSPF (AD 110), EIGRP internal (AD 90), and RIP (AD 120). Which route is installed in the routing table?",
        "options": [
            {"id": "a", "text": "The EIGRP route, because AD 90 is the lowest", "correct": True, "rationale": "Correct. When multiple routing protocols offer the SAME prefix, the router installs the one with the lowest administrative distance. EIGRP internal (90) beats OSPF (110) and RIP (120)."},
            {"id": "b", "text": "The OSPF route, because OSPF is more reliable than EIGRP", "correct": False, "rationale": "Incorrect. The router decides purely by AD value, not subjective reliability; OSPF's 110 is higher (less preferred) than EIGRP's 90."},
            {"id": "c", "text": "The RIP route, because it has the highest AD", "correct": False, "rationale": "Incorrect. Higher AD is LESS preferred; RIP's 120 is the worst of the three and would not be installed."},
            {"id": "d", "text": "All three, load-balanced", "correct": False, "rationale": "Incorrect. Routes from different protocols for the same prefix are not load-balanced; the lowest-AD source wins and the others are not installed."},
        ],
        "explanation": "Administrative distance ranks trustworthiness across protocols: Connected 0, Static 1, eBGP 20, EIGRP 90, OSPF 110, IS-IS 115, RIP 120, EIGRP external 170, iBGP 200. Lowest AD for a given prefix is installed.",
    },
    {
        "id": "cd3-005",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Administrative distance",
        "stem": "Which list shows the default administrative distances in correct order from MOST to LEAST preferred?",
        "options": [
            {"id": "a", "text": "Connected (0), Static (1), EIGRP internal (90), OSPF (110), RIP (120)", "correct": True, "rationale": "Correct. Lower AD = more preferred. Connected 0 < Static 1 < EIGRP 90 < OSPF 110 < RIP 120 is the correct ascending (most-to-least preferred) order."},
            {"id": "b", "text": "Static (1), Connected (0), OSPF (110), EIGRP (90), RIP (120)", "correct": False, "rationale": "Incorrect. Connected (0) is more preferred than Static (1), and EIGRP (90) is more preferred than OSPF (110); both are out of order here."},
            {"id": "c", "text": "RIP (120), OSPF (110), EIGRP (90), Static (1), Connected (0)", "correct": False, "rationale": "Incorrect. This is least-to-most preferred (descending AD), the reverse of what was asked."},
            {"id": "d", "text": "Connected (0), Static (1), OSPF (90), EIGRP (110), RIP (120)", "correct": False, "rationale": "Incorrect. The AD values are swapped: EIGRP internal is 90 and OSPF is 110, not the reverse."},
        ],
        "explanation": "Default ADs (lower is better): Connected 0, Static 1, eBGP 20, EIGRP 90, OSPF 110, IS-IS 115, RIP 120, EIGRP external 170, iBGP 200. Memorizing these is essential for predicting route selection.",
    },
    # ------------------------------------------------------- 3.3 static routing
    {
        "id": "cd3-006",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Static routing",
        "stem": "Which command configures a static route so that traffic to 192.168.50.0/24 is sent to next-hop 10.0.0.2?",
        "options": [
            {"id": "a", "text": "ip route 192.168.50.0 255.255.255.0 10.0.0.2", "correct": True, "rationale": "Correct. The syntax is 'ip route <destination-network> <subnet-mask> <next-hop>'. /24 = 255.255.255.0, and 10.0.0.2 is the next-hop IP."},
            {"id": "b", "text": "ip route 192.168.50.0 0.0.0.255 10.0.0.2", "correct": False, "rationale": "Incorrect. Static routes use a SUBNET mask (255.255.255.0), not a wildcard mask (0.0.0.255). Wildcards are for ACLs and OSPF network statements."},
            {"id": "c", "text": "ip route 10.0.0.2 255.255.255.0 192.168.50.0", "correct": False, "rationale": "Incorrect. The destination and next-hop are reversed; the destination network must come first, then the next hop."},
            {"id": "d", "text": "route add 192.168.50.0 mask 255.255.255.0 10.0.0.2", "correct": False, "rationale": "Incorrect. 'route add ... mask ...' is Windows host syntax, not Cisco IOS configuration."},
        ],
        "explanation": "Cisco static route syntax: 'ip route destination subnet-mask {next-hop-ip | exit-interface}'. Subnet masks (not wildcards) are used. A floating static adds a higher AD at the end.",
    },
    {
        "id": "cd3-007",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Floating static routes",
        "stem": "A primary route to 0.0.0.0/0 is learned via OSPF (AD 110). You want a static backup via a different ISP that is used ONLY if the OSPF default disappears. Which command creates this floating static route?",
        "options": [
            {"id": "a", "text": "ip route 0.0.0.0 0.0.0.0 198.51.100.1 130", "correct": True, "rationale": "Correct. Adding an AD of 130 (higher than OSPF's 110) makes this static route 'float': it stays out of the table while the OSPF default is present, and installs only if OSPF's route is lost."},
            {"id": "b", "text": "ip route 0.0.0.0 0.0.0.0 198.51.100.1", "correct": False, "rationale": "Incorrect. With the default static AD of 1, this route would be PREFERRED over OSPF (110) and always used, defeating the backup-only goal."},
            {"id": "c", "text": "ip route 0.0.0.0 0.0.0.0 198.51.100.1 90", "correct": False, "rationale": "Incorrect. AD 90 is still lower than OSPF's 110, so the static would win and be used as primary, not as a floating backup."},
            {"id": "d", "text": "ip route 0.0.0.0 0.0.0.0 198.51.100.1 110", "correct": False, "rationale": "Incorrect. Matching OSPF's AD of 110 creates ambiguity rather than a clear backup; the AD must be HIGHER than the primary's (e.g., 130) to float."},
        ],
        "explanation": "A floating static route uses an administrative distance higher than the primary route's so it remains inactive until the primary fails. To back up an OSPF default (AD 110), give the static an AD above 110 (e.g., 130).",
    },
    {
        "id": "cd3-008",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Static routing",
        "stem": "An engineer configures 'ip route 0.0.0.0 0.0.0.0 GigabitEthernet0/1' on a router whose G0/1 connects to a multi-access Ethernet segment with several neighbors. Why is using only the exit interface (no next hop) problematic here?",
        "options": [
            {"id": "a", "text": "On a multi-access link the router must resolve the destination MAC via ARP for every unknown destination, which can flood ARP and cause issues; a next-hop IP avoids this", "correct": True, "rationale": "Correct. With only an exit interface on a broadcast multi-access segment, the router treats every destination as directly connected and ARPs for each, generating excessive ARP and proxy-ARP reliance. Specifying a next-hop IP (or interface + next hop) is recommended."},
            {"id": "b", "text": "Exit-interface static routes are not supported in IOS", "correct": False, "rationale": "Incorrect. Exit-interface static routes ARE supported and work fine on point-to-point links; the concern is specifically multi-access segments."},
            {"id": "c", "text": "It will be rejected because 0.0.0.0/0 cannot be static", "correct": False, "rationale": "Incorrect. 0.0.0.0/0 is a perfectly valid static default route; the issue is the missing next hop on a multi-access link."},
            {"id": "d", "text": "It automatically raises the AD to 255, disabling the route", "correct": False, "rationale": "Incorrect. Using an exit interface does not change the AD to 255; static default AD remains 1 unless explicitly set."},
        ],
        "explanation": "On point-to-point links, exit-interface-only static routes are fine. On multi-access (Ethernet) links they force the router to ARP for every destination as if directly connected, so best practice is to include a next-hop IP (optionally with the interface).",
    },
    {
        "id": "cd3-009",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "IPv6 static routing",
        "stem": "Which command correctly configures an IPv6 static default route pointing to next-hop 2001:db8:0:12::2?",
        "options": [
            {"id": "a", "text": "ipv6 route ::/0 2001:db8:0:12::2", "correct": True, "rationale": "Correct. ::/0 is the IPv6 default route (equivalent to 0.0.0.0/0 in IPv4), and 'ipv6 route ::/0 <next-hop>' installs the default to that next hop."},
            {"id": "b", "text": "ip route ::/0 2001:db8:0:12::2", "correct": False, "rationale": "Incorrect. IPv6 static routes use the 'ipv6 route' command, not 'ip route' (which is for IPv4)."},
            {"id": "c", "text": "ipv6 route 0.0.0.0/0 2001:db8:0:12::2", "correct": False, "rationale": "Incorrect. The IPv6 default prefix is ::/0, not the IPv4-style 0.0.0.0/0."},
            {"id": "d", "text": "ipv6 route ::/128 2001:db8:0:12::2", "correct": False, "rationale": "Incorrect. ::/128 is a single host route (the unspecified address), not the default route; the default is ::/0."},
        ],
        "explanation": "IPv6 static routing uses 'ipv6 route <prefix>/<len> <next-hop|interface>'. The default route prefix is ::/0. Remember to enable 'ipv6 unicast-routing' globally for the router to forward IPv6.",
    },
    # ----------------------------------------------------------- 3.4 OSPF
    {
        "id": "cd3-010",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "OSPF DR/BDR election",
        "stem": "On a broadcast multi-access segment, four OSPF routers have these settings:\n  R1: priority 1, RID 1.1.1.1\n  R2: priority 1, RID 2.2.2.2\n  R3: priority 100, RID 3.3.3.3\n  R4: priority 0, RID 4.4.4.4\nWhich router becomes the DR?",
        "options": [
            {"id": "a", "text": "R3, because it has the highest OSPF interface priority", "correct": True, "rationale": "Correct. DR election uses highest interface priority first; R3's priority 100 beats the others' 1 (R4's 0 means it can never be DR/BDR). RID is only the tiebreaker when priorities are equal."},
            {"id": "b", "text": "R4, because it has the highest router ID number", "correct": False, "rationale": "Incorrect. R4 has priority 0, which explicitly disqualifies it from becoming DR or BDR regardless of its RID."},
            {"id": "c", "text": "R2, because it has the highest router ID among priority-1 routers", "correct": False, "rationale": "Incorrect. RID only breaks ties between EQUAL priorities; R3's higher priority (100) wins outright before RID is considered."},
            {"id": "d", "text": "R1, because the lowest router ID wins", "correct": False, "rationale": "Incorrect. DR election prefers the HIGHEST priority, then highest RID — not the lowest RID."},
        ],
        "explanation": "OSPF DR/BDR election: highest interface priority wins; ties broken by highest router ID. Priority 0 removes a router from the election entirely. So R3 (priority 100) is DR despite not having the highest RID.",
    },
    {
        "id": "cd3-011",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "Two OSPF routers on the same Ethernet segment are stuck in the 2-WAY/EXSTART cycle and never reach FULL. Their interfaces both show MTU 1500 on one side and 1400 on the other. What is the cause?",
        "options": [
            {"id": "a", "text": "An MTU mismatch — OSPF requires matching interface MTU to complete the database exchange", "correct": True, "rationale": "Correct. OSPF checks MTU during the database exchange (EXSTART/EXCHANGE). If MTUs differ, the adjacency hangs in EXSTART/EXCHANGE and never reaches FULL. Match the MTUs (or use 'ip ospf mtu-ignore' as a workaround)."},
            {"id": "b", "text": "Mismatched OSPF process IDs", "correct": False, "rationale": "Incorrect. OSPF process IDs are locally significant and need not match between neighbors; they do not prevent adjacency."},
            {"id": "c", "text": "Different OSPF priorities", "correct": False, "rationale": "Incorrect. Differing priorities only affect DR/BDR election, not whether the adjacency reaches FULL."},
            {"id": "d", "text": "One router has a higher router ID", "correct": False, "rationale": "Incorrect. Differing router IDs are normal and required (they must be unique); they do not cause an EXSTART hang."},
        ],
        "explanation": "OSPF neighbors must agree on MTU to complete the database exchange; a mismatch stalls the adjacency in EXSTART/EXCHANGE. Other must-match parameters include area ID, hello/dead timers, subnet/mask, and authentication. Process ID and RID need not match.",
    },
    {
        "id": "cd3-012",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_response",
        "difficulty": "expert",
        "study_topic": "OSPF adjacencies",
        "stem": "Which TWO parameters MUST match for two OSPFv2 routers to form a neighbor adjacency? (Choose TWO.)",
        "options": [
            {"id": "a", "text": "Hello and dead timer intervals", "correct": True, "rationale": "Correct. Mismatched hello/dead intervals prevent neighbors from maintaining the relationship; they must match on the segment."},
            {"id": "b", "text": "Area ID on the connecting interfaces", "correct": True, "rationale": "Correct. Both interfaces must be in the same OSPF area to form an adjacency."},
            {"id": "c", "text": "OSPF process ID", "correct": False, "rationale": "Incorrect. The process ID is locally significant; routers with different process IDs can still become neighbors."},
            {"id": "d", "text": "Router ID values", "correct": False, "rationale": "Incorrect. Router IDs must be UNIQUE, not matching; identical RIDs actually break OSPF."},
            {"id": "e", "text": "OSPF interface priority", "correct": False, "rationale": "Incorrect. Priority only influences DR/BDR election; it need not match for an adjacency to form."},
        ],
        "explanation": "OSPF neighbors must agree on: area ID, hello/dead timers, subnet and mask, authentication, MTU, and stub flags. They need NOT match process ID or priority, and router IDs must be unique.",
    },
    {
        "id": "cd3-013",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF cost & configuration",
        "stem": "With the default reference bandwidth (100 Mbps), what is the OSPF cost of a single 1 Gbps interface?",
        "options": [
            {"id": "a", "text": "1 (because cost is rounded up to a minimum of 1)", "correct": True, "rationale": "Correct. OSPF cost = reference bandwidth / interface bandwidth = 100 Mbps / 1000 Mbps = 0.1, which rounds UP to the minimum cost of 1. This is also why 10G, 1G, and 100M can all appear as cost 1 with the default reference, prompting admins to raise the reference bandwidth."},
            {"id": "b", "text": "10", "correct": False, "rationale": "Incorrect. 10 would be the cost of a 10 Mbps link (100/10); a 1 Gbps link computes to less than 1 and is rounded to 1."},
            {"id": "c", "text": "100", "correct": False, "rationale": "Incorrect. 100 is the cost of a 1 Mbps link, not 1 Gbps."},
            {"id": "d", "text": "1000", "correct": False, "rationale": "Incorrect. This appears to invert the formula; cost is reference/bandwidth, not bandwidth itself."},
        ],
        "explanation": "OSPF cost = reference bandwidth / interface bandwidth (min 1). With the default 100 Mbps reference, anything >= 100 Mbps yields cost 1, so 100M/1G/10G are indistinguishable. Raise the reference bandwidth (e.g., to 10000) to differentiate fast links.",
    },
    {
        "id": "cd3-014",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF cost & configuration",
        "stem": "An administrator configures 'passive-interface GigabitEthernet0/2' under the OSPF process. What is the effect on G0/2?",
        "options": [
            {"id": "a", "text": "OSPF stops sending hellos out G0/2 (no adjacencies form there), but the interface's subnet is still advertised", "correct": True, "rationale": "Correct. A passive interface suppresses OSPF hellos on that interface so no neighbor relationships form, yet the network remains advertised into OSPF. This is ideal for interfaces facing end hosts."},
            {"id": "b", "text": "The interface is shut down", "correct": False, "rationale": "Incorrect. Passive-interface does not administratively disable the interface; it only stops OSPF hellos there."},
            {"id": "c", "text": "The interface's subnet is removed from OSPF", "correct": False, "rationale": "Incorrect. The subnet continues to be advertised; only hello/adjacency formation is suppressed."},
            {"id": "d", "text": "OSPF begins flooding LSAs faster out that interface", "correct": False, "rationale": "Incorrect. Passive-interface reduces OSPF activity (no hellos/adjacencies) rather than increasing flooding."},
        ],
        "explanation": "passive-interface stops a routing protocol from forming adjacencies on that interface (no hellos) while still advertising its network. It's used on interfaces toward end devices to reduce overhead and exposure.",
    },
    {
        "id": "cd3-015",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "OSPF cost & configuration",
        "stem": "Which 'network' statement places interface 10.10.10.1/30 into OSPF area 0?",
        "options": [
            {"id": "a", "text": "network 10.10.10.0 0.0.0.3 area 0", "correct": True, "rationale": "Correct. OSPF network statements use a WILDCARD mask. A /30 has wildcard 0.0.0.3, matching 10.10.10.0-10.10.10.3, which includes the .1 interface, and 'area 0' assigns the area."},
            {"id": "b", "text": "network 10.10.10.0 255.255.255.252 area 0", "correct": False, "rationale": "Incorrect. OSPF network statements take a wildcard mask (0.0.0.3), not a subnet mask (255.255.255.252)."},
            {"id": "c", "text": "network 10.10.10.1 0.0.0.0 area 0", "correct": False, "rationale": "Incorrect. While a 0.0.0.0 wildcard could match exactly the interface IP, the address given (10.10.10.1) with that wildcard is valid syntax but the question's intended /30 match is 10.10.10.0 0.0.0.3; this option also risks mismatching if the IP differs. The standard answer for a /30 network is option a."},
            {"id": "d", "text": "network 10.10.10.0 0.0.0.255 area 0", "correct": False, "rationale": "Incorrect. 0.0.0.255 is a /24 wildcard, far broader than the /30 segment; it would match addresses outside the intended subnet."},
        ],
        "explanation": "OSPF 'network' statements use wildcard masks (inverse of the subnet mask). For a /30 (mask 255.255.255.252), the wildcard is 0.0.0.3. The statement matches interfaces in that range and assigns them to the specified area.",
    },
    {
        "id": "cd3-016",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "How does an OSPF router determine its router ID if no 'router-id' command is configured and loopbacks exist?",
        "options": [
            {"id": "a", "text": "It uses the highest IP address on any active loopback interface", "correct": True, "rationale": "Correct. Without an explicit router-id, OSPF selects the highest IP among up loopback interfaces; loopbacks are preferred because they are stable. If no loopback exists, it uses the highest active physical interface IP."},
            {"id": "b", "text": "It always uses the lowest physical interface IP address", "correct": False, "rationale": "Incorrect. OSPF prefers the HIGHEST IP, and loopbacks take precedence over physical interfaces; lowest is wrong."},
            {"id": "c", "text": "It uses the management VLAN IP only", "correct": False, "rationale": "Incorrect. There is no special 'management VLAN' rule; selection is explicit router-id, then highest loopback, then highest active physical interface."},
            {"id": "d", "text": "It generates a random 32-bit value", "correct": False, "rationale": "Incorrect. The RID is deterministic (config or highest loopback/physical IP), not random."},
        ],
        "explanation": "OSPF router-ID selection order: (1) manually configured router-id, (2) highest IP on an up loopback, (3) highest IP on an up physical interface. Loopbacks are preferred for stability; best practice is to set router-id explicitly.",
    },
    {
        "id": "cd3-017",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "On a point-to-point serial link running OSPF, will a DR/BDR be elected?",
        "options": [
            {"id": "a", "text": "No — OSPF does not elect a DR/BDR on point-to-point network types", "correct": True, "rationale": "Correct. DR/BDR election occurs only on broadcast and non-broadcast multi-access networks. Point-to-point links have just two routers, so no DR/BDR is needed or elected."},
            {"id": "b", "text": "Yes — every OSPF link elects a DR and BDR", "correct": False, "rationale": "Incorrect. DR/BDR is specific to multi-access segments; point-to-point and point-to-multipoint types skip it."},
            {"id": "c", "text": "Yes, but only a DR (no BDR) is elected", "correct": False, "rationale": "Incorrect. No DR is elected at all on point-to-point links; there's no multi-access segment to optimize."},
            {"id": "d", "text": "Only if authentication is enabled", "correct": False, "rationale": "Incorrect. Authentication has no bearing on DR/BDR election; the network type does."},
        ],
        "explanation": "DR/BDR reduce LSA flooding on multi-access (broadcast/NBMA) segments with many routers. On point-to-point links (only two routers), there's nothing to optimize, so OSPF elects no DR/BDR.",
    },
    # ------------------------------------------------------------ 3.5 FHRP
    {
        "id": "cd3-018",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "What problem do first hop redundancy protocols (FHRPs) like HSRP solve?",
        "options": [
            {"id": "a", "text": "They provide a single virtual default-gateway IP/MAC shared by multiple routers so hosts keep connectivity if the active gateway fails", "correct": True, "rationale": "Correct. FHRPs present one virtual IP (and virtual MAC) to hosts while two or more routers stand by; if the active router fails, a standby takes over the virtual addresses transparently, so hosts need no reconfiguration."},
            {"id": "b", "text": "They load-balance routing protocol updates between areas", "correct": False, "rationale": "Incorrect. FHRPs address default-gateway redundancy for hosts, not routing-protocol update distribution."},
            {"id": "c", "text": "They assign IP addresses to clients dynamically", "correct": False, "rationale": "Incorrect. Dynamic address assignment is DHCP; FHRPs provide gateway redundancy."},
            {"id": "d", "text": "They encrypt traffic between the host and gateway", "correct": False, "rationale": "Incorrect. FHRPs do not encrypt traffic; they provide a redundant virtual gateway."},
        ],
        "explanation": "FHRPs (HSRP, VRRP, GLBP) let multiple routers share a virtual gateway IP/MAC. Hosts point to the virtual IP; if the active router fails, a standby seamlessly assumes it, eliminating the single-gateway point of failure.",
    },
    {
        "id": "cd3-019",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "Which statement correctly distinguishes HSRP from VRRP?",
        "options": [
            {"id": "a", "text": "HSRP is Cisco-proprietary with one active and one standby router; VRRP is an open standard with a master and one or more backups", "correct": True, "rationale": "Correct. HSRP is Cisco-proprietary (active/standby terminology); VRRP is an IETF open standard (master/backup) interoperable across vendors. Both provide a virtual gateway."},
            {"id": "b", "text": "Both HSRP and VRRP are open standards", "correct": False, "rationale": "Incorrect. HSRP is Cisco-proprietary; only VRRP is an open standard."},
            {"id": "c", "text": "HSRP load-balances per host by default; VRRP does not support redundancy", "correct": False, "rationale": "Incorrect. HSRP is active/standby (not per-host load balancing by default — that's GLBP), and VRRP absolutely provides redundancy."},
            {"id": "d", "text": "VRRP is Cisco-proprietary and HSRP is the open standard", "correct": False, "rationale": "Incorrect. This reverses reality: HSRP is Cisco-proprietary, VRRP is the open standard."},
        ],
        "explanation": "HSRP (Cisco, active/standby) and VRRP (IETF open standard, master/backup) both present a virtual gateway with active failover. GLBP (also Cisco) adds actual per-host load balancing across multiple forwarders.",
    },
    {
        "id": "cd3-020",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "Which FHRP can actively load-balance outbound traffic across multiple routers using a single virtual gateway IP, by handing out different virtual MAC addresses to different hosts?",
        "options": [
            {"id": "a", "text": "GLBP", "correct": True, "rationale": "Correct. GLBP (Gateway Load Balancing Protocol, Cisco) uses one AVG that assigns different virtual MACs to ARP requests so multiple routers (AVFs) actively forward, achieving true per-host load balancing with one virtual IP."},
            {"id": "b", "text": "HSRP", "correct": False, "rationale": "Incorrect. HSRP is active/standby — only the active router forwards for a given group; it does not load-balance across routers (without multiple groups/SVIs)."},
            {"id": "c", "text": "VRRP", "correct": False, "rationale": "Incorrect. VRRP is master/backup; like HSRP, a single master forwards and backups wait, so no inherent per-host load balancing."},
            {"id": "d", "text": "STP", "correct": False, "rationale": "Incorrect. STP is a Layer 2 loop-prevention protocol, not an FHRP, and does not provide gateway load balancing."},
        ],
        "explanation": "GLBP is Cisco's FHRP that load-balances by giving different hosts different virtual MACs for the same virtual IP, so several routers forward simultaneously. HSRP and VRRP are active/standby (single forwarder per group).",
    },
    {
        "id": "cd3-021",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "In an HSRP group, the active router fails and the standby takes over. Why do hosts continue working without any change to their ARP cache?",
        "options": [
            {"id": "a", "text": "The standby assumes the same virtual IP AND virtual MAC, so the host's cached gateway MAC remains valid", "correct": True, "rationale": "Correct. HSRP failover transfers both the virtual IP and the virtual MAC to the new active router, so hosts that cached the virtual MAC keep sending to the same MAC — now answered by the standby — with no ARP change needed."},
            {"id": "b", "text": "Hosts immediately re-run DHCP to learn the new gateway", "correct": False, "rationale": "Incorrect. No DHCP renewal is needed; the gateway IP/MAC are unchanged from the host's perspective."},
            {"id": "c", "text": "The standby uses a different MAC and gratuitously updates every host's static route", "correct": False, "rationale": "Incorrect. The whole point of the virtual MAC is that it does NOT change; hosts don't have static routes updated by routers."},
            {"id": "d", "text": "The switches reboot to flush their tables", "correct": False, "rationale": "Incorrect. No reboot occurs; failover is designed to be transparent, sometimes with a gratuitous ARP to refresh switch MAC tables, but hosts keep the same gateway MAC."},
        ],
        "explanation": "HSRP/VRRP failover preserves the virtual IP and virtual MAC, so end hosts never need to update their ARP cache or gateway setting. The standby router simply begins answering for the same virtual addresses.",
    },
    # ------------------------------------------------- additional mix / depth
    {
        "id": "cd3-022",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Forwarding decision & longest prefix match",
        "stem": "A router must forward a packet to 192.168.4.17. The table contains:\n  192.168.4.0/24 via A\n  192.168.4.0/26 via B\n  192.168.4.16/28 via C\n  0.0.0.0/0 via D\nWhich path is chosen?",
        "options": [
            {"id": "a", "text": "Via C (192.168.4.16/28)", "correct": True, "rationale": "Correct. 192.168.4.17 is in /28 (.16-.31), /26 (.0-.63), and /24 (.0-.255). The longest prefix that contains it is the /28, so path C is chosen over the less-specific routes and the default."},
            {"id": "b", "text": "Via B (192.168.4.0/26)", "correct": False, "rationale": "Incorrect. .17 is within the /26, but the /28 is more specific (longer prefix) and also contains .17, so the /28 wins."},
            {"id": "c", "text": "Via A (192.168.4.0/24)", "correct": False, "rationale": "Incorrect. The /24 contains .17 but is the least specific of the matching routes; longest prefix match prefers the /28."},
            {"id": "d", "text": "Via D (default route)", "correct": False, "rationale": "Incorrect. The default route is used only when no more specific route matches; here several specific routes match, so the default is not used."},
        ],
        "explanation": "Longest prefix match: among all routes that CONTAIN the destination, the one with the most specific (longest) mask is selected. .17 fits /28, /26, /24, and default — the /28 is longest, so it wins.",
    },
    {
        "id": "cd3-023",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Routing table components",
        "stem": "In a routing table, what does the route code 'C' versus 'L' indicate for IPv4 entries?",
        "options": [
            {"id": "a", "text": "'C' is a directly connected network; 'L' is the local /32 host route for the router's own interface IP", "correct": True, "rationale": "Correct. 'C' marks the connected subnet of an interface; 'L' marks the specific /32 (the router's own interface address) installed so the router can receive traffic addressed directly to it."},
            {"id": "b", "text": "'C' means a static route; 'L' means a learned route", "correct": False, "rationale": "Incorrect. Static routes are coded 'S'; 'C' is connected and 'L' is local — neither relates to static vs learned."},
            {"id": "c", "text": "'C' is an OSPF route; 'L' is a RIP route", "correct": False, "rationale": "Incorrect. OSPF is 'O' and RIP is 'R'; 'C' and 'L' are connected and local interface routes."},
            {"id": "d", "text": "Both 'C' and 'L' indicate default routes", "correct": False, "rationale": "Incorrect. Default routes are 0.0.0.0/0 (often shown with '*'); 'C'/'L' are interface-derived, not default routes."},
        ],
        "explanation": "Connected interfaces generate two entries: 'C' for the subnet (e.g., 10.0.0.0/24) and 'L' for the interface's own address as a /32 (e.g., 10.0.0.1/32). Both appear automatically when an interface is up with an IP.",
    },
    {
        "id": "cd3-024",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "Which OSPF neighbor state indicates a FULLY synchronized link-state database between two routers?",
        "options": [
            {"id": "a", "text": "FULL", "correct": True, "rationale": "Correct. FULL is the final OSPF neighbor state, reached after the database exchange completes and both routers have identical link-state databases for the area. On multi-access links, non-DR/BDR routers may stably sit at 2-WAY with each other, but full adjacency is FULL."},
            {"id": "b", "text": "2-WAY", "correct": False, "rationale": "Incorrect. 2-WAY means bidirectional hellos are seen but databases are not yet synchronized; it is not full synchronization (though DROTHER-to-DROTHER pairs deliberately stay at 2-WAY)."},
            {"id": "c", "text": "EXSTART", "correct": False, "rationale": "Incorrect. EXSTART is an early stage where routers negotiate the master/slave relationship and sequence numbers; databases are not yet exchanged."},
            {"id": "d", "text": "INIT", "correct": False, "rationale": "Incorrect. INIT means a hello was received but the router hasn't yet seen its own ID in the neighbor's hello (no bidirectional communication yet)."},
        ],
        "explanation": "OSPF states progress Down -> Init -> 2-Way -> ExStart -> Exchange -> Loading -> Full. FULL indicates synchronized databases. On broadcast segments, DROTHER routers intentionally remain 2-WAY with each other and go FULL only with the DR/BDR.",
    },
    {
        "id": "cd3-025",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Static routing",
        "stem": "An engineer wants a host-specific static route directing only traffic for 8.8.8.8 to next-hop 10.0.0.9. Which command is correct?",
        "options": [
            {"id": "a", "text": "ip route 8.8.8.8 255.255.255.255 10.0.0.9", "correct": True, "rationale": "Correct. A host route uses a /32 mask (255.255.255.255), matching exactly one address (8.8.8.8) and forwarding only that traffic to 10.0.0.9."},
            {"id": "b", "text": "ip route 8.8.8.8 255.255.255.0 10.0.0.9", "correct": False, "rationale": "Incorrect. A /24 mask would match 8.8.8.0-8.8.8.255, not just the single host 8.8.8.8."},
            {"id": "c", "text": "ip route 8.8.8.8 0.0.0.0 10.0.0.9", "correct": False, "rationale": "Incorrect. 0.0.0.0 as a mask is invalid here; a host route requires the all-ones mask 255.255.255.255."},
            {"id": "d", "text": "ip route 8.8.8.8/32 10.0.0.9", "correct": False, "rationale": "Incorrect. IOS 'ip route' syntax requires a dotted-decimal mask (255.255.255.255), not slash notation."},
        ],
        "explanation": "A host route uses a /32 (255.255.255.255) mask to match a single IP. It is the most specific possible route and wins longest-prefix-match for that exact address.",
    },
    {
        "id": "cd3-026",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Administrative distance",
        "stem": "Why does a directly connected route (AD 0) always win over a static route to the same network configured with the default AD of 1?",
        "options": [
            {"id": "a", "text": "Lower administrative distance is more trusted, and 0 (connected) is lower than 1 (static)", "correct": True, "rationale": "Correct. AD ranks trustworthiness; the lower value wins. A connected route (AD 0) is considered the most reliable because the router can see the link directly, beating a static route's AD 1."},
            {"id": "b", "text": "Static routes are never installed when any other route exists", "correct": False, "rationale": "Incorrect. Static routes are frequently installed and preferred over dynamic protocols (which have higher AD); they just lose to connected routes for the same prefix."},
            {"id": "c", "text": "Connected routes have a better metric than static routes", "correct": False, "rationale": "Incorrect. The decision here is by AD (0 vs 1), not metric; AD is compared first when prefixes are equal length."},
            {"id": "d", "text": "The router randomly chooses connected routes", "correct": False, "rationale": "Incorrect. Selection is deterministic by AD, not random."},
        ],
        "explanation": "For equal-length prefixes, the router compares administrative distance and installs the lowest. Connected (0) is the most trusted, then static (1), then dynamic protocols. Metric is compared only within the same protocol.",
    },
    {
        "id": "cd3-027",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "OSPF cost & configuration",
        "stem": "Which command enables OSPF process 1 and is followed by network statements to advertise interfaces?",
        "options": [
            {"id": "a", "text": "router ospf 1", "correct": True, "rationale": "Correct. 'router ospf <process-id>' enters OSPF router configuration mode for that locally significant process; network statements then advertise interfaces and assign areas."},
            {"id": "b", "text": "router eigrp 1", "correct": False, "rationale": "Incorrect. That starts EIGRP, not OSPF; EIGRP uses an autonomous system number, and the protocol is different."},
            {"id": "c", "text": "ospf enable 1", "correct": False, "rationale": "Incorrect. 'ospf enable 1' is not valid IOS syntax for starting the OSPF process."},
            {"id": "d", "text": "ip ospf 1 area 0", "correct": False, "rationale": "Incorrect. 'ip ospf <pid> area <area>' is an INTERFACE-level command (an alternative to network statements), not the command that starts the OSPF process in global config."},
        ],
        "explanation": "Start OSPF with 'router ospf <process-id>' (process ID is locally significant). Then either use 'network <addr> <wildcard> area <n>' statements or configure 'ip ospf <pid> area <n>' on each interface.",
    },
    {
        "id": "cd3-028",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Routing table components",
        "stem": "A 'show ip route' output lists 'O E2 10.5.0.0/16 [110/20] via ...'. What does the 'E2' designation mean?",
        "options": [
            {"id": "a", "text": "An OSPF external type-2 route redistributed into OSPF from another source, whose metric does not increase as it crosses the OSPF domain", "correct": True, "rationale": "Correct. 'E2' marks an OSPF external Type 2 route (redistributed into OSPF). Its metric reflects only the external cost and stays constant internally, unlike E1 which adds internal cost along the path."},
            {"id": "b", "text": "An EIGRP route with external tag 2", "correct": False, "rationale": "Incorrect. The 'O' code identifies OSPF, not EIGRP; 'E2' is OSPF external type 2."},
            {"id": "c", "text": "An OSPF route in area 2", "correct": False, "rationale": "Incorrect. 'E2' denotes external type 2, not an area number; inter-area routes are marked 'O IA'."},
            {"id": "d", "text": "A directly connected route to a /16", "correct": False, "rationale": "Incorrect. Connected routes are coded 'C'; 'O E2' is an OSPF external route."},
        ],
        "explanation": "OSPF route codes: 'O' intra-area, 'O IA' inter-area, 'O E1'/'O E2' external (redistributed). E2 (the default for redistribution) keeps the external metric constant across the OSPF domain; E1 adds internal cost.",
    },
    {
        "id": "cd3-029",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Forwarding decision & longest prefix match",
        "stem": "Two routes to the SAME prefix 172.20.0.0/16 exist via EIGRP with metrics 30720 (path X) and 30720 (path Y), both AD 90. What does the router do?",
        "options": [
            {"id": "a", "text": "Installs both and load-balances (equal-cost multipath) across X and Y", "correct": True, "rationale": "Correct. Same prefix, same protocol, same AD, and EQUAL metrics means equal-cost multipath: the router installs both next hops and balances traffic across them (per-flow or per-packet)."},
            {"id": "b", "text": "Installs only path X because it was learned first", "correct": False, "rationale": "Incorrect. Learning order doesn't decide; equal-cost paths are both installed for load balancing."},
            {"id": "c", "text": "Chooses the path with the lower AD", "correct": False, "rationale": "Incorrect. Both have the same AD (90), so AD can't break the tie; equal metrics lead to load balancing."},
            {"id": "d", "text": "Drops the route as a conflict", "correct": False, "rationale": "Incorrect. Equal-cost paths are not a conflict; they are a feature (ECMP) the router uses to balance load."},
        ],
        "explanation": "When multiple routes to the same prefix have equal prefix length, AD, and metric, the router performs equal-cost multipath load balancing, installing all such paths (up to the maximum-paths limit).",
    },
    {
        "id": "cd3-030",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "In HSRP, which router forwards traffic for the virtual IP under normal conditions, and what determines which router holds that role?",
        "options": [
            {"id": "a", "text": "The active router forwards; it is chosen by highest HSRP priority, with highest IP address as the tiebreaker", "correct": True, "rationale": "Correct. The active router forwards for the virtual IP. Election uses highest priority (default 100); if priorities tie, the highest interface IP address wins. Preemption must be enabled for a higher-priority router to take over an existing active."},
            {"id": "b", "text": "The standby router forwards; it is chosen by lowest priority", "correct": False, "rationale": "Incorrect. The ACTIVE (not standby) router forwards, and HIGHER priority (not lowest) wins the election."},
            {"id": "c", "text": "Both routers forward simultaneously by default", "correct": False, "rationale": "Incorrect. HSRP is active/standby; only the active forwards for a group. Simultaneous forwarding is GLBP's behavior."},
            {"id": "d", "text": "The router with the lowest MAC address always forwards", "correct": False, "rationale": "Incorrect. HSRP election is by priority then highest IP, not by MAC address."},
        ],
        "explanation": "HSRP elects an active router (highest priority, tiebreak highest IP) to forward for the virtual IP, with a standby ready to take over. Without 'preempt', a recovering higher-priority router won't reclaim active automatically.",
    },
    {
        "id": "cd3-031",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "OSPF DR/BDR election",
        "stem": "After a DR is already elected on a segment, a new router with a higher OSPF priority joins. What happens to the DR role?",
        "options": [
            {"id": "a", "text": "Nothing changes immediately — OSPF DR is non-preemptive, so the existing DR stays until it fails or OSPF is reset", "correct": True, "rationale": "Correct. OSPF DR/BDR election is non-preemptive. A newly added higher-priority router does NOT seize the DR role; it must wait until the current DR goes down (or the process is cleared) to participate in a new election."},
            {"id": "b", "text": "The new router immediately becomes DR because of its higher priority", "correct": False, "rationale": "Incorrect. Unlike HSRP with preempt, OSPF never preempts an existing DR; higher priority only matters during a fresh election."},
            {"id": "c", "text": "Both routers become co-DRs", "correct": False, "rationale": "Incorrect. There is exactly one DR per multi-access segment; co-DRs do not exist."},
            {"id": "d", "text": "The segment loses its DR entirely", "correct": False, "rationale": "Incorrect. The existing DR remains in place; nothing is lost by a new router joining."},
        ],
        "explanation": "OSPF DR/BDR election is non-preemptive: once elected, a DR keeps the role even if a higher-priority router appears. A new election occurs only when the DR fails or OSPF is reset (clear ip ospf process).",
    },
    {
        "id": "cd3-032",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "hard",
        "study_topic": "Static routing",
        "stem": "Which TWO are valid ways to specify the path in an IPv4 static route? (Choose TWO.)",
        "options": [
            {"id": "a", "text": "A next-hop IP address (e.g., ip route 10.0.0.0 255.0.0.0 192.168.1.1)", "correct": True, "rationale": "Correct. Specifying a next-hop IP is the most common and recommended form, especially on multi-access links."},
            {"id": "b", "text": "An exit interface (e.g., ip route 10.0.0.0 255.0.0.0 GigabitEthernet0/0)", "correct": True, "rationale": "Correct. An exit interface is valid (ideal on point-to-point links) and can be combined with a next hop for a fully specified route."},
            {"id": "c", "text": "A wildcard mask instead of a subnet mask", "correct": False, "rationale": "Incorrect. Static routes require a subnet mask; wildcard masks are for ACLs and OSPF network statements."},
            {"id": "d", "text": "A routing protocol process ID", "correct": False, "rationale": "Incorrect. Static routes are manually defined and have no routing-protocol process ID."},
            {"id": "e", "text": "A DHCP pool name", "correct": False, "rationale": "Incorrect. DHCP pools assign host addresses and are unrelated to static route path specification."},
        ],
        "explanation": "An IPv4 static route specifies the path as a next-hop IP, an exit interface, or both (fully specified). It always uses a subnet mask. Exit-interface-only is best on point-to-point links; next-hop is preferred on multi-access links.",
    },
    {
        "id": "cd3-033",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Forwarding decision & longest prefix match",
        "stem": "Which order does a router use to make its default forwarding decision among candidate routes?",
        "options": [
            {"id": "a", "text": "Longest prefix match first, then administrative distance, then metric", "correct": True, "rationale": "Correct. The router first selects the most specific (longest) matching prefix; if multiple sources offer that same prefix, it compares administrative distance; among same-protocol routes it then compares metric."},
            {"id": "b", "text": "Administrative distance first, then prefix length, then metric", "correct": False, "rationale": "Incorrect. Prefix length (specificity) is evaluated before AD; a more specific route wins even with a higher AD."},
            {"id": "c", "text": "Metric first, then prefix length", "correct": False, "rationale": "Incorrect. Metric is the LAST tiebreaker and only within a single protocol; prefix length comes first."},
            {"id": "d", "text": "Lowest next-hop IP address first", "correct": False, "rationale": "Incorrect. Next-hop IP is not a selection criterion; the order is prefix length, AD, then metric."},
        ],
        "explanation": "Forwarding decision order: (1) longest prefix match (specificity), (2) administrative distance (between protocols offering that prefix), (3) metric (within the same protocol). Specificity always trumps AD and metric.",
    },
    {
        "id": "cd3-034",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "What is the default OSPF hello and dead interval on a broadcast (Ethernet) segment?",
        "options": [
            {"id": "a", "text": "Hello 10 seconds, dead 40 seconds", "correct": True, "rationale": "Correct. On broadcast and point-to-point networks, OSPF defaults to a 10-second hello and a 40-second dead interval (4x hello). Both must match between neighbors."},
            {"id": "b", "text": "Hello 30 seconds, dead 120 seconds", "correct": False, "rationale": "Incorrect. 30/120 are the defaults for non-broadcast (NBMA) network types, not broadcast Ethernet."},
            {"id": "c", "text": "Hello 5 seconds, dead 15 seconds", "correct": False, "rationale": "Incorrect. These are not OSPF defaults for broadcast links; the standard is 10/40."},
            {"id": "d", "text": "Hello 40 seconds, dead 10 seconds", "correct": False, "rationale": "Incorrect. The dead interval is always longer than the hello (typically 4x); 40/10 reverses them."},
        ],
        "explanation": "OSPF broadcast/point-to-point defaults: hello 10 s, dead 40 s. NBMA types default to 30 s/120 s. Hello and dead intervals must match for neighbors to form an adjacency.",
    },
    {
        "id": "cd3-035",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Routing table components",
        "stem": "A network 192.168.10.0/24 is reachable, but 'show ip route' shows no entry for it and no default route covers it. What happens to a packet destined for 192.168.10.5?",
        "options": [
            {"id": "a", "text": "The router drops the packet and (for some sources) sends an ICMP destination-unreachable", "correct": True, "rationale": "Correct. With no matching route and no default (gateway of last resort), the router has nowhere to forward the packet, so it drops it and may return an ICMP 'destination network unreachable' to the source."},
            {"id": "b", "text": "The router floods the packet out all interfaces", "correct": False, "rationale": "Incorrect. Routers do not flood unknown-destination unicast packets; that is Layer 2 switch behavior for unknown unicast frames."},
            {"id": "c", "text": "The router buffers the packet until a route appears", "correct": False, "rationale": "Incorrect. Routers do not hold packets waiting for a future route; unroutable packets are discarded immediately."},
            {"id": "d", "text": "The packet is sent to 127.0.0.1", "correct": False, "rationale": "Incorrect. The loopback address is not a catch-all; absent a matching route or default, the packet is dropped."},
        ],
        "explanation": "A router forwards only to destinations it has a route for. With no specific match and no default route, the packet is dropped and an ICMP unreachable may be returned. A default route (0.0.0.0/0) prevents such drops for unknown destinations.",
    },
    {
        "id": "cd3-036",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "IPv6 static routing",
        "stem": "Before an IPv6 router will forward IPv6 packets between interfaces, which global command must be enabled?",
        "options": [
            {"id": "a", "text": "ipv6 unicast-routing", "correct": True, "rationale": "Correct. By default a Cisco router does not route IPv6; 'ipv6 unicast-routing' in global config enables IPv6 packet forwarding between interfaces."},
            {"id": "b", "text": "ip routing", "correct": False, "rationale": "Incorrect. 'ip routing' enables IPv4 routing (and is on by default for routers); it does not enable IPv6 forwarding."},
            {"id": "c", "text": "ipv6 enable", "correct": False, "rationale": "Incorrect. 'ipv6 enable' is an INTERFACE command that turns on IPv6 (and a link-local address) on that interface; it does not enable router-wide IPv6 forwarding."},
            {"id": "d", "text": "ipv6 cef", "correct": False, "rationale": "Incorrect. 'ipv6 cef' enables Cisco Express Forwarding for IPv6 (a switching optimization), not the basic ability to route IPv6."},
        ],
        "explanation": "IPv6 routing is off by default on Cisco routers; enable it globally with 'ipv6 unicast-routing'. 'ipv6 enable' only activates IPv6 on a single interface; 'ipv6 cef' is a forwarding optimization.",
    },
    {
        "id": "cd3-037",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Administrative distance",
        "stem": "An eBGP route (AD 20) and an OSPF route (AD 110) both exist for the same prefix. Assuming both are valid, which is installed and why?",
        "options": [
            {"id": "a", "text": "The eBGP route, because AD 20 is lower (more preferred) than OSPF's 110", "correct": True, "rationale": "Correct. For the same prefix, the lowest AD wins. External BGP's AD of 20 is lower than OSPF's 110, so the eBGP route is installed in the routing table."},
            {"id": "b", "text": "The OSPF route, because OSPF is an interior gateway protocol", "correct": False, "rationale": "Incorrect. Being an IGP doesn't grant preference; the router compares AD numerically, and eBGP's 20 beats OSPF's 110."},
            {"id": "c", "text": "Both, because they come from different protocols", "correct": False, "rationale": "Incorrect. Different protocols offering the same prefix do not both install; the lower-AD source wins."},
            {"id": "d", "text": "Neither, because BGP and OSPF cannot coexist", "correct": False, "rationale": "Incorrect. BGP and OSPF commonly run together; AD arbitrates which route is used for a shared prefix."},
        ],
        "explanation": "Administrative distance arbitrates between protocols for the same prefix: eBGP 20 < OSPF 110, so the eBGP route is installed. (Note iBGP is AD 200, which would LOSE to OSPF — a common trap.)",
    },
    {
        "id": "cd3-038",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "OSPF cost & configuration",
        "stem": "A path traverses three links with OSPF costs 1, 10, and 4 from source to destination. What is the total OSPF cost the router uses for this path?",
        "options": [
            {"id": "a", "text": "15 (the sum of the outgoing interface costs along the path)", "correct": True, "rationale": "Correct. OSPF cost is cumulative: it sums the cost of each outgoing interface along the path. 1 + 10 + 4 = 15. OSPF selects the lowest total cost (SPF) to each destination."},
            {"id": "b", "text": "10 (the highest single link cost)", "correct": False, "rationale": "Incorrect. OSPF does not take the maximum link cost; it adds the costs of all outgoing interfaces along the path."},
            {"id": "c", "text": "1 (the lowest single link cost)", "correct": False, "rationale": "Incorrect. OSPF does not use the minimum cost; the path cost is the sum of outgoing interface costs."},
            {"id": "d", "text": "3 (the number of hops)", "correct": False, "rationale": "Incorrect. OSPF uses cost, not hop count (that's RIP). The total is the sum of the per-link costs, 15."},
        ],
        "explanation": "OSPF metric (cost) is additive along the path, summing each outgoing interface's cost. The SPF algorithm picks the path with the lowest cumulative cost. Hop count is RIP's metric, not OSPF's.",
    },
    {
        "id": "cd3-039",
        "domain": 3,
        "objective": "3.5",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "First hop redundancy (HSRP/VRRP/GLBP)",
        "stem": "What is a 'virtual IP address' in the context of an FHRP?",
        "options": [
            {"id": "a", "text": "A shared gateway IP that end hosts use, owned by whichever router is currently active/master", "correct": True, "rationale": "Correct. The virtual IP is the gateway address hosts are configured with; it is serviced by the active (HSRP)/master (VRRP) router and seamlessly transferred to a standby/backup on failover."},
            {"id": "b", "text": "A loopback IP used only for management", "correct": False, "rationale": "Incorrect. A management loopback is unrelated to FHRP; the virtual IP is the redundant default gateway hosts use."},
            {"id": "c", "text": "The public IP assigned by the ISP", "correct": False, "rationale": "Incorrect. The virtual IP is an internal gateway address, not an ISP-assigned public address."},
            {"id": "d", "text": "A multicast group address for routing updates", "correct": False, "rationale": "Incorrect. FHRPs do use multicast for their hellos, but the virtual IP is the unicast gateway address hosts point to, not a multicast group."},
        ],
        "explanation": "The FHRP virtual IP is the default gateway hosts are configured to use. It (and an associated virtual MAC) is held by the active/master router and moves to a standby/backup during failover, keeping host connectivity uninterrupted.",
    },
    {
        "id": "cd3-040",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Routing table components",
        "stem": "Which route source code in 'show ip route' represents a route learned via RIP?",
        "options": [
            {"id": "a", "text": "R", "correct": True, "rationale": "Correct. RIP-learned routes are marked with the code 'R' in the routing table."},
            {"id": "b", "text": "D", "correct": False, "rationale": "Incorrect. 'D' represents EIGRP (the D stands for DUAL, EIGRP's algorithm), not RIP."},
            {"id": "c", "text": "O", "correct": False, "rationale": "Incorrect. 'O' represents OSPF, not RIP."},
            {"id": "d", "text": "B", "correct": False, "rationale": "Incorrect. 'B' represents BGP-learned routes, not RIP."},
        ],
        "explanation": "Common route codes: C connected, L local, S static, R RIP, D EIGRP, O OSPF, B BGP, i IS-IS. Recognizing these codes is essential to reading a routing table.",
    },
    {
        "id": "cd3-041",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Administrative distance",
        "stem": "An iBGP route (AD 200) and an OSPF route (AD 110) exist for the same prefix. Which is installed, and why is this a common 'gotcha'?",
        "options": [
            {"id": "a", "text": "The OSPF route, because iBGP's AD of 200 is HIGHER (less preferred) than OSPF's 110 — surprising those who assume all BGP beats OSPF", "correct": True, "rationale": "Correct. While eBGP (20) beats OSPF, iBGP has an AD of 200, which is HIGHER than OSPF's 110, so the OSPF route wins. Many assume 'BGP always wins,' but only eBGP outranks IGPs by default."},
            {"id": "b", "text": "The iBGP route, because BGP always wins over IGPs", "correct": False, "rationale": "Incorrect. Only eBGP (AD 20) outranks OSPF; iBGP's AD 200 loses to OSPF's 110. This is exactly the misconception the question targets."},
            {"id": "c", "text": "Both are installed and load-balanced", "correct": False, "rationale": "Incorrect. Different protocols for the same prefix don't load-balance; the lower-AD route (OSPF) is installed."},
            {"id": "d", "text": "Neither, because BGP and OSPF conflict", "correct": False, "rationale": "Incorrect. They coexist fine; AD selects the OSPF route here."},
        ],
        "explanation": "Default ADs: eBGP 20 (beats IGPs), OSPF 110, iBGP 200 (loses to IGPs). The trap is assuming all BGP outranks OSPF — only eBGP does. For the same prefix, OSPF (110) beats iBGP (200).",
    },
    {
        "id": "cd3-042",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF DR/BDR election",
        "stem": "What is the PRIMARY purpose of electing a DR (and BDR) on a multi-access OSPF segment?",
        "options": [
            {"id": "a", "text": "To reduce the number of adjacencies and LSA flooding by having all routers exchange LSAs through the DR rather than full-mesh", "correct": True, "rationale": "Correct. Without a DR, n routers on a segment would form n(n-1)/2 adjacencies and flood LSAs to all. The DR (with BDR backup) becomes a central point: routers form full adjacency only with the DR/BDR, drastically reducing adjacencies and flooding overhead."},
            {"id": "b", "text": "To assign IP addresses to the segment", "correct": False, "rationale": "Incorrect. DR/BDR have nothing to do with address assignment (that's DHCP); they optimize OSPF LSA exchange."},
            {"id": "c", "text": "To encrypt OSPF hellos", "correct": False, "rationale": "Incorrect. Encryption/authentication is configured separately; the DR's role is to reduce adjacency and flooding overhead."},
            {"id": "d", "text": "To act as the default gateway for hosts", "correct": False, "rationale": "Incorrect. Default-gateway redundancy is FHRP's job; the DR is an OSPF flooding optimization, not a host gateway."},
        ],
        "explanation": "On multi-access segments, the DR/BDR reduce the adjacency mesh and LSA flooding: routers fully adjacency only with the DR/BDR and send LSAs to the DR (via 224.0.0.6), which redistributes them (via 224.0.0.5). This scales OSPF on shared media.",
    },
    {
        "id": "cd3-043",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Floating static routes",
        "stem": "A floating static route is configured but the engineer notices it is ALWAYS active, never floating. The primary route comes from EIGRP (AD 90). What is the MOST likely misconfiguration?",
        "options": [
            {"id": "a", "text": "The static route's AD was set lower than 90 (or left at the default 1), so it is preferred over EIGRP", "correct": True, "rationale": "Correct. For a static route to 'float' (act as backup), its AD must be HIGHER than the primary's. If it was left at the default 1 or set below 90, it beats EIGRP and is always installed, defeating the backup intent."},
            {"id": "b", "text": "EIGRP's AD is too low to ever be used", "correct": False, "rationale": "Incorrect. EIGRP's AD 90 is fine; the problem is the static's AD being lower than 90, not EIGRP's value."},
            {"id": "c", "text": "Floating static routes require OSPF as the primary", "correct": False, "rationale": "Incorrect. Floating statics work as backups to any primary source; they aren't tied to OSPF."},
            {"id": "d", "text": "The static route mask is wrong", "correct": False, "rationale": "Incorrect. While a wrong mask causes other problems, the described symptom (always active instead of floating) is an AD issue: its AD isn't higher than the primary's."},
        ],
        "explanation": "A floating static must have an AD greater than the primary route it backs up. To float behind EIGRP (90), set the static's AD above 90 (e.g., 100). Leaving it at the default 1 makes it preferred and thus always active.",
    },
    {
        "id": "cd3-044",
        "domain": 3,
        "objective": "3.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Routing table components",
        "stem": "What does 'variably subnetted' mean when seen in 'show ip route' output, e.g., '10.0.0.0/8 is variably subnetted, 5 subnets, 3 masks'?",
        "options": [
            {"id": "a", "text": "The router has routes to the 10.0.0.0 network using more than one prefix length (multiple masks), indicating VLSM is in use", "correct": True, "rationale": "Correct. 'Variably subnetted' means the major network is divided into subnets of differing prefix lengths (multiple masks) — the hallmark of VLSM. The output also reports how many subnets and distinct masks exist."},
            {"id": "b", "text": "The network uses only classful boundaries", "correct": False, "rationale": "Incorrect. Variable subnetting is the opposite of classful; it indicates multiple subnet masks (VLSM) within one major network."},
            {"id": "c", "text": "The routes were learned only via RIP version 1", "correct": False, "rationale": "Incorrect. RIPv1 is classful and does NOT support VLSM; variable subnetting implies a classless protocol/static config, not RIPv1."},
            {"id": "d", "text": "The network has no subnets at all", "correct": False, "rationale": "Incorrect. It explicitly reports multiple subnets and masks; saying there are none contradicts the output."},
        ],
        "explanation": "'Variably subnetted' indicates VLSM: the major network appears with subnets of different mask lengths. The output summarizes the count of subnets and distinct masks, helping you read classless routing tables.",
    },
    {
        "id": "cd3-045",
        "domain": 3,
        "objective": "3.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Forwarding decision & longest prefix match",
        "stem": "A packet is destined for 10.0.0.5. The table has only '10.0.0.0/30 via A' and '0.0.0.0/0 via B'. Which path is used?",
        "options": [
            {"id": "a", "text": "Via B (default route), because 10.0.0.5 is NOT within 10.0.0.0/30 (.0-.3)", "correct": True, "rationale": "Correct. A /30 covers only .0-.3, so 10.0.0.5 is outside it. The only route that CONTAINS .5 is the default 0.0.0.0/0, so the packet follows path B."},
            {"id": "b", "text": "Via A (10.0.0.0/30), because it is more specific", "correct": False, "rationale": "Incorrect. Specificity only matters among routes that actually contain the destination. .5 is not in .0-.3, so the /30 doesn't match and can't be used."},
            {"id": "c", "text": "The packet is dropped because the /30 doesn't match", "correct": False, "rationale": "Incorrect. A default route exists and covers all destinations, so the packet is forwarded via B rather than dropped."},
            {"id": "d", "text": "Load-balanced across A and B", "correct": False, "rationale": "Incorrect. The /30 doesn't contain .5, so there's only one matching route (the default); no load balancing occurs."},
        ],
        "explanation": "Longest prefix match applies only to routes that CONTAIN the destination. 10.0.0.5 is outside the /30 (.0-.3), so only the default route matches and is used. A more specific route that doesn't include the destination is irrelevant.",
    },
    {
        "id": "cd3-046",
        "domain": 3,
        "objective": "3.4",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "OSPF adjacencies",
        "stem": "Which multicast addresses does OSPFv2 use to send hellos and to communicate with the DR/BDR, respectively?",
        "options": [
            {"id": "a", "text": "224.0.0.5 (AllSPFRouters) for hellos/LSAs to all OSPF routers, and 224.0.0.6 (AllDRouters) to reach the DR/BDR", "correct": True, "rationale": "Correct. OSPF uses 224.0.0.5 to reach all OSPF routers (hellos, and flooding from the DR) and 224.0.0.6 for DROTHER routers to send updates to the DR and BDR."},
            {"id": "b", "text": "224.0.0.9 for hellos and 224.0.0.10 for the DR", "correct": False, "rationale": "Incorrect. 224.0.0.9 is RIPv2 and 224.0.0.10 is EIGRP; neither is used by OSPF."},
            {"id": "c", "text": "224.0.0.1 for hellos and 224.0.0.2 for the DR", "correct": False, "rationale": "Incorrect. 224.0.0.1 (all hosts) and 224.0.0.2 (all routers) are generic multicast groups, not OSPF's specific addresses."},
            {"id": "d", "text": "239.0.0.5 and 239.0.0.6", "correct": False, "rationale": "Incorrect. OSPF uses the link-local 224.0.0.x range, not administratively-scoped 239.0.0.x addresses."},
        ],
        "explanation": "OSPFv2 multicast: 224.0.0.5 (AllSPFRouters) for hellos and DR-to-all flooding; 224.0.0.6 (AllDRouters) for DROTHER routers to talk to the DR/BDR. (RIPv2 uses 224.0.0.9; EIGRP uses 224.0.0.10.)",
    },
]
