"""CompTIA Security+ SY0-701 acronym deck.

Each entry: {"acronym": "SIEM", "expansion": "Security Information and Event
Management", "domain": 4}. Used by the acronym-drill study mode.
"""

ACRONYMS = [
    {"acronym": "AAA", "expansion": "Authentication, Authorization, and Accounting", "domain": 1},
    {"acronym": "ACL", "expansion": "Access Control List", "domain": 4},
    {"acronym": "AES", "expansion": "Advanced Encryption Standard", "domain": 1},
    {"acronym": "AH", "expansion": "Authentication Header", "domain": 3},
    {"acronym": "AI", "expansion": "Artificial Intelligence", "domain": 2},
    {"acronym": "ALE", "expansion": "Annualized Loss Expectancy", "domain": 5},
    {"acronym": "AP", "expansion": "Access Point", "domain": 4},
    {"acronym": "API", "expansion": "Application Programming Interface", "domain": 4},
    {"acronym": "APT", "expansion": "Advanced Persistent Threat", "domain": 2},
    {"acronym": "ARO", "expansion": "Annualized Rate of Occurrence", "domain": 5},
    {"acronym": "ARP", "expansion": "Address Resolution Protocol", "domain": 2},
    {"acronym": "ASLR", "expansion": "Address Space Layout Randomization", "domain": 2},
    {"acronym": "ATT&CK", "expansion": "Adversarial Tactics, Techniques, and Common Knowledge", "domain": 4},
    {"acronym": "BAS", "expansion": "Breach and Attack Simulation", "domain": 4},
    {"acronym": "BCP", "expansion": "Business Continuity Plan", "domain": 5},
    {"acronym": "BGP", "expansion": "Border Gateway Protocol", "domain": 3},
    {"acronym": "BIA", "expansion": "Business Impact Analysis", "domain": 5},
    {"acronym": "BPA", "expansion": "Business Partners Agreement", "domain": 5},
    {"acronym": "BYOD", "expansion": "Bring Your Own Device", "domain": 4},
    {"acronym": "CA", "expansion": "Certificate Authority", "domain": 1},
    {"acronym": "CAPTCHA", "expansion": "Completely Automated Public Turing test to tell Computers and Humans Apart", "domain": 2},
    {"acronym": "CAR", "expansion": "Corrective Action Report", "domain": 4},
    {"acronym": "CASB", "expansion": "Cloud Access Security Broker", "domain": 3},
    {"acronym": "CBC", "expansion": "Cipher Block Chaining", "domain": 1},
    {"acronym": "CCMP", "expansion": "Counter Mode Cipher Block Chaining Message Authentication Code Protocol", "domain": 4},
    {"acronym": "CERT", "expansion": "Computer Emergency Response Team", "domain": 4},
    {"acronym": "CFB", "expansion": "Cipher Feedback", "domain": 1},
    {"acronym": "CIRT", "expansion": "Computer Incident Response Team", "domain": 4},
    {"acronym": "CMS", "expansion": "Content Management System", "domain": 3},
    {"acronym": "COOP", "expansion": "Continuity of Operations Plan", "domain": 5},
    {"acronym": "COPE", "expansion": "Corporate Owned, Personally Enabled", "domain": 4},
    {"acronym": "CRC", "expansion": "Cyclic Redundancy Check", "domain": 1},
    {"acronym": "CRL", "expansion": "Certificate Revocation List", "domain": 1},
    {"acronym": "CSP", "expansion": "Cloud Service Provider", "domain": 3},
    {"acronym": "CSR", "expansion": "Certificate Signing Request", "domain": 1},
    {"acronym": "CSRF", "expansion": "Cross-Site Request Forgery", "domain": 2},
    {"acronym": "CTM", "expansion": "Counter Mode", "domain": 1},
    {"acronym": "CVE", "expansion": "Common Vulnerabilities and Exposures", "domain": 4},
    {"acronym": "CVSS", "expansion": "Common Vulnerability Scoring System", "domain": 4},
    {"acronym": "CYOD", "expansion": "Choose Your Own Device", "domain": 4},
    {"acronym": "DAC", "expansion": "Discretionary Access Control", "domain": 4},
    {"acronym": "DDoS", "expansion": "Distributed Denial of Service", "domain": 2},
    {"acronym": "DEP", "expansion": "Data Execution Prevention", "domain": 2},
    {"acronym": "DES", "expansion": "Digital Encryption Standard", "domain": 1},
    {"acronym": "DHCP", "expansion": "Dynamic Host Configuration Protocol", "domain": 3},
    {"acronym": "DKIM", "expansion": "DomainKeys Identified Mail", "domain": 4},
    {"acronym": "DLL", "expansion": "Dynamic-Link Library", "domain": 2},
    {"acronym": "DLP", "expansion": "Data Loss Prevention", "domain": 4},
    {"acronym": "DMARC", "expansion": "Domain-based Message Authentication Reporting and Conformance", "domain": 4},
    {"acronym": "DNS", "expansion": "Domain Name System", "domain": 3},
    {"acronym": "DNSSEC", "expansion": "Domain Name System Security Extensions", "domain": 3},
    {"acronym": "DoS", "expansion": "Denial of Service", "domain": 2},
    {"acronym": "DPO", "expansion": "Data Protection Officer", "domain": 5},
    {"acronym": "DRP", "expansion": "Disaster Recovery Plan", "domain": 5},
    {"acronym": "EAP", "expansion": "Extensible Authentication Protocol", "domain": 4},
    {"acronym": "ECB", "expansion": "Electronic Code Book", "domain": 1},
    {"acronym": "ECC", "expansion": "Elliptic Curve Cryptography", "domain": 1},
    {"acronym": "EDR", "expansion": "Endpoint Detection and Response", "domain": 4},
    {"acronym": "EFS", "expansion": "Encrypting File System", "domain": 3},
    {"acronym": "ERP", "expansion": "Enterprise Resource Planning", "domain": 3},
    {"acronym": "ESN", "expansion": "Electronic Serial Number", "domain": 4},
    {"acronym": "ESP", "expansion": "Encapsulating Security Payload", "domain": 3},
    {"acronym": "FDE", "expansion": "Full Disk Encryption", "domain": 3},
    {"acronym": "FIM", "expansion": "File Integrity Monitoring", "domain": 4},
    {"acronym": "FRR", "expansion": "False Rejection Rate", "domain": 4},
    {"acronym": "FTP", "expansion": "File Transfer Protocol", "domain": 4},
    {"acronym": "FTPS", "expansion": "File Transfer Protocol Secure", "domain": 4},
    {"acronym": "GCM", "expansion": "Galois Counter Mode", "domain": 1},
    {"acronym": "GDPR", "expansion": "General Data Protection Regulation", "domain": 5},
    {"acronym": "GPO", "expansion": "Group Policy Object", "domain": 4},
    {"acronym": "GPS", "expansion": "Global Positioning System", "domain": 4},
    {"acronym": "GRE", "expansion": "Generic Routing Encapsulation", "domain": 3},
    {"acronym": "HA", "expansion": "High Availability", "domain": 3},
    {"acronym": "HIDS", "expansion": "Host-based Intrusion Detection System", "domain": 4},
    {"acronym": "HIPS", "expansion": "Host-based Intrusion Prevention System", "domain": 4},
    {"acronym": "HMAC", "expansion": "Hash-based Message Authentication Code", "domain": 1},
    {"acronym": "HOTP", "expansion": "HMAC-based One-Time Password", "domain": 4},
    {"acronym": "HSM", "expansion": "Hardware Security Module", "domain": 1},
    {"acronym": "HTML", "expansion": "Hypertext Markup Language", "domain": 3},
    {"acronym": "HTTP", "expansion": "Hypertext Transfer Protocol", "domain": 4},
    {"acronym": "HTTPS", "expansion": "Hypertext Transfer Protocol Secure", "domain": 4},
    {"acronym": "HVAC", "expansion": "Heating, Ventilation, and Air Conditioning", "domain": 3},
    {"acronym": "IaaS", "expansion": "Infrastructure as a Service", "domain": 3},
    {"acronym": "IaC", "expansion": "Infrastructure as Code", "domain": 3},
    {"acronym": "IAM", "expansion": "Identity and Access Management", "domain": 4},
    {"acronym": "ICS", "expansion": "Industrial Control Systems", "domain": 3},
    {"acronym": "IDS", "expansion": "Intrusion Detection System", "domain": 4},
    {"acronym": "IdP", "expansion": "Identity Provider", "domain": 4},
    {"acronym": "IKE", "expansion": "Internet Key Exchange", "domain": 3},
    {"acronym": "IoT", "expansion": "Internet of Things", "domain": 3},
    {"acronym": "IPS", "expansion": "Intrusion Prevention System", "domain": 4},
    {"acronym": "IPSec", "expansion": "Internet Protocol Security", "domain": 3},
    {"acronym": "IR", "expansion": "Incident Response", "domain": 4},
    {"acronym": "IRP", "expansion": "Incident Response Plan", "domain": 4},
    {"acronym": "ISO", "expansion": "International Organization for Standardization", "domain": 5},
    {"acronym": "ISP", "expansion": "Internet Service Provider", "domain": 3},
    {"acronym": "IV", "expansion": "Initialization Vector", "domain": 1},
    {"acronym": "KDC", "expansion": "Key Distribution Center", "domain": 4},
    {"acronym": "KEK", "expansion": "Key Encryption Key", "domain": 1},
    {"acronym": "L2TP", "expansion": "Layer 2 Tunneling Protocol", "domain": 3},
    {"acronym": "LDAP", "expansion": "Lightweight Directory Access Protocol", "domain": 4},
    {"acronym": "LEAP", "expansion": "Lightweight Extensible Authentication Protocol", "domain": 4},
    {"acronym": "MaaS", "expansion": "Monitoring as a Service", "domain": 3},
    {"acronym": "MAC", "expansion": "Mandatory Access Control", "domain": 4},
    {"acronym": "MAM", "expansion": "Mobile Application Management", "domain": 4},
    {"acronym": "MD5", "expansion": "Message Digest 5", "domain": 1},
    {"acronym": "MDM", "expansion": "Mobile Device Management", "domain": 4},
    {"acronym": "MFA", "expansion": "Multifactor Authentication", "domain": 4},
    {"acronym": "MFD", "expansion": "Multifunction Device", "domain": 3},
    {"acronym": "MOA", "expansion": "Memorandum of Agreement", "domain": 5},
    {"acronym": "MOU", "expansion": "Memorandum of Understanding", "domain": 5},
    {"acronym": "MSA", "expansion": "Master Service Agreement", "domain": 5},
    {"acronym": "MSP", "expansion": "Managed Service Provider", "domain": 5},
    {"acronym": "MSSP", "expansion": "Managed Security Service Provider", "domain": 5},
    {"acronym": "MTBF", "expansion": "Mean Time Between Failures", "domain": 5},
    {"acronym": "MTTR", "expansion": "Mean Time To Repair", "domain": 5},
    {"acronym": "MTD", "expansion": "Maximum Tolerable Downtime", "domain": 5},
    {"acronym": "NAC", "expansion": "Network Access Control", "domain": 3},
    {"acronym": "NAT", "expansion": "Network Address Translation", "domain": 3},
    {"acronym": "NDA", "expansion": "Non-Disclosure Agreement", "domain": 5},
    {"acronym": "NGFW", "expansion": "Next-Generation Firewall", "domain": 3},
    {"acronym": "NIDS", "expansion": "Network-based Intrusion Detection System", "domain": 4},
    {"acronym": "NIPS", "expansion": "Network-based Intrusion Prevention System", "domain": 4},
    {"acronym": "NIST", "expansion": "National Institute of Standards and Technology", "domain": 5},
    {"acronym": "NTLM", "expansion": "New Technology LAN Manager", "domain": 4},
    {"acronym": "NTP", "expansion": "Network Time Protocol", "domain": 4},
    {"acronym": "OAuth", "expansion": "Open Authorization", "domain": 4},
    {"acronym": "OCSP", "expansion": "Online Certificate Status Protocol", "domain": 1},
    {"acronym": "OSINT", "expansion": "Open-Source Intelligence", "domain": 2},
    {"acronym": "OSPF", "expansion": "Open Shortest Path First", "domain": 3},
    {"acronym": "OT", "expansion": "Operational Technology", "domain": 3},
    {"acronym": "OWASP", "expansion": "Open Worldwide Application Security Project", "domain": 2},
    {"acronym": "PaaS", "expansion": "Platform as a Service", "domain": 3},
    {"acronym": "PAM", "expansion": "Privileged Access Management", "domain": 4},
    {"acronym": "PAP", "expansion": "Password Authentication Protocol", "domain": 4},
    {"acronym": "PBKDF2", "expansion": "Password-Based Key Derivation Function 2", "domain": 1},
    {"acronym": "PCI DSS", "expansion": "Payment Card Industry Data Security Standard", "domain": 5},
    {"acronym": "PEAP", "expansion": "Protected Extensible Authentication Protocol", "domain": 4},
    {"acronym": "PGP", "expansion": "Pretty Good Privacy", "domain": 1},
    {"acronym": "PII", "expansion": "Personally Identifiable Information", "domain": 5},
    {"acronym": "PKI", "expansion": "Public Key Infrastructure", "domain": 1},
    {"acronym": "POP3", "expansion": "Post Office Protocol version 3", "domain": 4},
    {"acronym": "PPP", "expansion": "Point-to-Point Protocol", "domain": 3},
    {"acronym": "PPTP", "expansion": "Point-to-Point Tunneling Protocol", "domain": 3},
    {"acronym": "PtH", "expansion": "Pass the Hash", "domain": 2},
    {"acronym": "RA", "expansion": "Registration Authority", "domain": 1},
    {"acronym": "RADIUS", "expansion": "Remote Authentication Dial-In User Service", "domain": 4},
    {"acronym": "RAID", "expansion": "Redundant Array of Independent Disks", "domain": 3},
    {"acronym": "RAT", "expansion": "Remote Access Trojan", "domain": 2},
    {"acronym": "RBAC", "expansion": "Role-Based Access Control", "domain": 4},
    {"acronym": "RDP", "expansion": "Remote Desktop Protocol", "domain": 4},
    {"acronym": "RPO", "expansion": "Recovery Point Objective", "domain": 5},
    {"acronym": "RSA", "expansion": "Rivest, Shamir, Adleman", "domain": 1},
    {"acronym": "RTO", "expansion": "Recovery Time Objective", "domain": 5},
    {"acronym": "RTOS", "expansion": "Real-Time Operating System", "domain": 3},
    {"acronym": "S/MIME", "expansion": "Secure/Multipurpose Internet Mail Extensions", "domain": 4},
    {"acronym": "SaaS", "expansion": "Software as a Service", "domain": 3},
    {"acronym": "SAML", "expansion": "Security Assertion Markup Language", "domain": 4},
    {"acronym": "SASE", "expansion": "Secure Access Service Edge", "domain": 3},
    {"acronym": "SCADA", "expansion": "Supervisory Control and Data Acquisition", "domain": 3},
    {"acronym": "SCAP", "expansion": "Security Content Automation Protocol", "domain": 4},
    {"acronym": "SD-WAN", "expansion": "Software-Defined Wide Area Network", "domain": 3},
    {"acronym": "SDLC", "expansion": "Software Development Life Cycle", "domain": 4},
    {"acronym": "SDN", "expansion": "Software-Defined Networking", "domain": 3},
    {"acronym": "SED", "expansion": "Self-Encrypting Drive", "domain": 3},
    {"acronym": "SFTP", "expansion": "Secure File Transfer Protocol", "domain": 4},
    {"acronym": "SHA", "expansion": "Secure Hash Algorithm", "domain": 1},
    {"acronym": "SIEM", "expansion": "Security Information and Event Management", "domain": 4},
    {"acronym": "SLA", "expansion": "Service Level Agreement", "domain": 5},
    {"acronym": "SLE", "expansion": "Single Loss Expectancy", "domain": 5},
    {"acronym": "SMTP", "expansion": "Simple Mail Transfer Protocol", "domain": 4},
    {"acronym": "SMS", "expansion": "Short Message Service", "domain": 4},
    {"acronym": "SNMP", "expansion": "Simple Network Management Protocol", "domain": 4},
    {"acronym": "SOAR", "expansion": "Security Orchestration, Automation, and Response", "domain": 4},
    {"acronym": "SOC", "expansion": "Security Operations Center", "domain": 4},
    {"acronym": "SoW", "expansion": "Statement of Work", "domain": 5},
    {"acronym": "SPF", "expansion": "Sender Policy Framework", "domain": 4},
    {"acronym": "SQL", "expansion": "Structured Query Language", "domain": 2},
    {"acronym": "SQLi", "expansion": "SQL Injection", "domain": 2},
    {"acronym": "SSH", "expansion": "Secure Shell", "domain": 4},
    {"acronym": "SSL", "expansion": "Secure Sockets Layer", "domain": 3},
    {"acronym": "SSO", "expansion": "Single Sign-On", "domain": 4},
    {"acronym": "SSRF", "expansion": "Server-Side Request Forgery", "domain": 2},
    {"acronym": "STIX", "expansion": "Structured Threat Information eXpression", "domain": 4},
    {"acronym": "TACACS+", "expansion": "Terminal Access Controller Access-Control System Plus", "domain": 4},
    {"acronym": "TAXII", "expansion": "Trusted Automated eXchange of Intelligence Information", "domain": 4},
    {"acronym": "TCP", "expansion": "Transmission Control Protocol", "domain": 3},
    {"acronym": "TGT", "expansion": "Ticket Granting Ticket", "domain": 4},
    {"acronym": "TLS", "expansion": "Transport Layer Security", "domain": 3},
    {"acronym": "TOTP", "expansion": "Time-based One-Time Password", "domain": 4},
    {"acronym": "TPM", "expansion": "Trusted Platform Module", "domain": 1},
    {"acronym": "TTP", "expansion": "Tactics, Techniques, and Procedures", "domain": 2},
    {"acronym": "UDP", "expansion": "User Datagram Protocol", "domain": 3},
    {"acronym": "UEBA", "expansion": "User and Entity Behavior Analytics", "domain": 4},
    {"acronym": "UEFI", "expansion": "Unified Extensible Firmware Interface", "domain": 1},
    {"acronym": "UPS", "expansion": "Uninterruptible Power Supply", "domain": 3},
    {"acronym": "URL", "expansion": "Uniform Resource Locator", "domain": 3},
    {"acronym": "USB", "expansion": "Universal Serial Bus", "domain": 4},
    {"acronym": "UTM", "expansion": "Unified Threat Management", "domain": 3},
    {"acronym": "VDI", "expansion": "Virtual Desktop Infrastructure", "domain": 3},
    {"acronym": "VLAN", "expansion": "Virtual Local Area Network", "domain": 3},
    {"acronym": "VM", "expansion": "Virtual Machine", "domain": 3},
    {"acronym": "VPC", "expansion": "Virtual Private Cloud", "domain": 3},
    {"acronym": "VPN", "expansion": "Virtual Private Network", "domain": 3},
    {"acronym": "WAF", "expansion": "Web Application Firewall", "domain": 3},
    {"acronym": "WAP", "expansion": "Wireless Access Point", "domain": 4},
    {"acronym": "WEP", "expansion": "Wired Equivalent Privacy", "domain": 4},
    {"acronym": "WIDS", "expansion": "Wireless Intrusion Detection System", "domain": 4},
    {"acronym": "WIPS", "expansion": "Wireless Intrusion Prevention System", "domain": 4},
    {"acronym": "WORM", "expansion": "Write Once Read Many", "domain": 4},
    {"acronym": "WPA", "expansion": "Wi-Fi Protected Access", "domain": 4},
    {"acronym": "WPA2", "expansion": "Wi-Fi Protected Access 2", "domain": 4},
    {"acronym": "WPA3", "expansion": "Wi-Fi Protected Access 3", "domain": 4},
    {"acronym": "XDR", "expansion": "Extended Detection and Response", "domain": 4},
    {"acronym": "XML", "expansion": "Extensible Markup Language", "domain": 3},
    {"acronym": "XSS", "expansion": "Cross-Site Scripting", "domain": 2},
    {"acronym": "ZTNA", "expansion": "Zero Trust Network Access", "domain": 3},
]
