"""Security+ SY0-701 flashcard deck: definition -> term.

Covers core exam vocabulary across all five domains. Used by both the
multiple-choice and open-ended flashcard modes.
"""

CARDS = [
    # ---------------- Domain 1: General Security Concepts ----------------
    {"domain": 1, "study_topic": "Zero Trust architecture", "term": "Zero Trust",
     "definition": "A security model that assumes no implicit trust for any user or device, requiring continuous verification of every request regardless of network location."},
    {"domain": 1, "study_topic": "Zero Trust architecture", "term": "Policy Enforcement Point (PEP)",
     "definition": "The data-plane component in a Zero Trust architecture that actually allows, denies, or terminates a connection based on the policy engine's decision."},
    {"domain": 1, "study_topic": "Zero Trust architecture", "term": "Policy Engine",
     "definition": "The Zero Trust control-plane component that makes the grant/deny access decision by evaluating policy and trust data."},
    {"domain": 1, "study_topic": "CIA triad and non-repudiation", "term": "Non-repudiation",
     "definition": "Assurance that a party cannot deny the authenticity of their signature or a message they sent, commonly provided by digital signatures."},
    {"domain": 1, "study_topic": "AAA framework", "term": "Accounting",
     "definition": "The AAA component that tracks and records what an authenticated user does, such as resources accessed and commands run."},
    {"domain": 1, "study_topic": "Security control types", "term": "Compensating control",
     "definition": "An alternative control put in place when a primary control cannot be implemented, providing a comparable level of protection."},
    {"domain": 1, "study_topic": "Security control types", "term": "Detective control",
     "definition": "A control that identifies and alerts on an event during or after it occurs, such as a SIEM alert or IDS."},
    {"domain": 1, "study_topic": "Security control types", "term": "Deterrent control",
     "definition": "A control intended to discourage a threat actor from attempting an attack, such as warning signage or visible cameras."},
    {"domain": 1, "study_topic": "Security control categories", "term": "Managerial control",
     "definition": "An administrative control category consisting of policies, standards, and procedures that guide how security is governed."},
    {"domain": 1, "study_topic": "Gap analysis", "term": "Gap analysis",
     "definition": "An evaluation that compares the current security posture against a desired framework or baseline to identify shortfalls."},
    {"domain": 1, "study_topic": "Physical security", "term": "Access control vestibule",
     "definition": "A physical control with two interlocking doors that permits only one person through at a time to prevent tailgating (a mantrap)."},
    {"domain": 1, "study_topic": "Deception and disruption technologies", "term": "Honeytoken",
     "definition": "A piece of fake data (such as a bogus credential or record) planted to detect unauthorized access when it is used."},
    {"domain": 1, "study_topic": "Deception and disruption technologies", "term": "Honeypot",
     "definition": "A decoy system designed to attract attackers so their techniques can be observed and real systems protected."},
    {"domain": 1, "study_topic": "Certificates", "term": "OCSP stapling",
     "definition": "A method where the web server obtains and delivers a time-stamped, CA-signed certificate status during the TLS handshake, offloading revocation checks from clients."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate Revocation List (CRL)",
     "definition": "A CA-published list of certificates that have been revoked before their expiration date."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate Signing Request (CSR)",
     "definition": "A request containing a public key and identifying information sent to a CA to obtain a signed certificate."},
    {"domain": 1, "study_topic": "Certificates", "term": "Wildcard certificate",
     "definition": "A certificate that secures a domain and all of its first-level subdomains using an asterisk in the common name."},
    {"domain": 1, "study_topic": "Cryptographic hardware", "term": "Trusted Platform Module (TPM)",
     "definition": "A dedicated chip on a device's motherboard that securely stores keys and supports functions like full-disk encryption and boot attestation."},
    {"domain": 1, "study_topic": "Cryptographic hardware", "term": "Hardware Security Module (HSM)",
     "definition": "A dedicated, tamper-resistant appliance for generating, storing, and managing cryptographic keys at scale."},
    {"domain": 1, "study_topic": "Cryptographic hardware", "term": "Secure enclave",
     "definition": "An isolated processor region that protects sensitive data and keys even from the main operating system."},
    {"domain": 1, "study_topic": "Hashing and salting", "term": "Salting",
     "definition": "Adding random data to a password before hashing so identical passwords produce different hashes and rainbow tables are defeated."},
    {"domain": 1, "study_topic": "Hashing and salting", "term": "Key stretching",
     "definition": "Deliberately slowing a hashing process (e.g., PBKDF2, bcrypt) to make brute-force password cracking more expensive."},
    {"domain": 1, "study_topic": "Symmetric vs asymmetric encryption", "term": "Diffie-Hellman",
     "definition": "A key-exchange algorithm that lets two parties establish a shared secret over an insecure channel without transmitting the secret itself."},
    {"domain": 1, "study_topic": "Obfuscation techniques", "term": "Tokenization",
     "definition": "Replacing sensitive data with a non-sensitive substitute value (token) that maps back to the original via a secure lookup vault."},
    {"domain": 1, "study_topic": "Obfuscation techniques", "term": "Data masking",
     "definition": "Obscuring parts of data (e.g., showing only the last four digits) so the full value is hidden from unauthorized viewers."},
    {"domain": 1, "study_topic": "Blockchain and open public ledger", "term": "Blockchain",
     "definition": "A distributed, append-only ledger where each block is cryptographically linked to the previous one, making tampering evident."},
    {"domain": 1, "study_topic": "Change management", "term": "Backout plan",
     "definition": "A predefined procedure to revert a change and restore the prior state if the change fails or causes problems."},

    # ---------------- Domain 2: Threats, Vulnerabilities, Mitigations ----------------
    {"domain": 2, "study_topic": "Social engineering", "term": "Pretexting",
     "definition": "Creating a fabricated scenario or false identity to manipulate a victim into divulging information or performing an action."},
    {"domain": 2, "study_topic": "Social engineering", "term": "Business email compromise (BEC)",
     "definition": "An attack in which a spoofed or hijacked executive email account is used to trick employees into wiring funds or sharing data."},
    {"domain": 2, "study_topic": "Social engineering", "term": "Watering hole attack",
     "definition": "Compromising a legitimate website frequently visited by the target group so their systems become infected."},
    {"domain": 2, "study_topic": "Social engineering", "term": "Typosquatting",
     "definition": "Registering domains that resemble a legitimate site's name to catch users who mistype the URL."},
    {"domain": 2, "study_topic": "Malware types", "term": "Logic bomb",
     "definition": "Malicious code that stays dormant until triggered by a specific condition, such as a date or an event."},
    {"domain": 2, "study_topic": "Malware types", "term": "Rootkit",
     "definition": "Malware that hides its presence and provides privileged access by altering the operating system, often at the kernel level."},
    {"domain": 2, "study_topic": "Malware types", "term": "Worm",
     "definition": "Self-replicating malware that spreads across networks without user interaction or a host file."},
    {"domain": 2, "study_topic": "Web application vulnerabilities", "term": "Cross-site request forgery (CSRF)",
     "definition": "An attack that tricks an authenticated user's browser into submitting an unwanted request to a site they are logged into."},
    {"domain": 2, "study_topic": "Web application vulnerabilities", "term": "Cross-site scripting (XSS)",
     "definition": "Injecting malicious scripts into web pages that execute in other users' browsers."},
    {"domain": 2, "study_topic": "Web application vulnerabilities", "term": "SQL injection",
     "definition": "Inserting malicious SQL through input fields to manipulate or extract data from a backend database."},
    {"domain": 2, "study_topic": "Application vulnerabilities", "term": "Race condition (TOCTOU)",
     "definition": "A flaw where the outcome depends on timing between a check and its use, allowing manipulation in the gap (time-of-check to time-of-use)."},
    {"domain": 2, "study_topic": "Network attacks", "term": "On-path attack",
     "definition": "An attack where the adversary secretly relays and possibly alters communications between two parties (formerly man-in-the-middle)."},
    {"domain": 2, "study_topic": "Network attacks", "term": "DNS amplification",
     "definition": "A reflected DDoS technique that spoofs the victim's IP on small DNS queries so large responses flood the target."},
    {"domain": 2, "study_topic": "Cryptographic attacks", "term": "Birthday attack",
     "definition": "A brute-force method exploiting the probability of hash collisions, based on the birthday paradox."},
    {"domain": 2, "study_topic": "Cryptographic attacks", "term": "Downgrade attack",
     "definition": "Forcing a connection to use a weaker, older protocol or cipher that is easier to break."},
    {"domain": 2, "study_topic": "Indicators of malicious activity", "term": "Impossible travel",
     "definition": "An indicator where a single account logs in from geographically distant locations in a timeframe too short to physically travel."},
    {"domain": 2, "study_topic": "Threat actors", "term": "Shadow IT",
     "definition": "Hardware, software, or services used within an organization without explicit approval from the IT or security team."},
    {"domain": 2, "study_topic": "Physical attacks", "term": "RFID cloning",
     "definition": "Copying the data from a proximity access card or badge to create an unauthorized duplicate."},
    {"domain": 2, "study_topic": "Vulnerability scan and assessment result classification", "term": "False negative",
     "definition": "A real vulnerability or attack that a tool fails to detect or report — the most dangerous scan result."},
    {"domain": 2, "study_topic": "Mitigation techniques", "term": "Segmentation",
     "definition": "Dividing a network into isolated zones to limit lateral movement and contain the impact of a compromise."},
    {"domain": 2, "study_topic": "Password attacks", "term": "Password spraying",
     "definition": "Trying a few common passwords against many accounts to avoid triggering per-account lockouts."},

    # ---------------- Domain 3: Security Architecture ----------------
    {"domain": 3, "study_topic": "Firewalls", "term": "Web Application Firewall (WAF)",
     "definition": "A firewall that inspects HTTP/HTTPS traffic to protect web apps from attacks like SQL injection and XSS at Layer 7."},
    {"domain": 3, "study_topic": "Firewalls", "term": "Next-Generation Firewall (NGFW)",
     "definition": "A firewall that adds deep packet inspection, application awareness, and integrated IPS beyond traditional port/protocol filtering."},
    {"domain": 3, "study_topic": "Recovery sites", "term": "Hot site",
     "definition": "A fully equipped, continuously running alternate site that can take over operations almost immediately after a disaster."},
    {"domain": 3, "study_topic": "Recovery sites", "term": "Cold site",
     "definition": "An alternate location with space and utilities but no configured hardware or data, requiring significant setup before use."},
    {"domain": 3, "study_topic": "Data states", "term": "Data in use",
     "definition": "Data actively being processed in memory or by an application, protected by techniques like secure enclaves and access controls."},
    {"domain": 3, "study_topic": "Secure communication (VPN/TLS/IPSec)", "term": "IPsec tunnel mode",
     "definition": "An IPsec mode that encrypts the entire original IP packet and adds a new header, used for site-to-site VPNs."},
    {"domain": 3, "study_topic": "High availability", "term": "Load balancing",
     "definition": "Distributing traffic across multiple servers to improve availability, performance, and fault tolerance."},
    {"domain": 3, "study_topic": "Backups and replication", "term": "Journaling",
     "definition": "Recording changes in a log before committing them so data can be recovered to a consistent state after a failure."},
    {"domain": 3, "study_topic": "SDN and logical segmentation", "term": "Software-defined networking (SDN)",
     "definition": "An architecture that separates the network control plane from the data plane, enabling centralized, programmable management."},
    {"domain": 3, "study_topic": "Zero Trust / SASE", "term": "SASE",
     "definition": "Secure Access Service Edge — a cloud model that converges networking (SD-WAN) and security services (SWG, CASB, ZTNA) at the edge."},
    {"domain": 3, "study_topic": "ICS/SCADA and embedded systems", "term": "SCADA",
     "definition": "Supervisory Control and Data Acquisition — systems that monitor and control industrial processes and infrastructure."},
    {"domain": 3, "study_topic": "Failure modes", "term": "Fail-closed",
     "definition": "A design where a control blocks traffic or denies access if it fails, favoring security over availability."},
    {"domain": 3, "study_topic": "Third-party agreement types", "term": "Memorandum of Understanding (MOU)",
     "definition": "A non-binding agreement outlining the intentions and general terms between parties."},

    # ---------------- Domain 4: Security Operations ----------------
    {"domain": 4, "study_topic": "Incident response process", "term": "Containment",
     "definition": "The incident response phase focused on limiting the spread and impact of an incident before eradication."},
    {"domain": 4, "study_topic": "Email security (SPF/DKIM/DMARC)", "term": "DMARC",
     "definition": "An email policy that builds on SPF and DKIM, tells receivers how to handle failures, and provides sender reporting."},
    {"domain": 4, "study_topic": "Email security (SPF/DKIM/DMARC)", "term": "SPF",
     "definition": "A DNS record listing which mail servers are authorized to send email for a domain."},
    {"domain": 4, "study_topic": "Email security (SPF/DKIM/DMARC)", "term": "DKIM",
     "definition": "An email authentication method that adds a cryptographic signature verified via the sender's DNS public key."},
    {"domain": 4, "study_topic": "Access control models", "term": "Attribute-based access control (ABAC)",
     "definition": "An access model that grants access by evaluating attributes of the user, resource, action, and environment."},
    {"domain": 4, "study_topic": "Access control models", "term": "Mandatory access control (MAC)",
     "definition": "An access model where the system enforces access based on labels and clearances, and users cannot change permissions."},
    {"domain": 4, "study_topic": "Privileged access management", "term": "Just-in-time (JIT) access",
     "definition": "Granting elevated privileges only for a limited, approved time window and revoking them automatically afterward."},
    {"domain": 4, "study_topic": "SIEM & monitoring", "term": "SIEM",
     "definition": "Security Information and Event Management — a platform that aggregates and correlates logs from many sources to detect threats."},
    {"domain": 4, "study_topic": "EDR/XDR & DLP", "term": "EDR",
     "definition": "Endpoint Detection and Response — continuously records endpoint telemetry and enables investigation and response like isolation."},
    {"domain": 4, "study_topic": "EDR/XDR & DLP", "term": "Data Loss Prevention (DLP)",
     "definition": "Technology that detects and blocks sensitive data from leaving the organization across email, web, and endpoints."},
    {"domain": 4, "study_topic": "Vulnerability management & CVSS", "term": "CVSS base score",
     "definition": "The intrinsic severity rating of a vulnerability, independent of environment or current exploitation."},
    {"domain": 4, "study_topic": "Digital forensics", "term": "Order of volatility",
     "definition": "The sequence for collecting evidence from most to least perishable — registers/cache and RAM before disk and archives."},
    {"domain": 4, "study_topic": "Digital forensics and chain-of-custody process", "term": "Legal hold",
     "definition": "A formal process that preserves potentially relevant data and suspends its normal deletion when litigation is anticipated."},
    {"domain": 4, "study_topic": "Multifactor authentication", "term": "Something you are",
     "definition": "The inherence authentication factor category, based on biometrics like fingerprints or facial recognition."},
    {"domain": 4, "study_topic": "Federation & SSO (SAML/OAuth)", "term": "SAML",
     "definition": "An XML-based standard for exchanging authentication assertions, enabling federated web single sign-on between an IdP and service providers."},
    {"domain": 4, "study_topic": "Wireless security", "term": "WPA3-Enterprise",
     "definition": "The enterprise Wi-Fi security mode using 802.1X with a RADIUS server for per-user authentication."},
    {"domain": 4, "study_topic": "Hardening & secure baselines", "term": "Least functionality",
     "definition": "The hardening principle of running only the services, software, and ports required for a system's purpose."},
    {"domain": 4, "study_topic": "Automation & orchestration", "term": "SOAR",
     "definition": "Security Orchestration, Automation, and Response — tools that automate playbook-driven responses across security systems."},
    {"domain": 4, "study_topic": "Incident response process", "term": "Threat hunting",
     "definition": "Proactively searching telemetry with hypotheses about adversary techniques to find intrusions that evaded automated detection."},
    {"domain": 4, "study_topic": "Port and protocol security", "term": "Port 3389",
     "definition": "The default TCP port used by RDP (Remote Desktop Protocol)."},
    {"domain": 4, "study_topic": "Asset management", "term": "Certificate of destruction",
     "definition": "Documentation proving that data-bearing media was securely destroyed, including method, date, and serial numbers."},

    # ---------------- Domain 5: Program Management & Oversight ----------------
    {"domain": 5, "study_topic": "Quantitative risk analysis (SLE/ALE/ARO)", "term": "Single Loss Expectancy (SLE)",
     "definition": "The expected monetary loss from a single occurrence of a risk, calculated as Asset Value multiplied by Exposure Factor."},
    {"domain": 5, "study_topic": "Quantitative risk analysis (SLE/ALE/ARO)", "term": "Annualized Loss Expectancy (ALE)",
     "definition": "The expected yearly monetary loss from a risk, calculated as SLE multiplied by the Annualized Rate of Occurrence."},
    {"domain": 5, "study_topic": "Quantitative risk analysis (SLE/ALE/ARO)", "term": "Annualized Rate of Occurrence (ARO)",
     "definition": "The estimated number of times a specific risk event is expected to occur in a single year."},
    {"domain": 5, "study_topic": "Business impact analysis (RTO/RPO/MTTR/MTBF)", "term": "Recovery Time Objective (RTO)",
     "definition": "The maximum acceptable length of time to restore a system or process after a disruption."},
    {"domain": 5, "study_topic": "Business impact analysis (RTO/RPO/MTTR/MTBF)", "term": "Recovery Point Objective (RPO)",
     "definition": "The maximum acceptable amount of data loss measured in time — how far back the last usable backup can be."},
    {"domain": 5, "study_topic": "Business impact analysis (RTO/RPO/MTTR/MTBF)", "term": "Mean Time To Repair (MTTR)",
     "definition": "The average time required to repair a failed component or system and return it to service."},
    {"domain": 5, "study_topic": "Business impact analysis (RTO/RPO/MTTR/MTBF)", "term": "Mean Time Between Failures (MTBF)",
     "definition": "The average operational time between failures of a repairable system, indicating reliability."},
    {"domain": 5, "study_topic": "Risk management strategies", "term": "Risk transference",
     "definition": "Shifting the financial impact of a risk to a third party, typically through insurance or outsourcing."},
    {"domain": 5, "study_topic": "Risk register & appetite", "term": "Risk appetite",
     "definition": "The amount and type of risk an organization is willing to accept in pursuit of its objectives."},
    {"domain": 5, "study_topic": "Third-party agreements (SLA/MOU/MSA/BPA)", "term": "Service Level Agreement (SLA)",
     "definition": "A contract defining measurable service expectations, such as uptime and response times, between provider and customer."},
    {"domain": 5, "study_topic": "Third-party agreements (SLA/MOU/MSA/BPA)", "term": "Master Service Agreement (MSA)",
     "definition": "An overarching contract setting general terms so future work can be authorized via simpler statements of work."},
    {"domain": 5, "study_topic": "Third-party agreements (SLA/MOU/MSA/BPA)", "term": "Business Partners Agreement (BPA)",
     "definition": "An agreement defining the terms, responsibilities, and profit/loss sharing between business partners."},
    {"domain": 5, "study_topic": "Compliance & privacy (GDPR)", "term": "Right to be forgotten",
     "definition": "The GDPR data-subject right to have personal data erased under certain conditions."},
    {"domain": 5, "study_topic": "Data roles (controller/processor/custodian)", "term": "Data controller",
     "definition": "The party that determines the purposes and means of processing personal data."},
    {"domain": 5, "study_topic": "Data roles (controller/processor/custodian)", "term": "Data processor",
     "definition": "The party that processes personal data on behalf of, and under the instructions of, the data controller."},
    {"domain": 5, "study_topic": "Audits & penetration testing", "term": "Known environment test",
     "definition": "A penetration test where the tester is given full knowledge of the target (white-box)."},
    {"domain": 5, "study_topic": "Audits & penetration testing", "term": "Attestation",
     "definition": "A formal declaration, often by an independent auditor, confirming that controls or statements are accurate."},
    {"domain": 5, "study_topic": "Security awareness training", "term": "Phishing simulation",
     "definition": "A controlled fake phishing campaign used to measure and improve employees' ability to recognize and report attacks."},
    {"domain": 5, "study_topic": "Secure asset decommissioning and media sanitization", "term": "Cryptographic erase",
     "definition": "Sanitizing a self-encrypting drive by destroying its encryption key, rendering the data unrecoverable while keeping the drive usable."},
    {"domain": 5, "study_topic": "Vendor risk management", "term": "Right-to-audit clause",
     "definition": "A contract provision allowing a customer to review a vendor's security controls and compliance."},
    {"domain": 5, "study_topic": "Security governance & policies", "term": "Standard",
     "definition": "A mandatory rule that specifies how a policy is implemented, such as a required encryption algorithm or password length."},
]
