QUESTIONS = [
    {
        "id": "a1d4-001",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud service models",
        "stem": "A development team wants to deploy and run their custom web application without managing the underlying operating system, runtime patching, or server hardware, but they still need to write and control the application code itself. Which cloud service model BEST fits?",
        "options": [
            {"id": "a", "text": "Platform as a Service (PaaS)", "correct": True, "rationale": "Correct. PaaS provides a managed runtime/platform (OS, middleware, runtime are handled by the provider) on which the customer deploys and controls their own application code — exactly the described split of responsibility."},
            {"id": "b", "text": "Infrastructure as a Service (IaaS)", "correct": False, "rationale": "Incorrect. With IaaS the customer still manages the OS, patching, and runtime on provisioned VMs, which the team explicitly does NOT want to do."},
            {"id": "c", "text": "Software as a Service (SaaS)", "correct": False, "rationale": "Incorrect. SaaS delivers finished applications (e.g., email, CRM) to end users; the customer does not deploy their own custom application code."},
            {"id": "d", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS delivers virtual desktops to users; it is not a platform for hosting a custom web application."},
        ],
        "explanation": "IaaS = you manage OS and up (most control/effort); PaaS = provider manages the platform/OS, you manage just your app and data; SaaS = provider manages everything and you consume the finished app. A team wanting to run custom code without managing the OS wants PaaS.",
    },
    {
        "id": "a1d4-002",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud service models",
        "stem": "A company migrates its ERP system to a cloud provider. The provider now manages the entire stack — servers, OS, middleware, and the ERP application itself — and the company's employees simply log in via a browser. Which cloud service model is in use?",
        "options": [
            {"id": "a", "text": "Infrastructure as a Service (IaaS)", "correct": False, "rationale": "Incorrect. IaaS provides raw compute, storage, and networking, but the customer still manages the OS and applications. The company here manages nothing above the browser."},
            {"id": "b", "text": "Platform as a Service (PaaS)", "correct": False, "rationale": "Incorrect. PaaS lets customers deploy their own application code; the company here is simply consuming an existing ERP application, not writing code for the platform."},
            {"id": "c", "text": "Software as a Service (SaaS)", "correct": True, "rationale": "Correct. SaaS delivers a complete, ready-to-use application over the Internet. The provider manages the entire stack; users consume the finished software through a browser or thin client."},
            {"id": "d", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS delivers a virtual desktop environment, not a specific hosted business application like an ERP. The scenario describes consuming a finished application, not a full virtual desktop."},
        ],
        "explanation": "SaaS is the 'highest' abstraction model: the customer manages only their own data and user configuration; the provider handles everything else. Common SaaS examples are Microsoft 365, Salesforce, and hosted ERP systems.",
    },
    {
        "id": "a1d4-003",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud service models",
        "stem": "An enterprise rents raw virtual machines from a cloud provider. The enterprise's operations team installs the OS, applies patches, installs middleware, and deploys applications on those VMs. Under the shared-responsibility model, which layer does the CLOUD PROVIDER manage?",
        "options": [
            {"id": "a", "text": "Operating system patching and updates", "correct": False, "rationale": "Incorrect. Under IaaS, the customer (enterprise) is responsible for OS installation, patching, and updates on the rented VMs."},
            {"id": "b", "text": "Virtualization layer, physical servers, networking, and storage hardware", "correct": True, "rationale": "Correct. In IaaS the provider owns and manages the physical data center, hardware, hypervisor/virtualization layer, and physical network. Everything from the OS upward is the customer's responsibility."},
            {"id": "c", "text": "Application runtime, middleware, and databases installed on the VMs", "correct": False, "rationale": "Incorrect. The customer installs and manages all middleware, databases, and runtime environments on the IaaS VMs; the provider does not touch these layers."},
            {"id": "d", "text": "Application code and data stored on the VMs", "correct": False, "rationale": "Incorrect. Customer data and application code are always the customer's responsibility regardless of service model."},
        ],
        "explanation": "The IaaS shared-responsibility boundary sits below the OS. The provider ensures the physical hosts, network fabric, storage hardware, and hypervisor are available and secure. The customer owns everything from the guest OS upward, making IaaS the most customer-controlled (and most customer-managed) cloud model.",
    },
    {
        "id": "a1d4-004",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models",
        "stem": "A hospital system requires strict data-sovereignty controls: patient records must stay on hardware owned and operated exclusively by the hospital within its own data centers, yet administrators still want cloud-like self-service provisioning and elastic resource pools. Which cloud deployment model BEST meets these requirements?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": False, "rationale": "Incorrect. Public cloud infrastructure is owned and operated by a third-party provider and shared among many tenants, which violates the hospital's data-sovereignty and exclusive-ownership requirements."},
            {"id": "b", "text": "Community cloud", "correct": False, "rationale": "Incorrect. Community cloud shares infrastructure among organizations with similar concerns (e.g., healthcare providers), but the hardware is typically not exclusively owned by one organization and may still be off-premises."},
            {"id": "c", "text": "Private cloud", "correct": True, "rationale": "Correct. A private cloud is dedicated to a single organization. The hardware is owned and operated exclusively by (or for) that organization — on-premises or in a hosted private facility — satisfying data-sovereignty requirements while providing cloud-like self-service elasticity."},
            {"id": "d", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. A hybrid cloud intentionally combines private and public cloud environments. If patient data must stay exclusively on hospital-owned hardware, extending to public cloud would violate data-sovereignty rules."},
        ],
        "explanation": "Private cloud = single-tenant, organization-owned infrastructure with cloud automation/orchestration. Public cloud = multi-tenant, provider-owned. Hybrid = mix of both. Community = shared among organizations with a common mission or compliance need. Data-sovereignty + exclusive hardware ownership = private cloud.",
    },
    {
        "id": "a1d4-005",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models",
        "stem": "A retail company runs its core inventory database in its own on-premises data center but uses a public cloud provider to handle surge traffic during holiday sales events. The on-premises environment and the public cloud are connected and managed as a single integrated environment. This is an example of which cloud deployment model?",
        "options": [
            {"id": "a", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is a single-organization environment on dedicated infrastructure; it does not incorporate a public cloud provider."},
            {"id": "b", "text": "Community cloud", "correct": False, "rationale": "Incorrect. Community cloud is shared among multiple organizations with common concerns; it does not describe on-premises integration with a public provider for traffic bursting."},
            {"id": "c", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. A hybrid cloud connects and integrates on-premises (private) infrastructure with public cloud resources, allowing workloads to move between them — the classic 'cloud bursting' scenario described here."},
            {"id": "d", "text": "Public cloud", "correct": False, "rationale": "Incorrect. Public cloud is entirely provider-owned and off-premises; the scenario explicitly includes an on-premises core that is integrated with the cloud environment."},
        ],
        "explanation": "Hybrid cloud = two or more distinct cloud environments (typically private/on-premises + public) bound together by technology that allows data and application portability. Cloud bursting — using public cloud for peak demand while keeping normal workloads on-premises — is a classic hybrid cloud use case.",
    },
    {
        "id": "a1d4-006",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud characteristics",
        "stem": "An e-commerce platform automatically provisions 50 additional web server instances within two minutes when traffic spikes to 10× the baseline load, then terminates those instances when traffic returns to normal. Which cloud characteristic is PRIMARILY being demonstrated?",
        "options": [
            {"id": "a", "text": "High availability", "correct": False, "rationale": "Incorrect. High availability (HA) refers to the ability of a system to remain operational despite component failures, typically measured as uptime percentage (e.g., 99.999%). It does not inherently describe dynamic resource scaling."},
            {"id": "b", "text": "Metered utilization", "correct": False, "rationale": "Incorrect. Metered utilization (pay-as-you-go) refers to billing resources by actual consumption, not to the act of automatically adding or removing instances in response to demand."},
            {"id": "c", "text": "Rapid elasticity", "correct": True, "rationale": "Correct. Rapid elasticity is the ability to quickly scale resources outward (provision) and inward (de-provision) to match demand, often automatically. The scenario describes exactly this: auto-scaling in and out based on load."},
            {"id": "d", "text": "Shared resources", "correct": False, "rationale": "Incorrect. Shared resources (resource pooling) refers to the provider serving multiple tenants from the same physical infrastructure. While related to elasticity, it is not the characteristic being demonstrated by the auto-scaling behavior described."},
        ],
        "explanation": "The five NIST essential characteristics of cloud computing are: on-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service. Rapid elasticity specifically means resources can be provisioned and released automatically (or quickly) to scale with demand — the automatic scale-out/in described is a textbook example.",
    },
    {
        "id": "a1d4-007",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud characteristics",
        "stem": "A company migrates to a cloud platform and receives a monthly bill calculated by the exact number of CPU-hours, gigabytes of storage consumed, and gigabytes of data transferred during that billing period. Which cloud characteristic does this billing model reflect?",
        "options": [
            {"id": "a", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity is the ability to scale resources up and down quickly on demand; it describes the behavior of provisioning, not the billing methodology."},
            {"id": "b", "text": "High availability", "correct": False, "rationale": "Incorrect. High availability refers to uptime and fault tolerance guarantees (SLA), not to how the customer is charged for usage."},
            {"id": "c", "text": "Metered utilization (measured service)", "correct": True, "rationale": "Correct. Metered utilization (also called measured service or pay-as-you-go) means cloud resource usage is monitored, measured, and reported transparently, and customers are billed only for what they consume. CPU-hours, storage GB, and data transfer GB are classic metered metrics."},
            {"id": "d", "text": "Resource pooling", "correct": False, "rationale": "Incorrect. Resource pooling means the provider serves multiple tenants from shared physical resources. It is a delivery mechanism, not a billing model."},
        ],
        "explanation": "Measured service / metered utilization is one of NIST's essential cloud characteristics. It enables the pay-as-you-go model where costs are proportional to consumption. Customers pay only for compute time, storage, bandwidth, etc. that they actually use rather than purchasing fixed capacity upfront.",
    },
    {
        "id": "a1d4-008",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud characteristics",
        "stem": "A SaaS vendor guarantees that its service will be operational and accessible 99.99% of the time in any given calendar month, and achieves this through redundant data centers, automatic failover, and load balancing. Which cloud characteristic is the SLA PRIMARILY describing?",
        "options": [
            {"id": "a", "text": "Scalability", "correct": False, "rationale": "Incorrect. Scalability is the ability to handle growing workloads by adding resources (vertically or horizontally). While redundant infrastructure can help scalability, the SLA guarantee of continuous uptime specifically addresses availability, not growth capacity."},
            {"id": "b", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity specifically addresses dynamic scaling up and down of resources in response to demand. A fixed uptime percentage SLA describes availability, not elasticity."},
            {"id": "c", "text": "High availability", "correct": True, "rationale": "Correct. High availability (HA) is defined by a system's ability to remain operational and accessible despite failures, expressed as an uptime percentage. 99.99% uptime (~52 minutes/year downtime) achieved through redundant data centers and automatic failover is a classic HA architecture."},
            {"id": "d", "text": "File synchronization", "correct": False, "rationale": "Incorrect. File synchronization refers to keeping data consistent across devices or locations (e.g., cloud storage sync). It is not related to the uptime SLA guarantee described."},
        ],
        "explanation": "High availability is typically expressed as 'nines' of uptime: 99.9% (~8.7 hrs downtime/year), 99.99% (~52 min/year), 99.999% (~5.26 min/year). Achieving HA requires eliminating single points of failure through redundancy, load balancing, geographic distribution, and automatic failover — all mentioned in the scenario.",
    },
    {
        "id": "a1d4-009",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VDI/DaaS",
        "stem": "A company deploys virtual desktops where each desktop OS and its user profile reside on servers in the company's own on-premises data center. Users connect from thin clients using RDP. The IT department manages all hypervisors, storage, and the VDI broker. Which deployment type does this describe?",
        "options": [
            {"id": "a", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS is VDI hosted by a third-party cloud provider; the provider manages the infrastructure. This scenario has all infrastructure on-premises and managed by the company's own IT team."},
            {"id": "b", "text": "On-premises VDI", "correct": True, "rationale": "Correct. On-premises VDI means the virtual desktop infrastructure (hypervisors, storage, VDI broker, desktop images) is hosted in the organization's own data center and managed entirely by its own IT staff. Users connect remotely via thin clients."},
            {"id": "c", "text": "Public cloud IaaS", "correct": False, "rationale": "Incorrect. IaaS in a public cloud places the hypervisor and hardware under the cloud provider's control. The scenario explicitly states on-premises hardware managed by the company's IT department."},
            {"id": "d", "text": "Hybrid cloud VDI", "correct": False, "rationale": "Incorrect. Hybrid cloud VDI would integrate both on-premises and public cloud resources. The scenario is entirely on-premises with no cloud component mentioned."},
        ],
        "explanation": "VDI can be on-premises (company owns and manages all the infrastructure) or cloud-based (DaaS, where a provider hosts and manages the virtual desktop infrastructure). On-premises VDI gives maximum control and keeps data in-house but requires capital investment; DaaS shifts to an operational expense model with the provider managing infrastructure.",
    },
    {
        "id": "a1d4-010",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VDI/DaaS",
        "stem": "A startup wants to give 200 remote employees access to a fully managed Windows 10 virtual desktop environment. The startup does NOT want to purchase servers, storage, or VDI broker software — they want to pay a per-user monthly fee and have the provider handle all infrastructure and desktop management. Which solution BEST fits?",
        "options": [
            {"id": "a", "text": "On-premises VDI using VMware Horizon", "correct": False, "rationale": "Incorrect. On-premises VDI requires purchasing and managing servers, storage, licensing, and VDI broker software — exactly what the startup wants to avoid."},
            {"id": "b", "text": "Desktop as a Service (DaaS)", "correct": True, "rationale": "Correct. DaaS delivers virtual desktops from a cloud provider's infrastructure on a per-user subscription basis. The provider manages all underlying hardware, hypervisors, and often the desktop OS images, matching the startup's desire to avoid capital expenditure and infrastructure management."},
            {"id": "c", "text": "Software as a Service (SaaS) productivity suite", "correct": False, "rationale": "Incorrect. A SaaS productivity suite (e.g., Microsoft 365) provides hosted applications, not a full virtual Windows desktop environment where the user controls the OS and can install arbitrary applications."},
            {"id": "d", "text": "Platform as a Service (PaaS) container hosting", "correct": False, "rationale": "Incorrect. PaaS container hosting is for deploying applications, not for delivering virtual desktop environments to end users."},
        ],
        "explanation": "DaaS is essentially VDI delivered as a cloud service. Providers (e.g., Amazon WorkSpaces, Azure Virtual Desktop, Citrix DaaS) host the virtual desktops and charge per user per month. The customer avoids capital expenditure on hardware and VDI software licensing while still giving users a full desktop experience.",
    },
    {
        "id": "a1d4-011",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud characteristics",
        "stem": "A cloud storage service automatically replicates files edited on a user's laptop to servers in the cloud and then pushes those updates to the same user's smartphone and tablet within seconds. A second user who shares the folder sees the updated file appear on all their devices as well. Which cloud feature is PRIMARILY being described?",
        "options": [
            {"id": "a", "text": "High availability", "correct": False, "rationale": "Incorrect. High availability means the service remains accessible despite failures. While the replication infrastructure contributes to HA, the scenario specifically describes keeping file copies consistent across multiple devices and users in near-real time, which is a distinct feature."},
            {"id": "b", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity is the ability to dynamically scale compute or storage resources up and down. The scenario is about keeping files consistent across devices, not about scaling resources."},
            {"id": "c", "text": "File synchronization", "correct": True, "rationale": "Correct. File synchronization is the cloud feature of keeping files consistent (same version) across multiple devices and users in near-real time. Services like Dropbox, OneDrive, and Google Drive exemplify this — edits on one device propagate to all connected devices automatically."},
            {"id": "d", "text": "Metered utilization", "correct": False, "rationale": "Incorrect. Metered utilization is a billing model based on consumption. It does not describe the mechanism of propagating file changes to multiple devices."},
        ],
        "explanation": "File synchronization in cloud storage keeps data consistent across devices and among shared users. The sync client detects local changes, uploads them to the cloud, and the cloud service propagates the changes to all other connected clients. This is distinct from HA (uptime), elasticity (scaling), and metered billing.",
    },
    {
        "id": "a1d4-012",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Hypervisor types",
        "stem": "A data center deploys VMware ESXi directly on bare-metal servers without a host operating system underneath. ESXi has direct access to the physical hardware and uses its own kernel to manage virtual machines. Which type of hypervisor is this, and what is its MAIN advantage over the alternative type?",
        "options": [
            {"id": "a", "text": "Type 2 hypervisor; it is easier to install because it runs on top of an existing OS", "correct": False, "rationale": "Incorrect. VMware ESXi is a Type 1 (bare-metal) hypervisor that runs directly on hardware without a host OS. Ease of installation is actually the advantage of Type 2, not Type 1."},
            {"id": "b", "text": "Type 1 hypervisor; it provides lower overhead and better performance because there is no host OS consuming resources", "correct": True, "rationale": "Correct. ESXi is a Type 1 (bare-metal) hypervisor. Because there is no general-purpose host OS layer between the hypervisor and the hardware, there is less overhead, better hardware access, and higher performance — the primary advantage of Type 1 over Type 2."},
            {"id": "c", "text": "Type 2 hypervisor; it allows multiple host OSes to run simultaneously", "correct": False, "rationale": "Incorrect. Type 2 hypervisors run on top of a single host OS (e.g., Windows or Linux) and do not inherently support multiple host OSes. ESXi is Type 1, not Type 2."},
            {"id": "d", "text": "Type 1 hypervisor; it is better suited for developer laptops because it requires a host OS for driver support", "correct": False, "rationale": "Incorrect. Type 1 hypervisors do NOT require a host OS — that is the defining characteristic of Type 2. Developer laptop suitability is actually an advantage of Type 2 hypervisors like VMware Workstation or VirtualBox."},
        ],
        "explanation": "Type 1 (bare-metal) hypervisors (VMware ESXi, Microsoft Hyper-V, Xen) run directly on hardware. Type 2 (hosted) hypervisors (VirtualBox, VMware Workstation/Player, Parallels) run as applications on top of a host OS. Type 1 delivers better performance and is used in production data centers; Type 2 is easier to set up and preferred for development/testing on workstations.",
    },
    {
        "id": "a1d4-013",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Hypervisor types",
        "stem": "A software developer installs Oracle VirtualBox on their Windows 11 laptop to run a Linux virtual machine for testing. VirtualBox runs as a standard application within Windows. Which hypervisor type is this, and what is its PRIMARY limitation compared to the alternative?",
        "options": [
            {"id": "a", "text": "Type 1; it has limited hardware driver support because it lacks a host OS", "correct": False, "rationale": "Incorrect. VirtualBox is a Type 2 (hosted) hypervisor, not Type 1. The limitation described — lack of host OS driver support — is actually characteristic of Type 1, not Type 2."},
            {"id": "b", "text": "Type 2; VMs compete for resources with the host OS, resulting in higher overhead and lower VM performance than a bare-metal hypervisor", "correct": True, "rationale": "Correct. VirtualBox is a Type 2 (hosted) hypervisor. Because it runs on top of Windows, VMs share CPU, RAM, and I/O with the host OS processes, adding overhead and reducing performance compared to a Type 1 hypervisor with direct hardware access."},
            {"id": "c", "text": "Type 2; it cannot run on consumer hardware and requires server-grade CPUs", "correct": False, "rationale": "Incorrect. Type 2 hypervisors are specifically designed for consumer workstations and laptops. The scenario describes exactly that use case. No server-grade hardware is required."},
            {"id": "d", "text": "Type 1; the developer needs to partition the hard disk before installing it alongside Windows", "correct": False, "rationale": "Incorrect. VirtualBox is Type 2, not Type 1. Disk partitioning is associated with dual-booting, not hypervisor type."},
        ],
        "explanation": "Type 2 hypervisors (VirtualBox, VMware Workstation/Fusion, Parallels) run as applications atop a host OS. They are easy to install and great for developer workstations. Their main disadvantage is the overhead introduced by the host OS layer: VMs must compete with host OS processes for CPU and memory, resulting in lower performance than Type 1 bare-metal hypervisors used in data centers.",
    },
    {
        "id": "a1d4-014",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VM use cases",
        "stem": "A cybersecurity analyst needs to open a potentially malicious email attachment to examine its behavior without risking the production workstation. They run the file inside a virtual machine, observe its activity, then delete the VM snapshot to return to a clean state. Which VM use case does this BEST describe?",
        "options": [
            {"id": "a", "text": "Application virtualization", "correct": False, "rationale": "Incorrect. Application virtualization packages an application and its dependencies to run in isolation without full OS installation (e.g., App-V). It is used for compatibility, not for safely detonating malware."},
            {"id": "b", "text": "Sandbox", "correct": True, "rationale": "Correct. A sandbox is an isolated VM environment used to run untrusted or potentially malicious code safely. Changes are contained within the sandbox; the production host is not at risk. Analysts commonly use sandboxes for malware analysis."},
            {"id": "c", "text": "Legacy software support", "correct": False, "rationale": "Incorrect. Legacy software support means running an outdated OS or application (e.g., Windows XP) in a VM for compatibility with old software. The scenario is about isolating malicious code, not running legacy software."},
            {"id": "d", "text": "Cross-platform virtualization", "correct": False, "rationale": "Incorrect. Cross-platform virtualization means running a different OS (e.g., Linux on Windows) to use platform-specific tools. While a VM is used, the key purpose in the scenario is isolation for safety, not running a different OS for compatibility."},
        ],
        "explanation": "VM sandboxing isolates untrusted or potentially malicious code from the production environment. Any damage done by the malware stays inside the VM. After analysis, the analyst can delete the VM or revert to a clean snapshot. This is a core security use case for virtualization, distinct from development/testing, legacy software, or cross-platform compatibility use cases.",
    },
    {
        "id": "a1d4-015",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "VM resource requirements",
        "stem": "A technician is building a workstation to host multiple virtual machines simultaneously and wants to enable hardware-assisted virtualization for maximum performance. The workstation uses an Intel Core i9 processor. Which CPU feature MUST be enabled in the system BIOS/UEFI for the hypervisor to use hardware-assisted virtualization?",
        "options": [
            {"id": "a", "text": "AMD-V (AMD Virtualization)", "correct": False, "rationale": "Incorrect. AMD-V is AMD's hardware virtualization extension, equivalent to Intel VT-x. It is present only on AMD CPUs. The workstation uses an Intel Core i9, so AMD-V is not applicable."},
            {"id": "b", "text": "Intel VT-x (Intel Virtualization Technology)", "correct": True, "rationale": "Correct. Intel VT-x (sometimes also called Intel VT or VMXON capability) is Intel's hardware-assisted virtualization extension. It must be enabled in BIOS/UEFI on Intel-based systems to allow hypervisors to use hardware virtualization rather than slower software emulation."},
            {"id": "c", "text": "Intel Hyper-Threading (HTT)", "correct": False, "rationale": "Incorrect. Hyper-Threading allows a single physical CPU core to appear as two logical processors, improving multithreaded performance. It is a performance feature but is NOT the hardware virtualization extension required by hypervisors."},
            {"id": "d", "text": "Intel Turbo Boost", "correct": False, "rationale": "Incorrect. Turbo Boost dynamically increases CPU clock speed above the base frequency when thermal and power headroom permit. It is a performance feature, not a virtualization extension required for hypervisor hardware support."},
        ],
        "explanation": "Hardware-assisted virtualization requires CPU support: Intel VT-x for Intel CPUs and AMD-V for AMD CPUs. These extensions must be enabled in BIOS/UEFI. Without them, hypervisors fall back to slower software emulation. Intel also offers VT-d for I/O virtualization (device passthrough) and AMD has AMD-Vi/IOMMU for the same purpose. On the A+ exam, remember VT-x = Intel and AMD-V = AMD.",
    },
    {
        "id": "a1d4-016",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "VM resource requirements",
        "stem": "A technician needs to run four resource-intensive virtual machines simultaneously on a single workstation, each requiring 8 GB RAM. The host OS itself needs 8 GB to operate stably. What is the MINIMUM total RAM the workstation should have to avoid severe performance degradation due to memory contention?",
        "options": [
            {"id": "a", "text": "16 GB", "correct": False, "rationale": "Incorrect. 16 GB would cover only two VMs at 8 GB each with nothing left for the host OS. Running four 8 GB VMs and an 8 GB host OS on 16 GB would cause extreme memory overcommitment and disk-based swapping, severely degrading performance."},
            {"id": "b", "text": "32 GB", "correct": False, "rationale": "Incorrect. 32 GB covers four VMs (4 × 8 GB = 32 GB) but leaves zero memory for the host OS. With the host OS needing 8 GB, 32 GB would still cause memory contention."},
            {"id": "c", "text": "40 GB", "correct": True, "rationale": "Correct. The minimum calculation is: (4 VMs × 8 GB) + 8 GB host OS = 40 GB. In practice the closest standard DIMM configuration would be 48 GB (e.g., 3 × 16 GB) or 64 GB, but the question asks for minimum, which is 40 GB total."},
            {"id": "d", "text": "64 GB", "correct": False, "rationale": "Incorrect. 64 GB exceeds the minimum requirement. While 64 GB would provide comfortable headroom, the question asks for the minimum to avoid severe degradation, which is 40 GB (4 × 8 + 8)."},
        ],
        "explanation": "VM RAM planning: total required RAM = sum of all VM allocations + host OS overhead + any hypervisor overhead. Here: 4 VMs × 8 GB = 32 GB for VMs, plus 8 GB for the host OS = 40 GB minimum. Going below this forces the hypervisor to balloon or swap VM memory to disk, drastically reducing performance. In real deployments you'd add headroom (e.g., 64 GB), but 40 GB is the minimum floor.",
    },
    {
        "id": "a1d4-017",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Client-side virtualization security",
        "stem": "A technician configures a virtual machine used for security testing and enables a feature that prevents the VM from communicating with the host machine or any other VM on the same host, while still allowing the VM to access external Internet resources through NAT. Which VM network mode achieves this isolation?",
        "options": [
            {"id": "a", "text": "Bridged networking", "correct": False, "rationale": "Incorrect. Bridged networking connects the VM directly to the physical network as if it were a standalone physical machine. The VM gets its own IP on the LAN and can communicate with the host and all other network devices, providing no isolation."},
            {"id": "b", "text": "Host-only networking", "correct": False, "rationale": "Incorrect. Host-only networking allows the VM to communicate with the host machine and other VMs on the same host-only network, but blocks all external Internet access. The scenario requires Internet access via NAT while blocking host/VM communication — the opposite configuration."},
            {"id": "c", "text": "NAT networking", "correct": True, "rationale": "Correct. In NAT mode, the VM accesses external networks through the hypervisor's built-in NAT, getting Internet access while being isolated behind NAT from the host and other VMs (which cannot initiate connections to the VM). The VM has no direct layer-2 visibility to the host or peer VMs."},
            {"id": "d", "text": "Internal networking", "correct": False, "rationale": "Incorrect. Internal networking (available in some hypervisors like VirtualBox) only allows communication between VMs on the same internal network segment — there is no host communication and no Internet access, which does not match the requirement for Internet access via NAT."},
        ],
        "explanation": "VM network modes: Bridged = VM on physical LAN, visible to all; NAT = VM behind hypervisor NAT, Internet access available, but host and other VMs cannot reach the VM directly; Host-only = VM can only talk to the host and other host-only VMs, no Internet; Internal = VM-to-VM only on a virtual internal network. NAT provides Internet access while isolating the VM from the host and other VMs, making it appropriate for security-testing VMs.",
    },
    {
        "id": "a1d4-018",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_response",
        "difficulty": "hard",
        "study_topic": "VM use cases",
        "stem": "A technician is explaining the business justifications for implementing client-side virtualization to a manager. Select the TWO use cases that BEST demonstrate scenarios where virtualization provides a clear technical advantage over running applications natively.",
        "options": [
            {"id": "a", "text": "Running a legacy 32-bit Windows XP application that is incompatible with the company's new Windows 11 machines", "correct": True, "rationale": "Correct. Legacy software/OS support is a primary VM use case. Virtualizing Windows XP allows the legacy 32-bit application to run on modern hardware without maintaining old physical machines or risking incompatibility with the modern OS."},
            {"id": "b", "text": "Installing Microsoft Office on a new Windows 11 machine because it is not yet licensed", "correct": False, "rationale": "Incorrect. Purchasing and installing Microsoft Office natively is the standard approach; virtualization provides no technical advantage here. The issue is licensing, not compatibility, and creating a VM does not resolve an unlicensed software problem."},
            {"id": "c", "text": "Creating an isolated environment to safely test a new software deployment package before pushing it to production", "correct": True, "rationale": "Correct. Test/development and sandboxing are core VM use cases. A VM allows the technician to test the deployment package in an isolated snapshot-able environment; any problems can be identified without affecting production systems, and the VM can be rolled back."},
            {"id": "d", "text": "Adding a second physical monitor to improve a power user's productivity", "correct": False, "rationale": "Incorrect. Adding a second physical monitor is a hardware upgrade, not a virtualization scenario. Virtualization provides no advantage here — the monitor connects directly to the workstation's GPU."},
        ],
        "explanation": "Key client-side virtualization use cases: (1) Legacy software/OS support — run old OS versions needed for incompatible software on modern hardware; (2) Sandbox/test-development — isolate test environments, test patches or deployments, and revert snapshots if something goes wrong; (3) Application virtualization — run apps in isolation; (4) Cross-platform virtualization — run a different OS for platform-specific tools. Licensing issues and hardware upgrades are solved by non-VM means.",
    },
    {
        "id": "a1d4-019",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_response",
        "difficulty": "expert",
        "study_topic": "Cloud deployment models",
        "stem": "A cloud architect is discussing cloud deployment model characteristics with a client. Which TWO statements accurately describe a community cloud?",
        "options": [
            {"id": "a", "text": "The infrastructure is shared among several organizations that have common concerns such as compliance requirements, mission, or security policies", "correct": True, "rationale": "Correct. A community cloud is defined by shared infrastructure among a specific group of organizations with common interests, compliance needs (e.g., HIPAA for healthcare orgs), or missions. This is the defining characteristic that differentiates it from public cloud (open to all) and private cloud (single org)."},
            {"id": "b", "text": "It is always operated on-premises by one of the participating organizations and can never be hosted by a third-party provider", "correct": False, "rationale": "Incorrect. A community cloud can be hosted and managed by a third-party provider, one of the participating organizations, or a combination. Location (on-premises vs. provider-hosted) is not a defining constraint."},
            {"id": "c", "text": "Infrastructure costs and resources are distributed among the participating organizations rather than being borne by a single entity or opened to the general public", "correct": True, "rationale": "Correct. In a community cloud, the participating organizations share the costs and governance of the infrastructure. This is an advantage over a private cloud (single org pays all) and differs from public cloud (provider bears costs, charges per use to everyone)."},
            {"id": "d", "text": "Any member of the public can sign up and provision resources from a community cloud", "correct": False, "rationale": "Incorrect. Public cloud is open to anyone who signs up. Community cloud access is restricted to the member organizations with the shared interest or compliance requirement."},
        ],
        "explanation": "Community cloud: shared by a group of organizations with common characteristics (e.g., a consortium of hospitals sharing HIPAA-compliant infrastructure, or government agencies sharing a FedRAMP environment). It may be managed by the group, one member, or a third-party provider. Key traits: restricted access (members only), shared costs, and a common purpose or compliance framework. Contrast with public (open), private (single org), and hybrid (public + private integration).",
    },
    {
        "id": "a1d4-020",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_response",
        "difficulty": "expert",
        "study_topic": "VM resource requirements",
        "stem": "A technician is planning to configure a workstation to run Type 2 virtualization with multiple simultaneous VMs. Which TWO requirements MUST be met at the hardware or firmware level for the hypervisor to operate correctly with hardware-assisted virtualization?",
        "options": [
            {"id": "a", "text": "The CPU must support and have enabled hardware virtualization extensions (Intel VT-x or AMD-V) in BIOS/UEFI", "correct": True, "rationale": "Correct. Hardware-assisted virtualization requires explicit CPU support (Intel VT-x or AMD-V) and those extensions must be enabled in the system's BIOS/UEFI firmware. Without this, the hypervisor cannot use hardware acceleration and may fall back to software emulation or fail to start 64-bit guest VMs."},
            {"id": "b", "text": "The workstation must have a dedicated GPU with at least 4 GB of VRAM for each virtual machine", "correct": False, "rationale": "Incorrect. A dedicated GPU is not a general requirement for running virtual machines. VMs typically use emulated or paravirtualized graphics adapters. A dedicated GPU per VM is only needed for GPU-intensive workloads using GPU passthrough — this is not a baseline requirement."},
            {"id": "c", "text": "The workstation must have sufficient RAM to allocate to all VMs simultaneously plus the host OS overhead", "correct": True, "rationale": "Correct. RAM is the most critical resource constraint for running multiple VMs. Each VM requires dedicated RAM allocation that cannot be shared with other VMs or the host OS. Insufficient RAM causes excessive disk-based swapping (balloon driver swapping) and severe performance degradation, or VMs may fail to start."},
            {"id": "d", "text": "The workstation's hard drive must be formatted with FAT32 to support virtual disk image files", "correct": False, "rationale": "Incorrect. FAT32 is actually a limitation — it has a 4 GB maximum file size, which is far too small for typical VM disk images. VM disk images (VMDK, VHD, VDI) require filesystems that support large files, such as NTFS (Windows), ext4 (Linux), or APFS (macOS). FAT32 would prevent the creation of large VM disk images."},
        ],
        "explanation": "Core requirements for client-side virtualization: (1) CPU with VT-x (Intel) or AMD-V (AMD) enabled in BIOS/UEFI — required for hardware-assisted virtualization of 64-bit guests; (2) Sufficient RAM — each VM needs its own dedicated RAM allocation; the host OS and hypervisor also need RAM; (3) Adequate storage — VMs need disk space for virtual disk image files (NTFS or comparable filesystem required, NOT FAT32); (4) Network adapter — for VM network connectivity. GPU is optional and only required for specific GPU-accelerated workloads.",
    },
]
