QUESTIONS = [
    # ── Cloud service models (4 questions) ────────────────────────────────────
    {
        "id": "a1d4v2-001",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud service models",
        "stem": "A government agency wants to migrate its email and calendar system to the cloud. The new system will be owned by a commercial vendor, hosted on the vendor's servers, and accessed by agency employees via a web browser. The agency will configure user accounts and distribution lists but will perform no OS patching, no server maintenance, and no application updates. Which cloud service model is being adopted?",
        "options": [
            {"id": "a", "text": "Infrastructure as a Service (IaaS)", "correct": False, "rationale": "Incorrect. IaaS delivers raw compute and storage; the customer still installs and manages the OS, applications, and middleware. The agency here manages nothing below the application-user-configuration level."},
            {"id": "b", "text": "Platform as a Service (PaaS)", "correct": False, "rationale": "Incorrect. PaaS gives developers a platform on which to deploy their own custom code. The agency is consuming a finished, vendor-maintained email product, not deploying its own application code."},
            {"id": "c", "text": "Software as a Service (SaaS)", "correct": True, "rationale": "Correct. SaaS delivers a fully managed, ready-to-use application to end users. The vendor handles the entire technology stack; the customer only manages user accounts, data, and configuration settings. A hosted email/calendar service accessed via browser is a textbook SaaS example."},
            {"id": "d", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS delivers a full virtual desktop operating environment, not a specific hosted business application. The agency needs email and calendar, not a virtual Windows or Linux desktop."},
        ],
        "explanation": "SaaS sits at the highest abstraction layer: the provider manages physical hardware, virtualization, OS, middleware, and the application itself. The customer manages only user/data configuration. Common SaaS examples include hosted email (Gmail, Microsoft 365), CRM (Salesforce), and ERP systems. IaaS requires OS management, PaaS requires app deployment, DaaS delivers virtual desktops.",
    },
    {
        "id": "a1d4v2-002",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud service models",
        "stem": "A fintech startup is building a mobile payments application. They lease virtual machines from a cloud provider, install Ubuntu 22.04 on each VM, configure their own load balancer, deploy a PostgreSQL database, and push their custom Python application code. The cloud provider only guarantees availability of the underlying compute, network, and storage hardware. Which cloud service model BEST describes what this startup is consuming?",
        "options": [
            {"id": "a", "text": "Platform as a Service (PaaS)", "correct": False, "rationale": "Incorrect. PaaS abstracts away the OS and middleware; customers only deploy application code. The startup is explicitly installing and managing Ubuntu, PostgreSQL, and a load balancer — all layers above the hypervisor — which is the customer's responsibility under IaaS, not PaaS."},
            {"id": "b", "text": "Infrastructure as a Service (IaaS)", "correct": True, "rationale": "Correct. IaaS provides virtualized compute, networking, and storage; the customer manages everything from the OS upward. The startup installs the OS, manages middleware (PostgreSQL, load balancer), and deploys their app — this is the full IaaS customer-responsibility stack."},
            {"id": "c", "text": "Software as a Service (SaaS)", "correct": False, "rationale": "Incorrect. SaaS delivers finished applications that the customer simply configures and uses. The startup is building and deploying their own application from scratch, not consuming a finished product."},
            {"id": "d", "text": "Function as a Service (FaaS)", "correct": False, "rationale": "Incorrect. FaaS (serverless) executes small code functions in response to events without the customer managing any servers. The startup is managing full VMs with custom OS installs, which is IaaS, not serverless FaaS."},
        ],
        "explanation": "IaaS boundary: the provider manages physical hardware, storage fabric, network, and the hypervisor. Everything from the guest OS upward belongs to the customer. The startup controls OS selection, patching, middleware installation, and application deployment — the classic IaaS model. PaaS removes the OS responsibility; SaaS removes everything except data/config.",
    },
    {
        "id": "a1d4v2-003",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud service models",
        "stem": "An organization's development team pushes code to a cloud repository. A CI/CD pipeline automatically builds the code, runs tests, and deploys the compiled application to a managed runtime environment where the provider handles OS updates, auto-scaling, and load balancing. The developers only write application code and manage environment variables. Under the shared-responsibility model, which cloud service model is this?",
        "options": [
            {"id": "a", "text": "Infrastructure as a Service (IaaS)", "correct": False, "rationale": "Incorrect. IaaS requires the customer to manage the OS, patching, runtime environment, and middleware. The development team here does none of that — the provider handles OS updates, scaling, and load balancing. IaaS would give the team virtual machines they must configure themselves."},
            {"id": "b", "text": "Software as a Service (SaaS)", "correct": False, "rationale": "Incorrect. SaaS delivers a finished application to end users who simply use it. Here the developers are writing and deploying their own custom application code, which is not a SaaS consumption model."},
            {"id": "c", "text": "Platform as a Service (PaaS)", "correct": True, "rationale": "Correct. PaaS provides a managed platform (OS, runtime, middleware, auto-scaling, load balancing) on which the customer deploys their own application code. The developer responsibility is limited to the application layer and data — precisely what is described. Examples: Google App Engine, Heroku, Azure App Service."},
            {"id": "d", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS provides virtual desktop environments for end users. It is not a deployment platform for custom application code and has nothing to do with CI/CD pipelines or managed application runtimes."},
        ],
        "explanation": "PaaS provides a complete, managed development and runtime environment. The provider handles the infrastructure, OS, runtime/middleware, and platform services (CI/CD, scaling, load balancing). The customer writes the application code and configures it. This matches the scenario exactly. The key differentiator from IaaS is that no OS management is required; the differentiator from SaaS is that the customer still writes and owns the application logic.",
    },
    {
        "id": "a1d4v2-004",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud service models",
        "stem": "A cloud provider's shared-responsibility documentation states: 'The customer is responsible for application code, application data, and user access management. The provider is responsible for the runtime environment, OS, virtualization layer, physical servers, storage, and networking.' Which cloud service model does this responsibility split describe?",
        "options": [
            {"id": "a", "text": "Infrastructure as a Service (IaaS)", "correct": False, "rationale": "Incorrect. In IaaS, the customer's responsibility extends downward through OS, middleware, and runtime — not just application code and data. IaaS puts OS patching, runtime management, and middleware squarely on the customer."},
            {"id": "b", "text": "Platform as a Service (PaaS)", "correct": True, "rationale": "Correct. The described split — provider owns the runtime, OS, and everything below; customer owns app code, data, and access management — is the exact PaaS shared-responsibility model. The customer writes code, the provider manages the platform."},
            {"id": "c", "text": "Software as a Service (SaaS)", "correct": False, "rationale": "Incorrect. In SaaS, the customer does not own or deploy application code; they configure and use a finished app. The responsibility description explicitly lists 'application code' as a customer responsibility, which rules out SaaS."},
            {"id": "d", "text": "Community cloud", "correct": False, "rationale": "Incorrect. Community cloud is a deployment model (who uses and shares the infrastructure), not a service model. It does not describe how responsibility is divided between the provider and the customer for application vs. platform layers."},
        ],
        "explanation": "Shared-responsibility boundary cheat sheet: IaaS — provider manages: physical + hypervisor; customer manages: OS up through app+data. PaaS — provider manages: physical + hypervisor + OS + runtime/middleware; customer manages: app code + data + user access. SaaS — provider manages everything except customer data and user config. This question tests the ability to identify the model purely from the responsibility split rather than a named service.",
    },

    # ── Cloud deployment models (4 questions) ─────────────────────────────────
    {
        "id": "a1d4v2-005",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models",
        "stem": "A consortium of five regional banks builds a shared cloud environment dedicated exclusively to its member institutions. The infrastructure resides in a third-party-managed data center, complies with all financial-services regulatory requirements, and is paid for proportionally by each bank. No institution outside the consortium can access the environment. Which cloud deployment model does this BEST represent?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": False, "rationale": "Incorrect. Public cloud is open to any organization or individual that creates an account. The consortium environment is restricted to five specific member banks, so it is not a public cloud."},
            {"id": "b", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is dedicated to a single organization. This environment is shared among five different legal entities (the banks), which disqualifies it as a private cloud even though access is restricted."},
            {"id": "c", "text": "Community cloud", "correct": True, "rationale": "Correct. A community cloud is shared infrastructure used exclusively by a group of organizations with common concerns — in this case, five banks sharing regulatory compliance requirements. Costs and governance are distributed among the members, and third-party hosting is permitted."},
            {"id": "d", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. Hybrid cloud integrates two or more distinct cloud deployment models (typically private + public). This scenario describes a single shared environment serving a specific community, not a bridging of two different cloud types."},
        ],
        "explanation": "Community cloud: multi-tenant but access-restricted to a defined group of organizations sharing a common regulatory, compliance, or mission framework (e.g., banks under financial regulation, hospitals under HIPAA, government agencies under FedRAMP). Costs and governance are shared. The infrastructure may be on-premises or hosted by a third party. Key distinction: community = multiple orgs, private = single org, public = anyone.",
    },
    {
        "id": "a1d4v2-006",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models",
        "stem": "A manufacturing company runs its production control systems on-premises because low-latency network communication with factory floor equipment is critical and data must never leave the building. However, the company uses a third-party public cloud provider for HR, payroll, and business analytics workloads. Both environments are connected via a dedicated WAN link and managed through a unified operations portal. Which cloud deployment model is in use?",
        "options": [
            {"id": "a", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is a single-organization dedicated environment. This company intentionally extends into a public cloud provider for some workloads, which is not a characteristic of a pure private cloud."},
            {"id": "b", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. A hybrid cloud integrates on-premises (private) infrastructure with a public cloud, with workloads distributed based on requirements — latency-sensitive production systems on-premises, business applications in the public cloud. A dedicated WAN link and unified management portal are hallmarks of a hybrid cloud architecture."},
            {"id": "c", "text": "Community cloud", "correct": False, "rationale": "Incorrect. Community cloud is shared among multiple organizations with a common concern. This is a single company combining its own on-premises environment with a public cloud — a hybrid architecture, not a community one."},
            {"id": "d", "text": "Public cloud", "correct": False, "rationale": "Incorrect. The scenario explicitly includes on-premises infrastructure that the company owns and operates. A pure public cloud deployment would have no on-premises component."},
        ],
        "explanation": "Hybrid cloud connects and orchestrates on-premises or private cloud resources with public cloud services, allowing each workload to reside in the environment best suited to its requirements. Latency-sensitive or data-sovereignty workloads stay on-premises; less sensitive workloads leverage the public cloud's scalability and cost model. A dedicated connection (WAN, Direct Connect, ExpressRoute) between environments is a common hybrid cloud component.",
    },
    {
        "id": "a1d4v2-007",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models",
        "stem": "A small business owner signs up for a cloud computing service offered by a large provider. The owner can provision virtual machines within minutes using a web portal, shares the underlying physical infrastructure with thousands of other customers, and pays only for what is consumed each month. No capital investment in hardware is required. Which cloud deployment model is this?",
        "options": [
            {"id": "a", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is dedicated to one organization and typically requires capital investment in (or exclusive reservation of) hardware. The scenario describes shared infrastructure and a no-CapEx model, which is characteristic of public cloud."},
            {"id": "b", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. Hybrid cloud involves integrating on-premises or private infrastructure with public cloud. The scenario describes a single, purely provider-hosted environment with no on-premises component."},
            {"id": "c", "text": "Community cloud", "correct": False, "rationale": "Incorrect. Community cloud is restricted to a specific group of organizations with a shared concern. This service is open to any small business owner who signs up — it is not access-restricted to a defined community."},
            {"id": "d", "text": "Public cloud", "correct": True, "rationale": "Correct. Public cloud is owned and operated by a third-party provider and made available to the general public on a pay-per-use basis. Infrastructure is shared (multi-tenant) among many customers, no CapEx is required, and self-service provisioning is a defining characteristic. AWS, Azure, and Google Cloud are canonical examples."},
        ],
        "explanation": "Public cloud: provider-owned multi-tenant infrastructure available to anyone; pay-as-you-go; no customer hardware investment; self-service provisioning. Private cloud: single-tenant, organization-controlled. Hybrid: private + public integrated. Community: restricted group. Public cloud is the largest and most common deployment model for businesses seeking low entry cost and on-demand scalability.",
    },
    {
        "id": "a1d4v2-008",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud deployment models",
        "stem": "An enterprise is evaluating cloud strategies. Their security team insists that all customer data must reside on dedicated hardware controlled exclusively by the enterprise, within the enterprise's own data center, with no shared tenancy. However, they also want self-service provisioning, automated resource management, and elastic scalability just like a public cloud. Which deployment model BEST satisfies BOTH requirements simultaneously?",
        "options": [
            {"id": "a", "text": "Public cloud with dedicated instances", "correct": False, "rationale": "Incorrect. Even 'dedicated' public cloud instances run on provider-owned hardware in a provider-operated data center. The enterprise does not control the physical hardware or its physical location, failing the requirement for enterprise-owned, enterprise-controlled hardware."},
            {"id": "b", "text": "Hybrid cloud using both on-premises and public cloud resources", "correct": False, "rationale": "Incorrect. A hybrid cloud intentionally extends into a public cloud provider for some workloads. If all customer data must reside only on enterprise-controlled hardware with no shared tenancy, introducing a public cloud component would violate that constraint."},
            {"id": "c", "text": "Community cloud hosted by an industry consortium", "correct": False, "rationale": "Incorrect. A community cloud shares infrastructure among multiple organizations. Even within a consortium, the hardware is shared among the member organizations, violating the requirement for exclusively enterprise-controlled dedicated hardware."},
            {"id": "d", "text": "Private cloud deployed in the enterprise's own data center", "correct": True, "rationale": "Correct. A private cloud runs cloud-management software (e.g., VMware vSphere, OpenStack) on hardware owned and operated exclusively by the enterprise in its own data center. This provides cloud-like self-service, elasticity, and automation while maintaining complete physical control and no shared tenancy — satisfying both requirements."},
        ],
        "explanation": "The scenario lists two competing requirements: (1) exclusive physical control of hardware in the enterprise's own data center (eliminates public, community, and hybrid with public-cloud component); (2) cloud-like self-service and elasticity (eliminates traditional on-premises infrastructure without cloud orchestration). Only a private cloud delivers both — enterprise-owned hardware plus cloud automation/orchestration (OpenStack, VMware, etc.).",
    },

    # ── Cloud characteristics (4 questions) ───────────────────────────────────
    {
        "id": "a1d4v2-009",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud characteristics",
        "stem": "A developer logs into a cloud provider's web portal and, without calling the provider's support desk or submitting a ticket, provisions a 32-vCPU virtual machine, a 10 TB block storage volume, and a load balancer — all within two minutes. Which NIST essential cloud characteristic does this PRIMARILY illustrate?",
        "options": [
            {"id": "a", "text": "Resource pooling", "correct": False, "rationale": "Incorrect. Resource pooling means the provider serves multiple tenants from shared physical resources, abstracting the physical location. While resource pooling enables the provisioning experience, the defining feature demonstrated here is the ability to do it independently, without human intervention from the provider."},
            {"id": "b", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity is the ability to scale resources up and down to match demand, often automatically. The scenario describes initial provisioning by the developer, not dynamic scaling in response to changing load."},
            {"id": "c", "text": "On-demand self-service", "correct": True, "rationale": "Correct. On-demand self-service is the NIST characteristic that allows a consumer to unilaterally provision computing capabilities (compute, storage, networking) as needed, automatically, without requiring human interaction with the service provider. The developer provisioned resources instantly via the portal with no ticket or support call."},
            {"id": "d", "text": "Broad network access", "correct": False, "rationale": "Incorrect. Broad network access means cloud capabilities are available over the network and can be accessed through standard mechanisms by heterogeneous client platforms (phones, tablets, laptops, workstations). The scenario describes provisioning, not accessing the service over diverse network endpoints."},
        ],
        "explanation": "The five NIST essential cloud characteristics: (1) On-demand self-service — provision without human provider interaction; (2) Broad network access — access over standard networks from any device; (3) Resource pooling — multi-tenant shared physical resources; (4) Rapid elasticity — scale in and out dynamically; (5) Measured service — metered billing. Self-provisioning via a portal with no support call = on-demand self-service.",
    },
    {
        "id": "a1d4v2-010",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud characteristics",
        "stem": "A cloud storage platform allows users to access their files from a Windows laptop, an iPhone, an Android tablet, and a Chromebook, all using the standard HTTPS protocol and the provider's web application. Which NIST essential cloud characteristic does this PRIMARILY illustrate?",
        "options": [
            {"id": "a", "text": "On-demand self-service", "correct": False, "rationale": "Incorrect. On-demand self-service refers to the ability to provision resources without human provider intervention. The scenario describes accessing an already-provisioned service from multiple device types using standard protocols, not the act of provisioning."},
            {"id": "b", "text": "Broad network access", "correct": True, "rationale": "Correct. Broad network access means cloud services are available over standard network protocols (HTTPS in this case) and are accessible from heterogeneous client platforms — laptops, smartphones, tablets, thin clients. Supporting Windows, iOS, Android, and Chrome OS via HTTPS is the defining example."},
            {"id": "c", "text": "Metered utilization", "correct": False, "rationale": "Incorrect. Metered utilization refers to the pay-as-you-go billing model based on measured consumption of resources. Cross-device access via standard protocols describes availability/accessibility, not billing."},
            {"id": "d", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity describes the ability to scale resources up and down dynamically. Accessing the same files from different device types is about availability and accessibility, not about scaling compute or storage capacity."},
        ],
        "explanation": "Broad network access: services delivered over the network, accessible via standard mechanisms (HTTP/S, REST APIs) from diverse client platforms. Heterogeneous client support (Windows, macOS, iOS, Android, Linux) over standard protocols is the textbook example. This characteristic enables the 'any device, anywhere' promise of cloud computing, contrasting with traditional software that required specific OS/hardware.",
    },
    {
        "id": "a1d4v2-011",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud characteristics",
        "stem": "A cloud provider runs thousands of customers' virtual machines on the same physical servers. Each customer is unaware of, and does not control, the physical location of their workloads. The provider dynamically assigns physical resources to VMs based on overall demand, moving workloads between physical hosts transparently. Which NIST cloud characteristic is being described?",
        "options": [
            {"id": "a", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity is about scaling the amount of resources allocated to a tenant up or down to match demand. The described behavior — serving multiple tenants from shared hardware while abstracting physical location — is about multi-tenancy and abstraction, not scaling."},
            {"id": "b", "text": "Resource pooling", "correct": True, "rationale": "Correct. Resource pooling (multi-tenancy) means the provider's physical resources (compute, storage, network) are shared among multiple customers dynamically. Physical and virtual resources are assigned and reassigned based on demand, and customers do not know or control the specific physical hardware serving them. This is the multi-tenant, location-transparent foundation of cloud computing."},
            {"id": "c", "text": "Measured service", "correct": False, "rationale": "Incorrect. Measured service (metered utilization) refers to monitoring and billing customers based on actual resource consumption. It does not describe the mechanism of sharing physical infrastructure among tenants."},
            {"id": "d", "text": "On-demand self-service", "correct": False, "rationale": "Incorrect. On-demand self-service is the ability for customers to provision their own resources without human provider intervention. The scenario describes the provider's back-end resource management, not a customer self-provisioning action."},
        ],
        "explanation": "Resource pooling: the provider abstracts physical hardware into a shared pool served to multiple tenants. Physical resources (CPU, RAM, storage, network bandwidth) are dynamically allocated and reallocated. Customers share the infrastructure but are logically isolated. Location independence (customer doesn't know which server they're on) is a key feature. This is what makes cloud economics work — high utilization through multi-tenancy.",
    },
    {
        "id": "a1d4v2-012",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Cloud characteristics",
        "stem": "An IT manager reviews last month's cloud invoice and notices the bill itemizes exactly 712 compute-hours at $0.10/hour, 450 GB of stored data at $0.023/GB/month, and 320 GB of outbound data transfer at $0.09/GB. The total charge precisely reflects resource usage with no flat monthly fee. This billing approach is enabled by which NIST cloud characteristic?",
        "options": [
            {"id": "a", "text": "On-demand self-service", "correct": False, "rationale": "Incorrect. On-demand self-service enables customers to provision resources without interacting with the provider's staff. It explains how resources are provisioned, not how they are billed. The invoice described is based on consumption measurement, not on the self-service provisioning method."},
            {"id": "b", "text": "Resource pooling", "correct": False, "rationale": "Incorrect. Resource pooling is the multi-tenant sharing of physical infrastructure. While pooling enables efficient utilization that makes consumption-based pricing feasible, it is not the characteristic that describes the metered billing model itself."},
            {"id": "c", "text": "Rapid elasticity", "correct": False, "rationale": "Incorrect. Rapid elasticity is the ability to scale resources dynamically. An itemized invoice based on exact usage hours, storage GB, and transfer GB is about measuring and billing consumption, not about the capacity to scale."},
            {"id": "d", "text": "Measured service", "correct": True, "rationale": "Correct. Measured service (also called metered utilization) means cloud resource usage is monitored, controlled, reported, and billed transparently based on actual consumption. The invoice itemizing compute-hours, storage GB, and data transfer GB at specific rates is a direct expression of the measured service characteristic."},
        ],
        "explanation": "Measured service enables pay-as-you-go billing by instrumenting resource consumption at a granular level. Compute, storage, bandwidth, API calls, and other resources are metered and billed proportionally to usage. This eliminates the need for large upfront capital expenditure and allows cost to scale linearly with utilization — a core economic advantage of cloud computing.",
    },

    # ── Hypervisor types (3 questions) ────────────────────────────────────────
    {
        "id": "a1d4v2-013",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Hypervisor types",
        "stem": "A server administrator is setting up a production virtualization platform for a company's data center. The administrator installs Microsoft Hyper-V Server directly on a new rack-mounted server. After installation, there is no general-purpose Windows Server OS underneath Hyper-V — Hyper-V IS the first software layer the server runs. Which hypervisor type is this, and which other products belong to the SAME category?",
        "options": [
            {"id": "a", "text": "Type 2; other examples include VMware Workstation and Parallels Desktop", "correct": False, "rationale": "Incorrect. Microsoft Hyper-V Server (standalone, bare-metal) is a Type 1 hypervisor, not Type 2. VMware Workstation and Parallels are correctly identified as Type 2 examples, but they belong to the wrong type for Hyper-V Server."},
            {"id": "b", "text": "Type 1; other examples include VMware ESXi and Citrix XenServer (XCP-ng)", "correct": True, "rationale": "Correct. Microsoft Hyper-V Server running directly on hardware with no host OS is a Type 1 (bare-metal) hypervisor. VMware ESXi and Citrix XenServer/XCP-ng are the other primary Type 1 examples tested on the A+ exam — all run directly on hardware without a host OS."},
            {"id": "c", "text": "Type 1; other examples include Oracle VirtualBox and VMware Workstation Player", "correct": False, "rationale": "Incorrect. Hyper-V Server is correctly classified as Type 1, but Oracle VirtualBox and VMware Workstation Player are Type 2 (hosted) hypervisors that run on top of a host OS. They do not belong in the same category."},
            {"id": "d", "text": "Type 2; it requires Windows Server to be installed first as the host OS", "correct": False, "rationale": "Incorrect. Microsoft Hyper-V Server (the standalone free product) runs directly on bare metal without requiring a full Windows Server OS underneath. When Hyper-V is a role installed on top of Windows Server, that is a different deployment; standalone Hyper-V Server is Type 1."},
        ],
        "explanation": "Type 1 bare-metal hypervisors run directly on hardware: VMware ESXi, Microsoft Hyper-V Server (standalone), Citrix XenServer/XCP-ng, and KVM (Linux kernel-integrated). Type 2 hosted hypervisors run as applications on a host OS: Oracle VirtualBox, VMware Workstation/Player/Fusion, Parallels Desktop. Note: Windows Server with the Hyper-V role enabled is sometimes considered a gray area, but standalone Hyper-V Server is definitively Type 1.",
    },
    {
        "id": "a1d4v2-014",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Hypervisor types",
        "stem": "A security researcher wants to quickly spin up a throwaway Linux VM on their macOS laptop to examine a suspicious script. They want the simplest possible setup with no need to dedicate the entire laptop to the hypervisor. The VM does not need maximum performance. Which hypervisor type is MOST appropriate, and why?",
        "options": [
            {"id": "a", "text": "Type 1 (bare-metal), because it provides better performance and direct hardware access without a host OS overhead", "correct": False, "rationale": "Incorrect. While Type 1 does offer better performance, installing a Type 1 hypervisor on a laptop would replace macOS entirely, eliminating the native OS environment the researcher uses for daily work. The requirement is to add a VM alongside the existing macOS environment, not replace it."},
            {"id": "b", "text": "Type 2 (hosted), because it runs as an application on top of macOS, allowing the researcher to use both macOS and VMs simultaneously without replacing the existing OS", "correct": True, "rationale": "Correct. Type 2 hypervisors run as regular applications on a host OS, making them ideal for personal workstations and laptops. The researcher can keep macOS for daily work and run a Linux VM in a window alongside it. The performance trade-off is acceptable for this non-production security testing use case."},
            {"id": "c", "text": "Type 2 (hosted), because it provides lower latency and better hardware access than Type 1 for laptop environments", "correct": False, "rationale": "Incorrect. The reason to choose Type 2 for a laptop is convenience — running alongside the host OS — NOT because Type 2 offers better performance. Type 1 is the high-performance option; Type 2 has higher overhead due to the host OS layer."},
            {"id": "d", "text": "Type 1 (bare-metal), because it can be installed as a macOS application and switched between macOS and the hypervisor at login", "correct": False, "rationale": "Incorrect. Type 1 hypervisors are not installed as macOS applications — they replace the host OS entirely and run directly on the hardware. They cannot coexist alongside macOS as a launchable application."},
        ],
        "explanation": "Type 2 hypervisors (Parallels Desktop, VMware Fusion, VirtualBox on macOS) are the appropriate choice for personal/developer machines when the user needs to keep the native OS for regular work. The host OS manages hardware drivers (crucial for laptop peripherals), and the hypervisor runs as a standard process. Trade-off: some CPU/memory overhead from running two OS environments simultaneously — acceptable for development and testing, not ideal for production data center use.",
    },
    {
        "id": "a1d4v2-015",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "Hypervisor types",
        "stem": "A company evaluates two virtualization platforms: Platform A installs directly on server hardware, creates its own minimal kernel, and manages guest VMs with no intervening OS. Platform B installs on top of Windows Server, relies on Windows device drivers for all hardware access, and runs as a privileged process within Windows. A critical requirement is maximum VM density (most VMs per physical host) with minimal host-resource overhead. Which platform should be selected?",
        "options": [
            {"id": "a", "text": "Platform B, because Windows Server's device driver ecosystem provides better hardware compatibility for diverse server hardware", "correct": False, "rationale": "Incorrect. While Platform B (Type 2) does benefit from the host OS's driver ecosystem, hardware driver breadth is not the requirement. The requirement is maximum VM density with minimal overhead. Running a full Windows Server OS underneath the hypervisor adds substantial CPU and RAM overhead that directly reduces VM density."},
            {"id": "b", "text": "Platform A, because its bare-metal architecture eliminates the host OS overhead layer, leaving more CPU and RAM available for VMs, maximizing density", "correct": True, "rationale": "Correct. Platform A is a Type 1 (bare-metal) hypervisor. Because there is no host OS consuming CPU cycles and RAM, virtually all physical resources are available for VMs. This is why Type 1 hypervisors dominate production data centers where VM density and performance are critical."},
            {"id": "c", "text": "Platform B, because running on top of Windows Server simplifies VM management through familiar Windows administrative tools", "correct": False, "rationale": "Incorrect. Ease of management via familiar tools is an advantage of Platform B (Type 2), but management simplicity is not the stated requirement. Maximum VM density with minimal overhead requires minimizing host-resource consumption, which Platform A (Type 1) achieves better by eliminating the host OS layer."},
            {"id": "d", "text": "Platform A, because it requires fewer hardware resources to install and is therefore easier to deploy on low-end server hardware", "correct": False, "rationale": "Incorrect. While Type 1 hypervisors do have a smaller footprint, the rationale here conflates deployment ease with performance/density. The correct reason to choose Platform A for maximum VM density is the elimination of host OS overhead — not ease of installation on low-end hardware."},
        ],
        "explanation": "Type 1 vs. Type 2 performance/density trade-off: Type 1 (bare-metal) has no host OS, so all physical RAM and CPU are available to VMs and the hypervisor's own minimal footprint. Type 2 (hosted) requires the host OS to run first, consuming significant RAM (often 4–16 GB) and CPU cycles before a single VM is started. For production data center VM density, Type 1 is the unambiguous choice.",
    },

    # ── VM use cases (3 questions) ────────────────────────────────────────────
    {
        "id": "a1d4v2-016",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VM use cases",
        "stem": "A software quality assurance engineer needs to verify that a new application installer works correctly on Windows 7, Windows 10, and Windows 11 without maintaining three separate physical test machines. They create three VMs, one per OS version, run the installer on each, and check the results. When done, they revert each VM to a pre-install snapshot. Which VM use case BEST describes this scenario?",
        "options": [
            {"id": "a", "text": "Sandbox for malware analysis", "correct": False, "rationale": "Incorrect. A sandbox is used to safely run suspicious or malicious code in isolation to observe its behavior. The engineer here is testing a known, legitimate application installer for compatibility, not analyzing potentially malicious code."},
            {"id": "b", "text": "Test and development environment", "correct": True, "rationale": "Correct. Test/development VMs allow engineers to create multiple isolated OS environments for software testing without dedicating physical hardware to each. Snapshot-and-revert capability enables clean, repeatable test cycles across different OS versions — the classic QA use case."},
            {"id": "c", "text": "Legacy software support", "correct": False, "rationale": "Incorrect. Legacy software support means keeping an old OS running (e.g., Windows XP) because required software is incompatible with newer OSes. The engineer is testing a new installer across multiple OS versions for compatibility validation, not running legacy software because it cannot run elsewhere."},
            {"id": "d", "text": "Cross-platform virtualization for end-user productivity", "correct": False, "rationale": "Incorrect. Cross-platform virtualization typically means running a different OS to access platform-specific tools for regular use. The engineer is conducting structured QA testing with snapshot management, which is a test/development use case, not a productivity/end-user cross-platform scenario."},
        ],
        "explanation": "Test/development is one of the most important VM use cases in enterprise IT. VMs allow QA teams to maintain multiple OS configurations without dedicated hardware, run identical test scenarios against different platforms, and use snapshots to roll back cleanly after each test. This dramatically reduces the hardware cost and time needed for multi-platform testing.",
    },
    {
        "id": "a1d4v2-017",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "VM use cases",
        "stem": "A company acquired a specialized CAD application that runs only on 32-bit Windows XP. The application vendor has gone out of business and no update exists. All company workstations now run Windows 11. Rather than keeping a physical Windows XP machine, the IT team virtualizes the Windows XP environment and grants engineers access to run the CAD tool from their Windows 11 desktops. Which VM use case is this?",
        "options": [
            {"id": "a", "text": "Sandbox for isolating untrusted software", "correct": False, "rationale": "Incorrect. A sandbox is used to safely run potentially dangerous code to observe its behavior before exposing it to production systems. The CAD application is a trusted, legitimate tool — the VM is used because of OS incompatibility, not security concerns."},
            {"id": "b", "text": "Test and development environment", "correct": False, "rationale": "Incorrect. A test/development environment is used to test software changes or new deployments before production release. The team is running the legacy CAD application in permanent production use, not testing a new version or change."},
            {"id": "c", "text": "Legacy software support", "correct": True, "rationale": "Correct. Legacy software support is the use case where a VM running an older OS (Windows XP in this case) is maintained specifically because required software cannot run on newer operating systems. Virtualizing the old OS preserves access to the legacy application without maintaining physical old hardware."},
            {"id": "d", "text": "Cloud-based virtual desktop", "correct": False, "rationale": "Incorrect. A cloud-based virtual desktop (DaaS) is hosted in a provider's cloud infrastructure. The scenario describes on-premises virtualization to run a legacy application, not provisioning virtual desktops from a cloud provider."},
        ],
        "explanation": "Legacy software support VMs are a practical solution when applications depend on old OS versions that are incompatible with modern hardware or OSes. Instead of maintaining aged physical machines (which become hardware failure risks), IT virtualizes the legacy OS. The guest VM runs Windows XP while the host runs Windows 11; engineers launch the VM when they need the CAD tool. Security considerations (patching, network isolation) are important for legacy VMs running unsupported OSes.",
    },
    {
        "id": "a1d4v2-018",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VM use cases",
        "stem": "An enterprise has 30 physical servers, each running a single application at roughly 10% CPU utilization. An IT architect proposes consolidating all applications onto five powerful servers using virtual machines so each physical host runs six VMs. Which primary benefit of virtualization does this architecture achieve?",
        "options": [
            {"id": "a", "text": "Application sandboxing", "correct": False, "rationale": "Incorrect. Application sandboxing focuses on security isolation of untrusted code. The scenario describes consolidating underutilized servers to improve hardware efficiency — this is a resource consolidation and cost reduction objective, not a sandboxing objective."},
            {"id": "b", "text": "Server consolidation to improve hardware utilization and reduce costs", "correct": True, "rationale": "Correct. Server consolidation — running multiple VMs on fewer physical hosts — is one of the primary business drivers for virtualization. Servers running at 10% CPU utilization are wasteful; consolidating them into VMs on fewer high-powered servers increases hardware utilization, reduces power/cooling costs, and decreases data center footprint."},
            {"id": "c", "text": "Cross-platform OS compatibility for developer workstations", "correct": False, "rationale": "Incorrect. Cross-platform compatibility is a use case for running different OSes on workstations. Server consolidation in a data center is a capacity planning and cost reduction exercise, not a cross-platform compatibility scenario."},
            {"id": "d", "text": "Disaster recovery through VM snapshot replication", "correct": False, "rationale": "Incorrect. While VM snapshots and replication can support disaster recovery, the scenario describes physically consolidating underutilized servers onto fewer hosts — a consolidation and efficiency objective. Disaster recovery is a secondary benefit that could be layered on top, but it is not the primary purpose described."},
        ],
        "explanation": "Server consolidation was the original and most compelling business case for virtualization. Before hypervisors, most servers ran a single application at low CPU utilization (often <20%), wasting hardware, power, and rack space. Virtualization allows multiple application VMs to share a single physical host, dramatically improving utilization. This reduces hardware costs (fewer servers to buy), operational costs (less power and cooling), and physical space requirements.",
    },

    # ── VM resource requirements (2 questions) ────────────────────────────────
    {
        "id": "a1d4v2-019",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VM resource requirements",
        "stem": "A technician adds a new VM to a host that already runs several VMs. Shortly after, all VMs on the host — including previously well-performing ones — become extremely slow. Storage I/O wait times spike, and monitoring shows the host is paging heavily to disk. What is the MOST LIKELY cause of the performance degradation?",
        "options": [
            {"id": "a", "text": "The new VM's virtual NIC is broadcasting excessive traffic, saturating the virtual switch", "correct": False, "rationale": "Incorrect. Network broadcast storms can cause performance issues, but the symptom described — high disk I/O wait and heavy paging to disk — specifically points to memory exhaustion causing the hypervisor to swap VM RAM to disk, not a network-related problem."},
            {"id": "b", "text": "The host has insufficient RAM to simultaneously support all VMs, causing the hypervisor to balloon/swap VM memory to disk", "correct": True, "rationale": "Correct. When a hypervisor runs out of physical RAM, it uses techniques like memory ballooning or swapping VM pages to disk. This causes severe I/O wait and apparent slowness across all VMs, which matches the described symptoms exactly. Adding a new VM that pushed total RAM allocation past available physical RAM is the most likely cause."},
            {"id": "c", "text": "The host's CPU does not support hardware virtualization extensions (VT-x/AMD-V), forcing software emulation", "correct": False, "rationale": "Incorrect. If VT-x/AMD-V were unsupported, all VMs would have performed poorly from the start — the performance issue would be pre-existing and consistent, not triggered by adding one new VM. Additionally, a system without virtualization extensions typically cannot run 64-bit guest VMs at all."},
            {"id": "d", "text": "The new VM's virtual disk file was placed on a FAT32 formatted partition, limiting disk access", "correct": False, "rationale": "Incorrect. FAT32 has a 4 GB file size limit which would prevent creating a modern VM virtual disk in the first place — the VM likely would not have been created successfully. The symptom of system-wide memory paging is not caused by a filesystem format issue on one VM's disk."},
        ],
        "explanation": "RAM is the most common bottleneck when running multiple VMs. Unlike CPU (which can be time-sliced), each VM needs its full RAM allocation to be present in physical memory for reasonable performance. When the hypervisor runs out of physical RAM, it uses memory ballooning (asking the guest OS to voluntarily return pages) or swapping (writing VM RAM pages to a special swap file on disk). Disk-based memory swapping is orders of magnitude slower than RAM, causing extreme performance degradation visible as high I/O wait across all VMs.",
    },
    {
        "id": "a1d4v2-020",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VM resource requirements",
        "stem": "A technician attempts to create a 64-bit Windows 11 virtual machine on a workstation running VMware Workstation. The hypervisor reports an error: 'This virtual machine is configured for 64-bit guest operating systems. However, 64-bit operation is not possible. This host does not support Intel VT-x.' The BIOS shows an option labeled 'Intel Virtualization Technology.' What should the technician do FIRST?",
        "options": [
            {"id": "a", "text": "Reinstall VMware Workstation, as the error indicates a corrupted hypervisor installation", "correct": False, "rationale": "Incorrect. The error message explicitly states that the host hardware does not have VT-x enabled for the hypervisor. Reinstalling the hypervisor software cannot enable a hardware feature that is disabled at the firmware level."},
            {"id": "b", "text": "Downgrade the VM configuration to a 32-bit Windows guest OS, as 64-bit is not supported on this hardware", "correct": False, "rationale": "Incorrect. The BIOS shows an Intel Virtualization Technology option, meaning the CPU supports VT-x but it is currently disabled. The feature can be enabled. Switching to 32-bit is an unnecessary workaround when the correct solution is simply to enable VT-x in BIOS/UEFI."},
            {"id": "c", "text": "Enable Intel Virtualization Technology (VT-x) in the system BIOS/UEFI firmware settings", "correct": True, "rationale": "Correct. The error states VT-x is not enabled, and the BIOS shows a setting for it. The technician should reboot, enter BIOS/UEFI setup, navigate to the CPU or Advanced settings, enable 'Intel Virtualization Technology,' save, and exit. The hypervisor will then be able to run 64-bit guest VMs with hardware acceleration."},
            {"id": "d", "text": "Upgrade the CPU to one that supports Intel VT-x, as the current CPU lacks the virtualization extension", "correct": False, "rationale": "Incorrect. The BIOS already shows an 'Intel Virtualization Technology' option, which confirms the CPU has VT-x capability. The feature just needs to be enabled in BIOS/UEFI settings — no hardware replacement is necessary."},
        ],
        "explanation": "Many motherboards ship with Intel VT-x (or AMD-V) disabled by default in BIOS/UEFI even if the CPU supports it. When the hypervisor cannot detect the feature as active, it cannot run 64-bit guest VMs (since 64-bit hardware-assisted virtualization requires VT-x/AMD-V). The fix is always BIOS/UEFI firmware settings: enable 'Intel Virtualization Technology' or 'AMD-V/SVM Mode.' If no such option exists, the CPU may genuinely lack the feature, but in this scenario the BIOS option confirms hardware support.",
    },

    # ── VDI/DaaS (2 questions) ─────────────────────────────────────────────────
    {
        "id": "a1d4v2-021",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "VDI/DaaS",
        "stem": "An organization transitions from physical desktop PCs to thin clients. Each thin client connects to a central server farm where each employee's Windows 10 desktop — including their personal profile, applications, and data — runs as a virtual machine. The server farm is located in the company's own data center and managed entirely by the company's IT staff. Users experience a full Windows desktop without any local processing. Which term BEST describes this deployment?",
        "options": [
            {"id": "a", "text": "Desktop as a Service (DaaS)", "correct": False, "rationale": "Incorrect. DaaS is VDI hosted and managed by a cloud provider. In this scenario, the server farm and all VDI infrastructure are in the company's own data center and managed by its own IT staff — this is on-premises VDI, not a cloud service."},
            {"id": "b", "text": "Software as a Service (SaaS)", "correct": False, "rationale": "Incorrect. SaaS delivers finished applications over the Internet, managed by the vendor. A full virtual desktop environment where the user has a complete Windows OS experience is not a SaaS application — it is a virtualized desktop infrastructure."},
            {"id": "c", "text": "Virtual Desktop Infrastructure (VDI)", "correct": True, "rationale": "Correct. VDI hosts individual desktop OS instances (Windows 10 per user) as VMs on centralized server hardware. Users connect via thin clients using remote display protocols (RDP, ICA, PCoIP). When the infrastructure is in the company's own data center under IT management, it is on-premises VDI — the foundational model that DaaS is the cloud-hosted version of."},
            {"id": "d", "text": "Terminal Services / Remote Desktop Session Host (RDSH)", "correct": False, "rationale": "Incorrect. RDSH (formerly Terminal Services) allows multiple users to share a single server OS session simultaneously. VDI gives each user their own dedicated VM with their own OS instance. The scenario specifies individual Windows 10 desktops per employee — this is VDI's per-user VM model, not RDSH's shared session model."},
        ],
        "explanation": "VDI: each user gets a dedicated VM running a full desktop OS; central server hosts all VMs; thin clients connect via remote display protocols. DaaS: same VDI model but hosted and managed by a cloud provider. RDSH: multiple users share one server OS — cheaper but less isolated. The key differentiator in this question is who manages the infrastructure (company's IT = VDI, third-party provider = DaaS).",
    },
    {
        "id": "a1d4v2-022",
        "domain": 4,
        "objective": "4.1",
        "type": "multiple_choice",
        "difficulty": "expert",
        "study_topic": "VDI/DaaS",
        "stem": "A company with 500 remote employees is choosing between on-premises VDI and Desktop as a Service (DaaS). The CTO wants to minimize upfront capital expenditure, eliminate the burden of managing hypervisors and storage arrays, and retain the ability to scale from 500 to 1,000 users within a week if an acquisition occurs. Which solution provides ALL three benefits simultaneously?",
        "options": [
            {"id": "a", "text": "On-premises VDI using dedicated server hardware and storage arrays", "correct": False, "rationale": "Incorrect. On-premises VDI requires significant upfront capital expenditure (servers, storage, licenses) and requires the IT team to manage all hypervisors and storage infrastructure — two of the three requirements explicitly disqualified. Scaling to 1,000 users within a week would also require emergency hardware procurement, which typically takes weeks or months."},
            {"id": "b", "text": "Desktop as a Service (DaaS) from a cloud provider", "correct": True, "rationale": "Correct. DaaS is delivered as a subscription service (OpEx, no upfront hardware CapEx), the provider manages all hypervisors, storage, and infrastructure, and cloud-based DaaS can scale to thousands of users within hours or days by provisioning additional virtual desktops — all three CTO requirements are met simultaneously."},
            {"id": "c", "text": "On-premises VDI with a hot standby server cluster reserved for burst capacity", "correct": False, "rationale": "Incorrect. Pre-purchasing and maintaining idle hot-standby hardware dramatically increases both upfront capital expenditure and ongoing operational costs. The IT team still manages all hypervisors and storage. This solution fails on capital expenditure and infrastructure management burden."},
            {"id": "d", "text": "Physical desktop PCs shipped to each remote employee's home", "correct": False, "rationale": "Incorrect. Physical PCs involve significant hardware CapEx, eliminate any centralized management advantages of VDI, and cannot scale from 500 to 1,000 users within a week (hardware procurement and shipping logistics alone would prevent this). This option is inferior in every dimension requested."},
        ],
        "explanation": "DaaS advantages over on-premises VDI: (1) No CapEx — subscription/per-user monthly pricing; (2) Provider manages hypervisors, storage, networking, and patching; (3) Cloud elastic scaling — add users within hours, not months. On-premises VDI advantages: more control over data residency, potentially lower long-term TCO for stable large deployments, no dependency on provider. The CTO's three requirements all favor DaaS.",
    },

    # ── Client-side virtualization security (2 questions) ─────────────────────
    {
        "id": "a1d4v2-023",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_response",
        "difficulty": "hard",
        "study_topic": "Client-side virtualization security",
        "stem": "A technician is hardening a VM used for sensitive security research on a corporate laptop. The VM must be able to reach the Internet to download threat intelligence feeds, but it must NOT be reachable from the corporate LAN or from other VMs on the same host, and the corporate network must not be able to route traffic directly into the VM. Which TWO configuration actions will TOGETHER achieve these security requirements?",
        "options": [
            {"id": "a", "text": "Configure the VM's network adapter to use NAT mode so it accesses the Internet through the host's NAT engine without being directly addressable on the LAN", "correct": True, "rationale": "Correct. NAT mode hides the VM behind the hypervisor's NAT, providing outbound Internet access while making the VM unreachable from the corporate LAN (inbound connections cannot be initiated to the NAT'd VM). Other VMs are also unable to reach it directly."},
            {"id": "b", "text": "Disable or remove any shared-folder or drag-and-drop features between the host OS and the VM to prevent unintended data transfer pathways", "correct": True, "rationale": "Correct. Shared folders and drag-and-drop clipboard/file sharing between host and VM create data-transfer channels that bypass network-level controls. Disabling these features reduces the VM's attack surface and prevents sensitive research data from inadvertently leaking to or from the host OS."},
            {"id": "c", "text": "Configure the VM's network adapter to use Bridged mode so it gets a corporate LAN IP address for easier network management", "correct": False, "rationale": "Incorrect. Bridged mode places the VM directly on the corporate LAN with its own LAN IP address, making it fully reachable by and from other LAN hosts. This directly violates the requirement that the corporate network must not be able to route traffic into the VM."},
            {"id": "d", "text": "Increase the VM's vCPU allocation to four cores to ensure the security research workloads complete faster", "correct": False, "rationale": "Incorrect. Increasing vCPU allocation is a performance optimization and has no security implications for network isolation or data-transfer controls. It does not contribute to achieving the stated security requirements."},
        ],
        "explanation": "VM security hardening for sensitive research: (1) NAT networking — provides Internet access while blocking inbound LAN connectivity; (2) Disable guest integrations (shared folders, clipboard sharing, drag-and-drop) — eliminates data-leakage channels between host and guest; (3) Consider snapshots for clean-state recovery; (4) Keep VM tools updated but review which features are enabled. Bridged mode is the wrong choice here because it exposes the VM to the full corporate network.",
    },
    {
        "id": "a1d4v2-024",
        "domain": 4,
        "objective": "4.2",
        "type": "multiple_response",
        "difficulty": "expert",
        "study_topic": "Client-side virtualization security",
        "stem": "A company policy requires that virtual machines used for processing sensitive financial data must be configured to prevent data from leaking between the VM and the host OS or other VMs. Which TWO of the following configuration controls DIRECTLY address VM-to-host and VM-to-VM data leakage risks?",
        "options": [
            {"id": "a", "text": "Disabling clipboard sharing (copy-paste) between the guest VM and the host OS", "correct": True, "rationale": "Correct. Clipboard sharing allows data to be copied from the VM and pasted directly into the host OS (or vice versa) without any file transfer. Disabling this feature eliminates a covert channel through which sensitive financial data could be inadvertently or deliberately exfiltrated from the secure VM to the host or another VM that also has clipboard access."},
            {"id": "b", "text": "Setting the VM to use host-only networking instead of bridged networking", "correct": False, "rationale": "Incorrect. Host-only networking prevents the VM from reaching external networks, but it actually allows the VM to communicate with the host OS and other VMs on the same host-only adapter — which could be an additional leakage path. The question asks about controls that prevent data leakage between VM, host, and other VMs; host-only networking does not prevent VM-to-host communication."},
            {"id": "c", "text": "Disabling shared folders (host-to-guest folder mapping) between the host OS and the VM", "correct": True, "rationale": "Correct. Shared/mapped folders create a direct file-system bridge between the host OS and the VM. If a shared folder is mounted inside the sensitive-data VM, any process (including malware) running in the VM can read from or write to the host filesystem. Disabling shared folders eliminates this direct file-system data pathway."},
            {"id": "d", "text": "Allocating additional RAM to the VM to prevent memory swapping to the host's paging file", "correct": False, "rationale": "Incorrect. While memory over-commitment and swapping can introduce security concerns in some scenarios, allocating more RAM is primarily a performance optimization. It does not directly address the clipboard, file-sharing, or network-based data-leakage risks described in the policy requirement. The question asks for direct controls against VM-to-host and VM-to-VM data leakage."},
        ],
        "explanation": "VM isolation controls to prevent data leakage: (1) Disable clipboard/copy-paste sharing — eliminates the RAM-based clipboard channel; (2) Disable shared/mapped folders — eliminates the file-system bridge; (3) Use appropriate network isolation (NAT or no network for highly sensitive VMs) — prevents network-based exfiltration; (4) Disable drag-and-drop file transfer — another GUI-level data channel. Host-only networking is a network isolation tool but enables rather than prevents VM-to-host communication.",
    },
]
