"""
CompTIA Security+ (SY0-701) Domain 1: General Security Concepts
Flashcard deck covering objectives 1.1-1.4.
"""

CARDS = [
    # ------------------------------------------------------------------
    # 1.1 Compare and contrast various types of security controls
    # ------------------------------------------------------------------
    {"domain": 1, "study_topic": "Security control categories", "term": "Technical control",
     "definition": "A security control implemented using technology, such as firewalls, encryption, antivirus software, and access control lists, to reduce risk."},
    {"domain": 1, "study_topic": "Security control categories", "term": "Managerial control",
     "definition": "A security control implemented through administrative or governance actions, such as risk assessments and security policies, to manage risk by guiding strategy and personnel behavior."},
    {"domain": 1, "study_topic": "Security control categories", "term": "Operational control",
     "definition": "A security control implemented and executed primarily by people (rather than systems), such as security awareness training, incident response procedures, and configuration management."},
    {"domain": 1, "study_topic": "Security control categories", "term": "Physical control",
     "definition": "A security control that limits physical access to facilities, hardware, or areas, such as locks, fences, guards, and badge readers."},
    {"domain": 1, "study_topic": "Security control types", "term": "Preventive control",
     "definition": "A control that acts before an event to stop an incident from occurring, such as firewalls, access control lists, or security awareness training."},
    {"domain": 1, "study_topic": "Security control types", "term": "Deterrent control",
     "definition": "A control that discourages an attacker from attempting an intrusion by making the attempt appear more difficult or risky, such as warning signs, lighting, or visible security cameras."},
    {"domain": 1, "study_topic": "Security control types", "term": "Detective control",
     "definition": "A control that identifies and records that an intrusion or incident has occurred (or is occurring), such as log monitoring, IDS alerts, or security audits."},
    {"domain": 1, "study_topic": "Security control types", "term": "Corrective control",
     "definition": "A control that acts after an incident to limit its extent and restore normal operations, such as restoring backups, applying patches, or isolating an infected host."},
    {"domain": 1, "study_topic": "Security control types", "term": "Compensating control",
     "definition": "An alternative control used when a primary control is not feasible or cost-effective, providing similar protection to satisfy a security requirement, such as network segmentation used in place of an unpatchable legacy system's missing patch."},
    {"domain": 1, "study_topic": "Security control types", "term": "Directive control",
     "definition": "A control that directs or mandates a specific behavior or action, such as policies, standards, and procedures that tell personnel what they must do."},

    # ------------------------------------------------------------------
    # 1.2 Summarize fundamental security concepts
    # ------------------------------------------------------------------
    {"domain": 1, "study_topic": "CIA triad", "term": "Confidentiality",
     "definition": "The security principle that ensures information is accessible only to authorized individuals, systems, or processes, typically enforced through encryption and access controls."},
    {"domain": 1, "study_topic": "CIA triad", "term": "Integrity",
     "definition": "The security principle that ensures data has not been altered in an unauthorized manner, verified through mechanisms such as hashing and digital signatures."},
    {"domain": 1, "study_topic": "CIA triad", "term": "Availability",
     "definition": "The security principle that ensures information and systems are accessible to authorized users when needed, supported by redundancy, fault tolerance, and patching."},
    {"domain": 1, "study_topic": "Non-repudiation", "term": "Non-repudiation",
     "definition": "The assurance that a party cannot deny having performed an action, such as sending a message or making a transaction, typically provided through digital signatures and audit logs."},
    {"domain": 1, "study_topic": "AAA framework", "term": "Authentication",
     "definition": "The process of verifying that a subject (user, device, or system) is who or what it claims to be, typically by validating credentials such as passwords, tokens, or biometrics."},
    {"domain": 1, "study_topic": "AAA framework", "term": "Authorization",
     "definition": "The process of granting an authenticated subject specific permissions and access rights to resources based on policy."},
    {"domain": 1, "study_topic": "AAA framework", "term": "Accounting",
     "definition": "The process of tracking and logging a subject's actions and resource usage, providing an audit trail for review and non-repudiation."},
    {"domain": 1, "study_topic": "Authentication factors", "term": "Something you know",
     "definition": "A knowledge-based authentication factor, such as a password, PIN, or security question answer, that only the legitimate user should know."},
    {"domain": 1, "study_topic": "Authentication factors", "term": "Something you have",
     "definition": "A possession-based authentication factor, such as a smart card, hardware token, or smartphone authenticator app, that the legitimate user physically holds."},
    {"domain": 1, "study_topic": "Authentication factors", "term": "Something you are",
     "definition": "An inherence-based authentication factor using a physical biometric characteristic, such as a fingerprint, iris scan, or facial recognition, unique to the individual."},
    {"domain": 1, "study_topic": "Authentication factors", "term": "Somewhere you are",
     "definition": "A location-based authentication factor that validates identity using the subject's geographic location or network location, such as GPS coordinates or IP address."},
    {"domain": 1, "study_topic": "Authentication factors", "term": "Something you can do (behavioral)",
     "definition": "A behavioral biometric authentication factor based on how a person performs an action, such as typing cadence, signature dynamics, or gait analysis."},
    {"domain": 1, "study_topic": "Authentication", "term": "Multifactor authentication (MFA)",
     "definition": "An authentication scheme that requires two or more independent factors (e.g., something you know plus something you have) to verify identity, reducing the risk of compromise from a single stolen credential."},
    {"domain": 1, "study_topic": "Authentication", "term": "Authenticating people",
     "definition": "Verifying human identity using knowledge, possession, inherence, location, or behavioral factors, often combined for multifactor authentication."},
    {"domain": 1, "study_topic": "Authentication", "term": "Authenticating systems",
     "definition": "Verifying the identity of a device, service, or system (rather than a human) using mechanisms such as digital certificates, pre-shared keys, or API tokens."},
    {"domain": 1, "study_topic": "Gap analysis", "term": "Gap analysis",
     "definition": "An assessment process that compares an organization's current security posture against a desired standard or baseline to identify deficiencies that must be remediated."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Zero Trust",
     "definition": "A security model built on the principle of 'never trust, always verify,' which eliminates implicit trust and requires continuous verification of every user, device, and transaction regardless of network location."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Control plane",
     "definition": "The Zero Trust architecture layer responsible for defining and managing policy, including adaptive identity, threat scope reduction, policy-driven access control, and coordination via the policy engine and policy administrator."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Data plane",
     "definition": "The Zero Trust architecture layer responsible for actually processing traffic and enforcing the decisions made by the control plane, primarily through the policy enforcement point."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Adaptive identity",
     "definition": "A Zero Trust control-plane concept in which authentication and access decisions dynamically adjust based on real-time contextual signals such as user behavior, location, and device posture."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Threat scope reduction",
     "definition": "A Zero Trust principle of limiting the number of possible pathways or access points an attacker could exploit, minimizing the potential attack surface and blast radius."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Policy-driven access control",
     "definition": "A Zero Trust approach that grants access based on a defined set of policies combining role, context, and risk, rather than static network location."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Policy administrator",
     "definition": "The Zero Trust control-plane component that establishes and manages the communication path between a subject and a resource, issuing commands to the policy enforcement point based on the policy engine's decision."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Policy engine",
     "definition": "The Zero Trust control-plane component that evaluates access requests against policy and trust algorithms to produce a decision (grant, deny, or revoke access) for a given subject and resource."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Policy Enforcement Point (PEP)",
     "definition": "The Zero Trust data-plane component that allows, denies, or terminates a connection based on the policy engine's decision."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Implicit trust zones",
     "definition": "Network segments or areas within a Zero Trust architecture where entities are trusted without additional verification once they gain entry; Zero Trust design seeks to minimize the size and number of these zones."},
    {"domain": 1, "study_topic": "Zero Trust", "term": "Subject and system (Zero Trust)",
     "definition": "In Zero Trust terminology, the subject is the user, application, or service requesting access, and the system is the device or workload through which that access request is made; both must be independently verified."},
    {"domain": 1, "study_topic": "Physical security", "term": "Bollards",
     "definition": "Short, sturdy vertical posts installed around a building's perimeter to prevent vehicle-ramming attacks while still allowing pedestrian access."},
    {"domain": 1, "study_topic": "Physical security", "term": "Access control vestibule",
     "definition": "A small, secure entryway (also called a mantrap) with two interlocking doors that allows only one person to pass at a time, preventing tailgating into a secure facility."},
    {"domain": 1, "study_topic": "Physical security", "term": "Fencing",
     "definition": "A physical barrier that defines and protects the perimeter of a facility, deterring and delaying unauthorized entry."},
    {"domain": 1, "study_topic": "Physical security", "term": "Video surveillance",
     "definition": "The use of CCTV cameras to monitor and record activity in and around a facility, serving as both a deterrent and a detective/investigative control."},
    {"domain": 1, "study_topic": "Physical security", "term": "Security guard",
     "definition": "Personnel stationed to monitor access, verify identity, and respond to physical security incidents, providing a visible deterrent and active detective/preventive control."},
    {"domain": 1, "study_topic": "Physical security", "term": "Access badge",
     "definition": "A physical credential (often with an embedded RFID or smart chip) used to authenticate an individual and authorize physical entry to a facility or secure area."},
    {"domain": 1, "study_topic": "Physical security", "term": "Lighting",
     "definition": "Illumination of building perimeters and entry points used as a deterrent control to discourage intruders and improve the effectiveness of surveillance and guards."},
    {"domain": 1, "study_topic": "Physical security", "term": "Infrared sensor",
     "definition": "A motion or intrusion detection sensor that detects changes in infrared (heat) energy, commonly used to sense the presence or movement of a person in a monitored area."},
    {"domain": 1, "study_topic": "Physical security", "term": "Pressure sensor",
     "definition": "A physical intrusion detection sensor that detects weight or force applied to a surface, such as a floor mat or door plate, to trigger an alert."},
    {"domain": 1, "study_topic": "Physical security", "term": "Microwave sensor",
     "definition": "A motion detection sensor that emits microwave pulses and measures reflections to detect movement over a wide area, often used for outdoor perimeter detection."},
    {"domain": 1, "study_topic": "Physical security", "term": "Ultrasonic sensor",
     "definition": "A motion detection sensor that emits high-frequency sound waves and measures the reflection pattern to detect movement within an enclosed space."},
    {"domain": 1, "study_topic": "Deception and disruption technology", "term": "Honeypot",
     "definition": "A decoy system designed to look like a legitimate, vulnerable target in order to attract attackers, divert them from real assets, and allow defenders to observe attack techniques."},
    {"domain": 1, "study_topic": "Deception and disruption technology", "term": "Honeynet",
     "definition": "A network of multiple interconnected honeypots designed to simulate a realistic decoy network, allowing observation of how attackers move laterally and interact with multiple systems."},
    {"domain": 1, "study_topic": "Deception and disruption technology", "term": "Honeyfile",
     "definition": "A decoy file (e.g., named 'passwords.xlsx') placed on a system to lure and detect attackers or insiders who access or exfiltrate it, triggering an alert."},
    {"domain": 1, "study_topic": "Deception and disruption technology", "term": "Honeytoken",
     "definition": "A decoy piece of data, such as a fake credential, database record, or API key, embedded within real systems that triggers an alert when it is accessed or used, indicating unauthorized activity."},

    # ------------------------------------------------------------------
    # 1.3 Change management processes and their security impact
    # ------------------------------------------------------------------
    {"domain": 1, "study_topic": "Change management", "term": "Change management",
     "definition": "A formal process for proposing, reviewing, approving, implementing, and documenting changes to IT systems in a controlled manner to minimize risk and unintended security impact."},
    {"domain": 1, "study_topic": "Change management", "term": "Approval process",
     "definition": "The formal workflow through which a proposed change is reviewed and authorized by designated approvers, such as a change advisory board, before implementation."},
    {"domain": 1, "study_topic": "Change management", "term": "Ownership (change management)",
     "definition": "The assignment of a specific individual or role as accountable for a proposed change, including its planning, execution, and outcome."},
    {"domain": 1, "study_topic": "Change management", "term": "Stakeholders",
     "definition": "The individuals or groups affected by, or with an interest in, a proposed change who should be identified and consulted as part of the change management process."},
    {"domain": 1, "study_topic": "Change management", "term": "Impact analysis",
     "definition": "An assessment conducted before a change is implemented to determine its potential effects on systems, users, security posture, and business operations."},
    {"domain": 1, "study_topic": "Change management", "term": "Test results",
     "definition": "Documentation of the outcomes from testing a change in a non-production environment, used to validate that the change works as intended and does not introduce new risk before approval."},
    {"domain": 1, "study_topic": "Change management", "term": "Backout plan",
     "definition": "A predefined plan describing the steps to reverse or roll back a change if it fails or causes unintended negative consequences, restoring the system to its previous state."},
    {"domain": 1, "study_topic": "Change management", "term": "Maintenance window",
     "definition": "A scheduled time period, typically during low-usage hours, during which changes are implemented to minimize disruption to users and business operations."},
    {"domain": 1, "study_topic": "Change management", "term": "Standard operating procedure (SOP)",
     "definition": "A documented, step-by-step set of instructions that describes how to perform a routine activity or change consistently and securely."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Allow list",
     "definition": "A security configuration approach that permits only explicitly approved applications, IP addresses, or activities to execute or connect, denying everything else by default."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Deny list (block list)",
     "definition": "A security configuration approach that explicitly blocks known-bad applications, IP addresses, or activities while permitting everything else by default."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Restricted activities",
     "definition": "Actions or operations that are limited or prohibited during a change window to reduce risk, such as disabling user access to a system while it is being updated."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Downtime",
     "definition": "The period during which a system, service, or application is unavailable to users, which must be planned for and minimized as part of a change's technical impact assessment."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Service restart",
     "definition": "The technical requirement to stop and start a background service to apply a change, which can cause temporary unavailability and must be accounted for in change planning."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Application restart",
     "definition": "The technical requirement to stop and start an application to apply a change, which can interrupt user sessions and must be scheduled appropriately."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Legacy applications",
     "definition": "Older applications that may be incompatible with current patches, standards, or configurations, often requiring compensating controls and careful consideration during change management."},
    {"domain": 1, "study_topic": "Technical change implications", "term": "Dependencies (change management)",
     "definition": "Other systems, services, or applications that rely on the component being changed, which must be identified so a change does not produce unintended downstream failures."},
    {"domain": 1, "study_topic": "Change documentation", "term": "Version control",
     "definition": "A system for tracking and managing changes to code, configurations, and documentation over time, allowing changes to be reviewed, compared, and rolled back if necessary."},
    {"domain": 1, "study_topic": "Change documentation", "term": "Updating diagrams",
     "definition": "The practice of revising network, system, and data flow diagrams to reflect the current state of the environment after a change is implemented, ensuring documentation accuracy."},
    {"domain": 1, "study_topic": "Change documentation", "term": "Updating policies and procedures",
     "definition": "The practice of revising organizational policies and procedures to reflect new processes, controls, or configurations introduced by a change."},

    # ------------------------------------------------------------------
    # 1.4 Cryptographic solutions
    # ------------------------------------------------------------------
    {"domain": 1, "study_topic": "PKI", "term": "Public key infrastructure (PKI)",
     "definition": "The framework of policies, procedures, hardware, software, and roles used to create, manage, distribute, and revoke digital certificates and manage public-key encryption."},
    {"domain": 1, "study_topic": "PKI", "term": "Public key",
     "definition": "The publicly shareable half of an asymmetric key pair, used to encrypt data or verify a digital signature created by the corresponding private key."},
    {"domain": 1, "study_topic": "PKI", "term": "Private key",
     "definition": "The secret half of an asymmetric key pair, kept confidential by its owner, used to decrypt data encrypted with the public key or to create digital signatures."},
    {"domain": 1, "study_topic": "PKI", "term": "Key escrow",
     "definition": "The practice of storing a copy of a cryptographic key with a trusted third party, allowing authorized recovery of encrypted data if the original key is lost or as required by policy."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "Full-disk encryption (FDE)",
     "definition": "Encryption that protects the entire contents of a storage drive, including the operating system, ensuring data is unreadable if the physical drive is stolen."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "Partition encryption",
     "definition": "Encryption applied to a specific logical partition of a storage device rather than the entire disk, protecting only the data within that partition."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "File encryption",
     "definition": "Encryption applied to individual files, protecting their contents regardless of where the file is stored or transmitted."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "Volume encryption",
     "definition": "Encryption applied to a logical storage volume, which may span multiple disks or be a container, protecting all data written to that volume."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "Database encryption",
     "definition": "Encryption applied to an entire database or specific tables/columns within it, protecting stored data from unauthorized access at rest."},
    {"domain": 1, "study_topic": "Encryption levels", "term": "Record encryption",
     "definition": "Encryption applied to individual records within a database, providing granular protection for specific rows of sensitive data."},
    {"domain": 1, "study_topic": "Encryption in transit", "term": "Transport/communication encryption",
     "definition": "Encryption applied to data as it moves across a network, such as TLS or IPSec, protecting confidentiality and integrity of data in transit."},
    {"domain": 1, "study_topic": "Encryption fundamentals", "term": "Asymmetric encryption",
     "definition": "An encryption method that uses a mathematically related key pair, a public key and a private key, where data encrypted with one key can only be decrypted with the other."},
    {"domain": 1, "study_topic": "Encryption fundamentals", "term": "Symmetric encryption",
     "definition": "An encryption method that uses a single shared secret key for both encryption and decryption, offering faster performance than asymmetric encryption but requiring secure key distribution."},
    {"domain": 1, "study_topic": "Encryption fundamentals", "term": "Key exchange",
     "definition": "The process by which two parties securely share or derive a shared cryptographic key over an insecure channel, such as through the Diffie-Hellman key exchange protocol."},
    {"domain": 1, "study_topic": "Encryption fundamentals", "term": "Algorithms (cryptographic)",
     "definition": "The mathematical procedures used to perform encryption, decryption, hashing, or key generation, such as AES, RSA, and SHA-256."},
    {"domain": 1, "study_topic": "Encryption fundamentals", "term": "Key length",
     "definition": "The size of a cryptographic key, typically measured in bits, where longer keys generally provide greater resistance to brute-force attacks."},
    {"domain": 1, "study_topic": "Cryptographic tools", "term": "Trusted Platform Module (TPM)",
     "definition": "A dedicated hardware chip embedded in a device that securely generates and stores cryptographic keys and supports features such as full-disk encryption and secure boot."},
    {"domain": 1, "study_topic": "Cryptographic tools", "term": "Hardware security module (HSM)",
     "definition": "A dedicated physical device that securely generates, stores, and manages cryptographic keys and performs cryptographic operations, often used to protect high-value keys such as a CA's root key."},
    {"domain": 1, "study_topic": "Cryptographic tools", "term": "Key management system (KMS)",
     "definition": "A system that centrally manages the lifecycle of cryptographic keys, including generation, distribution, rotation, storage, and revocation."},
    {"domain": 1, "study_topic": "Cryptographic tools", "term": "Secure enclave",
     "definition": "An isolated, hardware-based secure processing area within a device's chip that protects sensitive data and cryptographic operations from the rest of the system, even if the main OS is compromised."},
    {"domain": 1, "study_topic": "Obfuscation", "term": "Steganography",
     "definition": "The practice of concealing a message or data within another file, such as embedding text within an image, so that its existence is hidden rather than merely encrypted."},
    {"domain": 1, "study_topic": "Obfuscation", "term": "Tokenization",
     "definition": "A data protection technique that replaces sensitive data with a non-sensitive placeholder value (a token) that has no exploitable value, with the original data mapped and stored securely elsewhere."},
    {"domain": 1, "study_topic": "Obfuscation", "term": "Data masking",
     "definition": "A technique that obscures original data by replacing, shuffling, or partially hiding it (e.g., showing only the last four digits of a credit card number) so sensitive values are not exposed."},
    {"domain": 1, "study_topic": "Hashing", "term": "Hashing",
     "definition": "A one-way mathematical function that converts input data of any size into a fixed-length output (hash/digest), used to verify data integrity since any change to the input produces a different hash."},
    {"domain": 1, "study_topic": "Hashing", "term": "Salting",
     "definition": "The practice of adding random data to a password before hashing it, which ensures identical passwords produce different hashes and defeats precomputed rainbow table attacks."},
    {"domain": 1, "study_topic": "Hashing", "term": "Key stretching",
     "definition": "A technique that strengthens a weak key or password by repeatedly processing it through a hashing algorithm (e.g., PBKDF2, bcrypt), making brute-force attacks significantly slower."},
    {"domain": 1, "study_topic": "Digital signatures", "term": "Digital signature",
     "definition": "A cryptographic mechanism that uses a sender's private key to sign a hash of a message, allowing recipients to verify the message's authenticity, integrity, and non-repudiation using the sender's public key."},
    {"domain": 1, "study_topic": "Blockchain", "term": "Blockchain",
     "definition": "A distributed, cryptographically linked ledger of transaction records maintained across a decentralized network of nodes, where each block references the previous block's hash to ensure tamper evidence."},
    {"domain": 1, "study_topic": "Blockchain", "term": "Open public ledger",
     "definition": "A distributed and typically transparent record of transactions, such as a public blockchain, that anyone can view and verify, providing integrity through decentralization and cryptographic linking."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate authority (CA)",
     "definition": "A trusted entity within a PKI that issues, signs, and manages digital certificates, vouching for the identity of the certificate holder."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate revocation list (CRL)",
     "definition": "A list published by a certificate authority containing the serial numbers of certificates that have been revoked before their expiration date and should no longer be trusted."},
    {"domain": 1, "study_topic": "Certificates", "term": "Online Certificate Status Protocol (OCSP)",
     "definition": "A protocol that allows a client to query a certificate authority in real time to determine whether a specific digital certificate is still valid or has been revoked, offering a faster alternative to downloading a full CRL."},
    {"domain": 1, "study_topic": "Certificates", "term": "Self-signed certificate",
     "definition": "A digital certificate signed by its own creator rather than a trusted certificate authority, often used for internal testing but not inherently trusted by external clients."},
    {"domain": 1, "study_topic": "Certificates", "term": "Third-party certificate",
     "definition": "A digital certificate issued and signed by an external, trusted certificate authority, allowing browsers and clients to automatically trust it via a chain of trust."},
    {"domain": 1, "study_topic": "Certificates", "term": "Root of trust",
     "definition": "The foundational, inherently trusted certificate authority or cryptographic key at the top of a PKI hierarchy from which the trust of all subordinate certificates is derived."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate signing request (CSR)",
     "definition": "A block of encoded text containing an applicant's public key and identifying information that is submitted to a certificate authority to request the issuance of a digital certificate."},
    {"domain": 1, "study_topic": "Certificates", "term": "Wildcard certificate",
     "definition": "A digital certificate that uses a wildcard notation (e.g., *.example.com) to secure a base domain and all of its first-level subdomains with a single certificate."},
    {"domain": 1, "study_topic": "Certificates", "term": "Certificate attributes",
     "definition": "The identifying fields within a digital certificate, such as subject name, issuer, validity period, public key, and Subject Alternative Name (SAN), that define what the certificate covers and who issued it."},
]
