"""CompTIA Security+ SY0-701 — Domain 2: Threats, Vulnerabilities, and Mitigations.

Covers objectives 2.1 through 2.5: threat actors and motivations, threat
vectors and attack surfaces, vulnerability types, indicators of malicious
activity, and mitigation techniques.
"""

from __future__ import annotations

CARDS: list[dict] = [
    # ------------------------------------------------------------------
    # 2.1 Threat actors, attributes, and motivations
    # ------------------------------------------------------------------
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Nation-state actor",
        "definition": "A highly resourced, government-sponsored threat actor that conducts espionage, sabotage, or warfare using advanced persistent threat (APT) techniques.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Unskilled attacker",
        "definition": "A low-skill attacker (formerly called a script kiddie) who uses pre-built tools and scripts written by others without understanding the underlying techniques.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Hacktivist",
        "definition": "A threat actor motivated by political or social causes who attacks or defaces targets to promote an ideological agenda rather than for financial gain.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Insider threat",
        "definition": "A current or former employee, contractor, or partner who intentionally or unintentionally misuses authorized access to harm the organization.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Organized crime",
        "definition": "A well-funded, highly capable group of criminals that conducts cyberattacks such as ransomware and fraud purely for financial gain.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actors",
        "term": "Shadow IT",
        "definition": "Hardware, software, or cloud services deployed by employees or departments without the knowledge, approval, or oversight of the IT/security team, creating unmanaged risk.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor attributes",
        "term": "Internal threat actor",
        "definition": "A threat actor who already has legitimate access inside the organization, such as an employee or contractor, making detection harder due to trusted access.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor attributes",
        "term": "External threat actor",
        "definition": "A threat actor with no authorized access to the organization who must breach perimeter defenses from outside to attack systems or data.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor attributes",
        "term": "Resources and funding (threat actor attribute)",
        "definition": "An attribute describing how much money, staffing, and infrastructure a threat actor has available, ranging from minimal (unskilled attackers) to virtually unlimited (nation-states).",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor attributes",
        "term": "Level of sophistication/capability",
        "definition": "An attribute describing a threat actor's technical skill and ability to develop custom tools, zero-day exploits, and advanced tradecraft versus relying on off-the-shelf tools.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Data exfiltration (motivation)",
        "definition": "A threat actor motivation focused on stealing sensitive data such as intellectual property, PII, or credentials for profit or intelligence value.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Espionage (motivation)",
        "definition": "A threat actor motivation involving covert intelligence gathering, typically by nation-states, to gain political, military, or economic advantage.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Service disruption (motivation)",
        "definition": "A threat actor motivation aimed at taking systems or services offline, such as through a DDoS attack, to cause operational harm.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Blackmail (motivation)",
        "definition": "A threat actor motivation involving the threat to expose stolen or embarrassing data unless the victim pays or complies with demands.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Financial gain (motivation)",
        "definition": "A threat actor motivation centered on directly profiting from an attack, such as through ransomware payments, fraud, or selling stolen data.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Philosophical/political beliefs (motivation)",
        "definition": "A threat actor motivation, typical of hacktivists, driven by ideological, political, or social causes rather than money.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Ethical motivation",
        "definition": "A threat actor motivation in which the actor believes they are acting for the greater good, such as a white-hat hacker or a whistleblower exposing wrongdoing.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Revenge (motivation)",
        "definition": "A threat actor motivation, common among disgruntled insiders, driven by a desire to retaliate against an organization or individual.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "Disruption/chaos (motivation)",
        "definition": "A threat actor motivation focused purely on causing damage or disorder for its own sake, without a specific financial or ideological goal.",
    },
    {
        "domain": 2,
        "study_topic": "Threat actor motivations",
        "term": "War (motivation)",
        "definition": "A threat actor motivation involving nation-state-sponsored cyberattacks conducted as part of, or in preparation for, armed conflict.",
    },
    # ------------------------------------------------------------------
    # 2.2 Threat vectors and attack surfaces
    # ------------------------------------------------------------------
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Message-based vector",
        "definition": "An attack surface where malicious content is delivered via email, SMS, or instant messaging to trick a user into clicking a link or opening an attachment.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Image-based vector",
        "definition": "An attack vector in which malicious code or scripts are embedded within an image file, executing when the image is processed or rendered.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "File-based vector",
        "definition": "An attack vector where malware is hidden inside a seemingly legitimate document or executable file that a user is tricked into opening.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Voice call vector",
        "definition": "An attack vector in which an attacker uses a phone call (vishing) to socially engineer a victim into revealing information or performing an action.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Removable device vector",
        "definition": "An attack vector in which malware is delivered via USB drives or other removable media, such as a dropped USB baiting attack.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Vulnerable software vector",
        "definition": "An attack vector that exploits unpatched or poorly coded client-based or agentless software to gain unauthorized access.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Client-based vulnerable software",
        "definition": "Software that must be installed locally on a device (an agent), whose local vulnerabilities can be exploited to compromise the host.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Agentless vulnerable software",
        "definition": "Software or services that operate without installing a local client, such as network-based or cloud-based scanning, which can still contain exploitable vulnerabilities.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Unsupported systems and applications",
        "definition": "Software or hardware that no longer receives vendor patches or security updates, leaving known vulnerabilities permanently unmitigated.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Unsecure networks",
        "definition": "Wireless, wired, or Bluetooth networks lacking proper encryption or authentication controls, allowing attackers to intercept or manipulate traffic.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Open service ports",
        "definition": "Network ports left open and listening for connections that are not required for business operations, increasing the attack surface available to adversaries.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Default credentials",
        "definition": "Factory-set usernames and passwords on devices or software that, if left unchanged, allow attackers easy unauthorized access.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Supply chain attack vector",
        "definition": "An attack that compromises an organization indirectly through its managed service providers, vendors, or suppliers rather than attacking it directly.",
    },
    {
        "domain": 2,
        "study_topic": "Threat vectors",
        "term": "Managed service provider (MSP) risk",
        "definition": "The risk that a third party managing an organization's IT infrastructure could be compromised or misused as an entry point into the organization's network.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Phishing",
        "definition": "A social engineering attack that uses fraudulent emails appearing to be from a trusted source to trick victims into revealing information or installing malware.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Vishing",
        "definition": "A social engineering attack conducted over voice calls or voicemail that tricks victims into divulging sensitive information.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Smishing",
        "definition": "A social engineering attack delivered via SMS text messages that tricks victims into clicking malicious links or divulging information.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Misinformation/disinformation",
        "definition": "The spread of false information, either unintentionally (misinformation) or deliberately (disinformation), to deceive or influence targets.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Impersonation",
        "definition": "A social engineering technique in which an attacker pretends to be a trusted person, such as an executive or IT support, to manipulate a victim.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Business email compromise (BEC)",
        "definition": "A social engineering attack in which an attacker impersonates or compromises an executive's email account to trick employees into transferring funds or data.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Pretexting",
        "definition": "A social engineering technique in which an attacker fabricates a believable scenario or false identity to persuade a victim to divulge information.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Watering hole attack",
        "definition": "An attack that compromises a website known to be frequently visited by the target group, infecting visitors' devices when they browse the site.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Brand impersonation",
        "definition": "A social engineering technique in which an attacker mimics a well-known company's branding, emails, or website to deceive victims into trusting a malicious message.",
    },
    {
        "domain": 2,
        "study_topic": "Human vectors / social engineering",
        "term": "Typosquatting",
        "definition": "A technique in which an attacker registers domain names that are common misspellings of legitimate sites to capture mistyped traffic or deliver malware.",
    },
    # ------------------------------------------------------------------
    # 2.3 Vulnerabilities
    # ------------------------------------------------------------------
    {
        "domain": 2,
        "study_topic": "Application vulnerabilities",
        "term": "Memory injection",
        "definition": "A vulnerability in which an attacker injects malicious code directly into a running process's memory space to execute arbitrary code.",
    },
    {
        "domain": 2,
        "study_topic": "Application vulnerabilities",
        "term": "Buffer overflow",
        "definition": "A vulnerability in which a program writes more data to a memory buffer than it was allocated, overwriting adjacent memory and potentially allowing code execution.",
    },
    {
        "domain": 2,
        "study_topic": "Application vulnerabilities",
        "term": "Race condition",
        "definition": "A vulnerability that occurs when the outcome of a process depends on the timing or order of uncontrollable events, allowing exploitation of the timing gap.",
    },
    {
        "domain": 2,
        "study_topic": "Application vulnerabilities",
        "term": "Time-of-check to time-of-use (TOCTOU)",
        "definition": "A race-condition vulnerability where a resource's state is checked and then used, and an attacker changes the resource in between, causing unintended behavior.",
    },
    {
        "domain": 2,
        "study_topic": "Application vulnerabilities",
        "term": "Malicious update",
        "definition": "A vulnerability introduced when a trusted software update mechanism is compromised to distribute malware disguised as a legitimate patch.",
    },
    {
        "domain": 2,
        "study_topic": "Operating system vulnerabilities",
        "term": "Operating system vulnerability",
        "definition": "A flaw in an OS's code or configuration, such as an unpatched kernel bug, that can be exploited to gain unauthorized access or elevate privileges.",
    },
    {
        "domain": 2,
        "study_topic": "Web vulnerabilities",
        "term": "SQL injection (SQLi)",
        "definition": "A web application vulnerability in which an attacker inserts malicious SQL statements into an input field to manipulate or exfiltrate database data.",
    },
    {
        "domain": 2,
        "study_topic": "Web vulnerabilities",
        "term": "Cross-site scripting (XSS)",
        "definition": "A web application vulnerability in which an attacker injects malicious client-side scripts into trusted web pages that execute in other users' browsers.",
    },
    {
        "domain": 2,
        "study_topic": "Hardware vulnerabilities",
        "term": "Firmware vulnerability",
        "definition": "A flaw in the low-level software embedded in hardware devices that can be exploited to gain persistent, hard-to-detect control of the device.",
    },
    {
        "domain": 2,
        "study_topic": "Hardware vulnerabilities",
        "term": "End-of-life (EOL) hardware/software",
        "definition": "A product that the vendor has stopped selling and supporting, though it may still receive limited support, unlike end-of-support products.",
    },
    {
        "domain": 2,
        "study_topic": "Hardware vulnerabilities",
        "term": "Legacy hardware/software",
        "definition": "Outdated systems that are no longer supported or updated by the vendor, often kept in use due to cost or compatibility needs, posing significant security risk.",
    },
    {
        "domain": 2,
        "study_topic": "Virtualization vulnerabilities",
        "term": "VM escape",
        "definition": "A vulnerability that allows an attacker to break out of an isolated virtual machine and gain access to the host hypervisor or other VMs on the same host.",
    },
    {
        "domain": 2,
        "study_topic": "Virtualization vulnerabilities",
        "term": "Resource reuse (virtualization)",
        "definition": "A vulnerability in which data remnants left in shared memory or storage from one virtual machine or tenant can be accessed by another after reallocation.",
    },
    {
        "domain": 2,
        "study_topic": "Cloud vulnerabilities",
        "term": "Cloud-specific vulnerability",
        "definition": "A weakness unique to cloud environments, such as misconfigured storage buckets, insecure APIs, or weak identity and access management, that exposes data or resources.",
    },
    {
        "domain": 2,
        "study_topic": "Supply chain vulnerabilities",
        "term": "Service provider vulnerability",
        "definition": "A supply chain weakness arising from a third-party service provider's security practices that can be exploited to compromise its customers.",
    },
    {
        "domain": 2,
        "study_topic": "Supply chain vulnerabilities",
        "term": "Hardware provider vulnerability",
        "definition": "A supply chain weakness in which compromised or counterfeit components from a hardware manufacturer introduce risk into the finished product.",
    },
    {
        "domain": 2,
        "study_topic": "Supply chain vulnerabilities",
        "term": "Software provider vulnerability",
        "definition": "A supply chain weakness in which a software vendor's insecure development or distribution practices introduce vulnerabilities into downstream customers' systems.",
    },
    {
        "domain": 2,
        "study_topic": "Cryptographic vulnerabilities",
        "term": "Cryptographic vulnerability",
        "definition": "A weakness resulting from the use of weak algorithms, improper key management, or flawed implementation of encryption that can expose protected data.",
    },
    {
        "domain": 2,
        "study_topic": "Misconfiguration vulnerabilities",
        "term": "Misconfiguration vulnerability",
        "definition": "A security weakness caused by incorrectly configured systems, such as open permissions, default settings, or disabled security controls.",
    },
    {
        "domain": 2,
        "study_topic": "Mobile vulnerabilities",
        "term": "Side loading",
        "definition": "The practice of installing applications on a mobile device from a source other than the official app store, bypassing security vetting and increasing malware risk.",
    },
    {
        "domain": 2,
        "study_topic": "Mobile vulnerabilities",
        "term": "Jailbreaking",
        "definition": "The process of removing manufacturer or carrier restrictions on a mobile device to gain root-level access, which disables built-in security protections.",
    },
    {
        "domain": 2,
        "study_topic": "Zero-day vulnerabilities",
        "term": "Zero-day vulnerability",
        "definition": "A previously unknown software or hardware flaw that has no available patch, giving defenders zero days to prepare before it can be exploited.",
    },
    # ------------------------------------------------------------------
    # 2.4 Indicators of malicious activity
    # ------------------------------------------------------------------
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Ransomware",
        "definition": "Malware that encrypts a victim's files or systems and demands payment, often in cryptocurrency, in exchange for the decryption key.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Trojan",
        "definition": "Malware disguised as legitimate software that tricks users into installing it, after which it performs malicious actions in the background.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Worm",
        "definition": "Self-replicating malware that spreads across networks and systems without requiring user interaction or a host file.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Spyware",
        "definition": "Malware that covertly monitors and collects information about a user's activity, such as browsing habits or credentials, and sends it to an attacker.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Bloatware",
        "definition": "Unnecessary pre-installed or unwanted software that consumes system resources and can introduce additional attack surface or vulnerabilities.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Virus",
        "definition": "Malicious code that attaches itself to a legitimate host file or program and requires user execution to replicate and spread.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Keylogger",
        "definition": "Malware or a device that records a user's keystrokes to capture sensitive information such as usernames, passwords, and credit card numbers.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Logic bomb",
        "definition": "Malicious code that lies dormant until triggered by a specific condition or date, at which point it executes its damaging payload.",
    },
    {
        "domain": 2,
        "study_topic": "Malware attacks",
        "term": "Rootkit",
        "definition": "Malware designed to gain and maintain privileged access to a system while hiding its presence from the operating system and security tools.",
    },
    {
        "domain": 2,
        "study_topic": "Physical attacks",
        "term": "Brute force (physical)",
        "definition": "A physical attack technique that uses repeated force or systematic attempts, such as trying many key or PIN combinations, to bypass a physical security control.",
    },
    {
        "domain": 2,
        "study_topic": "Physical attacks",
        "term": "RFID cloning",
        "definition": "A physical attack in which an attacker copies the data from a legitimate RFID badge or card to create a duplicate for unauthorized access.",
    },
    {
        "domain": 2,
        "study_topic": "Physical attacks",
        "term": "Environmental attack",
        "definition": "An attack that targets a facility's physical environment, such as HVAC, power, or fire suppression systems, to disrupt operations or damage equipment.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Distributed denial-of-service (DDoS)",
        "definition": "An attack in which multiple compromised systems flood a target with traffic simultaneously to exhaust its resources and deny service to legitimate users.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Amplified DDoS attack",
        "definition": "A DDoS technique that exploits protocols returning larger responses than the requests, multiplying the volume of traffic directed at the victim.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Reflected DDoS attack",
        "definition": "A DDoS technique in which an attacker sends requests with a spoofed source address so that responses are directed to the victim instead of the attacker.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "DNS attack",
        "definition": "An attack that targets the Domain Name System, such as DNS poisoning or hijacking, to redirect users to malicious sites or disrupt name resolution.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Wireless attack",
        "definition": "An attack targeting Wi-Fi networks, such as evil twin access points, deauthentication attacks, or jamming, to intercept traffic or deny service.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "On-path attack",
        "definition": "An attack, formerly called man-in-the-middle, in which an attacker secretly intercepts and possibly alters communication between two parties.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Credential replay attack",
        "definition": "An attack in which a threat actor captures valid authentication credentials or tokens and reuses them to impersonate the legitimate user.",
    },
    {
        "domain": 2,
        "study_topic": "Network attacks",
        "term": "Malicious code (network indicator)",
        "definition": "Unexpected or unauthorized code, such as scripts or executables, detected traversing or executing on the network that indicates a potential compromise.",
    },
    {
        "domain": 2,
        "study_topic": "Application attacks",
        "term": "Injection attack",
        "definition": "An attack in which malicious input is inserted into an application to manipulate its execution, such as SQL, command, or LDAP injection.",
    },
    {
        "domain": 2,
        "study_topic": "Application attacks",
        "term": "Replay attack",
        "definition": "An attack in which a threat actor intercepts valid data transmissions, such as authentication tokens, and retransmits them to gain unauthorized access.",
    },
    {
        "domain": 2,
        "study_topic": "Application attacks",
        "term": "Privilege escalation",
        "definition": "An attack in which a threat actor exploits a vulnerability or misconfiguration to gain higher-level access rights than originally granted.",
    },
    {
        "domain": 2,
        "study_topic": "Application attacks",
        "term": "Forgery",
        "definition": "An attack in which a threat actor tricks an application into accepting a fraudulent request or data as legitimate, such as cross-site request forgery.",
    },
    {
        "domain": 2,
        "study_topic": "Application attacks",
        "term": "Directory traversal",
        "definition": "An attack in which a threat actor manipulates file path input to access files and directories stored outside the web root folder.",
    },
    {
        "domain": 2,
        "study_topic": "Cryptographic attacks",
        "term": "Downgrade attack",
        "definition": "An attack that forces a system to abandon a strong encryption protocol in favor of a weaker, legacy one that is easier to break.",
    },
    {
        "domain": 2,
        "study_topic": "Cryptographic attacks",
        "term": "Collision attack",
        "definition": "A cryptographic attack in which two different inputs are found that produce the same hash output, undermining the hash function's integrity guarantee.",
    },
    {
        "domain": 2,
        "study_topic": "Cryptographic attacks",
        "term": "Birthday attack",
        "definition": "A cryptographic attack that exploits the probability theory behind the birthday paradox to find hash collisions faster than brute force would suggest.",
    },
    {
        "domain": 2,
        "study_topic": "Password attacks",
        "term": "Password spraying",
        "definition": "A password attack that tries one or a few commonly used passwords across many different user accounts to avoid triggering account lockout policies.",
    },
    {
        "domain": 2,
        "study_topic": "Password attacks",
        "term": "Brute force (password)",
        "definition": "A password attack that systematically attempts every possible combination of characters until the correct password is found.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Account lockout (indicator)",
        "definition": "An indicator of malicious activity in which a legitimate user is unexpectedly locked out, often the result of repeated failed login attempts by an attacker.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Concurrent session usage (indicator)",
        "definition": "An indicator of malicious activity showing the same user account logged in from multiple locations or devices simultaneously, suggesting credential theft.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Blocked content (indicator)",
        "definition": "An indicator of malicious activity in which security tools log repeated attempts to access or transmit content that violates policy, suggesting an attack in progress.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Impossible travel (indicator)",
        "definition": "An indicator of malicious activity in which a user account shows logins from geographically distant locations within a timeframe that would be physically impossible to travel.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Resource consumption (indicator)",
        "definition": "An indicator of malicious activity in which CPU, memory, disk, or bandwidth usage spikes abnormally, potentially signaling malware, cryptomining, or a DoS attack.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Resource inaccessibility (indicator)",
        "definition": "An indicator of malicious activity in which files, systems, or services suddenly become unavailable, such as due to ransomware encryption or a denial-of-service attack.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Out-of-cycle logging (indicator)",
        "definition": "An indicator of malicious activity in which log entries appear at unusual times or frequencies outside normal patterns, suggesting unauthorized activity.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Published/documented indicator",
        "definition": "An indicator of compromise that has been publicly disclosed or documented by threat intelligence sources, such as a known malicious IP or file hash.",
    },
    {
        "domain": 2,
        "study_topic": "Indicators of compromise",
        "term": "Missing logs (indicator)",
        "definition": "An indicator of malicious activity in which expected log data is absent or has gaps, often because an attacker deleted or tampered with logs to cover their tracks.",
    },
    # ------------------------------------------------------------------
    # 2.5 Mitigation techniques
    # ------------------------------------------------------------------
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Segmentation (mitigation)",
        "definition": "A mitigation technique that divides a network into isolated zones or VLANs to limit the spread of an attack and contain compromised systems.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Access control (mitigation)",
        "definition": "A mitigation technique that restricts who can access resources using mechanisms such as access control lists (ACLs) and file/folder permissions.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Access control list (ACL)",
        "definition": "A set of rules that specifies which users or systems are permitted or denied access to a particular resource or network segment.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Application allow list",
        "definition": "A mitigation technique that permits only pre-approved applications to execute on a system, blocking all others by default.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Isolation (mitigation)",
        "definition": "A mitigation technique that separates a compromised or high-risk system from the rest of the network to prevent an attack from spreading.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Patching",
        "definition": "A mitigation technique of applying vendor-released updates to software and systems to remediate known vulnerabilities.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Encryption (mitigation)",
        "definition": "A mitigation technique that converts data into an unreadable format using cryptographic algorithms so that only authorized parties with the key can access it.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Monitoring (mitigation)",
        "definition": "A mitigation technique involving the continuous observation of systems, networks, and logs to detect and respond to suspicious or malicious activity.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Least privilege (mitigation)",
        "definition": "A mitigation technique that grants users and systems only the minimum access rights necessary to perform their required functions.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Configuration enforcement",
        "definition": "A mitigation technique that ensures systems remain compliant with an approved secure baseline configuration, alerting or remediating any drift.",
    },
    {
        "domain": 2,
        "study_topic": "Mitigation techniques",
        "term": "Decommissioning",
        "definition": "A mitigation technique of properly retiring outdated or unneeded systems, including secure data removal, to eliminate their associated attack surface.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Hardening",
        "definition": "The process of reducing a system's attack surface by disabling unnecessary features, applying secure configurations, and removing default weaknesses.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Endpoint protection installation",
        "definition": "A hardening technique of deploying anti-malware and endpoint detection and response (EDR) software on devices to detect and block threats.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Host-based firewall",
        "definition": "A hardening technique using software running on an individual endpoint that filters inbound and outbound network traffic for that specific device.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Host-based intrusion prevention system (HIPS)",
        "definition": "A hardening technique using software installed on an endpoint that monitors and automatically blocks detected malicious activity on that host.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Disabling ports and protocols",
        "definition": "A hardening technique that turns off unused network ports and protocols on a system to reduce the number of exploitable entry points.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Default password changes",
        "definition": "A hardening technique of replacing factory-set default credentials on devices and software with strong, unique passwords immediately upon deployment.",
    },
    {
        "domain": 2,
        "study_topic": "Hardening techniques",
        "term": "Removal of unnecessary software",
        "definition": "A hardening technique of uninstalling applications, services, and features that are not required for a system's function, reducing its attack surface.",
    },
]
