"""Security+ SY0-701 Domain 3 (Security Architecture) flashcard deck.

Covers objectives 3.1-3.4: architecture models, secure infrastructure,
data protection, and resilience/recovery.
"""

from __future__ import annotations

CARDS: list[dict] = [
    # ------------------------------------------------------------------
    # 3.1 Architecture models
    # ------------------------------------------------------------------
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Cloud computing",
        "definition": "A model for delivering on-demand computing resources (servers, storage, applications) over the internet, typically billed on a pay-as-you-go basis.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Shared responsibility model",
        "definition": "A cloud security framework that defines which security tasks the cloud service provider handles and which tasks remain the customer's responsibility, varying by service model.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "IaaS (Infrastructure as a Service)",
        "definition": "A cloud service model providing virtualized computing resources (compute, storage, networking) where the customer manages the OS, applications, and data while the provider manages the underlying hardware.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "PaaS (Platform as a Service)",
        "definition": "A cloud service model that provides a managed platform (OS, runtime, middleware) for customers to develop and deploy applications without managing the underlying infrastructure.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "SaaS (Software as a Service)",
        "definition": "A cloud service model where the provider hosts and manages a complete application that customers access over the network, typically via a browser.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Public cloud",
        "definition": "A cloud deployment model where computing resources are owned and operated by a third-party provider and shared among multiple tenants over the public internet.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Private cloud",
        "definition": "A cloud deployment model where computing resources are dedicated to a single organization, hosted either on-premises or by a third party, for greater control and isolation.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Community cloud",
        "definition": "A cloud deployment model where infrastructure is shared among several organizations with common regulatory, security, or compliance requirements.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Hybrid cloud",
        "definition": "A cloud deployment model that combines private and public (or on-premises and cloud) environments, requiring careful integration of connectivity, data synchronization, and security controls across both.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Hybrid cloud considerations",
        "definition": "Design factors for hybrid environments such as consistent identity management, secure connectivity between environments, data residency, latency, and unified monitoring across on-premises and cloud resources.",
    },
    {
        "domain": 3,
        "study_topic": "Cloud architecture",
        "term": "Third-party vendors (cloud)",
        "definition": "External organizations that supply cloud infrastructure, platforms, or software, requiring due diligence, contractual security requirements, and ongoing risk management since the organization remains accountable for data protection.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Infrastructure as Code (IaC)",
        "definition": "The practice of managing and provisioning infrastructure through machine-readable definition files (templates/scripts) rather than manual configuration, enabling consistent, repeatable, and version-controlled deployments.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Serverless computing",
        "definition": "A cloud execution model in which the provider dynamically allocates compute resources to run code (functions) on demand, so the customer never manages the underlying servers.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Microservices architecture",
        "definition": "A software design approach that structures an application as a collection of small, independently deployable services that communicate over well-defined APIs, improving scalability and fault isolation.",
    },
    {
        "domain": 3,
        "study_topic": "Network infrastructure",
        "term": "Physical isolation / air-gapped network",
        "definition": "A security architecture in which a system or network has no physical or wireless connection to any other network, preventing remote network-based attacks.",
    },
    {
        "domain": 3,
        "study_topic": "Network infrastructure",
        "term": "Logical segmentation",
        "definition": "Dividing a network into isolated segments using technologies like VLANs or subnets, without requiring separate physical hardware, to contain traffic and limit lateral movement.",
    },
    {
        "domain": 3,
        "study_topic": "Network infrastructure",
        "term": "Software-defined networking (SDN)",
        "definition": "A network architecture that decouples the control plane from the data plane, allowing network behavior to be centrally programmed and managed via software rather than manual device configuration.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "On-premises architecture",
        "definition": "An infrastructure model where an organization owns, hosts, and fully manages its own hardware and software within its own facilities, giving maximum control but requiring greater capital investment and maintenance responsibility.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Centralized architecture",
        "definition": "A design where computing resources, data, and administrative control are consolidated in a single location or system, simplifying management but creating a single point of failure.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Decentralized architecture",
        "definition": "A design where computing resources and administrative control are distributed across multiple locations or systems, improving resilience but increasing management complexity.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Containerization",
        "definition": "A virtualization method that packages an application and its dependencies into a lightweight, portable container that shares the host OS kernel, enabling fast, consistent deployment across environments.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Virtualization",
        "definition": "The creation of virtual (rather than physical) versions of computing resources, such as servers or operating systems, using a hypervisor to run multiple isolated virtual machines on shared hardware.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Hypervisor",
        "definition": "Software that creates and manages virtual machines by allocating physical hardware resources among them; Type 1 hypervisors run directly on hardware, while Type 2 run atop a host OS.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "IoT (Internet of Things)",
        "definition": "A category of network-connected physical devices (sensors, appliances, wearables) that collect and exchange data, often with limited processing power, storage, and built-in security controls.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "ICS/SCADA",
        "definition": "Industrial Control Systems and Supervisory Control and Data Acquisition systems used to monitor and control physical industrial processes (e.g., manufacturing, utilities), often prioritizing availability over confidentiality and difficult to patch.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "RTOS (Real-Time Operating System)",
        "definition": "An operating system designed to process data and respond to inputs within a strict, predictable time constraint, commonly used in embedded and industrial control systems where timing is critical.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "Embedded systems",
        "definition": "Specialized computing devices built into a larger product to perform a dedicated function, often with limited resources, long lifecycles, and constrained ability to receive security patches.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture models",
        "term": "High availability (architecture)",
        "definition": "A system design principle that uses redundancy, failover, and elimination of single points of failure to ensure a system remains operational and accessible for as close to 100% of the time as possible.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Availability (architecture consideration)",
        "definition": "The design consideration of ensuring systems and data remain accessible to authorized users when needed, often achieved through redundancy and failover mechanisms.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Resilience (architecture consideration)",
        "definition": "The design consideration of a system's ability to withstand and quickly recover from disruptions, failures, or attacks while maintaining essential functions.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Cost (architecture consideration)",
        "definition": "The design consideration of balancing capital expenditure, operating expenditure, and total cost of ownership when selecting and building an architecture.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Responsiveness (architecture consideration)",
        "definition": "The design consideration of how quickly a system processes requests and returns results, impacting user experience and operational efficiency.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Scalability (architecture consideration)",
        "definition": "The design consideration of a system's ability to handle increased load by adding resources (scaling up/out) without a redesign or loss of performance.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Ease of deployment (architecture consideration)",
        "definition": "The design consideration of how quickly and simply an architecture or system can be provisioned and put into production.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Risk transference (architecture consideration)",
        "definition": "The design consideration of shifting the impact or management of risk to a third party, such as through cloud outsourcing or insurance, rather than eliminating the risk itself.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Ease of recovery (architecture consideration)",
        "definition": "The design consideration of how simply and quickly a system or its data can be restored to normal operation after a failure or incident.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Patch availability (architecture consideration)",
        "definition": "The design consideration of whether a vendor regularly provides security updates for a system or device, affecting its long-term risk posture.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Inability to patch (architecture consideration)",
        "definition": "The design consideration that some systems, such as legacy or embedded devices, cannot be patched, requiring compensating controls like segmentation to manage risk.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Power (architecture consideration)",
        "definition": "The design consideration of ensuring adequate and reliable electrical power supply, including backup power, for systems and facilities.",
    },
    {
        "domain": 3,
        "study_topic": "Architecture considerations",
        "term": "Compute (architecture consideration)",
        "definition": "The design consideration of ensuring sufficient processing capacity (CPU, memory) is available to meet workload and performance demands.",
    },
    # ------------------------------------------------------------------
    # 3.2 Secure infrastructure
    # ------------------------------------------------------------------
    {
        "domain": 3,
        "study_topic": "Infrastructure considerations",
        "term": "Device placement",
        "definition": "The strategic physical or logical positioning of security and network devices (e.g., firewalls, sensors) within an infrastructure to maximize visibility and control over traffic flow.",
    },
    {
        "domain": 3,
        "study_topic": "Infrastructure considerations",
        "term": "Security zones",
        "definition": "Logical or physical groupings of network segments with similar trust levels (e.g., trusted, untrusted, DMZ) that have defined boundaries and policies controlling traffic between them.",
    },
    {
        "domain": 3,
        "study_topic": "Infrastructure considerations",
        "term": "Attack surface",
        "definition": "The sum of all points where an unauthorized user could attempt to enter or extract data from a system, which security architecture aims to minimize.",
    },
    {
        "domain": 3,
        "study_topic": "Infrastructure considerations",
        "term": "Connectivity (infrastructure consideration)",
        "definition": "The design consideration of how devices and networks are linked together, including bandwidth, redundancy, and the types of connections (wired, wireless, VPN) used.",
    },
    {
        "domain": 3,
        "study_topic": "Failure modes",
        "term": "Fail-open",
        "definition": "A failure mode in which a security device, upon failure, allows all traffic to pass through unimpeded, prioritizing availability over security.",
    },
    {
        "domain": 3,
        "study_topic": "Failure modes",
        "term": "Fail-closed",
        "definition": "A failure mode in which a security device, upon failure, blocks all traffic, prioritizing security over availability.",
    },
    {
        "domain": 3,
        "study_topic": "Device attributes",
        "term": "Active device",
        "definition": "A network security device that sits directly in the traffic path and can actively block, modify, or drop traffic in real time, such as an inline IPS.",
    },
    {
        "domain": 3,
        "study_topic": "Device attributes",
        "term": "Passive device",
        "definition": "A network security device that monitors a copy of traffic without sitting in the direct communication path, able to detect and alert but not block traffic in real time.",
    },
    {
        "domain": 3,
        "study_topic": "Device attributes",
        "term": "Inline device",
        "definition": "A device deployed directly in the flow of network traffic so that all traffic must physically pass through it, allowing it to actively block malicious traffic.",
    },
    {
        "domain": 3,
        "study_topic": "Device attributes",
        "term": "Tap/monitor mode",
        "definition": "A deployment configuration in which a device receives a mirrored copy of network traffic (via a network tap or SPAN port) for passive analysis without being in the direct traffic path.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Jump server",
        "definition": "A hardened intermediary system that administrators use to access and manage devices in a separate, more secure network zone, centralizing and logging privileged access.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Proxy server",
        "definition": "A server that acts as an intermediary between clients and other servers, forwarding requests and responses while providing content filtering, caching, anonymization, or logging.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Forward proxy",
        "definition": "A proxy server that sits between internal clients and the internet, managing and filtering outbound requests on behalf of the clients.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Reverse proxy",
        "definition": "A proxy server that sits in front of one or more backend servers, handling inbound client requests and providing load balancing, caching, and an additional layer of security for the servers.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "IDS (Intrusion Detection System)",
        "definition": "A security tool that monitors network or system traffic for suspicious activity and generates alerts, operating passively without blocking traffic.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "IPS (Intrusion Prevention System)",
        "definition": "A security tool deployed inline that monitors traffic for malicious activity and can actively block or drop that traffic in real time.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Load balancer",
        "definition": "A device or service that distributes incoming network or application traffic across multiple servers to optimize resource use, maximize throughput, and improve availability.",
    },
    {
        "domain": 3,
        "study_topic": "Network appliances",
        "term": "Sensors (network appliance)",
        "definition": "Devices or software agents placed throughout a network to collect traffic, log, or telemetry data for monitoring, detection, and analysis purposes.",
    },
    {
        "domain": 3,
        "study_topic": "Port security",
        "term": "802.1X",
        "definition": "An IEEE standard for port-based network access control that requires devices to authenticate before being granted access to a wired or wireless network.",
    },
    {
        "domain": 3,
        "study_topic": "Port security",
        "term": "EAP (Extensible Authentication Protocol)",
        "definition": "A flexible authentication framework used in wireless and point-to-point connections that supports multiple authentication methods, commonly used alongside 802.1X.",
    },
    {
        "domain": 3,
        "study_topic": "Port security",
        "term": "Port security (switch feature)",
        "definition": "A switch-level control that restricts which MAC addresses can connect to a specific physical port, preventing unauthorized devices from accessing the network.",
    },
    {
        "domain": 3,
        "study_topic": "Firewall types",
        "term": "WAF (Web Application Firewall)",
        "definition": "A firewall specifically designed to filter, monitor, and block HTTP/HTTPS traffic to and from a web application, protecting against attacks like SQL injection and cross-site scripting.",
    },
    {
        "domain": 3,
        "study_topic": "Firewall types",
        "term": "UTM (Unified Threat Management)",
        "definition": "A security appliance that consolidates multiple security functions, such as firewall, antivirus, IPS, and content filtering, into a single device.",
    },
    {
        "domain": 3,
        "study_topic": "Firewall types",
        "term": "NGFW (Next-Generation Firewall)",
        "definition": "A firewall that combines traditional packet filtering with additional capabilities such as deep packet inspection, application awareness, and integrated intrusion prevention.",
    },
    {
        "domain": 3,
        "study_topic": "Firewall types",
        "term": "Layer 4 firewall",
        "definition": "A firewall that filters traffic based on transport-layer information such as source/destination IP addresses and port numbers, without inspecting application content.",
    },
    {
        "domain": 3,
        "study_topic": "Firewall types",
        "term": "Layer 7 firewall",
        "definition": "A firewall that filters traffic based on application-layer data, allowing it to inspect and control traffic by application, content, or user identity.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "VPN (Virtual Private Network)",
        "definition": "A technology that creates an encrypted, secure tunnel over a public network, allowing remote users or sites to securely access private network resources.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "Remote access",
        "definition": "The ability to connect to and use a network or system from a location outside the physical premises, typically secured through VPNs, MFA, and strict access controls.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "Tunneling",
        "definition": "The process of encapsulating one network protocol within another to securely transmit data across an untrusted network, forming the basis of VPN technology.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "TLS (Transport Layer Security)",
        "definition": "A cryptographic protocol that provides secure, encrypted communication over a network, commonly used to secure web traffic and as a VPN tunneling method.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "IPSec (Internet Protocol Security)",
        "definition": "A suite of protocols that authenticates and encrypts IP packets to secure communication between hosts or networks, commonly used to establish VPN tunnels.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "SD-WAN (Software-Defined Wide Area Network)",
        "definition": "A virtualized approach to managing a wide area network that uses software-based control to intelligently route traffic across multiple connection types, improving performance and simplifying management.",
    },
    {
        "domain": 3,
        "study_topic": "Secure communication/access",
        "term": "SASE (Secure Access Service Edge)",
        "definition": "A cloud-delivered architecture that combines network security functions (such as SWG, CASB, ZTNA, and firewall) with SD-WAN capabilities into a single unified service.",
    },
    # ------------------------------------------------------------------
    # 3.3 Data protection
    # ------------------------------------------------------------------
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Regulated data",
        "definition": "Data subject to specific legal or industry compliance requirements (e.g., HIPAA, PCI DSS) that dictate how it must be handled, stored, and protected.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Trade secret",
        "definition": "Confidential business information, such as formulas or processes, that provides a competitive advantage and is protected as long as it remains secret.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Intellectual property (IP)",
        "definition": "Creations of the mind, such as inventions, designs, and trademarks, that are legally protected and owned by an individual or organization.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Legal information (data type)",
        "definition": "Data related to legal proceedings, contracts, or regulatory obligations that may require special handling due to privilege or compliance requirements.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Financial information (data type)",
        "definition": "Data related to monetary transactions, accounts, or financial status, such as credit card numbers or bank details, that typically requires strict protection.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Human-readable data",
        "definition": "Data formatted in a way that can be directly understood by people without special processing, such as plaintext documents.",
    },
    {
        "domain": 3,
        "study_topic": "Data types",
        "term": "Non-human-readable data",
        "definition": "Data formatted for machine processing, such as binary or encrypted data, that cannot be directly understood by people without decoding or interpretation.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Sensitive data classification",
        "definition": "A data classification level indicating information that requires protection from unauthorized disclosure due to potential harm if exposed.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Confidential data classification",
        "definition": "A data classification level for information intended only for specific individuals or groups within an organization, with unauthorized disclosure causing serious harm.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Public data classification",
        "definition": "A data classification level for information that can be freely disclosed to anyone without risk or harm to the organization.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Restricted data classification",
        "definition": "A data classification level for information with the highest sensitivity, limited to a very small number of authorized individuals, often due to legal or regulatory requirements.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Private data classification",
        "definition": "A data classification level for information intended for use only within an organization, not meant for public release but generally less sensitive than restricted data.",
    },
    {
        "domain": 3,
        "study_topic": "Data classifications",
        "term": "Critical data classification",
        "definition": "A data classification level for information essential to business operations, where loss or compromise would severely disrupt the organization.",
    },
    {
        "domain": 3,
        "study_topic": "Data states",
        "term": "Data at rest",
        "definition": "Data stored on physical or virtual media, such as hard drives or databases, that is not actively moving through a network, typically protected with encryption and access controls.",
    },
    {
        "domain": 3,
        "study_topic": "Data states",
        "term": "Data in transit",
        "definition": "Data actively moving across a network from one location to another, typically protected using encryption protocols like TLS or IPSec.",
    },
    {
        "domain": 3,
        "study_topic": "Data states",
        "term": "Data in use",
        "definition": "Data actively being processed, accessed, or modified in memory by an application, requiring protections such as encryption or secure enclaves since it may be temporarily unencrypted.",
    },
    {
        "domain": 3,
        "study_topic": "General data considerations",
        "term": "Data sovereignty",
        "definition": "The principle that data is subject to the laws and regulations of the country in which it is physically located or collected.",
    },
    {
        "domain": 3,
        "study_topic": "General data considerations",
        "term": "Geolocation (data consideration)",
        "definition": "The use of location data to determine or restrict where data can be accessed, stored, or processed, often for compliance or security purposes.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Geographic restrictions (data)",
        "definition": "Controls that limit data access or storage to specific geographic locations to comply with data sovereignty laws or reduce risk.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Encryption (data protection method)",
        "definition": "The process of converting data into an unreadable format using an algorithm and key, so that only authorized parties with the correct key can decrypt and access it.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Hashing (data protection method)",
        "definition": "A one-way mathematical function that converts data into a fixed-length string (hash), used to verify data integrity since the same input always produces the same output.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Data masking",
        "definition": "A technique that hides or obscures original data with modified or fictitious values while preserving its format, often used to protect sensitive data in non-production environments.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Tokenization",
        "definition": "A data protection method that replaces sensitive data with a non-sensitive placeholder (token) that has no exploitable value, while the original data is securely stored elsewhere in a token vault.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Obfuscation (data protection method)",
        "definition": "The practice of deliberately making data or code difficult to understand or interpret in order to protect it from unauthorized analysis or reverse engineering.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Segmentation (data protection method)",
        "definition": "Dividing data storage or network access into isolated segments to limit exposure and contain the impact of a breach.",
    },
    {
        "domain": 3,
        "study_topic": "Methods to secure data",
        "term": "Permission restrictions (data protection method)",
        "definition": "Access controls that limit who can view, modify, or delete specific data, typically enforced through file system permissions or access control lists based on the principle of least privilege.",
    },
    # ------------------------------------------------------------------
    # 3.4 Resilience and recovery
    # ------------------------------------------------------------------
    {
        "domain": 3,
        "study_topic": "High availability",
        "term": "Load balancing (resilience)",
        "definition": "A resilience technique that distributes workload across multiple servers to prevent any single server from becoming a bottleneck or point of failure.",
    },
    {
        "domain": 3,
        "study_topic": "High availability",
        "term": "Clustering",
        "definition": "A resilience technique in which multiple servers are grouped together to work as a single system, providing failover and load distribution so that if one node fails, others continue to provide service.",
    },
    {
        "domain": 3,
        "study_topic": "Site considerations",
        "term": "Hot site",
        "definition": "A fully equipped, redundant disaster recovery site with up-to-date data and systems that can take over operations almost immediately after a disruption.",
    },
    {
        "domain": 3,
        "study_topic": "Site considerations",
        "term": "Cold site",
        "definition": "A disaster recovery site with basic infrastructure (space, power, cooling) but no pre-installed servers or data, requiring significant time to become operational.",
    },
    {
        "domain": 3,
        "study_topic": "Site considerations",
        "term": "Warm site",
        "definition": "A disaster recovery site that is partially equipped with hardware and connectivity but requires some data restoration and configuration before becoming fully operational.",
    },
    {
        "domain": 3,
        "study_topic": "Site considerations",
        "term": "Geographic dispersion",
        "definition": "The practice of distributing systems, data centers, or backups across multiple physical locations to reduce the risk that a single regional event disrupts all operations.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "Platform diversity",
        "definition": "The strategy of using different technology platforms, vendors, or architectures to reduce the risk that a single vulnerability or failure affects the entire environment.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "Multi-cloud systems",
        "definition": "An architecture that uses cloud services from multiple providers to reduce vendor lock-in, increase resilience, and avoid a single point of failure.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "Continuity of operations (COOP)",
        "definition": "A plan and set of procedures that ensure an organization's essential functions can continue during and after a significant disruption or disaster.",
    },
    {
        "domain": 3,
        "study_topic": "Capacity planning",
        "term": "Capacity planning",
        "definition": "The process of determining the resources (people, technology, infrastructure) an organization needs to meet current and future demand, including during disaster recovery.",
    },
    {
        "domain": 3,
        "study_topic": "Capacity planning",
        "term": "People (capacity planning)",
        "definition": "The capacity planning consideration of ensuring sufficient trained personnel are available to maintain operations and execute recovery procedures during a disruption.",
    },
    {
        "domain": 3,
        "study_topic": "Capacity planning",
        "term": "Technology (capacity planning)",
        "definition": "The capacity planning consideration of ensuring adequate hardware, software, and systems are available to support operations at required performance levels.",
    },
    {
        "domain": 3,
        "study_topic": "Capacity planning",
        "term": "Infrastructure (capacity planning)",
        "definition": "The capacity planning consideration of ensuring facilities, power, network, and other foundational resources can support current and future operational needs.",
    },
    {
        "domain": 3,
        "study_topic": "Testing",
        "term": "Tabletop exercise",
        "definition": "A discussion-based testing method in which stakeholders walk through a simulated incident or disaster scenario to evaluate plans and procedures without actually disrupting operations.",
    },
    {
        "domain": 3,
        "study_topic": "Testing",
        "term": "Failover testing",
        "definition": "A testing method that validates the process of automatically or manually switching operations from a primary system to a redundant or backup system.",
    },
    {
        "domain": 3,
        "study_topic": "Testing",
        "term": "Simulation testing",
        "definition": "A testing method that mimics a real disaster or incident scenario in a controlled environment to evaluate response procedures and team readiness.",
    },
    {
        "domain": 3,
        "study_topic": "Testing",
        "term": "Parallel processing testing",
        "definition": "A recovery testing method in which backup systems are run alongside production systems to verify they function correctly without taking the primary system offline.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Onsite backup",
        "definition": "A backup copy of data stored at the same physical location as the original data, providing fast recovery but vulnerable to site-wide disasters.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Offsite backup",
        "definition": "A backup copy of data stored at a different physical location from the original data, protecting against site-wide disasters but potentially slower to restore.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Backup frequency",
        "definition": "The interval at which backups are performed, balancing recovery point objectives against storage costs and system performance impact.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Backup encryption",
        "definition": "The practice of encrypting backup data to protect its confidentiality both at rest and in transit, preventing unauthorized access if backup media is lost or stolen.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Snapshot",
        "definition": "A point-in-time copy of a system's state or data, commonly used with virtual machines, that allows for quick rollback but is typically not a substitute for full backups.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Recovery (backup)",
        "definition": "The process of restoring data or systems from a backup to return them to an operational state after data loss, corruption, or a disaster.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Replication",
        "definition": "The continuous or scheduled copying of data between systems or locations to maintain synchronized, up-to-date redundant copies for availability and disaster recovery.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Journaling (backup)",
        "definition": "A method of recording changes to data in a sequential log before they are committed, allowing systems to recover to a specific point in time and maintain data integrity after a failure.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Full backup",
        "definition": "A backup type that copies all selected data in its entirety, providing the simplest and fastest restoration but requiring the most storage space and time to perform.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Incremental backup",
        "definition": "A backup type that copies only the data that has changed since the last backup of any type, minimizing backup time and storage but requiring all increments for a full restore.",
    },
    {
        "domain": 3,
        "study_topic": "Backups",
        "term": "Differential backup",
        "definition": "A backup type that copies all data changed since the last full backup, requiring more storage than incremental backups but a simpler, faster restoration process.",
    },
    {
        "domain": 3,
        "study_topic": "Power",
        "term": "Generator",
        "definition": "A backup power device that produces electricity from fuel to sustain operations during an extended power outage, typically used alongside a UPS for continuous coverage.",
    },
    {
        "domain": 3,
        "study_topic": "Power",
        "term": "UPS (Uninterruptible Power Supply)",
        "definition": "A device that provides short-term battery backup power to critical systems during a power outage, allowing time for a graceful shutdown or for a generator to start.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "RTO (Recovery Time Objective)",
        "definition": "The maximum acceptable amount of time a system or process can be down after a disruption before it must be restored to avoid unacceptable business impact.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "RPO (Recovery Point Objective)",
        "definition": "The maximum acceptable amount of data loss, measured in time, that an organization can tolerate between the last backup and a disruption.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "Redundancy",
        "definition": "The duplication of critical components or systems to increase reliability and eliminate single points of failure.",
    },
    {
        "domain": 3,
        "study_topic": "Resilience and recovery",
        "term": "Single point of failure (SPOF)",
        "definition": "A component within a system that, if it fails, would cause the entire system or process to stop functioning, making its elimination a key goal of resilient design.",
    },
]
