"""CompTIA Security+ SY0-701 — Domain 4: Security Operations.

Comprehensive flashcard deck covering objectives 4.1 through 4.9.
"""

from __future__ import annotations

CARDS: list[dict] = [
    # ------------------------------------------------------------------
    # 4.1 Secure baselines and hardening
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.1 Secure Baselines",
        "term": "Secure baseline",
        "definition": "A documented, minimum-security configuration standard that a system must meet before it is placed into production.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Secure Baselines",
        "term": "Establish (baseline)",
        "definition": "The phase of the baseline lifecycle in which an organization defines the approved secure configuration settings for a given system type.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Secure Baselines",
        "term": "Deploy (baseline)",
        "definition": "The phase of the baseline lifecycle in which the approved secure configuration is applied consistently to all applicable systems, often via imaging or configuration management tools.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Secure Baselines",
        "term": "Maintain (baseline)",
        "definition": "The ongoing phase of the baseline lifecycle in which systems are periodically reassessed and remediated to ensure they still conform to the approved secure configuration as threats and requirements evolve.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Secure Baselines",
        "term": "Hardening",
        "definition": "The process of reducing a system's attack surface by disabling unnecessary services, closing unused ports, removing default accounts, and applying secure configuration settings.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Mobile device hardening",
        "definition": "Securing smartphones and tablets through full-disk encryption, screen locks, remote wipe capability, and MDM-enforced policies before allowing enterprise data access.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Workstation hardening",
        "definition": "Securing end-user computers by removing unneeded software, enforcing least privilege, enabling host-based firewalls and antivirus, and applying OS security patches.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Switch hardening",
        "definition": "Securing network switches by disabling unused ports, enabling port security and DHCP snooping, changing default credentials, and restricting management access to trusted networks.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Router hardening",
        "definition": "Securing routers by disabling unnecessary services (e.g., HTTP management, unused routing protocols), changing default credentials, and restricting administrative access to secure management interfaces.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Cloud infrastructure hardening",
        "definition": "Securing cloud resources by applying least-privilege IAM policies, disabling public access to storage by default, encrypting data at rest and in transit, and enabling cloud-native security monitoring.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Server hardening",
        "definition": "Securing server operating systems and applications by removing unneeded roles/services, applying patches promptly, restricting administrative access, and enabling logging and auditing.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Industrial Control System (ICS)",
        "definition": "A system of hardware and software used to monitor and control physical industrial processes, requiring specialized hardening since patching and downtime windows are often severely constrained.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Supervisory Control and Data Acquisition (SCADA)",
        "definition": "A type of ICS used to monitor and control geographically dispersed infrastructure such as power grids and water systems, typically hardened using network segmentation and air-gapping rather than frequent patching.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Embedded system",
        "definition": "A purpose-built computing device with dedicated firmware (e.g., printers, medical devices, POS terminals) that often cannot run traditional endpoint security agents and must be hardened through network isolation.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Real-Time Operating System (RTOS)",
        "definition": "An operating system designed to process data and guarantee response times within strict deadlines, commonly used in embedded and industrial devices where security features may be limited.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Internet of Things (IoT) device",
        "definition": "A network-connected physical device (e.g., cameras, sensors, smart appliances) that frequently ships with weak default credentials and limited patching capability, requiring network segmentation and credential changes to harden.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Air-gapped network",
        "definition": "A network that is physically isolated from other networks, including the internet, commonly used to protect ICS/SCADA and other highly sensitive systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Default credential removal",
        "definition": "A hardening step that replaces manufacturer-set usernames and passwords with unique, strong credentials to prevent trivial unauthorized access.",
    },
    {
        "domain": 4,
        "study_topic": "4.1 Hardening Targets",
        "term": "Attack surface reduction",
        "definition": "The practice of disabling unused ports, protocols, services, and features on a system to minimize the number of ways it can be attacked.",
    },

    # ------------------------------------------------------------------
    # 4.2 Wireless, mobile, and application security
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Mobile Device Management (MDM)",
        "definition": "Software that enables centralized policy enforcement, application control, remote wipe, and configuration management for an organization's mobile devices.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Bring Your Own Device (BYOD)",
        "definition": "A deployment model in which employees use their personally owned devices to access corporate resources, raising challenges around data separation and privacy.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Corporate-Owned, Personally Enabled (COPE)",
        "definition": "A deployment model in which the organization purchases and owns the device but allows the employee to also use it for personal purposes.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Choose Your Own Device (CYOD)",
        "definition": "A deployment model in which employees select a device from a company-approved list, and the organization typically retains ownership and management control.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Cellular connection method",
        "definition": "A mobile connectivity option that uses carrier networks (e.g., 4G/5G) and is generally harder to intercept than Wi-Fi but may bypass corporate network security controls.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Wi-Fi connection method",
        "definition": "A mobile connectivity option using wireless local area networks that must be secured with strong encryption (e.g., WPA3) and authentication to prevent eavesdropping.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Mobile Solutions",
        "term": "Bluetooth connection method",
        "definition": "A short-range wireless connectivity option that presents risks such as bluejacking and bluesnarfing if left discoverable or unpaired devices are trusted.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "WPA3",
        "definition": "The current Wi-Fi Protected Access standard that uses Simultaneous Authentication of Equals (SAE) to replace the pre-shared key exchange and provides stronger encryption than WPA2.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "AAA framework",
        "definition": "A security framework of Authentication, Authorization, and Accounting used to control and record access to network and wireless resources.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "RADIUS",
        "definition": "A client-server AAA protocol commonly used to centralize authentication for wireless (802.1X), VPN, and dial-in network access.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "Cryptographic protocol (wireless)",
        "definition": "The encryption scheme (e.g., AES-CCMP in WPA2 or AES-GCMP in WPA3) that protects the confidentiality and integrity of wireless network traffic.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "Extensible Authentication Protocol (EAP)",
        "definition": "A flexible authentication framework used within 802.1X wireless and wired network access that supports multiple authentication methods.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "EAP-FAST",
        "definition": "An EAP method developed by Cisco that uses a Protected Access Credential to establish a secure tunnel without requiring server-side digital certificates.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "EAP-TLS",
        "definition": "An EAP method that requires digital certificates on both the client and server, providing mutual authentication and among the strongest EAP options.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "EAP-TTLS",
        "definition": "An EAP method that establishes a TLS tunnel using only a server-side certificate, inside which the client can authenticate with a weaker method such as a password.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Wireless Security Settings",
        "term": "Protected EAP (PEAP)",
        "definition": "An EAP method that encapsulates EAP within a TLS tunnel using a server-side certificate, commonly paired with MS-CHAPv2 for client authentication.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Input validation",
        "definition": "A secure coding practice that checks and sanitizes user-supplied data before processing it, preventing attacks such as SQL injection and cross-site scripting.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Secure cookie",
        "definition": "A cookie flagged with attributes like Secure, HttpOnly, and SameSite to ensure it is only transmitted over HTTPS and is protected against theft via client-side scripts and cross-site requests.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Static code analysis (SAST)",
        "definition": "A testing technique that examines an application's source code for vulnerabilities without executing the program.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Dynamic code analysis (DAST)",
        "definition": "A testing technique that examines a running application for vulnerabilities by interacting with it, without access to the underlying source code.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Code signing",
        "definition": "The practice of applying a digital signature to software to verify the publisher's identity and confirm the code has not been tampered with since it was signed.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Sandboxing (application)",
        "definition": "Running an application or code sample in an isolated environment so its behavior can be observed and contained without risking the host system.",
    },
    {
        "domain": 4,
        "study_topic": "4.2 Application Security",
        "term": "Application monitoring",
        "definition": "The continuous observation of an application's behavior, performance, and logs to detect anomalies, errors, or signs of compromise.",
    },

    # ------------------------------------------------------------------
    # 4.3 Vulnerability management
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Vulnerability scan",
        "definition": "An automated process that probes systems and applications for known weaknesses such as missing patches or misconfigurations.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Package monitoring",
        "definition": "The practice of tracking third-party software libraries and dependencies for newly disclosed vulnerabilities so they can be updated promptly.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Threat feed",
        "definition": "A continuously updated stream of information about current threats, indicators of compromise, and attacker tactics used to inform defensive decisions.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Open Source Intelligence (OSINT)",
        "definition": "Threat and target information gathered from publicly available sources such as websites, social media, and public records.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Proprietary threat intelligence",
        "definition": "Threat data collected and sold by commercial vendors, often providing more curated or exclusive insight than open-source feeds.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Information-sharing organization",
        "definition": "A group, such as an Information Sharing and Analysis Center (ISAC), through which organizations in the same sector exchange threat intelligence.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Dark web monitoring",
        "definition": "The practice of scanning hidden, non-indexed parts of the internet for evidence of leaked credentials, stolen data, or planned attacks against an organization.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Penetration testing",
        "definition": "An authorized, simulated attack against a system or network conducted to identify exploitable vulnerabilities before real attackers do.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Responsible disclosure program",
        "definition": "A formal process by which security researchers report discovered vulnerabilities to a vendor privately, allowing time for a fix before public release.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Bug bounty program",
        "definition": "A program that pays external researchers a reward for responsibly discovering and reporting vulnerabilities in an organization's products or systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "System audit",
        "definition": "A structured review of a system's configuration, access controls, and logs to verify compliance with security policy and identify weaknesses.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Identification",
        "term": "Process audit",
        "definition": "A structured review of an organization's procedures and workflows to confirm they are followed correctly and achieve their intended security outcomes.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "False positive (vulnerability)",
        "definition": "A scan or alert result that incorrectly identifies a vulnerability or threat that does not actually exist.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "False negative (vulnerability)",
        "definition": "A scan or alert result that fails to identify a real vulnerability or threat that is actually present.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Vulnerability prioritization",
        "definition": "The process of ranking identified vulnerabilities for remediation based on factors such as severity, exploitability, and asset criticality.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Common Vulnerability Scoring System (CVSS)",
        "definition": "A standardized framework that assigns a numeric severity score (0-10) to a vulnerability based on factors like attack vector, complexity, and impact.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Common Vulnerabilities and Exposures (CVE)",
        "definition": "A publicly maintained dictionary of standardized identifiers used to uniquely reference known software and hardware vulnerabilities.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Vulnerability classification",
        "definition": "The categorization of a vulnerability by type, such as misconfiguration, missing patch, weak encryption, or zero-day, to guide appropriate remediation.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Exposure factor",
        "definition": "The percentage of an asset's value that would be lost if a specific vulnerability were successfully exploited.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Environmental variables (CVSS)",
        "definition": "CVSS scoring metrics that adjust a vulnerability's base severity score to reflect an organization's specific environment, such as compensating controls already in place.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Industry impact",
        "definition": "The potential consequence a vulnerability or breach could have across an entire industry sector, influencing how urgently it must be addressed.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Organizational impact",
        "definition": "The potential consequence a vulnerability or breach could have specifically on an organization, including financial, operational, and reputational effects.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Analysis",
        "term": "Risk tolerance",
        "definition": "The level of risk an organization is willing to accept before taking action, which directly influences vulnerability remediation timelines and priorities.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Patching (remediation)",
        "definition": "Applying vendor-released updates to software or firmware to close known vulnerabilities.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Cyber insurance",
        "definition": "A risk-transfer response to vulnerabilities in which an organization purchases a policy to offset the financial impact of a security incident.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Segmentation (remediation)",
        "definition": "Isolating a vulnerable system on its own network segment to limit the potential impact if it is exploited, used when patching is not immediately possible.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Compensating control",
        "definition": "An alternative security control implemented to satisfy a requirement or mitigate a risk when the primary recommended control cannot be applied.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Exception (vulnerability management)",
        "definition": "A formally approved, temporary deviation from a security requirement or remediation deadline, typically with an expiration date and required justification.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Response and Remediation",
        "term": "Exemption (vulnerability management)",
        "definition": "A formally approved, permanent exclusion of a system or requirement from a security policy because it does not apply or the risk has been otherwise accepted.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Validation and Reporting",
        "term": "Rescanning",
        "definition": "Running a follow-up vulnerability scan after remediation to confirm that the identified vulnerability has actually been fixed.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Validation and Reporting",
        "term": "Audit (vulnerability validation)",
        "definition": "An independent review used to confirm that remediation actions were properly implemented and that controls remain effective.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Validation and Reporting",
        "term": "Verification",
        "definition": "The step in the vulnerability management lifecycle that confirms remediation was completed correctly and did not introduce new issues.",
    },
    {
        "domain": 4,
        "study_topic": "4.3 Vulnerability Validation and Reporting",
        "term": "Vulnerability reporting",
        "definition": "The documentation and communication of scan results, risk levels, and remediation status to stakeholders and management.",
    },

    # ------------------------------------------------------------------
    # 4.4 Alerting and monitoring
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Monitoring computing resources",
        "definition": "The continuous observation of systems, applications, and infrastructure to detect performance issues, misconfigurations, and security events.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Log aggregation",
        "definition": "The process of collecting log data from multiple systems into a centralized location for correlation, analysis, and long-term storage.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Alerting",
        "definition": "The automated notification of security or operations personnel when monitoring tools detect events that meet defined criteria.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Scanning (monitoring activity)",
        "definition": "The periodic, automated examination of systems and networks to identify vulnerabilities, misconfigurations, or unauthorized changes.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Reporting (monitoring activity)",
        "definition": "The generation of summaries and dashboards from monitoring data to communicate security posture and trends to stakeholders.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Archiving (monitoring activity)",
        "definition": "The long-term retention of log and monitoring data to satisfy compliance requirements and support later forensic investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Quarantine (alert response)",
        "definition": "An automated or manual remediation action that isolates a suspicious file, host, or account from the rest of the network to prevent further harm.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Alert tuning",
        "definition": "The ongoing process of adjusting monitoring thresholds and rules to reduce false positives and false negatives, improving alert accuracy over time.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Security Content Automation Protocol (SCAP)",
        "definition": "A suite of open standards used to automate vulnerability management, measurement, and policy compliance evaluation across systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Security benchmark",
        "definition": "A vendor-neutral, consensus-based configuration standard, such as a CIS Benchmark, used to measure whether a system meets recognized secure configuration guidelines.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Agent-based monitoring",
        "definition": "A monitoring approach that installs software directly on the target host to collect detailed telemetry, offering deeper visibility at the cost of deployment overhead.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Agentless monitoring",
        "definition": "A monitoring approach that collects data remotely without installing software on the target host, reducing deployment overhead but sometimes providing less depth.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Security Information and Event Management (SIEM)",
        "definition": "A platform that aggregates, correlates, and analyzes log and event data from across the enterprise to detect and alert on potential security incidents.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Antivirus (monitoring tool)",
        "definition": "Software that detects, blocks, and removes known malware using signature-based and heuristic detection methods.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Data Loss Prevention (DLP) monitoring",
        "definition": "A monitoring capability that inspects data in use, in motion, and at rest to detect and prevent unauthorized transmission of sensitive information.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "SNMP trap",
        "definition": "An unsolicited notification sent from a managed network device to a monitoring station to report a significant event without waiting to be polled.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "NetFlow",
        "definition": "A network protocol that collects metadata about IP traffic flows, such as source/destination and volume, enabling traffic analysis without capturing full packet contents.",
    },
    {
        "domain": 4,
        "study_topic": "4.4 Monitoring Activities and Tools",
        "term": "Vulnerability scanner (monitoring tool)",
        "definition": "A tool that automatically probes systems on a recurring basis to identify missing patches, misconfigurations, and known vulnerabilities.",
    },

    # ------------------------------------------------------------------
    # 4.5 Enterprise security capabilities
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Firewall rule",
        "definition": "A configured statement that permits or denies network traffic based on criteria such as source/destination IP, port, and protocol.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Access control list (network)",
        "definition": "An ordered set of rules applied to a router or firewall interface that permits or denies traffic based on defined criteria.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Screened subnet",
        "definition": "A network segment, also called a DMZ, that sits between an internal network and an untrusted network to host public-facing services while isolating the internal network.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Intrusion Detection System (IDS)",
        "definition": "A monitoring system that analyzes network or host activity to detect suspicious behavior and generates alerts without taking direct action to block it.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Intrusion Prevention System (IPS)",
        "definition": "A monitoring system placed inline with network traffic that can automatically detect and block malicious activity in real time.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Trend analysis (IDS/IPS)",
        "definition": "A detection approach that identifies threats by analyzing patterns and changes in behavior or traffic over time rather than matching a single known indicator.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Signature-based detection",
        "definition": "A detection method that identifies known threats by matching traffic or file characteristics against a database of predefined attack signatures.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Web filter",
        "definition": "A security control that inspects and restricts outbound web traffic based on policy, such as blocking access to malicious or inappropriate sites.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Agent-based web filtering",
        "definition": "A web filtering approach in which software installed on the endpoint enforces browsing policy regardless of the network the device is connected to.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Centralized proxy (web filtering)",
        "definition": "A web filtering approach in which all web traffic is routed through a central proxy server that enforces policy before forwarding requests to the internet.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "URL scanning",
        "definition": "A web filtering technique that inspects requested web addresses in real time against threat intelligence to block access to malicious sites.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Content categorization",
        "definition": "A web filtering technique that classifies websites into categories, such as gambling or social media, so policy can allow or block traffic by category.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Block rule (web filtering)",
        "definition": "A specific policy entry that explicitly denies access to a defined website, domain, or category regardless of other filtering settings.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Reputation-based filtering",
        "definition": "A web or email filtering technique that blocks traffic to or from sources with a known history of malicious activity based on threat intelligence scoring.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Group Policy",
        "definition": "A Windows feature that allows administrators to centrally define and enforce security and configuration settings across many computers and users in a domain.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Security-Enhanced Linux (SELinux)",
        "definition": "A Linux kernel security module that enforces mandatory access control policies to restrict what actions processes and users can perform.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Secure protocol selection",
        "definition": "The practice of choosing encrypted, authenticated protocols (e.g., HTTPS instead of HTTP, SFTP instead of FTP) when implementing network services.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Port selection (secure protocols)",
        "definition": "The practice of configuring services to use the correct, expected port for a secure protocol to ensure proper filtering and monitoring.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Transport method (secure protocols)",
        "definition": "The mechanism, such as TLS encapsulation or IPSec tunneling, used to protect data as it moves between systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "DNS filtering",
        "definition": "A security control that blocks resolution of known malicious or unwanted domain names before a connection to them can be established.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "DMARC",
        "definition": "Domain-based Message Authentication, Reporting, and Conformance — an email authentication policy that tells receiving servers how to handle messages that fail SPF or DKIM checks.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "DomainKeys Identified Mail (DKIM)",
        "definition": "An email authentication method that uses a digital signature to verify that a message's content was not altered in transit and originated from the claimed domain.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Sender Policy Framework (SPF)",
        "definition": "An email authentication method that uses DNS records to specify which mail servers are authorized to send email on behalf of a domain.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Email gateway",
        "definition": "A security appliance or service that filters inbound and outbound email for spam, malware, phishing, and policy violations before delivery.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "File integrity monitoring (FIM)",
        "definition": "A control that tracks and alerts on unauthorized changes to critical system and application files by comparing them against a known-good baseline.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Data Loss Prevention (DLP)",
        "definition": "A set of tools and processes that detect and prevent sensitive data from being exfiltrated, leaked, or improperly shared.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Network Access Control (NAC)",
        "definition": "A security solution that enforces policy compliance and authentication before granting devices access to the network.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Endpoint Detection and Response (EDR)",
        "definition": "A security solution that continuously monitors endpoint activity to detect, investigate, and respond to advanced threats that bypass traditional antivirus.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "Extended Detection and Response (XDR)",
        "definition": "A security solution that expands on EDR by correlating and analyzing data across endpoints, network, cloud, and email to provide unified threat detection and response.",
    },
    {
        "domain": 4,
        "study_topic": "4.5 Enterprise Capabilities",
        "term": "User behavior analytics (UBA)",
        "definition": "A security capability that establishes a baseline of normal user activity and flags deviations that may indicate compromised credentials or insider threats.",
    },

    # ------------------------------------------------------------------
    # 4.6 Identity and access management
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Provisioning (user account)",
        "definition": "The process of creating a user account and assigning the appropriate access rights when a person joins an organization or changes roles.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Deprovisioning (user account)",
        "definition": "The process of disabling or deleting a user account and revoking access rights when a person leaves an organization or no longer requires access.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Permission assignment",
        "definition": "The act of granting specific access rights to a user or group, which must be carefully scoped to avoid unintended implications like privilege creep.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Identity proofing",
        "definition": "The process of verifying that a person is who they claim to be before issuing them a digital identity or credential.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Federation",
        "definition": "An arrangement that allows a user's identity and authentication to be trusted across multiple, separately administered systems or organizations.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Single Sign-On (SSO)",
        "definition": "An authentication capability that allows a user to log in once and gain access to multiple independent systems or applications without re-authenticating.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Lightweight Directory Access Protocol (LDAP)",
        "definition": "A protocol used to query and modify directory service information, commonly used to centralize user authentication and authorization data.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "OAuth",
        "definition": "An open standard for delegated authorization that allows a third-party application to access a user's resources without exposing their credentials.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Security Assertion Markup Language (SAML)",
        "definition": "An XML-based standard used to exchange authentication and authorization data between an identity provider and a service provider, commonly enabling SSO.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Interoperability (IAM)",
        "definition": "The ability of different identity and access management systems to work together across platforms and organizational boundaries.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Attestation (access review)",
        "definition": "A formal, periodic review process in which managers or system owners certify that a user's assigned access rights remain appropriate.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Mandatory access control (MAC)",
        "definition": "An access control model in which access decisions are made by a central authority based on fixed security labels, and users cannot alter permissions.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Discretionary access control (DAC)",
        "definition": "An access control model in which the owner of a resource decides who is granted access to it.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Role-based access control (RBAC)",
        "definition": "An access control model that assigns permissions to users based on their job role rather than to each user individually.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Rule-based access control",
        "definition": "An access control model that grants or denies access based on a predefined set of system-enforced rules, such as firewall ACLs.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Attribute-based access control (ABAC)",
        "definition": "An access control model that grants access based on a combination of user, resource, and environmental attributes evaluated at request time.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Time-of-day restriction",
        "definition": "An access control mechanism that limits when a user or system can log in or access resources, such as only during business hours.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Identity and Access Management",
        "term": "Least privilege",
        "definition": "The security principle of granting users and processes only the minimum access rights necessary to perform their required tasks.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Multifactor authentication (MFA)",
        "definition": "An authentication method that requires a user to present two or more independent factors from different categories to verify their identity.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Biometrics",
        "definition": "An authentication factor based on a unique physical or behavioral characteristic of a person, such as a fingerprint, iris pattern, or voice.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Hard authentication token",
        "definition": "A physical device, such as a key fob or smart card, that generates or stores a credential used as an authentication factor.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Soft authentication token",
        "definition": "A software-based credential, such as an authenticator app generating time-based one-time passwords, used as an authentication factor.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Security key",
        "definition": "A physical hardware device, such as a USB or NFC token supporting FIDO2/WebAuthn, used as a phishing-resistant authentication factor.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Something you know",
        "definition": "An authentication factor category based on knowledge only the legitimate user should possess, such as a password or PIN.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Something you have",
        "definition": "An authentication factor category based on possession of a physical or virtual item, such as a hardware token or smartphone.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Something you are",
        "definition": "An authentication factor category based on an inherent physical or behavioral trait of the user, such as a fingerprint.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Multifactor Authentication",
        "term": "Somewhere you are",
        "definition": "An authentication factor category based on the user's physical or network location, such as GPS coordinates or an approved IP range.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password length",
        "definition": "A key password best practice specifying a minimum number of characters, since longer passwords are exponentially harder to brute force.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password complexity",
        "definition": "A password best practice requiring a mix of character types, such as uppercase, lowercase, numbers, and symbols, to resist guessing and cracking attacks.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password reuse",
        "definition": "The risky practice of using the same password across multiple accounts, which allows a single credential breach to compromise many systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password expiration and age",
        "definition": "Policy settings that define the maximum time a password may be used before it must be changed and the minimum time before it can be changed again.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password manager",
        "definition": "An application that securely generates, stores, and autofills strong, unique passwords for each of a user's accounts.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Passwordless authentication",
        "definition": "An authentication approach that verifies identity using factors such as biometrics or security keys instead of a traditional shared secret password.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Privileged Access Management (PAM)",
        "definition": "A set of tools and processes that secure, control, monitor, and audit access for accounts with elevated administrative privileges.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Just-in-time permissions",
        "definition": "A PAM technique that grants elevated access only for the limited time needed to complete a specific task, then automatically revokes it.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Password vaulting",
        "definition": "A PAM technique that stores privileged credentials in a secure, centralized repository and checks them out to authorized users on demand.",
    },
    {
        "domain": 4,
        "study_topic": "4.6 Password Concepts and PAM",
        "term": "Ephemeral credentials",
        "definition": "Short-lived, automatically expiring credentials issued for a single session or task to reduce the risk of long-term credential theft or misuse.",
    },

    # ------------------------------------------------------------------
    # 4.7 Automation and orchestration
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "User provisioning (automation)",
        "definition": "An automation use case that automatically creates accounts and assigns baseline access when a new user is added to an identity system.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Resource provisioning (automation)",
        "definition": "An automation use case that automatically deploys and configures infrastructure, such as servers or cloud instances, based on predefined templates.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Guard rails (automation)",
        "definition": "Automated policy controls that prevent users or systems from taking actions outside approved, secure boundaries.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Security groups (automation)",
        "definition": "Automatically applied, template-based sets of access rules assigned to cloud resources or network segments to enforce consistent policy.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Ticket creation (automation)",
        "definition": "An automation use case in which monitoring or security tools automatically generate helpdesk or incident tickets when predefined conditions are met.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Escalation (automation)",
        "definition": "An automation use case that automatically routes an alert or ticket to higher-tier personnel when it is not resolved within a defined time or severity threshold.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Enabling/disabling services and access (automation)",
        "definition": "An automation use case that programmatically turns services or account access on or off in response to triggers, such as disabling an account upon termination.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Continuous integration and testing",
        "definition": "An automation practice in which code changes are automatically built, tested, and validated—including security checks—as they are merged into a shared repository.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Integrations and APIs (automation)",
        "definition": "The use of application programming interfaces to connect disparate security tools so they can share data and trigger automated actions across platforms.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Automation efficiency benefit",
        "definition": "A benefit of automation in which repetitive manual tasks are performed faster and more consistently, freeing staff time for higher-value work.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Enforcing baselines (automation benefit)",
        "definition": "A benefit of automation in which secure configuration baselines are consistently applied and continuously verified across all systems without manual effort.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Standard infrastructure configurations",
        "definition": "A benefit of automation in which infrastructure is deployed identically every time from templates, reducing configuration drift and human error.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Scaling in a secure manner",
        "definition": "A benefit of automation in which security controls and configurations are automatically applied as an organization grows resources, avoiding gaps introduced by manual scaling.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Employee retention (automation benefit)",
        "definition": "A benefit of automation in which removing tedious, repetitive manual work improves job satisfaction and helps retain skilled security staff.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Reaction time (automation benefit)",
        "definition": "A benefit of automation in which automated detection and response actions occur far faster than a human analyst could act manually.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Workforce multiplier",
        "definition": "A benefit of automation in which a small security team can accomplish the work of a much larger team by automating routine tasks.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Complexity (automation consideration)",
        "definition": "A consideration in adopting automation, since interconnected scripts and workflows can become difficult to understand, maintain, and troubleshoot.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Cost (automation consideration)",
        "definition": "A consideration in adopting automation, since tooling, licensing, and development effort require upfront and ongoing investment.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Single point of failure (automation)",
        "definition": "A consideration in adopting automation, since a flaw in a widely used automated script or platform can simultaneously impact every system it manages.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Technical debt (automation)",
        "definition": "A consideration in adopting automation, referring to the accumulated cost of maintaining outdated or poorly documented automated processes over time.",
    },
    {
        "domain": 4,
        "study_topic": "4.7 Automation and Orchestration",
        "term": "Ongoing supportability",
        "definition": "A consideration in adopting automation regarding whether the organization has the skills and resources to maintain and update automated processes long-term.",
    },

    # ------------------------------------------------------------------
    # 4.8 Incident response
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Incident response process",
        "definition": "The structured lifecycle organizations follow to prepare for, detect, and recover from security incidents, typically comprising preparation, detection, analysis, containment, eradication, recovery, and lessons learned.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Preparation (incident response)",
        "definition": "The incident response phase focused on establishing tools, procedures, training, and communication plans before an incident occurs.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Detection (incident response)",
        "definition": "The incident response phase in which monitoring tools or personnel identify indicators that a security incident may be occurring.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Analysis (incident response)",
        "definition": "The incident response phase in which the scope, cause, and impact of an incident are investigated and confirmed.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Containment (incident response)",
        "definition": "The incident response phase focused on limiting the spread and impact of an incident, such as isolating affected systems from the network.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Eradication (incident response)",
        "definition": "The incident response phase in which the root cause of an incident, such as malware or an attacker's foothold, is completely removed from the environment.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Recovery (incident response)",
        "definition": "The incident response phase in which affected systems are restored to normal operation and validated as clean before returning to production.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Lessons learned (incident response)",
        "definition": "The incident response phase in which the team reviews what happened and how it was handled to improve processes and prevent recurrence.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Incident response training",
        "definition": "Ongoing education that ensures personnel understand their roles and can execute the incident response plan effectively when a real incident occurs.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Tabletop exercise",
        "definition": "A discussion-based incident response test in which participants talk through their roles and decisions for a simulated scenario without operating real systems.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Simulation (incident response testing)",
        "definition": "A hands-on incident response test in which participants actively perform their response actions against a realistic, simulated attack scenario.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Root cause analysis",
        "definition": "A structured investigation technique used after an incident to identify the underlying reason it occurred, so the same weakness can be permanently fixed.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Incident Response",
        "term": "Threat hunting",
        "definition": "A proactive security practice in which analysts actively search for indicators of undetected threats within an environment, rather than waiting for alerts.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Digital forensics",
        "definition": "The scientific process of identifying, collecting, preserving, and analyzing digital evidence in a manner that maintains its integrity for legal or investigative purposes.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Legal hold",
        "definition": "A directive requiring an organization to preserve all relevant data and records because they may be needed for pending or anticipated litigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Chain of custody",
        "definition": "A documented record tracking who collected, handled, and had access to a piece of evidence, used to prove its integrity was maintained.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Acquisition (forensics)",
        "definition": "The forensic process of collecting digital evidence, typically starting with the most volatile data first and using write-blocking tools to avoid altering the original source.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Forensic reporting",
        "definition": "The formal documentation of forensic findings, methods, and conclusions in a manner suitable for use in legal or disciplinary proceedings.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "Preservation (forensics)",
        "definition": "The forensic practice of protecting evidence from alteration, damage, or destruction from the moment it is identified through the conclusion of an investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.8 Digital Forensics",
        "term": "E-discovery",
        "definition": "The process of identifying, collecting, and producing electronically stored information in response to a legal request or litigation.",
    },

    # ------------------------------------------------------------------
    # 4.9 Data sources for investigations
    # ------------------------------------------------------------------
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Firewall log",
        "definition": "A log data source that records allowed and denied connection attempts, useful for identifying blocked attacks and traffic patterns during an investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Application log",
        "definition": "A log data source generated by software applications that records events such as errors, user actions, and transactions relevant to an investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Endpoint log",
        "definition": "A log data source recording activity on an individual device, such as process execution and file access, useful for tracing attacker actions on a host.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "OS-specific security log",
        "definition": "A log data source native to an operating system, such as the Windows Security log or Linux auditd log, that records authentication and privilege-related events.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "IPS/IDS log",
        "definition": "A log data source that records detected or blocked intrusion attempts, providing detail on the signatures or anomalies that triggered an alert.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Network log",
        "definition": "A log data source, such as router or switch logs, that records network-level events like interface changes, routing updates, and connection activity.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Metadata (investigation data source)",
        "definition": "Data that describes other data, such as file timestamps, email headers, or image EXIF data, which can reveal important contextual details during an investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Vulnerability scan output (data source)",
        "definition": "Results from vulnerability scanning tools that can help investigators determine whether a known weakness was likely exploited in an incident.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Automated report (data source)",
        "definition": "A scheduled or triggered summary generated by security tools that consolidates findings for review during an investigation.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Dashboard (data source)",
        "definition": "A visual interface that consolidates real-time metrics and alerts from multiple security tools, helping investigators quickly assess the current situation.",
    },
    {
        "domain": 4,
        "study_topic": "4.9 Data Sources for Investigations",
        "term": "Packet capture (PCAP)",
        "definition": "A recording of raw network traffic that allows investigators to reconstruct and analyze the exact data exchanged during a security event.",
    },
]
