"""Security+ SY0-701 Domain 5 flashcards: Security Program Management and Oversight."""

CARDS = [
    # --- 5.1 Security governance: guidelines ---
    {
        "domain": 5,
        "study_topic": "Security governance",
        "term": "Guidelines",
        "definition": "Recommended, non-mandatory practices that help personnel achieve policy objectives when strict standards do not fit every situation.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance",
        "term": "Security governance",
        "definition": "The overall framework of policies, roles, and processes an organization uses to direct and control its information security program in alignment with business objectives.",
    },
    # --- 5.1 Policies ---
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Acceptable use policy (AUP)",
        "definition": "A policy that defines the rules and constraints employees must agree to in order to use organizational networks, systems, and devices.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Information security policies",
        "definition": "High-level, board- or executive-approved statements that establish an organization's overall goals, expectations, and requirements for protecting information assets.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Business continuity policy",
        "definition": "A policy that establishes management's commitment and requirements for keeping essential business functions operating during and after a disruptive event.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Disaster recovery policy",
        "definition": "A policy that defines the organization's approach and requirements for restoring IT systems and data after a disaster or major outage.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Incident response policy",
        "definition": "A policy that defines roles, responsibilities, and required actions for detecting, responding to, and recovering from security incidents.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Software development lifecycle (SDLC) policy",
        "definition": "A policy that mandates secure coding practices, testing, and review gates throughout each phase of application development.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance policies",
        "term": "Change management policy",
        "definition": "A policy that requires proposed changes to systems or processes to be documented, reviewed, approved, and tracked before implementation.",
    },
    # --- 5.1 Standards ---
    {
        "domain": 5,
        "study_topic": "Security governance standards",
        "term": "Password standard",
        "definition": "A mandatory, specific set of technical requirements (length, complexity, rotation, reuse rules) that all passwords in an organization must meet.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance standards",
        "term": "Access control standard",
        "definition": "A mandatory technical specification defining how authentication, authorization, and account provisioning must be implemented across systems.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance standards",
        "term": "Physical security standard",
        "definition": "A mandatory specification for controls such as badges, locks, cameras, and facility design that protect physical premises and assets.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance standards",
        "term": "Encryption standard",
        "definition": "A mandatory specification of approved algorithms, key lengths, and key management practices required for protecting data at rest and in transit.",
    },
    # --- 5.1 Procedures ---
    {
        "domain": 5,
        "study_topic": "Security governance procedures",
        "term": "Change management procedure",
        "definition": "The documented, step-by-step process for submitting, reviewing, approving, testing, and implementing a change through a change advisory board.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance procedures",
        "term": "Onboarding procedure",
        "definition": "The documented steps for provisioning accounts, access, equipment, and training when a new employee joins the organization.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance procedures",
        "term": "Offboarding procedure",
        "definition": "The documented steps for revoking access, recovering assets, and disabling accounts when an employee leaves or changes roles.",
    },
    {
        "domain": 5,
        "study_topic": "Security governance procedures",
        "term": "Playbooks",
        "definition": "Detailed, step-by-step operational guides used by security teams to execute a consistent, repeatable response to a specific type of incident or scenario.",
    },
    # --- 5.1 External considerations ---
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "Regulatory considerations",
        "definition": "Requirements imposed by government regulators (such as HIPAA or GLBA) that an organization's security program must satisfy to remain compliant.",
    },
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "Legal considerations",
        "definition": "Contractual, statutory, and liability obligations that shape how an organization must design and enforce its security policies.",
    },
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "Industry considerations",
        "definition": "Sector-specific standards and best practices (such as PCI DSS for payment card processing) that influence an organization's governance requirements.",
    },
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "Local/regional considerations",
        "definition": "Governance requirements driven by laws or expectations specific to a city, state, or geographic region in which the organization operates.",
    },
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "National considerations",
        "definition": "Governance requirements driven by the laws and regulatory bodies of the country in which the organization operates.",
    },
    {
        "domain": 5,
        "study_topic": "External governance considerations",
        "term": "Global considerations",
        "definition": "Governance requirements arising from operating across multiple jurisdictions, such as complying with the GDPR when handling EU residents' data.",
    },
    # --- 5.1 Monitoring/revision ---
    {
        "domain": 5,
        "study_topic": "Governance monitoring and revision",
        "term": "Monitoring and revision of governance",
        "definition": "The ongoing process of reviewing and updating policies, standards, and procedures to keep them effective as threats, technology, and regulations change.",
    },
    # --- 5.1 Governance structures ---
    {
        "domain": 5,
        "study_topic": "Governance structures",
        "term": "Boards",
        "definition": "A governing body, such as a board of directors, that provides top-level oversight and approval authority for an organization's security governance.",
    },
    {
        "domain": 5,
        "study_topic": "Governance structures",
        "term": "Committees",
        "definition": "A group of stakeholders, such as a security steering committee, formed to review, guide, and make decisions on specific governance areas.",
    },
    {
        "domain": 5,
        "study_topic": "Governance structures",
        "term": "Government entities",
        "definition": "External regulatory or legislative bodies that create laws, regulations, and oversight requirements affecting an organization's governance.",
    },
    {
        "domain": 5,
        "study_topic": "Governance structures",
        "term": "Centralized governance",
        "definition": "A governance structure in which a single authority or team makes security policy and decisions for the entire organization.",
    },
    {
        "domain": 5,
        "study_topic": "Governance structures",
        "term": "Decentralized governance",
        "definition": "A governance structure in which individual business units or regions have autonomy to make their own security policy and decisions.",
    },
    # --- 5.1 Roles and responsibilities ---
    {
        "domain": 5,
        "study_topic": "Data roles and responsibilities",
        "term": "Data owner",
        "definition": "The individual, typically a senior executive, who has ultimate organizational responsibility and accountability for a specific set of data.",
    },
    {
        "domain": 5,
        "study_topic": "Data roles and responsibilities",
        "term": "Data controller",
        "definition": "The entity that determines the purposes and means of processing personal data, and bears primary legal responsibility for that processing under privacy law.",
    },
    {
        "domain": 5,
        "study_topic": "Data roles and responsibilities",
        "term": "Data processor",
        "definition": "An entity that processes personal data on behalf of, and under the instructions of, the data controller.",
    },
    {
        "domain": 5,
        "study_topic": "Data roles and responsibilities",
        "term": "Data custodian/steward",
        "definition": "The individual responsible for the day-to-day technical management, storage, and security of data according to the data owner's classification and rules.",
    },
    # --- 5.2 Risk management ---
    {
        "domain": 5,
        "study_topic": "Risk identification",
        "term": "Risk identification",
        "definition": "The process of discovering, recognizing, and documenting risks that could affect an organization's assets, operations, or objectives.",
    },
    {
        "domain": 5,
        "study_topic": "Risk assessment",
        "term": "Risk assessment",
        "definition": "The overall process of identifying, analyzing, and evaluating risk to determine its significance and inform mitigation decisions.",
    },
    {
        "domain": 5,
        "study_topic": "Risk assessment",
        "term": "Ad hoc risk assessment",
        "definition": "A risk assessment performed on an as-needed, unscheduled basis, typically in response to a specific event or request.",
    },
    {
        "domain": 5,
        "study_topic": "Risk assessment",
        "term": "Recurring risk assessment",
        "definition": "A risk assessment conducted on a regular, scheduled basis, such as quarterly or annually, to keep risk data current.",
    },
    {
        "domain": 5,
        "study_topic": "Risk assessment",
        "term": "One-time risk assessment",
        "definition": "A risk assessment performed a single time, often to evaluate a specific project, system, or point-in-time decision.",
    },
    {
        "domain": 5,
        "study_topic": "Risk assessment",
        "term": "Continuous risk assessment",
        "definition": "An ongoing, real-time process of monitoring and evaluating risk using automated tools rather than periodic snapshots.",
    },
    # --- 5.2 Risk analysis ---
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Qualitative risk analysis",
        "definition": "A risk analysis method that uses subjective, descriptive ratings (such as low, medium, high) to evaluate the likelihood and impact of risks.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Quantitative risk analysis",
        "definition": "A risk analysis method that uses numerical, dollar-based values to calculate and express the likelihood and impact of risks.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Single loss expectancy (SLE)",
        "definition": "The monetary loss expected from a single occurrence of a risk event, calculated as asset value multiplied by exposure factor (SLE = AV x EF).",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Annualized loss expectancy (ALE)",
        "definition": "The expected monetary loss from a risk over a one-year period, calculated as single loss expectancy multiplied by annualized rate of occurrence (ALE = SLE x ARO).",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Annualized rate of occurrence (ARO)",
        "definition": "The estimated number of times a specific risk event is expected to occur within a single year.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Probability",
        "definition": "The estimated chance that a specific risk event will occur, used as an input to both qualitative and quantitative risk analysis.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Likelihood",
        "definition": "A measure of how probable it is that a threat will exploit a vulnerability, often expressed qualitatively (rare, possible, likely) or numerically.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Exposure factor (EF)",
        "definition": "The percentage of an asset's value that would be lost if a specific risk event occurred.",
    },
    {
        "domain": 5,
        "study_topic": "Risk analysis",
        "term": "Impact",
        "definition": "The magnitude of harm, financial or otherwise, that would result if a risk materializes.",
    },
    # --- 5.2 Risk register ---
    {
        "domain": 5,
        "study_topic": "Risk register",
        "term": "Risk register",
        "definition": "A centralized document that catalogs identified risks along with their analysis, ownership, treatment plan, and status.",
    },
    {
        "domain": 5,
        "study_topic": "Risk register",
        "term": "Key risk indicators (KRIs)",
        "definition": "Metrics used to provide early warning signals that a risk's likelihood or impact is increasing.",
    },
    {
        "domain": 5,
        "study_topic": "Risk register",
        "term": "Risk owner",
        "definition": "The individual assigned accountability for managing, monitoring, and treating a specific risk listed in the risk register.",
    },
    {
        "domain": 5,
        "study_topic": "Risk register",
        "term": "Risk threshold",
        "definition": "The level of risk exposure, above which a risk requires escalation, treatment, or management action.",
    },
    # --- 5.2 Risk tolerance/appetite ---
    {
        "domain": 5,
        "study_topic": "Risk tolerance and appetite",
        "term": "Risk tolerance",
        "definition": "The specific, measurable amount of risk deviation from the risk appetite that an organization is willing to accept for a given objective.",
    },
    {
        "domain": 5,
        "study_topic": "Risk tolerance and appetite",
        "term": "Risk appetite",
        "definition": "The general amount and type of risk an organization is willing to pursue or retain in order to achieve its objectives.",
    },
    {
        "domain": 5,
        "study_topic": "Risk tolerance and appetite",
        "term": "Expansionary risk appetite",
        "definition": "A risk appetite reflecting a willingness to accept higher risk in pursuit of growth, innovation, or new opportunities.",
    },
    {
        "domain": 5,
        "study_topic": "Risk tolerance and appetite",
        "term": "Conservative risk appetite",
        "definition": "A risk appetite reflecting a preference to minimize risk exposure, even at the cost of slower growth or missed opportunities.",
    },
    {
        "domain": 5,
        "study_topic": "Risk tolerance and appetite",
        "term": "Neutral risk appetite",
        "definition": "A risk appetite that balances risk-taking and risk avoidance, neither aggressively pursuing nor strictly avoiding risk.",
    },
    # --- 5.2 Risk management strategies ---
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk transfer",
        "definition": "A risk management strategy that shifts the financial impact of a risk to a third party, such as through purchasing cyber insurance.",
    },
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk acceptance",
        "definition": "A risk management strategy in which the organization acknowledges a risk and chooses to take no action to reduce it, often because the cost of mitigation exceeds the potential loss.",
    },
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk exemption",
        "definition": "A formally approved permanent departure from a security policy or control requirement for a specific accepted risk.",
    },
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk exception",
        "definition": "A formally approved, typically temporary or time-bound, departure from a security policy or control requirement for a specific accepted risk.",
    },
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk avoidance",
        "definition": "A risk management strategy that eliminates exposure to a risk entirely by not engaging in the activity that creates it.",
    },
    {
        "domain": 5,
        "study_topic": "Risk management strategies",
        "term": "Risk mitigation",
        "definition": "A risk management strategy that reduces the likelihood or impact of a risk through the implementation of security controls.",
    },
    {
        "domain": 5,
        "study_topic": "Risk reporting",
        "term": "Risk reporting",
        "definition": "The process of communicating identified risks, their analysis, and treatment status to stakeholders and leadership for decision-making.",
    },
    # --- 5.2 Business impact analysis ---
    {
        "domain": 5,
        "study_topic": "Business impact analysis",
        "term": "Business impact analysis (BIA)",
        "definition": "A process that identifies and evaluates the potential effects of disruptions to critical business operations, informing continuity and recovery priorities.",
    },
    {
        "domain": 5,
        "study_topic": "Business impact analysis",
        "term": "Recovery time objective (RTO)",
        "definition": "The maximum acceptable amount of time a system or process can be down before its unavailability causes unacceptable harm to the business.",
    },
    {
        "domain": 5,
        "study_topic": "Business impact analysis",
        "term": "Recovery point objective (RPO)",
        "definition": "The maximum acceptable amount of data loss, measured in time, that a business can tolerate following a disruption.",
    },
    {
        "domain": 5,
        "study_topic": "Business impact analysis",
        "term": "Mean time to repair (MTTR)",
        "definition": "The average time required to repair a failed system or component and restore it to operation.",
    },
    {
        "domain": 5,
        "study_topic": "Business impact analysis",
        "term": "Mean time between failures (MTBF)",
        "definition": "The average predicted time that will elapse between one failure of a system and the next during normal operation.",
    },
    # --- 5.3 Third-party risk: vendor assessment ---
    {
        "domain": 5,
        "study_topic": "Vendor assessment",
        "term": "Vendor penetration testing",
        "definition": "The practice of reviewing or requiring a vendor's penetration test results to evaluate the security posture of their products or services.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor assessment",
        "term": "Right-to-audit clause",
        "definition": "A contract provision that grants an organization the legal right to audit a vendor's security controls, processes, or records.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor assessment",
        "term": "Evidence of internal audits",
        "definition": "Documentation a vendor provides showing that they have conducted their own internal security or compliance audits.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor assessment",
        "term": "Independent assessments",
        "definition": "Security evaluations of a vendor performed by an unbiased third party rather than the vendor or the customer themselves.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor assessment",
        "term": "Supply chain analysis",
        "definition": "The evaluation of risks introduced by all the suppliers, vendors, and partners involved in producing and delivering a product or service.",
    },
    # --- 5.3 Vendor selection ---
    {
        "domain": 5,
        "study_topic": "Vendor selection",
        "term": "Due diligence (vendor selection)",
        "definition": "The research and investigation an organization performs on a prospective vendor before entering into a business relationship.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor selection",
        "term": "Conflict of interest",
        "definition": "A situation in which a vendor or individual has competing interests or loyalties that could compromise objectivity or judgment in a business relationship.",
    },
    # --- 5.3 Agreement types ---
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Service-level agreement (SLA)",
        "definition": "A contract that defines the minimum level of service, performance metrics, and remedies a vendor commits to provide a customer.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Memorandum of agreement (MOA)",
        "definition": "A formal, binding document that outlines specific responsibilities and commitments agreed upon between two or more parties.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Memorandum of understanding (MOU)",
        "definition": "A document that expresses a mutual, generally non-binding intent and understanding between parties to work together, without the legal weight of a contract.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Master service agreement (MSA)",
        "definition": "A contract that establishes the overarching terms and conditions governing future work between two parties, under which individual statements of work are issued.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Work order (WO)",
        "definition": "A document authorizing and describing a specific task or set of deliverables to be completed under an existing master service agreement.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Statement of work (SOW)",
        "definition": "A document that details the specific work, deliverables, timeline, and terms for a particular project performed by a vendor.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Non-disclosure agreement (NDA)",
        "definition": "A legal contract that obligates the parties to keep specified information confidential and not disclose it to unauthorized parties.",
    },
    {
        "domain": 5,
        "study_topic": "Third-party agreement types",
        "term": "Business partners agreement (BPA)",
        "definition": "A legal agreement that defines the terms, responsibilities, profit and loss sharing, and dispute resolution process between business partners.",
    },
    # --- 5.3 Vendor monitoring ---
    {
        "domain": 5,
        "study_topic": "Vendor monitoring",
        "term": "Vendor monitoring",
        "definition": "The ongoing process of tracking a vendor's performance, security posture, and compliance throughout the life of the business relationship.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor monitoring",
        "term": "Vendor questionnaires",
        "definition": "Standardized sets of security and compliance questions sent to vendors to assess their risk posture before or during a business relationship.",
    },
    {
        "domain": 5,
        "study_topic": "Vendor monitoring",
        "term": "Rules of engagement",
        "definition": "A document that defines the scope, boundaries, methods, and authorization for activities such as vendor testing or a penetration test.",
    },
    # --- 5.4 Security compliance ---
    {
        "domain": 5,
        "study_topic": "Compliance reporting",
        "term": "Internal compliance reporting",
        "definition": "Compliance status communicated within the organization, such as to leadership or an audit committee, to track adherence to policies and regulations.",
    },
    {
        "domain": 5,
        "study_topic": "Compliance reporting",
        "term": "External compliance reporting",
        "definition": "Compliance status communicated to outside parties, such as regulators, customers, or auditors, to demonstrate adherence to requirements.",
    },
    # --- 5.4 Consequences of non-compliance ---
    {
        "domain": 5,
        "study_topic": "Consequences of non-compliance",
        "term": "Fines (non-compliance)",
        "definition": "Monetary penalties imposed by regulators or governing bodies when an organization fails to meet compliance requirements.",
    },
    {
        "domain": 5,
        "study_topic": "Consequences of non-compliance",
        "term": "Sanctions",
        "definition": "Punitive restrictions or penalties, such as loss of certification or trade privileges, imposed on an organization for non-compliance.",
    },
    {
        "domain": 5,
        "study_topic": "Consequences of non-compliance",
        "term": "Reputational damage",
        "definition": "The loss of customer trust and brand value that can result from a publicized compliance failure or security incident.",
    },
    {
        "domain": 5,
        "study_topic": "Consequences of non-compliance",
        "term": "Loss of license",
        "definition": "The revocation of a business or professional license as a consequence of failing to meet regulatory compliance obligations.",
    },
    {
        "domain": 5,
        "study_topic": "Consequences of non-compliance",
        "term": "Contractual impacts",
        "definition": "Consequences such as contract termination, penalties, or loss of business that arise from failing to meet compliance obligations agreed to in a contract.",
    },
    # --- 5.4 Compliance monitoring ---
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "Due diligence/care (compliance)",
        "definition": "The ongoing reasonable steps an organization takes to identify and manage compliance risk (due diligence) and to act responsibly once risk is known (due care).",
    },
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "Attestation",
        "definition": "A formal declaration, often by a senior official, affirming that specific compliance requirements or controls have been met.",
    },
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "Acknowledgement",
        "definition": "A record confirming that an individual has read, understood, and agreed to comply with a policy or requirement.",
    },
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "Internal compliance monitoring",
        "definition": "Compliance verification activities conducted by staff or teams within the organization itself.",
    },
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "External compliance monitoring",
        "definition": "Compliance verification activities conducted by outside parties such as regulators or independent auditors.",
    },
    {
        "domain": 5,
        "study_topic": "Compliance monitoring",
        "term": "Automation (compliance monitoring)",
        "definition": "The use of tools to continuously and automatically check systems and configurations against compliance requirements, reducing manual effort and error.",
    },
    # --- 5.4 Privacy ---
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Legal implications of privacy (local/regional/national/global)",
        "definition": "The varying privacy laws and obligations that apply depending on the jurisdiction in which data is collected, stored, or processed.",
    },
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Data subject",
        "definition": "The individual whose personal data is being collected, processed, or stored.",
    },
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Data controller vs. data processor",
        "definition": "The distinction between the entity that determines why and how personal data is processed (controller) and the entity that processes it on the controller's behalf (processor).",
    },
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Data ownership (privacy)",
        "definition": "The assignment of accountability for a specific set of personal or organizational data, including its accuracy, protection, and lifecycle.",
    },
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Data inventory and retention",
        "definition": "The practice of cataloging what data an organization holds and defining how long each data type must be kept before secure disposal.",
    },
    {
        "domain": 5,
        "study_topic": "Privacy",
        "term": "Right to be forgotten",
        "definition": "A privacy right, established under laws such as the GDPR, that allows individuals to request the deletion of their personal data.",
    },
    # --- 5.5 Audits and assessments ---
    {
        "domain": 5,
        "study_topic": "Audits and assessments",
        "term": "Attestation (audit)",
        "definition": "A formal statement, often from an auditor or executive, certifying that an audit's findings or a control's effectiveness are accurate.",
    },
    {
        "domain": 5,
        "study_topic": "Internal audits",
        "term": "Internal audit - compliance",
        "definition": "An internal review conducted to verify that the organization is adhering to applicable laws, regulations, and internal policies.",
    },
    {
        "domain": 5,
        "study_topic": "Internal audits",
        "term": "Audit committee",
        "definition": "A governance body, often a subset of the board of directors, responsible for overseeing the organization's audit and compliance activities.",
    },
    {
        "domain": 5,
        "study_topic": "Internal audits",
        "term": "Self-assessments",
        "definition": "An internal audit process in which a department or team evaluates its own compliance with policies and controls.",
    },
    {
        "domain": 5,
        "study_topic": "External audits",
        "term": "External audit - regulatory",
        "definition": "An audit conducted by or on behalf of a government or regulatory body to verify compliance with laws and regulations.",
    },
    {
        "domain": 5,
        "study_topic": "External audits",
        "term": "Examinations",
        "definition": "A formal external review, often by a regulator, of an organization's records, controls, and practices to verify compliance.",
    },
    {
        "domain": 5,
        "study_topic": "External audits",
        "term": "Assessment (external)",
        "definition": "An external evaluation of an organization's security posture or compliance, often performed by a customer, partner, or consultant.",
    },
    {
        "domain": 5,
        "study_topic": "External audits",
        "term": "Independent third-party audit",
        "definition": "An audit performed by an outside organization with no vested interest, providing an unbiased assessment of controls and compliance.",
    },
    # --- 5.5 Penetration testing ---
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Physical penetration test",
        "definition": "A penetration test that assesses the effectiveness of physical security controls by attempting to gain unauthorized entry into a facility.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Offensive penetration test",
        "definition": "A penetration test conducted from an attacker's perspective (red team) to actively exploit vulnerabilities and gain access.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Defensive penetration test",
        "definition": "A penetration test exercise focused on the defender's (blue team's) ability to detect and respond to simulated attacks.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Integrated penetration test",
        "definition": "A penetration test in which red and blue teams collaborate and share information in real time, sometimes called a purple team exercise.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Known environment testing",
        "definition": "A penetration test, also called white-box testing, in which testers are given full knowledge of the target's systems and architecture in advance.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Partially known environment testing",
        "definition": "A penetration test, also called gray-box testing, in which testers are given limited knowledge of the target environment before testing.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Unknown environment testing",
        "definition": "A penetration test, also called black-box testing, in which testers are given no prior knowledge of the target environment and must discover it themselves.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Reconnaissance",
        "definition": "The information-gathering phase of a penetration test in which testers collect data about the target before attempting exploitation.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Passive reconnaissance",
        "definition": "Information gathering performed without directly interacting with the target system, such as researching public records or OSINT sources.",
    },
    {
        "domain": 5,
        "study_topic": "Penetration testing",
        "term": "Active reconnaissance",
        "definition": "Information gathering performed by directly interacting with the target system, such as port scanning, which carries a risk of detection.",
    },
    # --- 5.6 Security awareness: phishing ---
    {
        "domain": 5,
        "study_topic": "Phishing awareness",
        "term": "Phishing campaigns",
        "definition": "Simulated phishing exercises sent to employees to test and improve their ability to recognize and appropriately handle phishing attempts.",
    },
    {
        "domain": 5,
        "study_topic": "Phishing awareness",
        "term": "Recognizing a phishing attempt",
        "definition": "Training that teaches users to identify red flags in messages, such as suspicious senders, urgent language, and mismatched links.",
    },
    {
        "domain": 5,
        "study_topic": "Phishing awareness",
        "term": "Responding to reported suspicious messages",
        "definition": "The defined process security teams follow to investigate, triage, and remediate messages that users report as potentially malicious.",
    },
    # --- 5.6 Anomalous behavior recognition ---
    {
        "domain": 5,
        "study_topic": "Anomalous behavior recognition",
        "term": "Risky behavior",
        "definition": "User actions that knowingly increase security exposure, such as using unapproved applications or sharing credentials.",
    },
    {
        "domain": 5,
        "study_topic": "Anomalous behavior recognition",
        "term": "Unexpected behavior",
        "definition": "User or system activity that deviates from established norms or baselines, which may indicate a security issue requiring investigation.",
    },
    {
        "domain": 5,
        "study_topic": "Anomalous behavior recognition",
        "term": "Unintentional behavior",
        "definition": "Accidental user actions, such as mistakenly sending data to the wrong recipient, that create security risk without malicious intent.",
    },
    # --- 5.6 User guidance and training ---
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Policy/handbooks",
        "definition": "Written materials that communicate an organization's security policies and expected employee behavior in an accessible format.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Situational awareness",
        "definition": "Training that helps employees stay alert to their surroundings and recognize potential security threats, such as tailgating or shoulder surfing.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Insider threat awareness",
        "definition": "Training that helps employees recognize and report signs of malicious or negligent activity originating from within the organization.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Password management training",
        "definition": "Training that teaches employees best practices for creating, storing, and protecting passwords, including the use of password managers.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Removable media and cables training",
        "definition": "Training that addresses the risks of using unauthorized USB drives, external media, and cables, including malware and data exfiltration.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Social engineering awareness",
        "definition": "Training that helps employees recognize and resist manipulation tactics used by attackers to gain unauthorized access or information.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Operational security (OPSEC) training",
        "definition": "Training that teaches employees to protect sensitive information about operations, plans, and capabilities from adversaries.",
    },
    {
        "domain": 5,
        "study_topic": "User guidance and training",
        "term": "Hybrid/remote work environment training",
        "definition": "Training that addresses security risks specific to working outside a traditional office, such as securing home networks and public Wi-Fi use.",
    },
    # --- 5.6 Reporting and monitoring ---
    {
        "domain": 5,
        "study_topic": "Security awareness reporting and monitoring",
        "term": "Initial reporting and monitoring",
        "definition": "The baseline training and reporting completed by employees when they first join an organization or awareness program.",
    },
    {
        "domain": 5,
        "study_topic": "Security awareness reporting and monitoring",
        "term": "Recurring reporting and monitoring",
        "definition": "Ongoing, periodic security awareness training and metrics tracking used to reinforce behavior and measure program effectiveness over time.",
    },
    # --- 5.6 Development and execution ---
    {
        "domain": 5,
        "study_topic": "Security awareness program lifecycle",
        "term": "Development (awareness program)",
        "definition": "The phase of a security awareness program in which training content, materials, and delivery methods are created based on identified needs.",
    },
    {
        "domain": 5,
        "study_topic": "Security awareness program lifecycle",
        "term": "Execution (awareness program)",
        "definition": "The phase of a security awareness program in which training is delivered to employees and its effectiveness is tracked and measured.",
    },
]
