"""AZ-900 Domain 1: Describe cloud concepts.

Question bank for Microsoft Azure Fundamentals (AZ-900), Domain 1.
Covers cloud computing and the shared responsibility model, cloud
deployment models (public/private/hybrid), the consumption-based model
and CapEx vs OpEx, cloud benefits (high availability, scalability,
elasticity, reliability, predictability, disaster recovery), and cloud
service types (IaaS/PaaS/SaaS, including serverless).

Objectives:
    1.1 - Describe cloud computing
    1.2 - Describe the benefits of using cloud services
    1.3 - Describe cloud service types
"""

QUESTIONS = [
    # ------------------------------------------------------------------
    # Cloud computing and shared responsibility (objective 1.1)
    # ------------------------------------------------------------------
    {
        "id": "az1-001",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which of the following describes cloud computing?",
        "options": [
            {"id": "a", "text": "The delivery of computing services, such as servers, storage, and networking, over the internet", "correct": True, "rationale": "Correct. Cloud computing is the delivery of computing services over the internet, typically on a pay-as-you-go basis."},
            {"id": "b", "text": "The practice of hosting all applications on servers in your own datacenter", "correct": False, "rationale": "Incorrect. Hosting everything in your own datacenter describes an on-premises environment, not cloud computing."},
            {"id": "c", "text": "A licensing model for purchasing perpetual software licenses", "correct": False, "rationale": "Incorrect. Cloud computing is a service delivery model, not a software licensing model."},
            {"id": "d", "text": "A network topology that connects branch offices to headquarters", "correct": False, "rationale": "Incorrect. Connecting branch offices describes a wide area network design, not cloud computing."},
        ],
        "explanation": "Cloud computing is the delivery of computing services—compute, storage, networking, databases, and more—over the internet, usually paid for based on usage.",
    },
    {
        "id": "az1-002",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In the shared responsibility model, who is always responsible for the information and data stored in the cloud?",
        "options": [
            {"id": "a", "text": "The customer", "correct": True, "rationale": "Correct. The customer always retains responsibility for their information and data in every cloud service model."},
            {"id": "b", "text": "The cloud provider", "correct": False, "rationale": "Incorrect. The provider manages the underlying infrastructure, but responsibility for the data itself always stays with the customer."},
            {"id": "c", "text": "The internet service provider", "correct": False, "rationale": "Incorrect. The ISP only carries network traffic; it has no role in the shared responsibility model."},
            {"id": "d", "text": "Responsibility is shared equally between customer and provider", "correct": False, "rationale": "Incorrect. Some responsibilities are shared, but data is always the customer's responsibility, not a shared one."},
        ],
        "explanation": "Regardless of the service model, the customer is always responsible for their data, devices, and accounts and identities.",
    },
    {
        "id": "az1-003",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In the shared responsibility model, who is always responsible for the physical security of the datacenter?",
        "options": [
            {"id": "a", "text": "The cloud provider", "correct": True, "rationale": "Correct. The provider is always responsible for the physical datacenter, physical network, and physical hosts."},
            {"id": "b", "text": "The customer", "correct": False, "rationale": "Incorrect. Customers never manage the provider's physical facilities in a cloud model."},
            {"id": "c", "text": "A third-party auditor", "correct": False, "rationale": "Incorrect. Auditors may verify controls, but they are not responsible for operating physical security."},
            {"id": "d", "text": "The customer's security team", "correct": False, "rationale": "Incorrect. The customer's security team manages the customer's own responsibilities, such as data and identities, not the provider's datacenters."},
        ],
        "explanation": "The cloud provider is always responsible for the physical datacenter, the physical network, and the physical hosts.",
    },
    {
        "id": "az1-004",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which of the following describes the shared responsibility model?",
        "options": [
            {"id": "a", "text": "Security and management responsibilities are divided between the cloud provider and the customer", "correct": True, "rationale": "Correct. The shared responsibility model defines which tasks the provider handles and which tasks the customer handles."},
            {"id": "b", "text": "The cloud provider is responsible for all security tasks", "correct": False, "rationale": "Incorrect. The customer always keeps some responsibilities, such as data and identities."},
            {"id": "c", "text": "The customer is responsible for all security tasks", "correct": False, "rationale": "Incorrect. The provider always handles the physical infrastructure; the customer never carries every responsibility in the cloud."},
            {"id": "d", "text": "Multiple customers share responsibility for each other's workloads", "correct": False, "rationale": "Incorrect. Customers are isolated from one another; responsibility is shared between a customer and the provider, not between customers."},
        ],
        "explanation": "The shared responsibility model splits responsibilities between the cloud provider and the customer, and the split changes depending on the service type (IaaS, PaaS, or SaaS).",
    },
    {
        "id": "az1-005",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "You deploy a virtual machine by using an IaaS service. Who is responsible for patching the guest operating system?",
        "options": [
            {"id": "a", "text": "The customer", "correct": True, "rationale": "Correct. In IaaS, the customer manages the operating system, including updates and patches."},
            {"id": "b", "text": "The cloud provider", "correct": False, "rationale": "Incorrect. In IaaS, the provider manages the physical host and hypervisor, not the guest operating system."},
            {"id": "c", "text": "The operating system vendor", "correct": False, "rationale": "Incorrect. The vendor releases patches, but applying them to an IaaS virtual machine is the customer's responsibility."},
            {"id": "d", "text": "No patching is required in the cloud", "correct": False, "rationale": "Incorrect. Guest operating systems in IaaS still require regular patching."},
        ],
        "explanation": "With IaaS, the customer is responsible for the operating system and everything installed on it; the provider is responsible for the physical infrastructure.",
    },
    {
        "id": "az1-006",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In a SaaS solution, who is responsible for managing and maintaining the application software?",
        "options": [
            {"id": "a", "text": "The cloud provider", "correct": True, "rationale": "Correct. In SaaS, the provider manages the application, the operating system, and all underlying infrastructure."},
            {"id": "b", "text": "The customer", "correct": False, "rationale": "Incorrect. In SaaS, the customer only manages their data, accounts, and devices, not the application itself."},
            {"id": "c", "text": "The customer's development team", "correct": False, "rationale": "Incorrect. SaaS applications are maintained by the provider; the customer does not develop or maintain them."},
            {"id": "d", "text": "An independent software vendor hired by the customer", "correct": False, "rationale": "Incorrect. The SaaS provider maintains the application as part of the service."},
        ],
        "explanation": "SaaS places the most responsibility on the provider, which manages the application and all layers beneath it.",
    },
    {
        "id": "az1-007",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Your company uses Microsoft 365. Who is responsible for managing user accounts and identities?",
        "options": [
            {"id": "a", "text": "The customer", "correct": True, "rationale": "Correct. Accounts and identities are always the customer's responsibility, even in SaaS."},
            {"id": "b", "text": "Microsoft", "correct": False, "rationale": "Incorrect. Microsoft manages the application and infrastructure, but the customer manages its own users and identities."},
            {"id": "c", "text": "The device manufacturer", "correct": False, "rationale": "Incorrect. Device manufacturers have no role in managing an organization's user accounts."},
            {"id": "d", "text": "The internet service provider", "correct": False, "rationale": "Incorrect. ISPs provide connectivity only and do not manage cloud identities."},
        ],
        "explanation": "In every cloud service model, the customer remains responsible for information and data, devices, and accounts and identities.",
    },
    {
        "id": "az1-008",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_response",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In the shared responsibility model, which two responsibilities always belong to the customer, regardless of the cloud service type? Select two.",
        "options": [
            {"id": "a", "text": "Information and data", "correct": True, "rationale": "Correct. The customer always retains responsibility for their data in every service model."},
            {"id": "b", "text": "Accounts and identities", "correct": True, "rationale": "Correct. The customer always manages its own user accounts and identities."},
            {"id": "c", "text": "The physical network", "correct": False, "rationale": "Incorrect. The physical network is always the cloud provider's responsibility."},
            {"id": "d", "text": "The physical hosts", "correct": False, "rationale": "Incorrect. Physical hosts are always managed by the cloud provider."},
        ],
        "explanation": "Data, devices, and accounts and identities are always customer responsibilities; the physical datacenter, network, and hosts are always provider responsibilities.",
    },
    {
        "id": "az1-009",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which cloud service type places the greatest management responsibility on the customer?",
        "options": [
            {"id": "a", "text": "IaaS", "correct": True, "rationale": "Correct. With IaaS, the customer manages the operating system, middleware, runtime, applications, and data."},
            {"id": "b", "text": "PaaS", "correct": False, "rationale": "Incorrect. In PaaS, the provider manages the operating system and runtime, leaving less for the customer to manage than IaaS."},
            {"id": "c", "text": "SaaS", "correct": False, "rationale": "Incorrect. SaaS places the least management responsibility on the customer."},
            {"id": "d", "text": "Serverless computing", "correct": False, "rationale": "Incorrect. Serverless abstracts away infrastructure management almost entirely, so the customer manages very little."},
        ],
        "explanation": "IaaS gives the customer the most control and therefore the most management responsibility of the cloud service types.",
    },
    {
        "id": "az1-010",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which of the following are typical services offered through cloud computing?",
        "options": [
            {"id": "a", "text": "Compute power, storage, and networking", "correct": True, "rationale": "Correct. Virtual machines, storage, and networking are core cloud computing services, along with databases, AI, and more."},
            {"id": "b", "text": "Office furniture leasing", "correct": False, "rationale": "Incorrect. Cloud computing delivers IT services, not physical office equipment."},
            {"id": "c", "text": "On-site hardware repair", "correct": False, "rationale": "Incorrect. Cloud providers maintain their own hardware; they do not repair customer-owned equipment."},
            {"id": "d", "text": "Printed software manuals", "correct": False, "rationale": "Incorrect. Documentation may be provided online, but it is not what defines cloud computing services."},
        ],
        "explanation": "Cloud computing delivers IT services such as virtual machines, storage, databases, and networking over the internet.",
    },
    {
        "id": "az1-011",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "You use a PaaS database service. Who is responsible for maintaining the underlying operating system?",
        "options": [
            {"id": "a", "text": "The cloud provider", "correct": True, "rationale": "Correct. In PaaS, the provider manages the operating system, runtime, and physical infrastructure."},
            {"id": "b", "text": "The customer", "correct": False, "rationale": "Incorrect. Customers manage the operating system only in IaaS, not in PaaS."},
            {"id": "c", "text": "The database administrator employed by the customer", "correct": False, "rationale": "Incorrect. The customer's DBA manages the data and database configuration, not the operating system in a PaaS service."},
            {"id": "d", "text": "The operating system vendor", "correct": False, "rationale": "Incorrect. The OS vendor supplies the software, but the cloud provider operates and maintains it in PaaS."},
        ],
        "explanation": "In PaaS, the provider maintains the physical infrastructure and the operating system; the customer focuses on applications and data.",
    },
    {
        "id": "az1-012",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In the shared responsibility model, which responsibility can be shared between the customer and the provider in a PaaS deployment?",
        "options": [
            {"id": "a", "text": "Identity and directory infrastructure", "correct": True, "rationale": "Correct. In PaaS and SaaS, responsibility for identity and directory infrastructure is shared between customer and provider."},
            {"id": "b", "text": "Information and data", "correct": False, "rationale": "Incorrect. Data is always solely the customer's responsibility."},
            {"id": "c", "text": "The physical datacenter", "correct": False, "rationale": "Incorrect. The physical datacenter is always solely the provider's responsibility."},
            {"id": "d", "text": "The customer's end-user devices", "correct": False, "rationale": "Incorrect. Devices are always solely the customer's responsibility."},
        ],
        "explanation": "Some responsibilities, such as identity and directory infrastructure and network controls, are shared or vary by service type, while data and physical infrastructure never change owners.",
    },
    {
        "id": "az1-013",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which of the following are always the responsibility of the cloud provider in every cloud service model?",
        "options": [
            {"id": "a", "text": "Physical hosts, physical network, and physical datacenter", "correct": True, "rationale": "Correct. The provider always manages the physical infrastructure in every cloud service model."},
            {"id": "b", "text": "User accounts and passwords", "correct": False, "rationale": "Incorrect. Accounts and identities are always the customer's responsibility."},
            {"id": "c", "text": "Data stored by the customer", "correct": False, "rationale": "Incorrect. Customer data is always the customer's responsibility."},
            {"id": "d", "text": "The customer's laptops and mobile devices", "correct": False, "rationale": "Incorrect. Devices are always managed by the customer."},
        ],
        "explanation": "The physical datacenter, physical network, and physical hosts are always managed by the cloud provider.",
    },
    {
        "id": "az1-014",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Your company runs all workloads in its own on-premises datacenter. Who is responsible for maintaining the hardware, the operating systems, and the applications?",
        "options": [
            {"id": "a", "text": "Your company", "correct": True, "rationale": "Correct. In an on-premises environment, the organization is responsible for every layer, from the building to the applications."},
            {"id": "b", "text": "A cloud provider", "correct": False, "rationale": "Incorrect. No cloud provider is involved in a fully on-premises environment."},
            {"id": "c", "text": "The hardware manufacturer", "correct": False, "rationale": "Incorrect. Manufacturers may honor warranties, but day-to-day operation and maintenance belong to the organization."},
            {"id": "d", "text": "The software vendors", "correct": False, "rationale": "Incorrect. Vendors supply software and updates, but the organization must deploy and maintain everything on-premises."},
        ],
        "explanation": "On-premises, the organization carries full responsibility for all layers; moving to the cloud shifts part of that responsibility to the provider.",
    },
    {
        "id": "az1-015",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which of the following is an example of using cloud computing?",
        "options": [
            {"id": "a", "text": "Running a website on virtual machines hosted by a cloud provider", "correct": True, "rationale": "Correct. Renting virtual machines from a cloud provider over the internet is a classic example of cloud computing."},
            {"id": "b", "text": "Installing an application on a server in your office server room", "correct": False, "rationale": "Incorrect. A server in your own office is an on-premises deployment, not cloud computing."},
            {"id": "c", "text": "Storing files on a USB flash drive", "correct": False, "rationale": "Incorrect. Local removable storage is not a cloud service."},
            {"id": "d", "text": "Connecting two office buildings with a leased line", "correct": False, "rationale": "Incorrect. A leased line is traditional networking, not a cloud computing service."},
        ],
        "explanation": "Cloud computing means consuming IT services, such as virtual machines or storage, from a provider over the internet.",
    },
    {
        "id": "az1-016",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Your company migrates an on-premises server to an IaaS virtual machine in the cloud. Which responsibility transfers from your company to the cloud provider?",
        "options": [
            {"id": "a", "text": "Maintaining the physical server hardware", "correct": True, "rationale": "Correct. After migrating to IaaS, the provider owns and maintains the physical hosts, network, and datacenter."},
            {"id": "b", "text": "Patching the operating system", "correct": False, "rationale": "Incorrect. In IaaS, the customer still patches the guest operating system."},
            {"id": "c", "text": "Managing user accounts", "correct": False, "rationale": "Incorrect. Accounts and identities always remain the customer's responsibility."},
            {"id": "d", "text": "Classifying and protecting company data", "correct": False, "rationale": "Incorrect. Data remains the customer's responsibility in every model."},
        ],
        "explanation": "Moving to IaaS transfers responsibility for physical infrastructure to the provider, while the customer keeps the operating system, applications, and data.",
    },
    {
        "id": "az1-017",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Your company adopts a SaaS email service. Which task remains your company's responsibility?",
        "options": [
            {"id": "a", "text": "Controlling which users can access mailboxes", "correct": True, "rationale": "Correct. Managing accounts, identities, and access is always the customer's responsibility, even in SaaS."},
            {"id": "b", "text": "Patching the email server operating system", "correct": False, "rationale": "Incorrect. In SaaS, the provider manages the operating system and the application."},
            {"id": "c", "text": "Upgrading the email application to new versions", "correct": False, "rationale": "Incorrect. The SaaS provider upgrades and maintains the application."},
            {"id": "d", "text": "Replacing failed hard drives in the datacenter", "correct": False, "rationale": "Incorrect. Physical hardware is always the provider's responsibility."},
        ],
        "explanation": "Even with SaaS, the customer still manages data, devices, and accounts and identities, including who can access the service.",
    },
    {
        "id": "az1-018",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "Which two tasks are the responsibility of the cloud provider in a PaaS deployment? Select two.",
        "options": [
            {"id": "a", "text": "Patching the operating system", "correct": True, "rationale": "Correct. In PaaS, the provider manages and patches the operating system."},
            {"id": "b", "text": "Maintaining the physical network in the datacenter", "correct": True, "rationale": "Correct. Physical infrastructure is always maintained by the provider."},
            {"id": "c", "text": "Managing the customer's data", "correct": False, "rationale": "Incorrect. Data is always the customer's responsibility."},
            {"id": "d", "text": "Managing the customer's user accounts", "correct": False, "rationale": "Incorrect. Accounts and identities are always the customer's responsibility."},
        ],
        "explanation": "In PaaS, the provider handles physical infrastructure and the operating system, while the customer keeps responsibility for data, accounts, and applications.",
    },
    {
        "id": "az1-019",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "What is the main purpose of the shared responsibility model?",
        "options": [
            {"id": "a", "text": "To clarify which security and management tasks are handled by the provider and which are handled by the customer", "correct": True, "rationale": "Correct. The model defines the division of responsibilities so nothing is left unmanaged."},
            {"id": "b", "text": "To determine how much each customer pays for cloud services", "correct": False, "rationale": "Incorrect. Pricing is defined by the consumption-based model, not the shared responsibility model."},
            {"id": "c", "text": "To split the cost of hardware between multiple customers", "correct": False, "rationale": "Incorrect. The model concerns responsibilities, not cost sharing between customers."},
            {"id": "d", "text": "To assign blame after a security breach", "correct": False, "rationale": "Incorrect. The model is a planning framework for dividing tasks, not a blame-assignment process."},
        ],
        "explanation": "The shared responsibility model clarifies which tasks belong to the cloud provider and which belong to the customer, depending on the service type.",
    },
    {
        "id": "az1-020",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "In the shared responsibility model, how is responsibility for network controls handled in a PaaS deployment?",
        "options": [
            {"id": "a", "text": "It is shared between the customer and the cloud provider", "correct": True, "rationale": "Correct. In PaaS, responsibility for network controls and applications varies by service and is shared between customer and provider."},
            {"id": "b", "text": "It belongs entirely to the customer", "correct": False, "rationale": "Incorrect. Full customer responsibility for network controls applies to on-premises and IaaS, not PaaS."},
            {"id": "c", "text": "It belongs entirely to the cloud provider", "correct": False, "rationale": "Incorrect. Full provider responsibility for network controls applies to SaaS, not PaaS."},
            {"id": "d", "text": "Network controls do not exist in PaaS deployments", "correct": False, "rationale": "Incorrect. PaaS services still have configurable network controls, such as access restrictions and firewall rules."},
        ],
        "explanation": "For PaaS, responsibilities such as network controls, applications, and identity infrastructure are shared between the customer and the provider.",
    },
    # ------------------------------------------------------------------
    # Cloud deployment models (objective 1.1)
    # ------------------------------------------------------------------
    {
        "id": "az1-021",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which cloud deployment model combines a public cloud with a private cloud or on-premises infrastructure?",
        "options": [
            {"id": "a", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. A hybrid cloud connects a public cloud with a private cloud or on-premises environment so resources can be used across both."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. A public cloud consists only of provider-hosted resources available to the general public."},
            {"id": "c", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is used by a single organization and does not, by itself, include a public cloud."},
            {"id": "d", "text": "Community cloud", "correct": False, "rationale": "Incorrect. A community cloud is shared by organizations with common concerns; it is not a combination of public and private clouds."},
        ],
        "explanation": "A hybrid cloud combines public cloud services with private cloud or on-premises resources, letting workloads and data move between the two.",
    },
    {
        "id": "az1-022",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which of the following describes a public cloud?",
        "options": [
            {"id": "a", "text": "Cloud services owned and operated by a third-party provider and made available to anyone over the internet", "correct": True, "rationale": "Correct. In a public cloud, a provider such as Microsoft owns the infrastructure and offers services to the general public."},
            {"id": "b", "text": "A cloud environment used exclusively by a single organization", "correct": False, "rationale": "Incorrect. Exclusive use by one organization describes a private cloud."},
            {"id": "c", "text": "A combination of on-premises infrastructure and provider-hosted services", "correct": False, "rationale": "Incorrect. Combining on-premises and provider-hosted resources describes a hybrid cloud."},
            {"id": "d", "text": "Any cloud service that is free of charge", "correct": False, "rationale": "Incorrect. Public refers to who can access the services, not to their price."},
        ],
        "explanation": "A public cloud is owned by a cloud provider and offers resources over the internet to anyone who wants to purchase them.",
    },
    {
        "id": "az1-023",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which of the following describes a private cloud?",
        "options": [
            {"id": "a", "text": "A cloud environment used exclusively by a single organization", "correct": True, "rationale": "Correct. A private cloud delivers cloud services that are dedicated to one organization."},
            {"id": "b", "text": "Cloud services available to the general public over the internet", "correct": False, "rationale": "Incorrect. Services available to anyone describe a public cloud."},
            {"id": "c", "text": "A model in which workloads run partly on-premises and partly in a public cloud", "correct": False, "rationale": "Incorrect. Splitting workloads between environments describes a hybrid cloud."},
            {"id": "d", "text": "A cloud service that stores only confidential data", "correct": False, "rationale": "Incorrect. A private cloud is defined by who uses it, not by the classification of the data it stores."},
        ],
        "explanation": "A private cloud provides cloud services that are used exclusively by a single organization, whether hosted in its own datacenter or by a third party.",
    },
    {
        "id": "az1-024",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A private cloud must be physically located in the organization's own datacenter. Is this statement true?",
        "options": [
            {"id": "a", "text": "No, a private cloud can also be hosted by a third party", "correct": True, "rationale": "Correct. A private cloud is defined by exclusive use, not by location; a third party can host it in an offsite datacenter."},
            {"id": "b", "text": "Yes, a private cloud always runs on the organization's own premises", "correct": False, "rationale": "Incorrect. Location does not define a private cloud; exclusive use by one organization does."},
            {"id": "c", "text": "Yes, but only if the organization has fewer than two datacenters", "correct": False, "rationale": "Incorrect. The number of datacenters an organization owns has nothing to do with the definition of a private cloud."},
        ],
        "explanation": "A private cloud can run in an organization's own datacenter or be hosted offsite by a third-party provider; what matters is that a single organization uses it exclusively.",
    },
    {
        "id": "az1-025",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A regulation requires your company to keep certain customer records on-premises, but you want to run your public website in the cloud. Which deployment model should you use?",
        "options": [
            {"id": "a", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. A hybrid cloud lets you keep regulated data on-premises while running other workloads in the public cloud."},
            {"id": "b", "text": "Public cloud only", "correct": False, "rationale": "Incorrect. A public-cloud-only approach would not satisfy the requirement to keep some records on-premises."},
            {"id": "c", "text": "Private cloud only", "correct": False, "rationale": "Incorrect. A private-cloud-only approach would not use the public cloud for the website as intended."},
            {"id": "d", "text": "Community cloud", "correct": False, "rationale": "Incorrect. A community cloud serves organizations with shared concerns and does not address this split between on-premises and public cloud."},
        ],
        "explanation": "Hybrid cloud is the right fit when some workloads or data must remain on-premises while others run in the public cloud.",
    },
    {
        "id": "az1-026",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Your company wants to avoid purchasing hardware and wants the cloud provider to maintain all infrastructure. Which deployment model should you use?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": True, "rationale": "Correct. In a public cloud, the provider owns and maintains all hardware, and the customer pays only for what it uses."},
            {"id": "b", "text": "Private cloud hosted in your own datacenter", "correct": False, "rationale": "Incorrect. A self-hosted private cloud requires the organization to purchase and maintain its own hardware."},
            {"id": "c", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. A hybrid cloud still includes an on-premises or private component that the organization must maintain."},
            {"id": "d", "text": "On-premises virtualization", "correct": False, "rationale": "Incorrect. On-premises virtualization requires buying and maintaining your own servers."},
        ],
        "explanation": "The public cloud removes the need for the customer to buy or maintain physical infrastructure.",
    },
    {
        "id": "az1-027",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Your on-premises datacenter handles normal workloads, but you want to use public cloud capacity only during seasonal demand peaks. Which deployment model does this describe?",
        "options": [
            {"id": "a", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. Bursting from on-premises infrastructure into the public cloud during peaks is a classic hybrid cloud scenario."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. A public-only model would run all workloads in the cloud, not just peak overflow."},
            {"id": "c", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private-only model would not use public cloud capacity at all."},
            {"id": "d", "text": "Multicloud", "correct": False, "rationale": "Incorrect. Multicloud means using multiple public cloud providers, which is not what this scenario describes."},
        ],
        "explanation": "Using public cloud resources to supplement on-premises capacity during demand spikes, sometimes called cloud bursting, is a hybrid cloud use case.",
    },
    {
        "id": "az1-028",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_response",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which two statements about the public cloud are true? Select two.",
        "options": [
            {"id": "a", "text": "The cloud provider owns and maintains the hardware", "correct": True, "rationale": "Correct. In a public cloud, the provider is responsible for purchasing and maintaining all physical infrastructure."},
            {"id": "b", "text": "Services are available to anyone who wants to purchase them over the internet", "correct": True, "rationale": "Correct. Public cloud services are offered to the general public over the internet."},
            {"id": "c", "text": "The customer must buy the physical servers that run its workloads", "correct": False, "rationale": "Incorrect. Customers rent capacity in a public cloud; they never buy the underlying servers."},
            {"id": "d", "text": "Only one organization can use a public cloud at a time", "correct": False, "rationale": "Incorrect. Public clouds serve many customers on shared infrastructure; exclusive use describes a private cloud."},
        ],
        "explanation": "In a public cloud, the provider owns the infrastructure, many customers share it, and anyone can purchase services over the internet.",
    },
    {
        "id": "az1-029",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which cloud deployment model gives an organization the greatest control over its resources and hardware?",
        "options": [
            {"id": "a", "text": "Private cloud", "correct": True, "rationale": "Correct. A private cloud is dedicated to one organization, giving it the most control over hardware, security, and configuration."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. In a public cloud, the provider controls the hardware and the underlying platform."},
            {"id": "c", "text": "SaaS", "correct": False, "rationale": "Incorrect. SaaS is a service type, not a deployment model, and it offers the least control."},
            {"id": "d", "text": "Community cloud", "correct": False, "rationale": "Incorrect. A community cloud is shared among several organizations, so no single organization has full control."},
        ],
        "explanation": "A private cloud offers the most control because the environment is dedicated to a single organization.",
    },
    {
        "id": "az1-030",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A government agency requires that its workloads run on infrastructure dedicated solely to the agency because of strict data control requirements. Which deployment model should it use?",
        "options": [
            {"id": "a", "text": "Private cloud", "correct": True, "rationale": "Correct. A private cloud provides dedicated infrastructure for a single organization, which satisfies strict control requirements."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. Public cloud infrastructure is shared among many customers, which conflicts with the dedicated-infrastructure requirement."},
            {"id": "c", "text": "Multicloud", "correct": False, "rationale": "Incorrect. Multicloud uses multiple public providers and does not provide dedicated infrastructure."},
            {"id": "d", "text": "SaaS", "correct": False, "rationale": "Incorrect. SaaS is a service type delivered from shared infrastructure, not a deployment model with dedicated hardware."},
        ],
        "explanation": "Organizations with strict regulatory or data control requirements often choose a private cloud because the infrastructure is dedicated to them alone.",
    },
    {
        "id": "az1-031",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "In which cloud deployment model do multiple organizations share the same physical infrastructure managed by the provider?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": True, "rationale": "Correct. Public cloud infrastructure is multi-tenant; many customers share the provider's hardware while remaining logically isolated."},
            {"id": "b", "text": "Private cloud", "correct": False, "rationale": "Incorrect. Private cloud infrastructure is dedicated to a single organization."},
            {"id": "c", "text": "On-premises datacenter", "correct": False, "rationale": "Incorrect. An on-premises datacenter is owned and used by one organization and is not a cloud deployment model."},
            {"id": "d", "text": "Hosted desktop environment", "correct": False, "rationale": "Incorrect. A hosted desktop is a service offering, not a cloud deployment model."},
        ],
        "explanation": "Public clouds are multi-tenant: the provider's infrastructure is shared by many customers with logical isolation between them.",
    },
    {
        "id": "az1-032",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Your company plans to build its own private cloud in its datacenter. Which financial impact should the company expect compared to using a public cloud?",
        "options": [
            {"id": "a", "text": "Higher upfront capital costs for hardware", "correct": True, "rationale": "Correct. Building a private cloud requires purchasing servers, storage, and networking upfront, which is capital expenditure."},
            {"id": "b", "text": "No hardware costs at all", "correct": False, "rationale": "Incorrect. Avoiding hardware costs is a benefit of the public cloud, not a self-hosted private cloud."},
            {"id": "c", "text": "Pay-as-you-go billing from a provider", "correct": False, "rationale": "Incorrect. Pay-as-you-go billing applies to public cloud services, not to hardware the company buys itself."},
            {"id": "d", "text": "Automatic and unlimited capacity on demand", "correct": False, "rationale": "Incorrect. A private cloud is limited by the hardware the organization purchases; near-unlimited capacity is a public cloud trait."},
        ],
        "explanation": "A self-hosted private cloud requires significant upfront capital expenditure and offers only as much capacity as the purchased hardware provides.",
    },
    {
        "id": "az1-033",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A company keeps a legacy database on-premises and runs its new customer-facing web app in Azure. The web app queries the on-premises database. Which deployment model is the company using?",
        "options": [
            {"id": "a", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. Connecting on-premises resources with public cloud resources so they work together is a hybrid cloud."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. The environment includes on-premises infrastructure, so it is not purely public cloud."},
            {"id": "c", "text": "Private cloud", "correct": False, "rationale": "Incorrect. The web app runs in the public cloud, so this is not a private-only environment."},
            {"id": "d", "text": "Multicloud", "correct": False, "rationale": "Incorrect. Only one public cloud provider is involved; multicloud requires more than one."},
        ],
        "explanation": "Running workloads across both on-premises infrastructure and a public cloud, with connectivity between them, is a hybrid cloud deployment.",
    },
    {
        "id": "az1-034",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "You plan to run cloud services on hardware in your own datacenter while managing those resources with the same tools as your public cloud resources. Which deployment model does this describe?",
        "options": [
            {"id": "a", "text": "Hybrid cloud", "correct": True, "rationale": "Correct. Extending public cloud services and management tools to on-premises hardware is a hybrid cloud approach."},
            {"id": "b", "text": "Public cloud", "correct": False, "rationale": "Incorrect. Running services on your own on-premises hardware is not a public cloud deployment."},
            {"id": "c", "text": "Community cloud", "correct": False, "rationale": "Incorrect. A community cloud is shared among multiple organizations, which is not described here."},
            {"id": "d", "text": "Multicloud", "correct": False, "rationale": "Incorrect. Multicloud refers to using services from more than one public cloud provider."},
        ],
        "explanation": "Solutions that bring cloud services and unified management to on-premises hardware, such as Azure Arc and Azure Stack, support hybrid cloud deployments.",
    },
    {
        "id": "az1-035",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which deployment model makes cloud resources available to the general public over the internet?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": True, "rationale": "Correct. Public cloud resources can be purchased and used by anyone over the internet."},
            {"id": "b", "text": "Private cloud", "correct": False, "rationale": "Incorrect. Private cloud resources are restricted to a single organization."},
            {"id": "c", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. Hybrid describes combining public and private environments, not general public availability."},
            {"id": "d", "text": "On-premises infrastructure", "correct": False, "rationale": "Incorrect. On-premises infrastructure serves only the organization that owns it."},
        ],
        "explanation": "The public cloud model offers services over the public internet to anyone who wants to use or purchase them.",
    },
    {
        "id": "az1-036",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A startup with no existing IT infrastructure wants to launch its product quickly with minimal upfront investment. Which cloud deployment model should it choose?",
        "options": [
            {"id": "a", "text": "Public cloud", "correct": True, "rationale": "Correct. The public cloud requires no hardware purchase and lets the startup deploy quickly and pay as it goes."},
            {"id": "b", "text": "Private cloud in its own datacenter", "correct": False, "rationale": "Incorrect. Building a private cloud requires significant upfront investment in hardware and facilities."},
            {"id": "c", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. The startup has no on-premises infrastructure to combine with a public cloud, so hybrid adds cost without benefit."},
            {"id": "d", "text": "An on-premises server room", "correct": False, "rationale": "Incorrect. Buying and operating its own servers is the opposite of minimal upfront investment."},
        ],
        "explanation": "The public cloud suits organizations that want speed and low upfront cost, since the provider supplies all the infrastructure.",
    },
    {
        "id": "az1-037",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "In a private cloud hosted in your organization's own datacenter, who is responsible for purchasing and maintaining the hardware?",
        "options": [
            {"id": "a", "text": "Your organization", "correct": True, "rationale": "Correct. In a self-hosted private cloud, the organization buys, operates, and maintains its own hardware."},
            {"id": "b", "text": "A public cloud provider", "correct": False, "rationale": "Incorrect. Public cloud providers maintain hardware only for their own public cloud services."},
            {"id": "c", "text": "The organization's internet service provider", "correct": False, "rationale": "Incorrect. ISPs provide connectivity, not datacenter hardware."},
            {"id": "d", "text": "No one; private clouds do not use physical hardware", "correct": False, "rationale": "Incorrect. Every cloud, private or public, runs on physical hardware somewhere."},
        ],
        "explanation": "With a self-hosted private cloud, the organization carries the cost and effort of buying and maintaining the underlying infrastructure.",
    },
    {
        "id": "az1-038",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which two are valid reasons for an organization to choose a hybrid cloud? Select two.",
        "options": [
            {"id": "a", "text": "It must keep sensitive data on-premises to meet regulatory requirements while using the public cloud for other workloads", "correct": True, "rationale": "Correct. Meeting data residency or regulatory requirements while still using the public cloud is a core hybrid use case."},
            {"id": "b", "text": "It wants to use public cloud capacity to handle demand peaks that exceed on-premises capacity", "correct": True, "rationale": "Correct. Supplementing on-premises capacity with the public cloud during peaks is a classic hybrid scenario."},
            {"id": "c", "text": "It wants to eliminate all on-premises management responsibilities", "correct": False, "rationale": "Incorrect. A hybrid cloud keeps an on-premises component that the organization must still manage; only a full public cloud move removes it."},
            {"id": "d", "text": "It wants a single provider to own all of the hardware", "correct": False, "rationale": "Incorrect. In a hybrid cloud, the organization still owns the private or on-premises hardware."},
        ],
        "explanation": "Hybrid clouds suit organizations that need to keep some workloads or data on-premises while still benefiting from public cloud scale and services.",
    },
    {
        "id": "az1-039",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "A company uses services from both Microsoft Azure and another public cloud provider. What is this approach called?",
        "options": [
            {"id": "a", "text": "Multicloud", "correct": True, "rationale": "Correct. Using two or more public cloud providers is a multicloud approach."},
            {"id": "b", "text": "Hybrid cloud", "correct": False, "rationale": "Incorrect. Hybrid cloud combines public cloud with private or on-premises infrastructure, not two public providers."},
            {"id": "c", "text": "Private cloud", "correct": False, "rationale": "Incorrect. A private cloud is dedicated to a single organization and is not defined by using multiple providers."},
            {"id": "d", "text": "Community cloud", "correct": False, "rationale": "Incorrect. A community cloud is shared infrastructure for organizations with common requirements, not multiple public providers."},
        ],
        "explanation": "Multicloud means an organization uses services from more than one public cloud provider at the same time.",
    },
    {
        "id": "az1-040",
        "domain": 1,
        "objective": "1.1",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Which statement about cloud deployment models is true?",
        "options": [
            {"id": "a", "text": "A private cloud can be hosted offsite by a third party while remaining dedicated to one organization", "correct": True, "rationale": "Correct. A private cloud is defined by exclusive use, so a third party can host it in its own datacenter for a single customer."},
            {"id": "b", "text": "A hybrid cloud uses services from at least two public cloud providers", "correct": False, "rationale": "Incorrect. Using multiple public providers is multicloud; hybrid combines public with private or on-premises."},
            {"id": "c", "text": "A public cloud requires the customer to maintain the hypervisor layer", "correct": False, "rationale": "Incorrect. The provider maintains the hypervisor and all physical infrastructure in a public cloud."},
            {"id": "d", "text": "A private cloud always costs less than a public cloud", "correct": False, "rationale": "Incorrect. Private clouds usually involve significant hardware and staffing costs and are often more expensive."},
        ],
        "explanation": "Private cloud is about exclusive use by one organization, not about location; it may be hosted internally or by a third party.",
    },
]
