"""AZ-900 Domain 3 question bank (set C): tools for managing and deploying
Azure resources (objective 3.3) and monitoring tools (objective 3.4), plus
SLAs and the Azure service lifecycle.

Covers the Azure portal, Cloud Shell, Azure CLI, Azure PowerShell, the Azure
mobile app, Azure Arc, infrastructure as code and ARM templates/Bicep, Azure
Advisor, Azure Service Health, Azure Monitor (Log Analytics, alerts, action
groups, Application Insights), and service level agreements and lifecycle.
Ids: az3c-001 .. az3c-115.
"""

QUESTIONS = [
    {
        "id": "az3c-001",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You need to run Azure CLI commands from a web browser without installing any tools on your local computer. What should you use?",
        "options": [
            {"id": "a", "text": "Azure Cloud Shell", "correct": True, "rationale": "Correct. Cloud Shell is a browser-based shell that comes with the Azure CLI (and Azure PowerShell) preinstalled, so nothing needs to be installed locally."},
            {"id": "b", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is for phones and tablets; the scenario asks for a browser-based solution on a computer."},
            {"id": "c", "text": "A locally installed Azure CLI", "correct": False, "rationale": "Incorrect. Installing the CLI locally violates the requirement to avoid installing anything."},
            {"id": "d", "text": "Azure Resource Manager", "correct": False, "rationale": "Incorrect. Resource Manager is the management layer that processes requests; it is not an interactive command-line environment."},
        ],
        "explanation": "Azure Cloud Shell provides a browser-based command line with the Azure CLI and Azure PowerShell preinstalled, requiring no local installation.",
    },
    {
        "id": "az3c-002",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Select the answer that correctly completes the sentence.\n\n___ is a web-based, unified console that provides a graphical user interface for creating, managing, and monitoring Azure resources.",
        "options": [
            {"id": "a", "text": "The Azure portal", "correct": True, "rationale": "Correct. The Azure portal is the web-based graphical console for managing everything in Azure."},
            {"id": "b", "text": "Azure PowerShell", "correct": False, "rationale": "Incorrect. Azure PowerShell is a command-line tool based on cmdlets, not a graphical console."},
            {"id": "c", "text": "The Azure CLI", "correct": False, "rationale": "Incorrect. The Azure CLI is a text-based command-line tool, not a graphical interface."},
            {"id": "d", "text": "Azure Monitor", "correct": False, "rationale": "Incorrect. Azure Monitor collects and analyzes telemetry; it is not the general-purpose management console."},
        ],
        "explanation": "The Azure portal is the browser-based graphical user interface for building, managing, and monitoring Azure resources.",
    },
    {
        "id": "az3c-003",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which Azure management tool uses commands that begin with az, such as az vm list?",
        "options": [
            {"id": "a", "text": "The Azure CLI", "correct": True, "rationale": "Correct. Azure CLI commands all start with az, for example az vm list or az group create."},
            {"id": "b", "text": "Azure PowerShell", "correct": False, "rationale": "Incorrect. Azure PowerShell uses Verb-Noun cmdlets such as Get-AzVM, not az commands."},
            {"id": "c", "text": "The Azure portal", "correct": False, "rationale": "Incorrect. The portal is a graphical interface and does not use typed az commands."},
            {"id": "d", "text": "Azure Advisor", "correct": False, "rationale": "Incorrect. Advisor is a recommendation service, not a command-line tool."},
        ],
        "explanation": "The Azure CLI is the cross-platform command-line tool whose commands all begin with az.",
    },
    {
        "id": "az3c-004",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which Azure management tool uses Verb-Noun cmdlets such as Get-AzVM and New-AzStorageAccount?",
        "options": [
            {"id": "a", "text": "Azure PowerShell", "correct": True, "rationale": "Correct. Azure PowerShell provides the Az module, whose cmdlets follow the PowerShell Verb-Noun naming pattern."},
            {"id": "b", "text": "The Azure CLI", "correct": False, "rationale": "Incorrect. The Azure CLI uses az commands, not Verb-Noun cmdlets."},
            {"id": "c", "text": "Azure Cloud Shell", "correct": False, "rationale": "Incorrect. Cloud Shell is the browser-based environment where tools run; the cmdlets themselves belong to Azure PowerShell."},
            {"id": "d", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is a graphical application for phones and tablets."},
        ],
        "explanation": "Azure PowerShell exposes Azure management through Az module cmdlets that follow PowerShell's Verb-Noun convention.",
    },
    {
        "id": "az3c-005",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Your team must create the same set of test resources every week and wants the process to be fast and repeatable with minimal chance of human error. Team members primarily work in Bash on Linux. What should you recommend?",
        "options": [
            {"id": "a", "text": "A script that uses the Azure CLI", "correct": True, "rationale": "Correct. The Azure CLI is cross-platform and Bash-friendly, and scripting the task makes it repeatable and consistent."},
            {"id": "b", "text": "Creating the resources manually in the Azure portal each week", "correct": False, "rationale": "Incorrect. Manual portal steps are slower and more error-prone when repeated frequently."},
            {"id": "c", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is designed for on-the-go monitoring and quick actions, not repeatable weekly provisioning."},
            {"id": "d", "text": "Emailing Azure support to create the resources", "correct": False, "rationale": "Incorrect. Azure support does not provision customer resources on request; customers manage their own resources."},
        ],
        "explanation": "For repeatable tasks, scripting beats manual portal work, and the Azure CLI is the natural fit for a Bash-oriented Linux team.",
    },
    {
        "id": "az3c-006",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "What does Azure Cloud Shell use to persist your files, such as scripts, between sessions?",
        "options": [
            {"id": "a", "text": "An Azure file share", "correct": True, "rationale": "Correct. Cloud Shell mounts an Azure Files share so your files are kept between sessions."},
            {"id": "b", "text": "The local disk of your computer", "correct": False, "rationale": "Incorrect. Cloud Shell runs in Azure, not on your local computer, so it does not store session files on your local disk."},
            {"id": "c", "text": "Browser cookies", "correct": False, "rationale": "Incorrect. Cookies store small pieces of web state, not scripts and files."},
            {"id": "d", "text": "Nothing; all files are deleted when the session ends", "correct": False, "rationale": "Incorrect. Files stored in the mounted file share persist across Cloud Shell sessions."},
        ],
        "explanation": "Cloud Shell attaches an Azure Files share to persist your scripts and files across browser sessions.",
    },
    {
        "id": "az3c-007",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You save a deployment script in Azure Cloud Shell, close the browser, and open Cloud Shell again the next day from a different computer. Is the script still available?",
        "options": [
            {"id": "a", "text": "Yes, because Cloud Shell persists files in an Azure file share associated with your account", "correct": True, "rationale": "Correct. The persistent file share travels with your Cloud Shell profile, so files are available from any browser or device you sign in from."},
            {"id": "b", "text": "No, because Cloud Shell deletes all files when the browser closes", "correct": False, "rationale": "Incorrect. Files placed in the mounted file share are retained between sessions."},
            {"id": "c", "text": "Only if the second computer has the Azure CLI installed", "correct": False, "rationale": "Incorrect. Cloud Shell needs no local installation; its tools and your files live in Azure."},
            {"id": "d", "text": "Only if both computers are on the same network", "correct": False, "rationale": "Incorrect. Cloud Shell is accessed over the internet; the client network does not affect file persistence."},
        ],
        "explanation": "Because Cloud Shell stores your files in an Azure Files share tied to your account, they follow you across devices and sessions.",
    },
    {
        "id": "az3c-008",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "An administrator who uses a MacBook wants to manage Azure resources from the local terminal by typing commands. Which tool can the administrator install?",
        "options": [
            {"id": "a", "text": "The Azure CLI", "correct": True, "rationale": "Correct. The Azure CLI is cross-platform and installs on macOS, Linux, and Windows."},
            {"id": "b", "text": "The Azure portal desktop client for macOS", "correct": False, "rationale": "Incorrect. The Azure portal is a website; there is no installable macOS portal client required."},
            {"id": "c", "text": "Hyper-V Manager", "correct": False, "rationale": "Incorrect. Hyper-V Manager manages on-premises Hyper-V hosts, not Azure resources, and is a Windows tool."},
            {"id": "d", "text": "Microsoft Management Console (MMC)", "correct": False, "rationale": "Incorrect. MMC is a Windows administrative framework and is not used to manage Azure from macOS."},
        ],
        "explanation": "The Azure CLI runs on Windows, macOS, and Linux, making it a good choice for command-line management from a Mac.",
    },
    {
        "id": "az3c-009",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Your Windows administrators already write PowerShell scripts to manage on-premises servers and want to reuse those skills to automate Azure management. What should they install?",
        "options": [
            {"id": "a", "text": "The Az PowerShell module", "correct": True, "rationale": "Correct. The Az module adds Azure management cmdlets to PowerShell, letting existing PowerShell skills carry over directly."},
            {"id": "b", "text": "A Linux virtual machine", "correct": False, "rationale": "Incorrect. A VM is not needed; the Az module installs into their existing PowerShell environment."},
            {"id": "c", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is for quick management from a phone, not PowerShell-based automation."},
            {"id": "d", "text": "Azure DevTest Labs", "correct": False, "rationale": "Incorrect. DevTest Labs manages development and test environments; it is not the PowerShell tooling for Azure."},
        ],
        "explanation": "Administrators comfortable with PowerShell should use Azure PowerShell (the Az module) so their scripting experience transfers to Azure.",
    },
    {
        "id": "az3c-010",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "While away from the office with only a smartphone, you want to check active alerts and view the status of your Azure virtual machines. What should you use?",
        "options": [
            {"id": "a", "text": "The Azure mobile app", "correct": True, "rationale": "Correct. The Azure mobile app lets you monitor resource health, view alerts, and take quick actions from iOS and Android devices."},
            {"id": "b", "text": "Azure Migrate", "correct": False, "rationale": "Incorrect. Azure Migrate assesses and migrates on-premises workloads to Azure; it is not a mobile monitoring tool."},
            {"id": "c", "text": "Azure ExpressRoute", "correct": False, "rationale": "Incorrect. ExpressRoute is a private network connection to Azure, not a management application."},
            {"id": "d", "text": "The Azure CLI installed on a desktop computer", "correct": False, "rationale": "Incorrect. The scenario specifies you have only a smartphone available."},
        ],
        "explanation": "The Azure mobile app provides on-the-go visibility into alerts and resource status from a phone or tablet.",
    },
    {
        "id": "az3c-011",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Can you run Azure CLI or Azure PowerShell commands from the Azure mobile app?",
        "options": [
            {"id": "a", "text": "Yes, the mobile app includes access to Azure Cloud Shell", "correct": True, "rationale": "Correct. The Azure mobile app can open Cloud Shell, so you can run Azure CLI and Azure PowerShell commands from a phone."},
            {"id": "b", "text": "No, the mobile app is read-only", "correct": False, "rationale": "Incorrect. The mobile app supports management actions such as restarting resources and also provides Cloud Shell access."},
            {"id": "c", "text": "Only if the phone has the Azure CLI installed locally", "correct": False, "rationale": "Incorrect. Cloud Shell runs in Azure, so no local CLI installation is needed on the phone."},
            {"id": "d", "text": "Only on tablets, not on phones", "correct": False, "rationale": "Incorrect. Cloud Shell access in the mobile app is not restricted to tablets."},
        ],
        "explanation": "The Azure mobile app includes Cloud Shell, allowing command-line management of Azure resources directly from a mobile device.",
    },
    {
        "id": "az3c-012",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Select the answer that correctly completes the sentence.\n\nWhen you start Azure Cloud Shell, you can choose between a Bash experience and a ___ experience.",
        "options": [
            {"id": "a", "text": "PowerShell", "correct": True, "rationale": "Correct. Cloud Shell offers a choice of Bash or PowerShell as its shell experience."},
            {"id": "b", "text": "Command Prompt (cmd.exe)", "correct": False, "rationale": "Incorrect. The classic Windows Command Prompt is not one of the Cloud Shell experiences."},
            {"id": "c", "text": "Python REPL", "correct": False, "rationale": "Incorrect. Although Python is available inside Cloud Shell, the shell experiences offered are Bash and PowerShell."},
            {"id": "d", "text": "graphical desktop", "correct": False, "rationale": "Incorrect. Cloud Shell is a command-line environment, not a graphical desktop."},
        ],
        "explanation": "Azure Cloud Shell provides two shell experiences: Bash and PowerShell.",
    },
    {
        "id": "az3c-013",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "A new administrator wants to explore an unfamiliar Azure service, browse its configuration pages, and try a one-off change while seeing all available settings visually. Which tool best fits this task?",
        "options": [
            {"id": "a", "text": "The Azure portal", "correct": True, "rationale": "Correct. The portal's graphical interface is ideal for exploring options and performing one-off tasks visually."},
            {"id": "b", "text": "An Azure CLI script", "correct": False, "rationale": "Incorrect. Scripts excel at repeatable automation, but they require knowing the commands in advance and do not aid visual discovery."},
            {"id": "c", "text": "An ARM template", "correct": False, "rationale": "Incorrect. Templates are for repeatable declarative deployments, not interactive exploration of a service's settings."},
            {"id": "d", "text": "A REST API call", "correct": False, "rationale": "Incorrect. Direct REST calls are the least discoverable option for someone learning a service."},
        ],
        "explanation": "The portal is best for visual exploration and one-off tasks, while command-line tools and templates are better for repeatable automation.",
    },
    {
        "id": "az3c-014",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "A colleague sends you the command az group create --name RG1 --location eastus. Which tool is this command written for?",
        "options": [
            {"id": "a", "text": "The Azure CLI", "correct": True, "rationale": "Correct. Commands starting with az belong to the Azure CLI."},
            {"id": "b", "text": "Azure PowerShell", "correct": False, "rationale": "Incorrect. The Azure PowerShell equivalent would be the New-AzResourceGroup cmdlet."},
            {"id": "c", "text": "The Azure portal", "correct": False, "rationale": "Incorrect. The portal uses a graphical interface rather than typed commands."},
            {"id": "d", "text": "Azure Resource Mover", "correct": False, "rationale": "Incorrect. Resource Mover relocates resources between regions; it is not the tool that runs az commands."},
        ],
        "explanation": "The az prefix identifies an Azure CLI command; this one creates a resource group named RG1 in the East US region.",
    },
    {
        "id": "az3c-015",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You see the command New-AzVM used in a deployment script. Which management tool runs this command?",
        "options": [
            {"id": "a", "text": "Azure PowerShell", "correct": True, "rationale": "Correct. New-AzVM is a cmdlet from the Az PowerShell module."},
            {"id": "b", "text": "The Azure CLI", "correct": False, "rationale": "Incorrect. The Azure CLI equivalent would be az vm create."},
            {"id": "c", "text": "Bash", "correct": False, "rationale": "Incorrect. Bash by itself has no Azure cmdlets; Verb-Noun cmdlets are a PowerShell convention."},
            {"id": "d", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is a graphical application, though it can host Cloud Shell where such cmdlets could run."},
        ],
        "explanation": "Verb-Noun cmdlets such as New-AzVM come from the Az module and run in Azure PowerShell.",
    },
    {
        "id": "az3c-016",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which statement about installing Azure command-line tools locally is true?",
        "options": [
            {"id": "a", "text": "Both the Azure CLI and Azure PowerShell can be installed on Windows, macOS, and Linux", "correct": True, "rationale": "Correct. Both tools are cross-platform; Azure PowerShell runs on PowerShell 7, which is available on all three operating systems."},
            {"id": "b", "text": "The Azure CLI can be installed only on Linux", "correct": False, "rationale": "Incorrect. The Azure CLI also installs on Windows and macOS."},
            {"id": "c", "text": "Azure PowerShell can be installed only on Windows", "correct": False, "rationale": "Incorrect. The Az module runs on cross-platform PowerShell, including macOS and Linux."},
            {"id": "d", "text": "Neither tool can be installed locally; they run only in Cloud Shell", "correct": False, "rationale": "Incorrect. Both tools can be installed locally; Cloud Shell is simply a convenient hosted alternative."},
        ],
        "explanation": "Both the Azure CLI and Azure PowerShell are cross-platform and can be installed on Windows, macOS, and Linux, or used preinstalled in Cloud Shell.",
    },
    {
        "id": "az3c-017",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which two statements about Azure Cloud Shell are true? Each correct selection is worth one point.",
        "options": [
            {"id": "a", "text": "It requires no installation of tools on your local computer", "correct": True, "rationale": "Correct. Cloud Shell runs in the browser with the Azure CLI, Azure PowerShell, and other tools already installed."},
            {"id": "b", "text": "It can persist your files by using an Azure file share", "correct": True, "rationale": "Correct. Cloud Shell mounts an Azure Files share so scripts and files survive between sessions."},
            {"id": "c", "text": "It can run only Windows-specific desktop applications", "correct": False, "rationale": "Incorrect. Cloud Shell is a command-line environment; it does not run graphical desktop applications."},
            {"id": "d", "text": "It requires a site-to-site VPN to your on-premises network", "correct": False, "rationale": "Incorrect. Cloud Shell is reached over standard HTTPS from a browser; no VPN is required."},
        ],
        "explanation": "Cloud Shell is a zero-install, browser-based shell whose files persist in an Azure Files share.",
    },
    {
        "id": "az3c-018",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Your operations team wants a single portal page that shows the specific charts, resource lists, and shortcuts they care about every morning. What should they create in the Azure portal?",
        "options": [
            {"id": "a", "text": "A custom dashboard", "correct": True, "rationale": "Correct. Azure portal dashboards can be customized with tiles for charts, resources, and shortcuts, and can be shared with a team."},
            {"id": "b", "text": "A new subscription", "correct": False, "rationale": "Incorrect. Subscriptions are billing and management boundaries, not visual layouts."},
            {"id": "c", "text": "A management group", "correct": False, "rationale": "Incorrect. Management groups organize subscriptions for governance; they do not present a customized monitoring page."},
            {"id": "d", "text": "A resource lock", "correct": False, "rationale": "Incorrect. Locks prevent accidental deletion or changes; they have nothing to do with portal layout."},
        ],
        "explanation": "Custom dashboards in the Azure portal give teams a tailored, shareable view of the charts and resources they use most.",
    },
    {
        "id": "az3c-019",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "A manager with no scripting experience needs to occasionally review resource configurations and make simple changes by pointing and clicking. Which tool should the manager use?",
        "options": [
            {"id": "a", "text": "The Azure portal", "correct": True, "rationale": "Correct. The portal's graphical interface requires no scripting knowledge."},
            {"id": "b", "text": "The Azure CLI", "correct": False, "rationale": "Incorrect. The CLI requires typing commands, which does not suit a point-and-click preference."},
            {"id": "c", "text": "Azure PowerShell", "correct": False, "rationale": "Incorrect. PowerShell cmdlets require command-line familiarity."},
            {"id": "d", "text": "An ARM template", "correct": False, "rationale": "Incorrect. Authoring JSON templates is a more technical activity than using a graphical console."},
        ],
        "explanation": "The Azure portal is the right choice for users who prefer a graphical, point-and-click management experience.",
    },
    {
        "id": "az3c-020",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "When you open Azure Cloud Shell from the Azure portal, what happens regarding authentication to Azure?",
        "options": [
            {"id": "a", "text": "You are automatically authenticated with the account you used to sign in to the portal", "correct": True, "rationale": "Correct. Cloud Shell sessions are automatically authenticated as the signed-in portal user, so commands run in your context immediately."},
            {"id": "b", "text": "You must create a separate Cloud Shell username and password", "correct": False, "rationale": "Incorrect. Cloud Shell uses your existing Azure sign-in; no separate credentials exist."},
            {"id": "c", "text": "You can run commands anonymously without any authentication", "correct": False, "rationale": "Incorrect. All Azure management operations require an authenticated identity."},
            {"id": "d", "text": "You must paste a certificate into the browser each session", "correct": False, "rationale": "Incorrect. No certificate handling is required; authentication flows from the portal sign-in."},
        ],
        "explanation": "Cloud Shell inherits the identity you signed in to the portal with, so you can run commands immediately without signing in again.",
    },
    {
        "id": "az3c-021",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which two tasks can you perform by using the Azure mobile app? Each correct answer presents a complete solution.",
        "options": [
            {"id": "a", "text": "View the health and metrics of your Azure resources", "correct": True, "rationale": "Correct. The mobile app shows resource status, metrics, and alerts so you can stay informed away from a desk."},
            {"id": "b", "text": "Run commands against your subscription through Cloud Shell", "correct": True, "rationale": "Correct. The mobile app includes Cloud Shell access for running Azure CLI and Azure PowerShell commands."},
            {"id": "c", "text": "Physically replace failed disks in an Azure datacenter", "correct": False, "rationale": "Incorrect. Microsoft manages all physical hardware in its datacenters; customers never service hardware."},
            {"id": "d", "text": "Change the prices Microsoft charges for Azure services", "correct": False, "rationale": "Incorrect. Service pricing is set by Microsoft and cannot be altered by any management tool."},
        ],
        "explanation": "The Azure mobile app supports monitoring resource health and metrics and includes Cloud Shell for running management commands.",
    },
    {
        "id": "az3c-022",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "A nightly maintenance job must stop a group of development virtual machines automatically, with no person involved. Which approach should you use?",
        "options": [
            {"id": "a", "text": "A scheduled Azure PowerShell or Azure CLI script", "correct": True, "rationale": "Correct. Unattended, recurring tasks are best handled by scripts run on a schedule, not interactive tools."},
            {"id": "b", "text": "An administrator signing in to the Azure portal every night", "correct": False, "rationale": "Incorrect. Requiring a person each night is exactly what the automation requirement rules out."},
            {"id": "c", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is an interactive tool for a person, not an unattended automation mechanism."},
            {"id": "d", "text": "The Azure status page", "correct": False, "rationale": "Incorrect. The status page only displays Azure service health; it cannot manage resources."},
        ],
        "explanation": "Command-line tools shine for automation: a scheduled script stops the VMs consistently every night without human involvement.",
    },
    {
        "id": "az3c-023",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You want to browse all resources in a subscription, open each one, and view built-in charts of its recent metrics without typing any commands. Which tool should you use?",
        "options": [
            {"id": "a", "text": "The Azure portal", "correct": True, "rationale": "Correct. The portal lists all resources graphically and shows built-in metric charts on each resource's overview page."},
            {"id": "b", "text": "The Azure CLI", "correct": False, "rationale": "Incorrect. The CLI requires typed commands and outputs text, not interactive charts."},
            {"id": "c", "text": "Azure PowerShell", "correct": False, "rationale": "Incorrect. PowerShell is command-based and does not provide a graphical browsing experience."},
            {"id": "d", "text": "An ARM template", "correct": False, "rationale": "Incorrect. Templates deploy resources; they are not a browsing or visualization tool."},
        ],
        "explanation": "The Azure portal provides graphical browsing of resources and built-in metric charts with no commands required.",
    },
    {
        "id": "az3c-024",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which statement about accessing Azure Cloud Shell is true?",
        "options": [
            {"id": "a", "text": "It can be launched from most modern web browsers, including from the Azure portal", "correct": True, "rationale": "Correct. Cloud Shell runs in modern browsers and can be opened from the portal's toolbar or directly at its own URL."},
            {"id": "b", "text": "It works only in Internet Explorer", "correct": False, "rationale": "Incorrect. Cloud Shell supports modern browsers; it is not tied to a single legacy browser."},
            {"id": "c", "text": "It requires a dedicated physical terminal device", "correct": False, "rationale": "Incorrect. No special hardware is needed; any supported browser works."},
            {"id": "d", "text": "It can be used only from computers joined to a corporate domain", "correct": False, "rationale": "Incorrect. Cloud Shell access depends on your Azure sign-in, not on domain membership of the client computer."},
        ],
        "explanation": "Cloud Shell is browser-based and can be opened from the Azure portal or directly, on any supported modern browser.",
    },
    {
        "id": "az3c-025",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You work from a locked-down kiosk computer where you cannot install software or browser extensions. During a single session you need to run both az commands and Az module cmdlets against your subscription. What should you use?",
        "options": [
            {"id": "a", "text": "Azure Cloud Shell, which has both the Azure CLI and Azure PowerShell preinstalled", "correct": True, "rationale": "Correct. Cloud Shell needs only a browser and includes both the Azure CLI and Azure PowerShell, so both command styles are available in one place."},
            {"id": "b", "text": "Install the Azure CLI and the Az module locally on the kiosk", "correct": False, "rationale": "Incorrect. The kiosk does not permit software installation."},
            {"id": "c", "text": "Use the Azure portal's graphical blades only", "correct": False, "rationale": "Incorrect. The portal GUI does not satisfy the requirement to run az commands and Az cmdlets."},
            {"id": "d", "text": "Request Remote Desktop access to an Azure datacenter host", "correct": False, "rationale": "Incorrect. Customers cannot access Azure's physical hosts; management happens through Azure's public interfaces."},
        ],
        "explanation": "Cloud Shell requires nothing but a browser and ships with both the Azure CLI and Azure PowerShell, covering both command styles from a restricted device.",
    },
    {
        "id": "az3c-026",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Select the answer that correctly completes the sentence.\n\nThe ___ lets you monitor and manage Azure resources from an iOS or Android device.",
        "options": [
            {"id": "a", "text": "Azure mobile app", "correct": True, "rationale": "Correct. The Azure mobile app brings monitoring and quick management actions to phones and tablets."},
            {"id": "b", "text": "Azure Kubernetes Service", "correct": False, "rationale": "Incorrect. AKS is a managed container orchestration service, not a mobile management client."},
            {"id": "c", "text": "Azure Load Balancer", "correct": False, "rationale": "Incorrect. Load Balancer distributes network traffic; it is not a management application."},
            {"id": "d", "text": "Azure Bastion", "correct": False, "rationale": "Incorrect. Bastion provides secure RDP/SSH connectivity to VMs through the portal, not mobile management of Azure."},
        ],
        "explanation": "The Azure mobile app is Microsoft's iOS and Android application for managing Azure on the go.",
    },
    {
        "id": "az3c-027",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which statement correctly compares the Azure CLI and Azure PowerShell?",
        "options": [
            {"id": "a", "text": "Both can manage the same Azure resources; the main difference is command syntax and the scripting ecosystem each fits into", "correct": True, "rationale": "Correct. Both tools call the same underlying management APIs; choosing between them is mostly a matter of syntax preference (az commands versus cmdlets) and existing skills."},
            {"id": "b", "text": "Only Azure PowerShell can create resources; the CLI is read-only", "correct": False, "rationale": "Incorrect. Both tools fully support creating, changing, and deleting resources."},
            {"id": "c", "text": "The Azure CLI works only inside Cloud Shell", "correct": False, "rationale": "Incorrect. The CLI can also be installed locally on Windows, macOS, and Linux."},
            {"id": "d", "text": "Azure PowerShell is required for all Linux administration", "correct": False, "rationale": "Incorrect. Linux administrators frequently prefer the Bash-friendly Azure CLI; neither tool is mandatory."},
        ],
        "explanation": "The CLI and Azure PowerShell offer equivalent management capabilities; teams choose based on familiar syntax and scripting environment.",
    },
    {
        "id": "az3c-028",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "You need to manage Azure resources from a laptop that runs Linux. Which two tools can you install locally on the laptop? Each correct answer presents a complete solution.",
        "options": [
            {"id": "a", "text": "The Azure CLI", "correct": True, "rationale": "Correct. The Azure CLI installs natively on Linux distributions."},
            {"id": "b", "text": "Azure PowerShell (the Az module on PowerShell 7)", "correct": True, "rationale": "Correct. PowerShell 7 is cross-platform, and the Az module runs on it under Linux."},
            {"id": "c", "text": "The Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app targets iOS and Android devices, not Linux laptops."},
            {"id": "d", "text": "Microsoft Endpoint Configuration Manager", "correct": False, "rationale": "Incorrect. Configuration Manager manages client devices and servers; it is not a tool for administering Azure resources from Linux."},
        ],
        "explanation": "Both the Azure CLI and Azure PowerShell are cross-platform and can be installed on a Linux laptop.",
    },
    {
        "id": "az3c-029",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Which statement about the Azure portal is true?",
        "options": [
            {"id": "a", "text": "It provides a graphical interface for managing nearly all Azure services and requires only a web browser", "correct": True, "rationale": "Correct. The portal is a browser-based GUI that covers almost every Azure service without any client installation."},
            {"id": "b", "text": "It must be reinstalled on each computer after every Azure update", "correct": False, "rationale": "Incorrect. The portal is a website; updates happen on Microsoft's side with nothing to install."},
            {"id": "c", "text": "It can be used only by the subscription owner", "correct": False, "rationale": "Incorrect. Any user granted appropriate role-based access can use the portal within their permissions."},
            {"id": "d", "text": "It is the only supported way to create Azure resources", "correct": False, "rationale": "Incorrect. Resources can also be created with the CLI, PowerShell, templates, SDKs, and the REST API."},
        ],
        "explanation": "The Azure portal is a browser-based graphical console for nearly all Azure services; nothing needs to be installed and it is one of several ways to manage resources.",
    },
    {
        "id": "az3c-030",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure portal, CLI, PowerShell, and Cloud Shell",
        "stem": "Select the answer that correctly completes the sentence.\n\nFor administrators who script in Bash on Linux, the most natural Azure command-line choice is ___.",
        "options": [
            {"id": "a", "text": "the Azure CLI", "correct": True, "rationale": "Correct. The Azure CLI's az commands integrate cleanly into Bash scripts and Linux workflows."},
            {"id": "b", "text": "the Azure portal", "correct": False, "rationale": "Incorrect. The portal is a graphical website, not a command-line tool for Bash scripting."},
            {"id": "c", "text": "the Azure mobile app", "correct": False, "rationale": "Incorrect. The mobile app is a phone application, not a scripting tool."},
            {"id": "d", "text": "Azure Service Health", "correct": False, "rationale": "Incorrect. Service Health reports Azure incidents and maintenance; it is not a command-line tool."},
        ],
        "explanation": "The Azure CLI is designed to feel natural in Bash environments, making it the usual choice for Linux-oriented scripting.",
    },
    {
        "id": "az3c-031",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure Arc",
        "stem": "Your company runs virtual machines on-premises and in another public cloud, plus resources in Azure. You need a single place in Azure to organize, govern, and manage all of these servers. What should you use?",
        "options": [
            {"id": "a", "text": "Azure Arc", "correct": True, "rationale": "Correct. Azure Arc projects servers running outside Azure into Azure Resource Manager so they can be managed alongside native Azure resources."},
            {"id": "b", "text": "Azure Virtual Desktop", "correct": False, "rationale": "Incorrect. Azure Virtual Desktop delivers virtualized Windows desktops; it does not manage external servers."},
            {"id": "c", "text": "Azure Content Delivery Network", "correct": False, "rationale": "Incorrect. A CDN caches content close to users; it has no server management role."},
            {"id": "d", "text": "Azure DNS", "correct": False, "rationale": "Incorrect. Azure DNS hosts DNS zones; it does not provide hybrid server management."},
        ],
        "explanation": "Azure Arc extends Azure management to servers running on-premises and in other clouds, giving one control plane for all environments.",
    },
    {
        "id": "az3c-032",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure Arc",
        "stem": "Select the answer that correctly completes the sentence.\n\n___ enables you to manage servers, Kubernetes clusters, and data services that run outside of Azure as if they were native Azure resources.",
        "options": [
            {"id": "a", "text": "Azure Arc", "correct": True, "rationale": "Correct. Arc projects non-Azure infrastructure into Azure Resource Manager for unified management and governance."},
            {"id": "b", "text": "Azure Backup", "correct": False, "rationale": "Incorrect. Azure Backup protects data with backups; it does not project external infrastructure into Azure."},
            {"id": "c", "text": "Azure Firewall", "correct": False, "rationale": "Incorrect. Azure Firewall filters network traffic; it is unrelated to hybrid resource management."},
            {"id": "d", "text": "Azure Blueprints", "correct": False, "rationale": "Incorrect. Blueprints package governance artifacts for Azure environments; they do not onboard non-Azure machines."},
        ],
        "explanation": "Azure Arc brings servers, Kubernetes clusters, and data services running anywhere under Azure's management umbrella.",
    },
    {
        "id": "az3c-033",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "You onboard an on-premises server to Azure Arc. Which of the following can you now do with that server?",
        "options": [
            {"id": "a", "text": "Place it in a resource group and apply tags to it like any other Azure resource", "correct": True, "rationale": "Correct. Arc-enabled servers appear as Azure resources, so they can live in resource groups and carry tags for organization."},
            {"id": "b", "text": "Have Microsoft assume responsibility for its physical hardware maintenance", "correct": False, "rationale": "Incorrect. The server remains in your datacenter; you still own and maintain the physical hardware."},
            {"id": "c", "text": "Automatically receive an Azure uptime SLA for the server", "correct": False, "rationale": "Incorrect. Azure SLAs cover Azure services; Arc does not extend uptime guarantees to your own hardware."},
            {"id": "d", "text": "Have the server physically migrated into an Azure region", "correct": False, "rationale": "Incorrect. Arc manages the server in place; it does not move workloads into Azure."},
        ],
        "explanation": "Arc-enabled servers become Azure resources, gaining organization features such as resource groups and tags while continuing to run where they are.",
    },
    {
        "id": "az3c-034",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "easy",
        "study_topic": "Azure Arc",
        "stem": "Azure Arc can bring machines running in which two locations under Azure management? Each correct answer presents a complete solution.",
        "options": [
            {"id": "a", "text": "Your on-premises datacenter", "correct": True, "rationale": "Correct. Arc is commonly used to manage on-premises servers from Azure."},
            {"id": "b", "text": "Another public cloud, such as AWS or Google Cloud", "correct": True, "rationale": "Correct. Arc supports multicloud scenarios, managing VMs that run in other providers' clouds."},
            {"id": "c", "text": "Only Azure regions, because Arc works solely inside Azure", "correct": False, "rationale": "Incorrect. Arc's whole purpose is to extend management to infrastructure outside Azure."},
            {"id": "d", "text": "Machines with no network connectivity of any kind", "correct": False, "rationale": "Incorrect. Arc-managed machines need connectivity to Azure so the Arc agent can communicate with the control plane."},
        ],
        "explanation": "Azure Arc extends Azure's control plane to on-premises datacenters and other public clouds, enabling hybrid and multicloud management.",
    },
    {
        "id": "az3c-035",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "For compliance reasons, a database server must remain in your own datacenter, but the governance team wants to apply Azure Policy and Azure RBAC to it. What should you use?",
        "options": [
            {"id": "a", "text": "Azure Arc", "correct": True, "rationale": "Correct. Arc lets the server stay on-premises while being governed with Azure Policy, RBAC, and tags as an Azure resource."},
            {"id": "b", "text": "Azure Migrate", "correct": False, "rationale": "Incorrect. Azure Migrate moves workloads into Azure, which the compliance requirement forbids."},
            {"id": "c", "text": "Azure Site Recovery", "correct": False, "rationale": "Incorrect. Site Recovery replicates workloads for disaster recovery; it does not apply Azure governance to an on-premises server."},
            {"id": "d", "text": "Azure CDN", "correct": False, "rationale": "Incorrect. A content delivery network is unrelated to server governance."},
        ],
        "explanation": "Azure Arc applies Azure governance capabilities to servers that must stay on-premises, with no migration required.",
    },
    {
        "id": "az3c-036",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "Your company runs Kubernetes clusters in AWS and in its own datacenter, alongside AKS clusters in Azure. You want to apply consistent configuration and policy to all of the clusters from one place. What should you use?",
        "options": [
            {"id": "a", "text": "Azure Arc-enabled Kubernetes", "correct": True, "rationale": "Correct. Arc-enabled Kubernetes attaches clusters running anywhere to Azure so configuration and policy can be applied consistently."},
            {"id": "b", "text": "Azure Container Registry", "correct": False, "rationale": "Incorrect. Container Registry stores container images; it does not govern external clusters."},
            {"id": "c", "text": "Azure Virtual Network peering", "correct": False, "rationale": "Incorrect. VNet peering connects Azure virtual networks; it does not manage Kubernetes clusters."},
            {"id": "d", "text": "Azure Load Balancer", "correct": False, "rationale": "Incorrect. Load Balancer distributes traffic; it has no cluster governance role."},
        ],
        "explanation": "Arc-enabled Kubernetes registers clusters from any environment into Azure for centralized configuration and policy management.",
    },
    {
        "id": "az3c-037",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "You want to run an Azure-managed database service, such as Azure SQL Managed Instance, on servers inside your own datacenter while managing it with Azure tools. Which capability makes this possible?",
        "options": [
            {"id": "a", "text": "Azure Arc-enabled data services", "correct": True, "rationale": "Correct. Arc-enabled data services let Azure data services such as SQL Managed Instance run on your infrastructure with Azure-style management."},
            {"id": "b", "text": "Azure Cache for Redis", "correct": False, "rationale": "Incorrect. Azure Cache for Redis is an in-memory cache service hosted in Azure, not a way to run Azure data services on-premises."},
            {"id": "c", "text": "Azure Data Box", "correct": False, "rationale": "Incorrect. Data Box is a physical appliance for transferring large amounts of data into Azure."},
            {"id": "d", "text": "Azure Files", "correct": False, "rationale": "Incorrect. Azure Files provides cloud file shares; it does not host managed database services on your hardware."},
        ],
        "explanation": "Azure Arc-enabled data services bring Azure data services to infrastructure outside Azure, keeping cloud-style management and updates.",
    },
    {
        "id": "az3c-038",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Azure Arc",
        "stem": "What is the primary benefit of using Azure Arc in a hybrid or multicloud environment?",
        "options": [
            {"id": "a", "text": "A single, consistent management and governance plane for resources wherever they run", "correct": True, "rationale": "Correct. Arc centralizes management so Azure tools, policies, and RBAC apply consistently across Azure, on-premises, and other clouds."},
            {"id": "b", "text": "Free Azure compute for on-premises workloads", "correct": False, "rationale": "Incorrect. Arc does not provide free compute; your on-premises hardware still runs and funds the workloads."},
            {"id": "c", "text": "Automatic conversion of all applications to serverless functions", "correct": False, "rationale": "Incorrect. Arc does not rewrite or convert applications."},
            {"id": "d", "text": "Elimination of the need for network connectivity between sites", "correct": False, "rationale": "Incorrect. Arc requires connectivity so external machines can communicate with Azure's control plane."},
        ],
        "explanation": "Azure Arc's core value is unified, consistent governance and management of resources across Azure, on-premises, and other clouds.",
    },
    {
        "id": "az3c-039",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "An on-premises server has been onboarded to Azure Arc. Can Azure Monitor collect performance data and logs from this server?",
        "options": [
            {"id": "a", "text": "Yes, monitoring agents and extensions can be deployed to Arc-enabled servers", "correct": True, "rationale": "Correct. Arc-enabled servers support Azure VM extensions, including the Azure Monitor agent, so telemetry can flow into Azure Monitor."},
            {"id": "b", "text": "No, Azure Monitor works only with resources physically hosted in Azure", "correct": False, "rationale": "Incorrect. Azure Monitor can collect data from on-premises machines through agents, and Arc simplifies deploying them."},
            {"id": "c", "text": "Only if the server is first migrated into Azure", "correct": False, "rationale": "Incorrect. No migration is required; the server is monitored where it runs."},
            {"id": "d", "text": "Only for Linux servers, never Windows", "correct": False, "rationale": "Incorrect. Arc and Azure Monitor support both Windows and Linux servers."},
        ],
        "explanation": "Arc-enabled servers can run Azure extensions such as the Azure Monitor agent, bringing on-premises telemetry into Azure Monitor.",
    },
    {
        "id": "az3c-040",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Azure Arc",
        "stem": "Which task is Azure Arc NOT designed to perform?",
        "options": [
            {"id": "a", "text": "Assessing and physically migrating on-premises virtual machines into Azure", "correct": True, "rationale": "Correct. Migration assessment and execution is the job of Azure Migrate; Arc manages resources where they already run."},
            {"id": "b", "text": "Applying Azure Policy to servers running outside Azure", "correct": False, "rationale": "Incorrect. Governing external servers with Azure Policy is a core Arc capability."},
            {"id": "c", "text": "Managing Kubernetes clusters hosted in other clouds", "correct": False, "rationale": "Incorrect. Arc-enabled Kubernetes exists precisely for this scenario."},
            {"id": "d", "text": "Representing on-premises machines as resources in the Azure portal", "correct": False, "rationale": "Incorrect. Projecting external machines into Azure Resource Manager is fundamental to how Arc works."},
        ],
        "explanation": "Azure Arc governs and manages resources in place; migrating workloads into Azure is handled by Azure Migrate.",
    },
    {
        "id": "az3c-041",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Select the answer that correctly completes the sentence.\n\n___ is the practice of defining and deploying infrastructure through machine-readable definition files rather than through manual configuration.",
        "options": [
            {"id": "a", "text": "Infrastructure as code", "correct": True, "rationale": "Correct. Infrastructure as code (IaC) captures the environment in files that can be versioned and deployed repeatedly."},
            {"id": "b", "text": "Platform as a service", "correct": False, "rationale": "Incorrect. PaaS is a cloud service model, not a deployment practice."},
            {"id": "c", "text": "Serverless computing", "correct": False, "rationale": "Incorrect. Serverless is a compute model where the platform manages servers; it is not the practice of defining infrastructure in files."},
            {"id": "d", "text": "Vertical scaling", "correct": False, "rationale": "Incorrect. Vertical scaling means resizing a resource up or down; it is unrelated to definition files."},
        ],
        "explanation": "Infrastructure as code manages environments through versionable definition files instead of manual clicks, enabling repeatable, consistent deployments.",
    },
    {
        "id": "az3c-042",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which statement best describes the declarative nature of an ARM template?",
        "options": [
            {"id": "a", "text": "You describe the desired end state of the environment, and Azure Resource Manager determines the steps to achieve it", "correct": True, "rationale": "Correct. Declarative templates state what should exist; Resource Manager works out how to create or update the resources."},
            {"id": "b", "text": "You list every command to run, in exact order, and Azure executes them one by one", "correct": False, "rationale": "Incorrect. A step-by-step list of commands describes the imperative approach, such as a CLI script."},
            {"id": "c", "text": "You record a video of portal clicks that Azure replays", "correct": False, "rationale": "Incorrect. Templates are JSON documents, not recordings of user actions."},
            {"id": "d", "text": "You can deploy only one resource per template", "correct": False, "rationale": "Incorrect. A single template can define and deploy many interdependent resources."},
        ],
        "explanation": "ARM templates are declarative: they define the intended end state and let Resource Manager handle the how.",
    },
    {
        "id": "az3c-043",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Before an ARM template creates any resources, you want confidence that the template is well-formed and the deployment will not fail because of syntax errors. What does Azure provide for this?",
        "options": [
            {"id": "a", "text": "Template validation that checks the template before the deployment starts", "correct": True, "rationale": "Correct. ARM template deployments can be validated first, catching syntax and basic configuration errors before any resource is touched."},
            {"id": "b", "text": "Nothing; errors can be discovered only after resources fail to deploy", "correct": False, "rationale": "Incorrect. Validation is built into the deployment process and can also be invoked explicitly."},
            {"id": "c", "text": "A mandatory review by Microsoft support for every template", "correct": False, "rationale": "Incorrect. Microsoft does not review customer templates; validation is automated."},
            {"id": "d", "text": "A requirement to deploy to production first as a test", "correct": False, "rationale": "Incorrect. Testing in production is the opposite of good practice; validation avoids the need."},
        ],
        "explanation": "ARM templates can be validated before deployment, so structural problems are caught before any resources are created.",
    },
    {
        "id": "az3c-044",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Ten developers each need an identical development environment in Azure consisting of a virtual network, a VM, and a storage account. Which approach delivers the most consistent results?",
        "options": [
            {"id": "a", "text": "Deploying the same ARM template or Bicep file for each developer", "correct": True, "rationale": "Correct. Deploying one template repeatedly produces identical environments and eliminates configuration drift between them."},
            {"id": "b", "text": "Having each developer build their environment manually in the portal", "correct": False, "rationale": "Incorrect. Ten manual builds will inevitably differ in small ways and take much longer."},
            {"id": "c", "text": "Emailing screenshots of the desired configuration to each developer", "correct": False, "rationale": "Incorrect. Screenshots still require error-prone manual reproduction."},
            {"id": "d", "text": "Sharing one environment among all ten developers", "correct": False, "rationale": "Incorrect. Sharing one environment does not meet the requirement that each developer has their own."},
        ],
        "explanation": "Templates guarantee that repeated deployments produce identical environments, which manual processes cannot reliably do.",
    },
    {
        "id": "az3c-045",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Can a single ARM template deploy an entire environment, such as a virtual network, several virtual machines, and a storage account, in one coordinated operation?",
        "options": [
            {"id": "a", "text": "Yes, a template can define many resources and Resource Manager orchestrates their deployment, including dependencies", "correct": True, "rationale": "Correct. Templates routinely describe whole environments, and Resource Manager creates the resources in the correct order."},
            {"id": "b", "text": "No, each template is limited to exactly one resource", "correct": False, "rationale": "Incorrect. Templates commonly define many resources together."},
            {"id": "c", "text": "Only if every resource is in a different subscription", "correct": False, "rationale": "Incorrect. A typical template deployment targets a single resource group or subscription scope; multi-resource templates are the norm."},
            {"id": "d", "text": "Only if the resources are deployed one per day", "correct": False, "rationale": "Incorrect. There is no such timing restriction; the deployment runs as a single operation."},
        ],
        "explanation": "ARM templates can describe complete multi-resource environments that Resource Manager deploys as one orchestrated operation.",
    },
    {
        "id": "az3c-046",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Your team finds ARM template JSON verbose and hard to read. You want a simpler, cleaner language for authoring Azure infrastructure as code that still deploys through Azure Resource Manager. What should you use?",
        "options": [
            {"id": "a", "text": "Bicep", "correct": True, "rationale": "Correct. Bicep offers concise, readable syntax and transpiles to ARM template JSON for deployment."},
            {"id": "b", "text": "HTML", "correct": False, "rationale": "Incorrect. HTML describes web pages, not Azure infrastructure."},
            {"id": "c", "text": "XML configuration files", "correct": False, "rationale": "Incorrect. ARM deployments use JSON or Bicep, not XML."},
            {"id": "d", "text": "Batch files", "correct": False, "rationale": "Incorrect. Batch files are imperative Windows scripts, not a declarative IaC language for Resource Manager."},
        ],
        "explanation": "Bicep is Microsoft's simpler infrastructure-as-code language that compiles to ARM JSON, keeping full Resource Manager compatibility.",
    },
    {
        "id": "az3c-047",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which term describes the property that deploying the same ARM template repeatedly leaves the environment in the same state, without creating duplicates or errors?",
        "options": [
            {"id": "a", "text": "Idempotent", "correct": True, "rationale": "Correct. An idempotent deployment can run any number of times and always converges on the same defined end state."},
            {"id": "b", "text": "Ephemeral", "correct": False, "rationale": "Incorrect. Ephemeral means short-lived, which is unrelated to repeatable deployment behavior."},
            {"id": "c", "text": "Imperative", "correct": False, "rationale": "Incorrect. Imperative describes step-by-step command execution, the opposite of the declarative template model."},
            {"id": "d", "text": "Elastic", "correct": False, "rationale": "Incorrect. Elasticity refers to scaling capacity with demand, not deployment behavior."},
        ],
        "explanation": "ARM template deployments are idempotent: repeating the same deployment yields the same resulting environment.",
    },
    {
        "id": "az3c-048",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which two of the following are characteristics of ARM templates? Each correct selection is worth one point.",
        "options": [
            {"id": "a", "text": "They can be stored in source control alongside application code", "correct": True, "rationale": "Correct. Templates are text files, so they version, diff, and review just like code."},
            {"id": "b", "text": "The same template can be deployed repeatedly with consistent results", "correct": True, "rationale": "Correct. Template deployments are repeatable and idempotent, producing consistent environments."},
            {"id": "c", "text": "They must be rewritten from scratch before every deployment", "correct": False, "rationale": "Incorrect. Reuse is the point of templates; the same file is deployed again and again."},
            {"id": "d", "text": "They can be executed only once per subscription", "correct": False, "rationale": "Incorrect. There is no such limit; templates can be deployed many times to many scopes."},
        ],
        "explanation": "ARM templates are versionable text files that can be deployed repeatedly with consistent, predictable results.",
    },
    {
        "id": "az3c-049",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "A regional disaster destroys the environment that hosts an application. The infrastructure was defined entirely in ARM templates kept in source control. How does this help recovery?",
        "options": [
            {"id": "a", "text": "The templates can be redeployed to another region to recreate the environment quickly and consistently", "correct": True, "rationale": "Correct. Because the environment is captured as code, it can be rebuilt on demand in a new region with the same configuration."},
            {"id": "b", "text": "It does not help; the environment must be rebuilt manually from memory", "correct": False, "rationale": "Incorrect. Avoiding manual, from-memory rebuilds is precisely the benefit of infrastructure as code."},
            {"id": "c", "text": "The templates automatically prevent regional disasters from occurring", "correct": False, "rationale": "Incorrect. Templates do not prevent disasters; they make recovery faster and more reliable."},
            {"id": "d", "text": "Microsoft support uses the templates to restore the old region's hardware", "correct": False, "rationale": "Incorrect. Recovery here means redeploying your resources, not restoring physical hardware."},
        ],
        "explanation": "Infrastructure captured as code can be redeployed anywhere on demand, making disaster recovery faster and more dependable.",
    },
    {
        "id": "az3c-050",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which of the following is an example of an imperative approach to deploying Azure infrastructure?",
        "options": [
            {"id": "a", "text": "A Bash script that runs a sequence of Azure CLI commands to create each resource", "correct": True, "rationale": "Correct. Imperative deployment specifies the exact commands and their order; a CLI script is a classic example."},
            {"id": "b", "text": "An ARM template describing the desired end state in JSON", "correct": False, "rationale": "Incorrect. ARM templates are declarative; they state what should exist rather than which commands to run."},
            {"id": "c", "text": "A Bicep file that defines the resources to deploy", "correct": False, "rationale": "Incorrect. Bicep is declarative, like the ARM JSON it compiles into."},
            {"id": "d", "text": "A resource lock on a resource group", "correct": False, "rationale": "Incorrect. Locks protect existing resources from changes; they are not a deployment approach."},
        ],
        "explanation": "Scripts that execute ordered commands (CLI or PowerShell) are imperative, whereas ARM templates and Bicep are declarative.",
    },
    {
        "id": "az3c-051",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which ARM template feature lets you supply different values, such as an environment name or VM size, each time the template is deployed?",
        "options": [
            {"id": "a", "text": "Parameters", "correct": True, "rationale": "Correct. Parameters accept values at deployment time, letting one template serve many environments."},
            {"id": "b", "text": "Resource locks", "correct": False, "rationale": "Incorrect. Locks prevent deletion or modification of resources; they are not part of template input."},
            {"id": "c", "text": "Availability zones", "correct": False, "rationale": "Incorrect. Availability zones are physical datacenter groupings, not a template input mechanism."},
            {"id": "d", "text": "Tags", "correct": False, "rationale": "Incorrect. Tags are metadata applied to resources; parameters are what carry per-deployment values into a template."},
        ],
        "explanation": "Template parameters allow the same ARM template to be reused with different values for each deployment.",
    },
    {
        "id": "az3c-052",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "hard",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Your organization's main ARM template has grown very large. You want to split it into smaller, reusable building blocks, such as a standard networking component that many deployments can share. What should you use?",
        "options": [
            {"id": "a", "text": "Linked or nested templates (or Bicep modules)", "correct": True, "rationale": "Correct. Linked/nested templates and Bicep modules break large deployments into reusable components that other templates can reference."},
            {"id": "b", "text": "A resource lock on the template file", "correct": False, "rationale": "Incorrect. Locks apply to deployed Azure resources, not to template file structure."},
            {"id": "c", "text": "Separate Azure subscriptions for every resource", "correct": False, "rationale": "Incorrect. Multiplying subscriptions does not modularize template code."},
            {"id": "d", "text": "Converting the template to a portal dashboard", "correct": False, "rationale": "Incorrect. Dashboards visualize resources; they cannot deploy infrastructure."},
        ],
        "explanation": "Linked/nested ARM templates and Bicep modules enable modular, reusable infrastructure-as-code components.",
    },
    {
        "id": "az3c-053",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "easy",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Select the answer that correctly completes the sentence.\n\nARM templates use a ___ syntax, meaning they state what should be deployed without listing the individual commands required to create it.",
        "options": [
            {"id": "a", "text": "declarative", "correct": True, "rationale": "Correct. Declarative syntax describes intent (the end state), leaving execution details to Azure Resource Manager."},
            {"id": "b", "text": "imperative", "correct": False, "rationale": "Incorrect. Imperative syntax lists explicit commands in order, which is how scripts work, not templates."},
            {"id": "c", "text": "compiled binary", "correct": False, "rationale": "Incorrect. ARM templates are human-readable JSON text, not compiled binaries."},
            {"id": "d", "text": "encrypted", "correct": False, "rationale": "Incorrect. Templates are plain text; encryption is not part of their syntax model."},
        ],
        "explanation": "ARM templates are declarative JSON: they define the desired outcome and Resource Manager handles how to reach it.",
    },
    {
        "id": "az3c-054",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Compared with configuring resources by hand in the Azure portal, what is a key advantage of deploying environments from templates?",
        "options": [
            {"id": "a", "text": "It reduces human error and configuration drift because every deployment follows the same definition", "correct": True, "rationale": "Correct. Template deployments remove the variability of manual steps, so environments stay consistent."},
            {"id": "b", "text": "It removes the need for any access permissions in Azure", "correct": False, "rationale": "Incorrect. Template deployments are still authorized through Azure RBAC like any other management operation."},
            {"id": "c", "text": "It makes all deployed resources free of charge", "correct": False, "rationale": "Incorrect. Resources cost the same regardless of how they are deployed."},
            {"id": "d", "text": "It guarantees Microsoft will manage the resources for you", "correct": False, "rationale": "Incorrect. Your management responsibilities are unchanged by the deployment method."},
        ],
        "explanation": "Templates make deployments consistent and repeatable, cutting the human error and drift inherent in manual portal work.",
    },
    {
        "id": "az3c-055",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_response",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Which two artifact types represent infrastructure as code for Azure deployments? Each correct answer presents a complete solution.",
        "options": [
            {"id": "a", "text": "An ARM template written in JSON", "correct": True, "rationale": "Correct. ARM templates are Azure's native declarative JSON IaC format."},
            {"id": "b", "text": "A Bicep file", "correct": True, "rationale": "Correct. Bicep files are declarative IaC that transpile to ARM JSON."},
            {"id": "c", "text": "A screenshot of the portal configuration", "correct": False, "rationale": "Incorrect. Images are not machine-deployable definitions."},
            {"id": "d", "text": "A spreadsheet listing resource names", "correct": False, "rationale": "Incorrect. A spreadsheet is documentation, not a deployable infrastructure definition."},
        ],
        "explanation": "ARM templates (JSON) and Bicep files are Azure's declarative infrastructure-as-code formats.",
    },
    {
        "id": "az3c-056",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "Your team is choosing between Bicep and ARM template JSON but worries that Bicep might support fewer Azure resource types. Is this concern valid?",
        "options": [
            {"id": "a", "text": "No, Bicep compiles to ARM template JSON, so it supports the same resource types as ARM templates", "correct": True, "rationale": "Correct. Because Bicep transpiles to ARM JSON, anything deployable with an ARM template is deployable with Bicep."},
            {"id": "b", "text": "Yes, Bicep can deploy only virtual machines", "correct": False, "rationale": "Incorrect. Bicep is a general-purpose IaC language for all Resource Manager resource types."},
            {"id": "c", "text": "Yes, Bicep works only with classic (pre-Resource Manager) resources", "correct": False, "rationale": "Incorrect. Bicep targets Azure Resource Manager, not the classic deployment model."},
            {"id": "d", "text": "No, because Bicep bypasses Azure Resource Manager entirely", "correct": False, "rationale": "Incorrect. Bicep deployments go through Resource Manager; that is why parity holds, not because ARM is bypassed."},
        ],
        "explanation": "Bicep transpiles to ARM template JSON and deploys through Resource Manager, so its resource coverage matches ARM templates.",
    },
    {
        "id": "az3c-057",
        "domain": 3,
        "objective": "3.3",
        "type": "multiple_choice",
        "difficulty": "medium",
        "study_topic": "Infrastructure as code and ARM templates",
        "stem": "You built a set of resources manually in the Azure portal and now want to redeploy the same configuration elsewhere by using infrastructure as code. Which portal capability gives you a starting point?",
        "options": [
            {"id": "a", "text": "Exporting an ARM template from the existing resources", "correct": True, "rationale": "Correct. The portal can export a template representing deployed resources, which you can refine and reuse as IaC."},
            {"id": "b", "text": "Downloading the subscription invoice", "correct": False, "rationale": "Incorrect. Invoices describe charges, not resource configuration."},
            {"id": "c", "text": "Taking a screenshot of each configuration blade", "correct": False, "rationale": "Incorrect. Screenshots cannot be deployed and would require manual reproduction."},
            {"id": "d", "text": "Applying a delete lock to the resource group", "correct": False, "rationale": "Incorrect. Locks protect resources; they do not capture configuration as code."},
        ],
        "explanation": "The portal's export template feature generates an ARM template from existing resources, providing a starting point for IaC reuse.",
    },
]
