"""Microsoft AZ-900 interactive-style items.

The real AZ-900 uses "For each of the following statements, select Yes or No"
sets and drag-drop matching (service -> description). These are modeled with
``pbq_categorize`` (Yes/No) and ``pbq_matching``, calibrated to real-exam
difficulty — classic statement sets, not tricky edge cases.
"""

QUESTIONS = [
    # ------------------------------------------------------------- #
    # Domain 1 — cloud concepts                                      #
    # ------------------------------------------------------------- #
    {
        "id": "azpbq-001",
        "domain": 1,
        "objective": "1.1",
        "type": "pbq_categorize",
        "difficulty": "easy",
        "study_topic": "Cloud computing and shared responsibility",
        "stem": "For each of the following statements about the shared responsibility model, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "In all cloud service models, the customer remains responsible for their information and data."},
            {"id": "s2", "text": "In an IaaS deployment, the cloud provider is responsible for patching the guest operating system."},
            {"id": "s3", "text": "The cloud provider is always responsible for the physical security of the datacenter."},
            {"id": "s4", "text": "In a SaaS deployment, the customer manages the underlying application code."},
        ],
        "answer": {"s1": "yes", "s2": "no", "s3": "yes", "s4": "no"},
        "rationales": {
            "s1": "Information and data, devices, and accounts/identities always remain the customer's responsibility in every service model.",
            "s2": "In IaaS the CUSTOMER manages the guest operating system, including patching; the provider manages the physical hosts underneath.",
            "s3": "Physical hosts, the physical network, and the physical datacenter are always the provider's responsibility in the cloud.",
            "s4": "In SaaS the provider manages the application itself; the customer just uses it and manages their data, devices, and identities.",
        },
        "explanation": "Customer always: data, devices, accounts/identities. Provider always: physical datacenter, network, hosts. Everything between (OS, network controls, applications) shifts by model — customer-managed in IaaS, shared/provider-managed as you move toward SaaS.",
    },
    {
        "id": "azpbq-002",
        "domain": 1,
        "objective": "1.3",
        "type": "pbq_matching",
        "difficulty": "easy",
        "study_topic": "Cloud service types (IaaS/PaaS/SaaS)",
        "stem": "Match each scenario to the cloud service type it describes.",
        "prompts": [
            {"id": "p1", "text": "Migrating on-premises servers to Azure virtual machines"},
            {"id": "p2", "text": "Hosting a web app without managing the OS or runtime"},
            {"id": "p3", "text": "Using Microsoft 365 email without managing any infrastructure"},
        ],
        "targets": [
            {"id": "iaas", "text": "IaaS"},
            {"id": "paas", "text": "PaaS"},
            {"id": "saas", "text": "SaaS"},
        ],
        "answer": {"p1": "iaas", "p2": "paas", "p3": "saas"},
        "rationales": {
            "p1": "Virtual machines are Infrastructure as a Service — you rent compute infrastructure and manage the OS and everything above it.",
            "p2": "A managed web-hosting platform (like Azure App Service) is Platform as a Service — the provider manages the OS and runtime; you bring the code.",
            "p3": "A complete, ready-to-use application like Microsoft 365 is Software as a Service — you manage nothing but your data and users.",
        },
        "explanation": "IaaS gives the most control (and most management burden), PaaS manages the platform so you focus on code, SaaS delivers the finished application. Lift-and-shift → IaaS; app hosting → PaaS; ready-made apps → SaaS.",
    },
    {
        "id": "azpbq-003",
        "domain": 1,
        "objective": "1.2",
        "type": "pbq_categorize",
        "difficulty": "medium",
        "study_topic": "Cloud benefits (HA, scalability, elasticity, DR)",
        "stem": "For each of the following statements about cloud benefits, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "Vertical scaling means adding more instances of a resource, such as more virtual machines."},
            {"id": "s2", "text": "Elasticity is the ability to automatically add or remove resources as demand changes."},
            {"id": "s3", "text": "High availability aims to keep services running with minimal downtime, often expressed as a percentage."},
            {"id": "s4", "text": "The consumption-based model requires paying for reserved hardware in advance."},
        ],
        "answer": {"s1": "no", "s2": "yes", "s3": "yes", "s4": "no"},
        "rationales": {
            "s1": "Adding more instances is HORIZONTAL scaling (scaling out). Vertical scaling (scaling up) means moving to a more powerful instance size.",
            "s2": "Elasticity is exactly this: automatically expanding and contracting resources to match demand, so you pay only for what you need.",
            "s3": "High availability is about maximizing uptime, commonly expressed as an SLA percentage such as 99.9%.",
            "s4": "The consumption-based model is pay-as-you-go for what you actually use — no upfront hardware costs; that is CapEx-style thinking.",
        },
        "explanation": "Scale up/down = vertical (bigger/smaller instance); scale out/in = horizontal (more/fewer instances). Elasticity automates that scaling with demand, and cloud pricing is consumption-based OpEx rather than upfront CapEx.",
    },
    {
        "id": "azpbq-004",
        "domain": 1,
        "objective": "1.1",
        "type": "pbq_matching",
        "difficulty": "easy",
        "study_topic": "Cloud deployment models (public/private/hybrid)",
        "stem": "Match each description to the cloud deployment model it describes.",
        "prompts": [
            {"id": "p1", "text": "Services are offered over the public internet and available to anyone who wants to purchase them"},
            {"id": "p2", "text": "Cloud resources are used exclusively by a single organization"},
            {"id": "p3", "text": "An organization runs some workloads on-premises and others in the public cloud, connected together"},
        ],
        "targets": [
            {"id": "pub", "text": "Public cloud"},
            {"id": "priv", "text": "Private cloud"},
            {"id": "hyb", "text": "Hybrid cloud"},
        ],
        "answer": {"p1": "pub", "p2": "priv", "p3": "hyb"},
        "rationales": {
            "p1": "The public cloud is owned by a provider and shared by many customers over the internet — like Azure itself.",
            "p2": "A private cloud dedicates its resources to one organization (it can still be hosted by a third party).",
            "p3": "Hybrid combines private/on-premises infrastructure with public cloud, letting workloads span or move between the two.",
        },
        "explanation": "Public = shared provider infrastructure; private = single organization (wherever hosted); hybrid = the two connected. AZ-900 loves the fact that a private cloud can be hosted offsite by a third party.",
    },
    # ------------------------------------------------------------- #
    # Domain 2 — architecture and services                           #
    # ------------------------------------------------------------- #
    {
        "id": "azpbq-005",
        "domain": 2,
        "objective": "2.1",
        "type": "pbq_categorize",
        "difficulty": "medium",
        "study_topic": "Regions, availability zones, and region pairs",
        "stem": "For each of the following statements about Azure regions and availability zones, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "An availability zone is one or more datacenters with independent power, cooling, and networking."},
            {"id": "s2", "text": "Deploying two VMs across availability zones protects against the failure of an entire region."},
            {"id": "s3", "text": "Region pairs are located at least 300 miles apart when possible."},
            {"id": "s4", "text": "Every Azure resource must be deployed into a specific availability zone."},
        ],
        "answer": {"s1": "yes", "s2": "no", "s3": "yes", "s4": "no"},
        "rationales": {
            "s1": "That is the definition — physically separate zones within a region, each with independent power, cooling, and networking.",
            "s2": "Availability zones protect against DATACENTER failure within a region. Protecting against full-region failure requires deploying to another region (e.g., the paired region).",
            "s3": "Where possible, region pairs are at least 300 miles apart to reduce the chance a single disaster affects both.",
            "s4": "Many services are regional or zone-redundant automatically; you are not required to pin every resource to a zone, and not all regions/services support zones.",
        },
        "explanation": "Zones guard against datacenter failure inside a region; region pairs (300+ miles apart) guard against regional disasters. Know which failure each construct protects against — it's a favorite exam distinction.",
    },
    {
        "id": "azpbq-006",
        "domain": 2,
        "objective": "2.2",
        "type": "pbq_matching",
        "difficulty": "easy",
        "study_topic": "Azure compute (VMs, App Service, containers, Functions)",
        "stem": "Match each requirement to the Azure compute service you should use.",
        "prompts": [
            {"id": "p1", "text": "Run a small piece of code triggered by an event, paying only when it runs"},
            {"id": "p2", "text": "Host a web app on a managed platform without managing servers"},
            {"id": "p3", "text": "Run a single container quickly without managing an orchestrator"},
            {"id": "p4", "text": "Orchestrate many containers with automated scaling and management"},
        ],
        "targets": [
            {"id": "func", "text": "Azure Functions"},
            {"id": "appsvc", "text": "Azure App Service"},
            {"id": "aci", "text": "Azure Container Instances"},
            {"id": "aks", "text": "Azure Kubernetes Service"},
        ],
        "answer": {"p1": "func", "p2": "appsvc", "p3": "aci", "p4": "aks"},
        "rationales": {
            "p1": "Azure Functions is serverless, event-driven compute billed per execution — ideal for small triggered code.",
            "p2": "App Service is the managed PaaS platform for hosting web apps and APIs without server management.",
            "p3": "Azure Container Instances is the fastest, simplest way to run a container in Azure — no orchestration layer.",
            "p4": "Azure Kubernetes Service is Azure's managed container orchestrator for running containers at scale.",
        },
        "explanation": "Event-triggered code → Functions; managed web hosting → App Service; one quick container → ACI; container fleet with orchestration → AKS. Matching workload to compute service is a guaranteed exam theme.",
    },
    {
        "id": "azpbq-007",
        "domain": 2,
        "objective": "2.3",
        "type": "pbq_matching",
        "difficulty": "medium",
        "study_topic": "Azure storage services and redundancy",
        "stem": "Match each storage requirement to the appropriate Azure option.",
        "prompts": [
            {"id": "p1", "text": "Store rarely accessed data at the lowest storage cost, where hours of retrieval delay is acceptable"},
            {"id": "p2", "text": "Replicate data synchronously across three availability zones in one region"},
            {"id": "p3", "text": "Provide SMB file shares that on-premises and cloud servers can both mount"},
            {"id": "p4", "text": "Store frequently accessed unstructured objects such as images and video"},
        ],
        "targets": [
            {"id": "arch", "text": "Archive access tier"},
            {"id": "zrs", "text": "Zone-redundant storage (ZRS)"},
            {"id": "files", "text": "Azure Files"},
            {"id": "hot", "text": "Blob storage, hot tier"},
        ],
        "answer": {"p1": "arch", "p2": "zrs", "p3": "files", "p4": "hot"},
        "rationales": {
            "p1": "The archive tier is offline storage with the lowest storage cost and a rehydration delay measured in hours — for data you almost never read.",
            "p2": "ZRS keeps three synchronous copies spread across availability zones within the region.",
            "p3": "Azure Files provides managed SMB (and NFS) file shares mountable from cloud and on-premises machines alike.",
            "p4": "Hot-tier blob storage is optimized for frequently accessed object data, with the highest storage cost but lowest access cost.",
        },
        "explanation": "Tiering trades storage cost against access cost/latency (hot → cool → cold → archive), redundancy options trade cost against failure protection (LRS → ZRS → GRS), Files covers the classic SMB share, and Blob covers unstructured objects.",
    },
    {
        "id": "azpbq-008",
        "domain": 2,
        "objective": "2.4",
        "type": "pbq_categorize",
        "difficulty": "medium",
        "study_topic": "Microsoft Entra ID and authentication (SSO, MFA, passwordless)",
        "stem": "For each of the following statements about Microsoft Entra ID, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "Microsoft Entra ID is Microsoft's cloud-based identity and access management service."},
            {"id": "s2", "text": "Multifactor authentication requires two or more of: something you know, something you have, something you are."},
            {"id": "s3", "text": "Single sign-on requires users to remember a separate password for each application."},
            {"id": "s4", "text": "Conditional Access can require MFA only when a sign-in looks risky or comes from outside trusted locations."},
        ],
        "answer": {"s1": "yes", "s2": "yes", "s3": "no", "s4": "yes"},
        "rationales": {
            "s1": "Entra ID (formerly Azure Active Directory) is the cloud identity provider behind Azure, Microsoft 365, and thousands of SaaS apps.",
            "s2": "MFA combines at least two different factor categories — knowledge, possession, and inherence.",
            "s3": "SSO is the opposite: one set of credentials grants access to multiple applications.",
            "s4": "Conditional Access evaluates signals (user, location, device, risk) and applies if-then controls such as requiring MFA — that adaptive behavior is its whole point.",
        },
        "explanation": "Entra ID provides identity; MFA strengthens authentication with multiple factor types; SSO reduces password sprawl; Conditional Access applies policy based on signals. These four definitions cover most identity questions on the exam.",
    },
    {
        "id": "azpbq-009",
        "domain": 2,
        "objective": "2.2",
        "type": "pbq_matching",
        "difficulty": "medium",
        "study_topic": "Azure networking (VNet, peering, VPN, ExpressRoute, DNS)",
        "stem": "Match each connectivity requirement to the Azure networking service you should use.",
        "prompts": [
            {"id": "p1", "text": "Connect an on-premises network to Azure with an encrypted tunnel over the public internet"},
            {"id": "p2", "text": "Connect an on-premises network to Azure over a private, dedicated connection that does not traverse the public internet"},
            {"id": "p3", "text": "Connect two Azure virtual networks so their resources communicate privately"},
            {"id": "p4", "text": "Host the DNS records for a public domain in Azure"},
        ],
        "targets": [
            {"id": "vpngw", "text": "VPN Gateway"},
            {"id": "expr", "text": "ExpressRoute"},
            {"id": "peer", "text": "Virtual network peering"},
            {"id": "dns", "text": "Azure DNS"},
        ],
        "answer": {"p1": "vpngw", "p2": "expr", "p3": "peer", "p4": "dns"},
        "rationales": {
            "p1": "A VPN Gateway builds an encrypted IPsec tunnel across the public internet between your network and an Azure VNet.",
            "p2": "ExpressRoute is a private circuit through a connectivity provider — traffic never touches the public internet, with higher reliability and speeds.",
            "p3": "VNet peering links two virtual networks (same or different regions) so they communicate over the Microsoft backbone.",
            "p4": "Azure DNS hosts DNS zones and answers queries for your domains using Azure's global name-server infrastructure.",
        },
        "explanation": "Encrypted-over-internet → VPN Gateway; private dedicated circuit → ExpressRoute; VNet-to-VNet → peering; domain hosting → Azure DNS. The VPN-vs-ExpressRoute distinction (public internet vs private circuit) is one of the most-tested facts on AZ-900.",
    },
    # ------------------------------------------------------------- #
    # Domain 3 — management and governance                           #
    # ------------------------------------------------------------- #
    {
        "id": "azpbq-010",
        "domain": 3,
        "objective": "3.2",
        "type": "pbq_categorize",
        "difficulty": "medium",
        "study_topic": "Resource locks",
        "stem": "For each of the following statements about Azure governance features, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "A Delete (CanNotDelete) lock allows a resource to be modified but not deleted."},
            {"id": "s2", "text": "A subscription Owner can delete a locked resource without first removing the lock."},
            {"id": "s3", "text": "Azure Policy can automatically remediate resources that are not compliant."},
            {"id": "s4", "text": "A policy assigned to a management group applies to all subscriptions within it."},
        ],
        "answer": {"s1": "yes", "s2": "no", "s3": "yes", "s4": "yes"},
        "rationales": {
            "s1": "A Delete lock blocks deletion while still permitting reads and modifications; a ReadOnly lock blocks modification too.",
            "s2": "Locks apply to everyone, including Owners — the lock must be removed before the resource can be deleted.",
            "s3": "Azure Policy supports remediation tasks that bring non-compliant resources into compliance automatically.",
            "s4": "Policy assignments are inherited down the hierarchy: management group → subscriptions → resource groups → resources.",
        },
        "explanation": "Locks (Delete vs ReadOnly) override even Owner permissions until removed and are inherited by child scopes, while Azure Policy audits/enforces standards and inherits down the management hierarchy with optional auto-remediation.",
    },
    {
        "id": "azpbq-011",
        "domain": 3,
        "objective": "3.4",
        "type": "pbq_matching",
        "difficulty": "easy",
        "study_topic": "Azure Advisor",
        "stem": "Match each monitoring requirement to the Azure service you should use.",
        "prompts": [
            {"id": "p1", "text": "Get personalized recommendations to reduce cost and improve reliability, security, and performance"},
            {"id": "p2", "text": "Find out whether an Azure outage or planned maintenance is affecting your resources"},
            {"id": "p3", "text": "Collect and query metrics and logs from your applications and resources"},
            {"id": "p4", "text": "Monitor the performance and usage of a live web application"},
        ],
        "targets": [
            {"id": "advisor", "text": "Azure Advisor"},
            {"id": "svchealth", "text": "Azure Service Health"},
            {"id": "monitor", "text": "Azure Monitor"},
            {"id": "appins", "text": "Application Insights"},
        ],
        "answer": {"p1": "advisor", "p2": "svchealth", "p3": "monitor", "p4": "appins"},
        "rationales": {
            "p1": "Advisor is the free recommendation engine covering reliability, security, performance, cost, and operational excellence.",
            "p2": "Service Health reports Azure incidents, planned maintenance, and health advisories that affect YOUR specific resources.",
            "p3": "Azure Monitor is the platform-wide metrics and logs pipeline (with Log Analytics for queries and alerts for action).",
            "p4": "Application Insights, a feature of Azure Monitor, provides APM — request rates, response times, failures — for live web apps.",
        },
        "explanation": "Advisor recommends, Service Health tells you about Azure-side problems affecting you, Monitor collects/queries telemetry, and Application Insights specializes in live web-app performance. Distinguishing these four is a staple of the exam.",
    },
    {
        "id": "azpbq-012",
        "domain": 3,
        "objective": "3.1",
        "type": "pbq_categorize",
        "difficulty": "medium",
        "study_topic": "Cost factors and pricing/TCO calculators",
        "stem": "For each of the following statements about Azure costs and tools, select Yes if the statement is true; otherwise select No.",
        "categories": [
            {"id": "yes", "text": "Yes"},
            {"id": "no", "text": "No"},
        ],
        "items": [
            {"id": "s1", "text": "The Total Cost of Ownership (TCO) calculator estimates the savings of migrating on-premises workloads to Azure."},
            {"id": "s2", "text": "The Pricing calculator provides an estimate of the monthly cost of Azure services you plan to deploy."},
            {"id": "s3", "text": "Inbound (ingress) data transfer to Azure is typically billed at a higher rate than outbound (egress) transfer."},
            {"id": "s4", "text": "Tags can be used to organize resources and track costs by department or project."},
        ],
        "answer": {"s1": "yes", "s2": "yes", "s3": "no", "s4": "yes"},
        "rationales": {
            "s1": "The TCO calculator compares current on-premises costs against Azure to estimate migration savings.",
            "s2": "The Pricing calculator estimates the cost of NEW Azure deployments you configure service-by-service.",
            "s3": "It is the reverse: ingress is generally free while egress (outbound) data transfer is what typically incurs charges.",
            "s4": "Tags are name/value pairs commonly used for cost allocation and reporting in Cost Management.",
        },
        "explanation": "TCO calculator = on-prem vs Azure comparison; Pricing calculator = estimate for planned Azure services; egress (not ingress) costs money; tags drive cost attribution. All four appear constantly on the real exam.",
    },
]
